"""Comprehensive Authoritative Clinical Knowledge Catalog for Phase 10A.

Compiles 500+ core essential medicine monographs derived from FDA DailyMed,
US NLM RxNorm, and official FDA-approved labeling across 14 major therapeutic classes.
"""
from typing import Any, Dict, List

# Core medicine seed catalog covering all major therapeutic categories
MEDICINE_SEED_CATALOG: List[Dict[str, Any]] = [
    # 1. Antibiotics & Antimicrobial Agents (60 drugs)
    {
        "name": "Amoxicillin", "strength": "500 mg", "form": "Oral Capsule/Tablet", "rxcui": "308189", "atc": "J01CA04",
        "class": "Penicillin Antibacterial", "aliases": ["Amoxil", "Moxatag", "Novamox", "Moxikind"],
        "indications": "Treatment of ear, nose, throat (ENT) infections, otitis media, streptococcal pharyngitis, pneumonia, sinusitis, and skin infections.",
        "dosage": "500 mg orally every 8 hours or 875 mg every 12 hours for 7 to 10 days.",
        "contraindications": "Hypersensitivity to amoxicillin, ampicillin, or other beta-lactams.",
        "warnings": "Serious anaphylaxis risk; Clostridioides difficile-associated diarrhea (CDAD).",
        "adverse_reactions": "Diarrhea, nausea, vomiting, skin rash, urticaria, candidiasis.",
        "interactions": "Probenecid increases levels; oral anticoagulants prolong prothrombin time; reduces oral contraceptive efficacy.",
        "pregnancy": "Pregnancy Category B; excreted in human milk.",
        "patient_counseling": "Complete entire prescribed course even if symptoms improve."
    },
    {
        "name": "Amoxicillin and Clavulanate", "strength": "875-125 mg", "form": "Oral Tablet", "rxcui": "308191", "atc": "J01CR02",
        "class": "Beta-Lactamase Inhibitor Combination", "aliases": ["Augmentin", "Clavam", "Moxikind-CV", "Augmentin XR"],
        "indications": "Recurrent otitis media, sinusitis, lower respiratory tract infections, and human/animal bites.",
        "dosage": "875/125 mg orally twice daily or 500/125 mg three times daily with meals.",
        "contraindications": "History of amoxicillin/clavulanate-associated cholestatic jaundice or hepatic dysfunction.",
        "warnings": "Hepatic dysfunction is more common than with amoxicillin alone; severe CDAD.",
        "adverse_reactions": "Diarrhea (frequent), nausea, vomiting, abdominal discomfort, vaginitis.",
        "interactions": "Warfarin INR elevation, allopurinol rash enhancement.",
        "pregnancy": "Category B. Use during labor may increase risk of necrotizing enterocolitis in neonates.",
        "patient_counseling": "Take at the start of a meal to enhance clavulanate absorption and minimize gastrointestinal intolerance."
    },
    {
        "name": "Ampicillin", "strength": "500 mg", "form": "Oral/IV", "rxcui": "723", "atc": "J01CA01",
        "class": "Aminopenicillin Antibacterial", "aliases": ["Principen", "Omnipen", "Campicillin"],
        "indications": "Treatment of respiratory tract infections, meningitis, endocarditis, and Listeria monocytogenes infections.",
        "dosage": "250 mg to 500 mg orally every 6 hours on an empty stomach; IV 1g to 2g every 4 to 6 hours.",
        "contraindications": "Known penicillin hypersensitivity.",
        "warnings": "Severe anaphylactic reactions; non-allergic ampicillin rash in infectious mononucleosis.",
        "adverse_reactions": "Maculopapular rash, diarrhea, nausea, glossitis, stomatitis.",
        "interactions": "Probenecid, methotrexate toxicity increased.",
        "pregnancy": "Category B. Compatible with breastfeeding.",
        "patient_counseling": "Take 1 hour before or 2 hours after meals with a full glass of water."
    },
    {
        "name": "Azithromycin", "strength": "500 mg", "form": "Oral Tablet", "rxcui": "198440", "atc": "J01FA10",
        "class": "Macrolide Antibacterial", "aliases": ["Zithromax", "Azithral", "Azee", "Z-Pak"],
        "indications": "Community-acquired pneumonia, acute bacterial exacerbations of COPD, chlamydia trachomatis, and pharyngitis.",
        "dosage": "500 mg on day 1, followed by 250 mg once daily on days 2 through 5 (Z-Pak).",
        "contraindications": "Hypersensitivity to azithromycin, erythromycin, or any macrolide/ketolide.",
        "warnings": "QT interval prolongation, torsades de pointes, and hepatotoxicity.",
        "adverse_reactions": "Diarrhea, nausea, abdominal pain, vomiting, headache.",
        "interactions": "Warfarin bleeding risk, cardiac antiarrhythmics (amiodarone, sotalol) risk of arrhythmias.",
        "pregnancy": "Category B. Excreted in breast milk.",
        "patient_counseling": "May take with or without food. Report palpitations or fainting."
    },
    {
        "name": "Clarithromycin", "strength": "500 mg", "form": "Oral Tablet", "rxcui": "21212", "atc": "J01FA09",
        "class": "Macrolide Antibacterial", "aliases": ["Biaxin", "Claribid", "Crixan", "Biaxin XL"],
        "indications": "Helicobacter pylori eradication, pharyngitis, sinusitis, and MAC prophylaxis in HIV.",
        "dosage": "250 mg to 500 mg orally every 12 hours for 7 to 14 days.",
        "contraindications": "Concomitant use with pimozide, astemizole, cisapride, ergotamine, or simvastatin/lovastatin.",
        "warnings": "Potent CYP3A4 inhibition; cardiac mortality signal in patients with coronary heart disease.",
        "adverse_reactions": "Dysgeusia (metallic taste), diarrhea, nausea, dyspepsia, abdominal pain.",
        "interactions": "Statins (severe rhabdomyolysis), digoxin toxicity, colchicine toxicity.",
        "pregnancy": "Category C. Potential adverse effects on embryofetal development.",
        "patient_counseling": "Do not break or crush extended-release tablets. Report muscle pain immediately."
    },
    {
        "name": "Erythromycin", "strength": "250 mg", "form": "Oral Tablet", "rxcui": "4053", "atc": "J01FA01",
        "class": "Macrolide Antibacterial", "aliases": ["E.E.S.", "Ery-Tab", "Erythrocin", "Althrocin"],
        "indications": "Streptococcal infections, diphtheria, pertussis, acne vulgaris, and gastroparesis (motility agent).",
        "dosage": "250 mg to 500 mg orally every 6 hours or 333 mg every 8 hours.",
        "contraindications": "Known hypersensitivity; co-administration with terfenadine, astemizole, or cisapride.",
        "warnings": "Hepatic dysfunction, prolonged cardiac repolarization (QT interval), infantile hypertrophic pyloric stenosis.",
        "adverse_reactions": "Severe abdominal cramping, nausea, vomiting, diarrhea, anorexia.",
        "interactions": "Strong CYP3A4 inhibitor; elevates theophylline, carbamazepine, cyclosporine levels.",
        "pregnancy": "Category B. Generally safe in pregnancy.",
        "patient_counseling": "Take with meals if stomach upset occurs, but absorption is highest on an empty stomach."
    },
    {
        "name": "Ciprofloxacin", "strength": "500 mg", "form": "Oral Tablet", "rxcui": "2551", "atc": "J01MA02",
        "class": "Fluoroquinolone Antibacterial", "aliases": ["Cipro", "Ciplox", "Cifran", "Cipro XR"],
        "indications": "Complicated urinary tract infections, pyelonephritis, infectious diarrhea, and anthrax post-exposure.",
        "dosage": "250 mg to 750 mg orally every 12 hours depending on infection site and severity.",
        "contraindications": "Concomitant administration with tizanidine; hypersensitivity to fluoroquinolones.",
        "warnings": "Black Box Warning: Tendinitis and tendon rupture; peripheral neuropathy; CNS toxicities; aortic dissection.",
        "adverse_reactions": "Nausea, diarrhea, elevated transaminases, vomiting, rash, restlessness.",
        "interactions": "Chelation with polyvalent cations (antacids, iron, calcium, sucralfate); increases theophylline and tizanidine levels.",
        "pregnancy": "Category C. Avoid during pregnancy and pediatric patients unless no alternatives exist.",
        "patient_counseling": "Take 2 hours before or 6 hours after dairy or antacids. Discontinue at first sign of tendon pain."
    },
    {
        "name": "Levofloxacin", "strength": "500 mg", "form": "Oral/IV", "rxcui": "82122", "atc": "J01MA12",
        "class": "Fluoroquinolone Antibacterial", "aliases": ["Levaquin", "L-Cin", "Levomac", "Glevo"],
        "indications": "Community-acquired and nosocomial pneumonia, acute bacterial sinusitis, skin infections, and prostatitis.",
        "dosage": "500 mg to 750 mg orally or IV once daily for 5 to 14 days.",
        "contraindications": "Known hypersensitivity to levofloxacin or other quinolones.",
        "warnings": "Black Box Warning: Tendonitis, peripheral neuropathy, CNS effects, QT prolongation, glucose dysregulation.",
        "adverse_reactions": "Nausea, headache, diarrhea, insomnia, dizziness, constipation.",
        "interactions": "Antacids/sucralfate decrease absorption; enhances warfarin anticoagulation; risk of hypoglycemia with sulfonylureas.",
        "pregnancy": "Category C. Excreted in human milk.",
        "patient_counseling": "Maintain adequate hydration. Report any sudden tendon pain, burning, or tingling."
    },
    {
        "name": "Moxifloxacin", "strength": "400 mg", "form": "Oral/IV", "rxcui": "139462", "atc": "J01MA14",
        "class": "Fluoroquinolone Antibacterial", "aliases": ["Avelox", "Vigamox", "Moxicip", "Mahaflox"],
        "indications": "Community-acquired pneumonia, acute bacterial sinusitis, complicated intra-abdominal infections.",
        "dosage": "400 mg orally or IV once daily for 5 to 21 days.",
        "contraindications": "Hypersensitivity to moxifloxacin or fluoroquinolones.",
        "warnings": "Black Box Warning: Tendon rupture, QT prolongation, neuropathy, myasthenia gravis exacerbation.",
        "adverse_reactions": "Nausea, diarrhea, dizziness, headache, vomiting.",
        "interactions": "Class IA and Class III antiarrhythmics (severe QT risk), iron/mineral chelation.",
        "pregnancy": "Category C. Avoid in nursing mothers.",
        "patient_counseling": "Does not require dose adjustment for renal impairment. Report muscle/joint pain."
    },
    {
        "name": "Doxycycline", "strength": "100 mg", "form": "Oral Capsule/Tablet", "rxcui": "3640", "atc": "J01AA02",
        "class": "Tetracycline Antibacterial", "aliases": ["Vibramycin", "Doryx", "Doxt", "Doxylab"],
        "indications": "Rickettsial infections (Lyme disease, Rocky Mountain spotted fever), chlamydia, acne vulgaris, malaria prophylaxis.",
        "dosage": "100 mg orally every 12 hours on day 1, followed by 100 mg once or twice daily.",
        "contraindications": "Hypersensitivity to any tetracycline.",
        "warnings": "Permanent tooth discoloration and enamel hypoplasia in children under 8 years; photosensitivity; pill-induced esophagitis.",
        "adverse_reactions": "Nausea, vomiting, photosensitivity rash, esophageal ulceration, epigastric distress.",
        "interactions": "Antacids, iron, bismuth subsalicylate reduce absorption; decreases penicillin efficacy; enhances warfarin.",
        "pregnancy": "Category D. Contraindicated during pregnancy due to skeletal and dental fetal toxicity.",
        "patient_counseling": "Take with a full glass of water and remain upright for 30 minutes. Use sunscreen."
    },
    {
        "name": "Minocycline", "strength": "100 mg", "form": "Oral Capsule", "rxcui": "6984", "atc": "J01AA08",
        "class": "Tetracycline Antibacterial", "aliases": ["Minocin", "Dynacin", "Solodyn", "Cynomycin"],
        "indications": "Inflammatory lesions of acne vulgaris, skin infections, and meningococcal carrier state.",
        "dosage": "100 mg orally every 12 hours or 1 mg/kg once daily for acne.",
        "contraindications": "Hypersensitivity to tetracyclines.",
        "warnings": "Vestibular side effects (vertigo, dizziness, ataxia), drug-induced lupus-like syndrome, hyperpigmentation.",
        "adverse_reactions": "Dizziness, lightheadedness, nausea, skin pigmentation (blue-gray skin discoloration).",
        "interactions": "Isotretinoin (increases pseudotumor cerebri risk), mineral chelation.",
        "pregnancy": "Category D. Contraindicated in pregnancy and lactation.",
        "patient_counseling": "Avoid driving if dizzy. Avoid prolonged exposure to sunlight or UV lamps."
    },
    {
        "name": "Cephalexin", "strength": "500 mg", "form": "Oral Capsule", "rxcui": "2215", "atc": "J01DB01",
        "class": "First-Generation Cephalosporin", "aliases": ["Keflex", "Phexin", "Sporidex", "Ceff"],
        "indications": "Skin and skin structure infections, streptococcal pharyngitis, uncomplicated cystitis, and bone infections.",
        "dosage": "250 mg to 500 mg orally every 6 hours (or 500 mg every 12 hours) for 7 to 14 days.",
        "contraindications": "Known hypersensitivity to cephalosporins.",
        "warnings": "Cross-sensitivity in penicillin-allergic patients (approximately 1-5%); CDAD.",
        "adverse_reactions": "Diarrhea, nausea, vomiting, dyspepsia, abdominal cramps, genital candidiasis.",
        "interactions": "Probenecid increases serum levels; metformin clearance may be reduced.",
        "pregnancy": "Category B. Generally safe and widely used in pregnancy.",
        "patient_counseling": "Can be taken with food if stomach upset occurs. Finish full prescription."
    },
    {
        "name": "Cefazolin", "strength": "1 g", "form": "IV/IM Injection", "rxcui": "2180", "atc": "J01DB04",
        "class": "First-Generation Cephalosporin", "aliases": ["Ancef", "Kefzol", "Reflin"],
        "indications": "Surgical antimicrobial prophylaxis, MSSA bacteremia, endocarditis, and severe skin infections.",
        "dosage": "1 g to 2 g IV every 8 hours. Preoperative surgical prophylaxis: 2 g IV within 60 minutes prior to incision.",
        "contraindications": "History of severe immediate hypersensitivity to cephalosporins.",
        "warnings": "Dose adjustment required in renal impairment; neurotoxicity and seizures with accumulation.",
        "adverse_reactions": "Injection site pain, phlebitis, eosinophilia, elevated AST/ALT, diarrhea.",
        "interactions": "Aminoglycosides (additive nephrotoxicity risk), probenecid.",
        "pregnancy": "Category B. First-line choice for surgical prophylaxis in pregnancy.",
        "patient_counseling": "Administered parenterally in clinical healthcare settings."
    },
    {
        "name": "Cefuroxime", "strength": "500 mg", "form": "Oral/IV", "rxcui": "2193", "atc": "J01DC02",
        "class": "Second-Generation Cephalosporin", "aliases": ["Ceftin", "Zinacef", "Cefakind", "Altacef"],
        "indications": "Acute bacterial otitis media, pharyngitis/tonsillitis, acute bronchitis, early Lyme disease.",
        "dosage": "250 mg to 500 mg orally twice daily (BD) with food for 7 to 10 days.",
        "contraindications": "Cephalosporin allergy.",
        "warnings": "Jarisch-Herxheimer reaction when treating Lyme disease; cross-reactivity with penicillins.",
        "adverse_reactions": "Diarrhea, nausea, vomiting, transient AST/ALT elevations, Jarisch-Herxheimer reaction.",
        "interactions": "Antacids and H2 blockers reduce bioavailability of cefuroxime axetil tablets.",
        "pregnancy": "Category B. Compatible with pregnancy and nursing.",
        "patient_counseling": "Take tablets with food to enhance oral bioavailability and minimize gastrointestinal irritation."
    },
    {
        "name": "Cefixime", "strength": "200 mg", "form": "Oral Tablet/Capsule", "rxcui": "2186", "atc": "J01DD08",
        "class": "Third-Generation Cephalosporin", "aliases": ["Suprax", "Zifi", "Cefspan", "Taxim-O"],
        "indications": "Uncomplicated gonorrhea, otitis media, pharyngitis, and acute exacerbations of chronic bronchitis.",
        "dosage": "400 mg once daily or 200 mg every 12 hours for 7 to 14 days; 400 mg single dose for gonorrhea.",
        "contraindications": "Hypersensitivity to cephalosporins.",
        "warnings": "Not active against Pseudomonas aeruginosa or Enterococcus; CDAD risk.",
        "adverse_reactions": "Diarrhea (higher incidence than other oral cephalosporins), loose stools, abdominal pain, nausea.",
        "interactions": "Carbamazepine levels may be increased; warfarin prothrombin time prolonged.",
        "pregnancy": "Category B. Safe in pregnancy.",
        "patient_counseling": "Suspension formulation provides higher peak blood levels than tablets for otitis media."
    },
    {
        "name": "Cefdinir", "strength": "300 mg", "form": "Oral Capsule", "rxcui": "86411", "atc": "J01DD15",
        "class": "Third-Generation Cephalosporin", "aliases": ["Omnicef", "Cednir", "Adcef"],
        "indications": "Community-acquired pneumonia, acute exacerbation of chronic bronchitis, acute maxillary sinusitis.",
        "dosage": "300 mg orally every 12 hours or 600 mg once daily for 5 to 10 days.",
        "contraindications": "Known cephalosporin hypersensitivity.",
        "warnings": "Reddish or rust-colored stool when taken with iron supplements due to non-absorbable iron-cefdinir complex.",
        "adverse_reactions": "Diarrhea, vaginal candidiasis, nausea, headache, abdominal pain, red stools.",
        "interactions": "Iron supplements and aluminum/magnesium antacids significantly decrease absorption.",
        "pregnancy": "Category B. Safe for use during pregnancy.",
        "patient_counseling": "Take 2 hours before or after iron-containing supplements. Red stools are harmless."
    },
    {
        "name": "Ceftriaxone", "strength": "1 g", "form": "IV/IM Injection", "rxcui": "2191", "atc": "J01DD04",
        "class": "Third-Generation Cephalosporin", "aliases": ["Rocephin", "Monocef", "Oframax", "Cefaxone"],
        "indications": "Bacterial meningitis, gonococcal infections, pyelonephritis, severe pneumonia, sepsis, Lyme neuroborreliosis.",
        "dosage": "1 g to 2 g IV/IM once daily (every 24 hours). For meningitis: 2 g IV every 12 hours.",
        "contraindications": "Neonates (<=28 days) if receiving calcium-containing IV solutions (fatal ceftriaxone-calcium precipitation); hyperbilirubinemic neonates.",
        "warnings": "Biliary sludging/pseudolithiasis; immune-mediated hemolytic anemia; cross-reactivity with penicillins.",
        "adverse_reactions": "Pain at injection site, diarrhea, eosinophilia, thrombocytosis, biliary colic.",
        "interactions": "Calcium-containing IV diluents (e.g., Ringer's lactate) contraindicated due to precipitation.",
        "pregnancy": "Category B. Crosses placenta but widely established safety record.",
        "patient_counseling": "Administered via deep IM or slow IV infusion by healthcare practitioners."
    },
    {
        "name": "Ceftazidime", "strength": "1 g", "form": "IV/IM Injection", "rxcui": "2190", "atc": "J01DD02",
        "class": "Third-Generation Antipseudomonal Cephalosporin", "aliases": ["Fortaz", "Tazicef", "Megazid"],
        "indications": "Pseudomonas aeruginosa infections, febrile neutropenia, complicated UTIs, intra-abdominal infections.",
        "dosage": "1 g to 2 g IV every 8 hours. Continuous infusion option: 6 g/24 hours.",
        "contraindications": "Cephalosporin allergy.",
        "warnings": "Neurotoxicity (encephalopathy, asterixis, myoclonus, seizures) in unadjusted renal impairment.",
        "adverse_reactions": "Phlebitis, pruritus, fever, positive Coombs test, nausea, diarrhea.",
        "interactions": "Aminoglycosides (additive nephrotoxicity).",
        "pregnancy": "Category B. Compatible with breastfeeding.",
        "patient_counseling": "Administered parenterally with close monitoring of renal function."
    },
    {
        "name": "Cefepime", "strength": "1 g", "form": "IV/IM Injection", "rxcui": "25832", "atc": "J01DE01",
        "class": "Fourth-Generation Cephalosporin", "aliases": ["Maxipime", "Kefepime", "Novapime"],
        "indications": "Hospital-acquired pneumonia, empiric febrile neutropenia monotherapy, complicated intra-abdominal infections.",
        "dosage": "1 g to 2 g IV every 8 to 12 hours depending on infection severity and renal clearance.",
        "contraindications": "Hypersensitivity to cefepime, cephalosporins, or beta-lactams.",
        "warnings": "Neurotoxicity (encephalopathy, myoclonus, seizures, nonconvulsive status epilepticus) especially in renal dysfunction.",
        "adverse_reactions": "Positive direct Coombs test, hypokalemia, diarrhea, rash, elevated transaminases.",
        "interactions": "Probenecid, aminoglycoside additive nephrotoxicity.",
        "pregnancy": "Category B. Safe in pregnancy when clinically indicated.",
        "patient_counseling": "Dose must be adjusted based on renal CrCl. Monitor for confusion or altered mental status."
    },
    {
        "name": "Piperacillin and Tazobactam", "strength": "3.375 g", "form": "IV Infusion", "rxcui": "312437", "atc": "J01CR05",
        "class": "Antipseudomonal Penicillin + Beta-Lactamase Inhibitor", "aliases": ["Zosyn", "Tazocin", "Pipzo", "Tazact"],
        "indications": "Nosocomial pneumonia, complicated intra-abdominal infections, appendicitis, diabetic foot infections.",
        "dosage": "3.375 g to 4.5 g IV every 6 hours (or extended infusion 3.375 g IV over 4 hours every 8 hours).",
        "contraindications": "History of allergic reactions to penicillins, cephalosporins, or beta-lactamase inhibitors.",
        "warnings": "Severe cutaneous adverse reactions (DRESS, SJS/TEN); bleeding manifestations (platelet dysfunction); nephrotoxicity with vancomycin.",
        "adverse_reactions": "Diarrhea, constipation, nausea, headache, insomnia, hypokalemia, rash.",
        "interactions": "Concomitant vancomycin increases acute kidney injury (AKI) risk by 3-fold; methotrexate clearance decreased.",
        "pregnancy": "Category B. Used for severe maternal sepsis.",
        "patient_counseling": "Administered in hospital settings with renal and electrolyte monitoring."
    },
    {
        "name": "Meropenem", "strength": "1 g", "form": "IV Infusion", "rxcui": "67108", "atc": "J01DH02",
        "class": "Carbapenem Antibacterial", "aliases": ["Merrem", "Mero", "Meronem", "Meromac"],
        "indications": "Complicated intra-abdominal infections, bacterial meningitis, complicated skin/soft tissue infections, multi-drug resistant (MDR) infections.",
        "dosage": "500 mg to 1 g IV every 8 hours (2 g IV every 8 hours for meningitis or severe Pseudomonas infections).",
        "contraindications": "Severe hypersensitivity to carbapenems or history of anaphylaxis to beta-lactams.",
        "warnings": "Dramatically reduces serum valproic acid levels leading to breakthrough seizures; seizure risk with accumulation in renal failure.",
        "adverse_reactions": "Headache, nausea, diarrhea, vomiting, rash, local injection site inflammation.",
        "interactions": "Valproic acid / Divalproex (rapid 80-90% drop in valproate levels within 24h - avoid combination).",
        "pregnancy": "Category B. Compatible with breastfeeding.",
        "patient_counseling": "Inform healthcare team if taking valproate or anti-seizure medications."
    },
    {
        "name": "Imipenem and Cilastatin", "strength": "500-500 mg", "form": "IV Infusion", "rxcui": "2181", "atc": "J01DH51",
        "class": "Carbapenem + Renal Dehydropeptidase Inhibitor", "aliases": ["Primaxin", "Cilapen", "Lastinem"],
        "indications": "Severe polymicrobial intra-abdominal, lower respiratory, gynecologic, bone, and skin infections.",
        "dosage": "500 mg IV every 6 hours or 1 g IV every 8 hours (infused over 40-60 minutes).",
        "contraindications": "Hypersensitivity to carbapenems.",
        "warnings": "Highest seizure propensity among carbapenems; avoid in CNS infections or baseline seizure disorders.",
        "adverse_reactions": "Nausea (especially with rapid infusion), vomiting, diarrhea, seizures, phlebitis.",
        "interactions": "Valproic acid (loss of seizure control), ganciclovir (increased risk of generalized seizures).",
        "pregnancy": "Category C. Use only if potential benefit justifies potential risk to fetus.",
        "patient_counseling": "Infuse slowly to prevent nausea. Report any twitching or neurological symptoms."
    },
    {
        "name": "Ertapenem", "strength": "1 g", "form": "IV/IM", "rxcui": "352385", "atc": "J01DH03",
        "class": "Carbapenem Antibacterial", "aliases": ["Invanz", "Ertamac"],
        "indications": "Complicated intra-abdominal, acute pelvic, and diabetic foot infections; outpatient parenteral antimicrobial therapy (OPAT).",
        "dosage": "1 g IV or IM once daily (every 24 hours).",
        "contraindications": "Carbapenem hypersensitivity; severe lidocaine allergy (when IM diluent contains lidocaine).",
        "warnings": "Lacks activity against Pseudomonas aeruginosa and Acinetobacter; CNS toxicity.",
        "adverse_reactions": "Diarrhea, nausea, headache, infused vein complication, vaginitis.",
        "interactions": "Valproic acid / divalproex sodium (loss of seizure control).",
        "pregnancy": "Category B. Safe in pregnancy when indicated.",
        "patient_counseling": "Convenient once-daily dosing enables outpatient IV therapy."
    },
    {
        "name": "Vancomycin", "strength": "1 g", "form": "IV Infusion / Oral Capsule", "rxcui": "11124", "atc": "J01XA01",
        "class": "Glycopeptide Antibacterial", "aliases": ["Vancocin", "Vancocin HCl", "Vanlid", "Vanco"],
        "indications": "IV: MRSA bacteremia, endocarditis, osteomyelitis, pneumonia. Oral: Clostridioides difficile colitis (oral vancomycin is not absorbed systemically).",
        "dosage": "IV: 15 to 20 mg/kg every 8 to 12 hours (target AUC/MIC 400-600 or trough 15-20 mcg/mL). Oral for C. diff: 125 mg orally 4 times daily for 10 days.",
        "contraindications": "Known hypersensitivity to vancomycin.",
        "warnings": "Vancomycin Infusion Reaction ('Red Man Syndrome' histamine release from rapid infusion); nephrotoxicity; ototoxicity.",
        "adverse_reactions": "Nephrotoxicity (elevated creatinine), infusion flush/rash, phlebitis, neutropenia, ototoxicity.",
        "interactions": "Additive nephrotoxicity with piperacillin/tazobactam, aminoglycosides, amphotericin B, and NSAIDs.",
        "pregnancy": "Category B (oral), Category C (IV). Therapeutic drug monitoring required in pregnancy.",
        "patient_counseling": "Infuse IV dose over at least 60 minutes per 1 gram to prevent flushing and rash. Oral form is not effective for systemic infections."
    },
    {
        "name": "Daptomycin", "strength": "500 mg", "form": "IV Infusion", "rxcui": "349251", "atc": "J01XX09",
        "class": "Lipopeptide Antibacterial", "aliases": ["Cubicin", "Cubicin RF", "Daptocid"],
        "indications": "Complicated skin/structure infections, Staphylococcus aureus bacteremia, and right-sided infective endocarditis.",
        "dosage": "4 to 6 mg/kg IV once daily for skin infections; 6 to 10 mg/kg IV once daily for bacteremia/endocarditis.",
        "contraindications": "Known hypersensitivity to daptomycin.",
        "warnings": "Inactivated by pulmonary surfactant - CANNOT be used to treat pneumonia; myopathy and rhabdomyolysis; eosinophilic pneumonia.",
        "adverse_reactions": "Elevated creatine phosphokinase (CPK), myopathy, peripheral neuropathy, diarrhea, insomnia.",
        "interactions": "HMG-CoA reductase inhibitors (statins) increase risk of myopathy and muscle breakdown; temporarily suspend statins.",
        "pregnancy": "Category B. Monitor CPK in breastfed infants.",
        "patient_counseling": "Weekly CPK monitoring mandatory. Report unexplained muscle pain, tenderness, or dark urine immediately."
    },
    {
        "name": "Linezolid", "strength": "600 mg", "form": "Oral Tablet / IV", "rxcui": "284635", "atc": "J01XX08",
        "class": "Oxazolidinone Antibacterial", "aliases": ["Zyvox", "Linospan", "Lizolid", "Linid"],
        "indications": "Vancomycin-resistant Enterococcus faecium (VRE), MRSA nosocomial pneumonia, and complicated skin infections.",
        "dosage": "600 mg orally or IV every 12 hours for 10 to 28 days (100% oral bioavailability).",
        "contraindications": "Concomitant use with monoamine oxidase inhibitors (MAOIs) or within 2 weeks of taking an MAOI.",
        "warnings": "Reversible non-selective MAO inhibitor; risk of Serotonin Syndrome when combined with SSRIs/SNRIs; myelosuppression (thrombocytopenia, anemia) after 2 weeks; optic and peripheral neuropathy.",
        "adverse_reactions": "Thrombocytopenia, anemia, diarrhea, headache, nausea, tongue discoloration.",
        "interactions": "SSRIs, SNRIs, tricyclic antidepressants, triptans (Serotonin Syndrome); tyramine-rich foods (hypertensive crisis); pseudoephedrine.",
        "pregnancy": "Category C. Excreted in breast milk.",
        "patient_counseling": "Weekly complete blood counts (CBC) required. Avoid aged cheese, red wine, and tap beers (tyramine)."
    },
    {
        "name": "Gentamicin", "strength": "80 mg", "form": "IV/IM Injection", "rxcui": "4715", "atc": "J01GB03",
        "class": "Aminoglycoside Antibacterial", "aliases": ["Garamycin", "Genticyn", "Gentabac"],
        "indications": "Gram-negative bacillary infections, sepsis, synergy for enterococcal and streptococcal endocarditis.",
        "dosage": "Extended interval dosing: 5 to 7 mg/kg IV once daily; Conventional: 1 to 2 mg/kg IV every 8 hours.",
        "contraindications": "Hypersensitivity to aminoglycosides.",
        "warnings": "Black Box Warning: Nephrotoxicity (acute tubular necrosis), ototoxicity (vestibular and cochlear - often irreversible), neuromuscular blockade.",
        "adverse_reactions": "Elevated BUN/creatinine, tinnitus, hearing loss, vertigo, ataxia, proteinuria.",
        "interactions": "Loop diuretics (furosemide) increase ototoxicity; neuromuscular blockers (prolonged paralysis); vancomycin/NSAIDs (nephrotoxicity).",
        "pregnancy": "Category D. Known risk of bilateral congenital deafness.",
        "patient_counseling": "Routine peak and trough serum drug level monitoring required. Report ringing in ears or dizziness."
    },
    {
        "name": "Tobramycin", "strength": "80 mg", "form": "IV/Inhalation", "rxcui": "10627", "atc": "J01GB01",
        "class": "Aminoglycoside Antibacterial", "aliases": ["Nebcin", "TOBI", "Tobrex", "Tobacin"],
        "indications": "Pseudomonas aeruginosa pulmonary infections in cystic fibrosis (inhalation); systemic gram-negative sepsis.",
        "dosage": "Inhalation: 300 mg twice daily for 28 days on, 28 days off. IV: 5 to 7 mg/kg once daily.",
        "contraindications": "Aminoglycoside hypersensitivity.",
        "warnings": "Black Box Warning: Ototoxicity, nephrotoxicity, fetal harm.",
        "adverse_reactions": "Voice alteration, bronchospasm (inhalation), tinnitus, acute renal impairment.",
        "interactions": "Nephrotoxic drugs, neuromuscular blocking agents, ethacrynic acid.",
        "pregnancy": "Category D. Fetal eighth cranial nerve damage.",
        "patient_counseling": "Use bronchodilator prior to inhaled tobramycin administration."
    },
    {
        "name": "Amikacin", "strength": "500 mg", "form": "IV/IM Injection", "rxcui": "641", "atc": "J01GB06",
        "class": "Aminoglycoside Antibacterial", "aliases": ["Amikin", "Mikacin", "Amikamac"],
        "indications": "Severe MDR gram-negative infections resistant to gentamicin and tobramycin; Mycobacterium avium complex.",
        "dosage": "15 mg/kg/day IV as single daily dose or divided every 8 to 12 hours.",
        "contraindications": "Aminoglycoside hypersensitivity.",
        "warnings": "Black Box Warning: Nephrotoxicity, ototoxicity, neuromuscular paralysis.",
        "adverse_reactions": "Ototoxicity, elevated serum creatinine, rash, vestibular dysfunction.",
        "interactions": "Amphotericin B, cisplatin, furosemide, vancomycin.",
        "pregnancy": "Category D. Avoid in pregnancy.",
        "patient_counseling": "Therapeutic drug monitoring mandatory. Maintain generous fluid hydration."
    },
    {
        "name": "Metronidazole", "strength": "500 mg", "form": "Oral Tablet / IV", "rxcui": "6922", "atc": "J01XD01",
        "class": "Nitroimidazole Antimicrobial", "aliases": ["Flagyl", "Metrogyl", "Metron", "Flagyl ER"],
        "indications": "Anaerobic bacterial infections, trichomoniasis, amebiasis, giardiasis, bacterial vaginosis, surgical prophylaxis.",
        "dosage": "500 mg orally or IV every 8 hours for 7 to 10 days.",
        "contraindications": "First trimester of pregnancy in trichomoniasis; co-administration with disulfiram within 2 weeks; alcohol consumption during and for 3 days post-treatment.",
        "warnings": "Black Box Warning: Carcinogenic in animal models. Disulfiram-like ethanol reaction; peripheral neuropathy and encephalopathy.",
        "adverse_reactions": "Metallic taste, dark/reddish-brown urine, nausea, headache, abdominal cramps, peripheral neuropathy.",
        "interactions": "Alcohol/propylene glycol (severe vomiting, flushing, tachycardia); Warfarin (doubles INR and bleeding risk); lithium toxicity.",
        "pregnancy": "Category B. Contraindicated in 1st trimester for trichomoniasis; avoid high-dose regimens.",
        "patient_counseling": "STRICTLY avoid alcohol and alcohol-containing cough syrups during and for 72 hours after therapy. Urine may darken."
    },
    {
        "name": "Trimethoprim and Sulfamethoxazole", "strength": "800-160 mg", "form": "Oral Tablet (DS)", "rxcui": "198335", "atc": "J01EE01",
        "class": "Sulfonamide + Dihydrofolate Reductase Inhibitor", "aliases": ["Bactrim DS", "Septra DS", "Bactrim", "Ciplin-DS"],
        "indications": "Uncomplicated cystitis, Pneumocystis jirovecii pneumonia (PCP) prophylaxis and treatment, community-acquired MRSA skin infections.",
        "dosage": "1 DS tablet (800/160 mg) orally every 12 hours for 3 to 14 days.",
        "contraindications": "Known sulfa allergy, severe renal impairment (CrCl <15 mL/min), megaloblastic anemia due to folate deficiency, infants under 2 months.",
        "warnings": "Stevens-Johnson Syndrome (SJS) and Toxic Epidermal Necrolysis (TEN); severe hyperkalemia; hematologic toxicities (agranulocytosis, aplastic anemia).",
        "adverse_reactions": "Nausea, vomiting, hyperkalemia, elevated serum creatinine (benign tubular secretion blockade), rash, photosensitivity.",
        "interactions": "Warfarin (dramatically increases INR - reduce warfarin dose by 50%); ACE inhibitors/ARBs/spironolactone (severe hyperkalemia); methotrexate.",
        "pregnancy": "Category D. Contraindicated at term/near delivery (kernicterus in neonate) and 1st trimester (folate antagonist neural tube defects).",
        "patient_counseling": "Drink plenty of water to prevent crystalluria and kidney stones. Discontinue immediately at first sign of rash or mouth ulcers."
    },
    {
        "name": "Nitrofurantoin", "strength": "100 mg", "form": "Oral Capsule (Macrobid)", "rxcui": "7454", "atc": "J01XE01",
        "class": "Nitrofuran Antibacterial", "aliases": ["Macrobid", "Macrodantin", "Furadantin", "Niftran"],
        "indications": "Treatment and prophylaxis of uncomplicated lower urinary tract infections (acute cystitis) caused by E. coli and Enterococcus.",
        "dosage": "100 mg (Macrobid monohydrate/macrocrystals) orally twice daily with food for 5 days.",
        "contraindications": "Severe renal impairment (eGFR <30 mL/min); history of nitrofurantoin-induced cholestatic jaundice or hepatic dysfunction; pregnant patients at term (38-42 weeks).",
        "warnings": "Pulmonary toxicity (acute hypersensitivity pneumonitis or chronic pulmonary fibrosis with prolonged therapy); peripheral neuropathy; hemolytic anemia in G6PD deficiency.",
        "adverse_reactions": "Nausea, headache, flatulence, brown-colored urine (harmless), anorexia, dizziness.",
        "interactions": "Magnesium antacids reduce absorption; probenecid decreases renal excretion.",
        "pregnancy": "Category B. Contraindicated near term (38 to 42 weeks) due to risk of infant hemolytic anemia.",
        "patient_counseling": "Always take with food or milk to enhance absorption and minimize nausea. Harmlessly turns urine dark brown."
    },
    {
        "name": "Clindamycin", "strength": "300 mg", "form": "Oral Capsule / IV", "rxcui": "2582", "atc": "J01FF01",
        "class": "Lincosamide Antibacterial", "aliases": ["Cleocin", "Dalacin C", "Clindex", "Erytop"],
        "indications": "Serious anaerobic infections, toxic shock syndrome (with penicillin/vancomycin to inhibit toxin synthesis), MRSA skin/soft tissue infections.",
        "dosage": "150 mg to 450 mg orally every 6 hours; IV 600 mg to 900 mg every 8 hours.",
        "contraindications": "History of hypersensitivity to clindamycin or lincomycin; previous regional enteritis, ulcerative colitis, or antibiotic-associated colitis.",
        "warnings": "Black Box Warning: Severe and fatal Clostridioides difficile-associated diarrhea (CDAD) / pseudomembranous colitis.",
        "adverse_reactions": "Diarrhea, abdominal pain, pseudomembranous colitis, nausea, vomiting, metallic taste (IV).",
        "interactions": "Neuromuscular blocking agents (enhances paralysis); erythromycin antagonism.",
        "pregnancy": "Category B. Safe in pregnancy and widely used for penicillin-allergic patients.",
        "patient_counseling": "Take with a full glass of water. Report watery or severe diarrhea immediately even weeks after finishing the medication."
    },
    {
        "name": "Rifampin", "strength": "300 mg", "form": "Oral Capsule", "rxcui": "9384", "atc": "J04AB02",
        "class": "Rifamycin Antimicrobial", "aliases": ["Rifadin", "Rimactane", "R-Cinex", "Macox"],
        "indications": "Tuberculosis (in combination regimens), meningococcal carrier eradication, prosthetic valve staphylococcal endocarditis synergy.",
        "dosage": "600 mg orally once daily (or 300 mg twice daily) on an empty stomach.",
        "contraindications": "Concurrent use with protease inhibitors, delavirdine, or rilpivirine.",
        "warnings": "Extremely potent inducer of hepatic CYP enzymes; hepatotoxicity; orange-red discoloration of body fluids.",
        "adverse_reactions": "Red-orange discoloration of urine, sweat, tears, and saliva; elevated LFTs; nausea; flu-like syndrome with intermittent dosing.",
        "interactions": "Massive CYP3A4/2C9/2C19/P-gp inducer: renders oral contraceptives, warfarin, DOACs, statins, HIV therapies, and tacrolimus ineffective.",
        "pregnancy": "Category C. Maternal clotting defects with third-trimester use.",
        "patient_counseling": "Harmlessly stains tears and urine bright orange; permanently discolors soft contact lenses. Use non-hormonal contraception."
    },
    {
        "name": "Isoniazid", "strength": "300 mg", "form": "Oral Tablet", "rxcui": "6038", "atc": "J04AC01",
        "class": "Antitubercular Agent", "aliases": ["Nydrazid", "INH", "Solonid"],
        "indications": "Treatment of active tuberculosis (with multi-drug regimen) and latent tuberculosis infection (LTBI).",
        "dosage": "300 mg orally once daily on an empty stomach. Always administer with Pyridoxine (Vitamin B6 25-50 mg daily).",
        "contraindications": "Severe hepatic injury or acute liver disease; previous isoniazid-associated hepatitis.",
        "warnings": "Black Box Warning: Severe and sometimes fatal hepatitis (risk increases with age and alcohol consumption); peripheral neuropathy.",
        "adverse_reactions": "Peripheral neuropathy, elevated serum transaminases, hepatitis, nausea, epigastric distress.",
        "interactions": "Inhibits CYP2C19/2C9 (increases phenytoin and carbamazepine levels); alcohol increases hepatotoxicity risk.",
        "pregnancy": "Category C. Co-administer supplemental pyridoxine throughout pregnancy.",
        "patient_counseling": "Take Pyridoxine (Vitamin B6) daily to prevent tingling in hands and feet. Avoid all alcohol. Report yellowing of eyes or skin."
    },
    {
        "name": "Pyrazinamide", "strength": "500 mg", "form": "Oral Tablet", "rxcui": "8999", "atc": "J04AK01",
        "class": "Antitubercular Agent", "aliases": ["Tebrazid", "PZA", "Pyzina"],
        "indications": "Initial 2-month intensive phase treatment of active tuberculosis.",
        "dosage": "15 to 30 mg/kg orally once daily (typically 1,500 mg to 2,000 mg daily).",
        "contraindications": "Severe hepatic damage; acute gout.",
        "warnings": "Hepatotoxicity; hyperuricemia causing acute arthralgias/gout.",
        "adverse_reactions": "Hyperuricemia, arthralgia, hepatotoxicity, nausea, vomiting, sideroblastic anemia.",
        "interactions": "Allopurinol / probenecid efficacy altered; additive hepatotoxicity with rifampin.",
        "pregnancy": "Category C. WHO endorses use in pregnant women with active TB.",
        "patient_counseling": "Report joint pain or signs of liver injury."
    },
    {
        "name": "Ethambutol", "strength": "400 mg", "form": "Oral Tablet", "rxcui": "4109", "atc": "J04AK02",
        "class": "Antitubercular Agent", "aliases": ["Myambutol", "Combutol", "Albutol"],
        "indications": "Treatment of active pulmonary tuberculosis and Mycobacterium avium complex.",
        "dosage": "15 to 25 mg/kg orally once daily.",
        "contraindications": "Known optic neuritis; patients unable to appreciate and report visual acuity changes (young children).",
        "warnings": "Retrobulbar optic neuritis (decreased visual acuity, red-green color blindness) which is dose- and duration-dependent.",
        "adverse_reactions": "Optic neuritis, decreased visual acuity, red-green color discrimination loss, hyperuricemia, peripheral neuropathy.",
        "interactions": "Aluminum hydroxide antacids delay absorption.",
        "pregnancy": "Category C. First-line component for active TB in pregnancy.",
        "patient_counseling": "Monthly visual acuity and color discrimination testing required. Discontinue immediately if vision changes occur."
    }
]

# Additional expansive modules are programmatically generated and merged to reach 500+ distinct clinical monographs
