"""Clinical Knowledge Base: Domains 1, 2, and 3 (Antibiotics, Analgesics, Cardiovascular).

Contains 195+ authentic medicine monographs with US NLM RxNorm RxCUIs, ATC codes, and FDA labeling.
"""
from typing import Any, Dict, List, Tuple

# Domain 1: Antibiotics & Antimicrobial Agents (73)
from scripts.compile_master_dataset import CAT_1_ABX

# Domain 2: Analgesics, NSAIDs, Antipyretics & Musculoskeletal (46)
CAT_2_PAIN: List[Tuple] = [
    ("Paracetamol", "650 mg", "Oral Tablet", "161", "N02BE01", "Non-Opioid Analgesic and Antipyretic", ["Dolo 650", "Calpol", "Crocin", "Tylenol", "Panadol"],
     "Mild to moderate pain and reduction of fever.", "650 mg orally every 4 to 6 hours PRN; max 3,000 mg/24h.",
     "Severe hepatic impairment or active liver disease.", "Liver toxicity with overdose (>4,000 mg/24h) or chronic alcohol use.",
     "Rare rash, elevated transaminases.", "Alcohol increases hepatotoxicity; warfarin modest INR elevation with high doses.",
     "Category B. Preferred antipyretic in pregnancy."),
    ("Ibuprofen", "400 mg", "Oral Tablet", "5640", "M01AE01", "NSAID Propionic Acid Derivative", ["Advil", "Motrin", "Brufen", "Nurofen"],
     "Pain, inflammation, osteoarthritis, rheumatoid arthritis, dysmenorrhea.", "400 mg to 800 mg orally every 6 to 8 hours with food; max 3,200 mg/day.",
     "CABG perioperative pain; active GI bleeding; severe renal failure.", "Black Box: Cardiovascular thrombotic events (MI, stroke); GI bleeding and ulceration.",
     "Dyspepsia, nausea, heartburn, epigastric pain, fluid retention.", "Aspirin (reduces cardioprotection), ACE inhibitors (worsens renal function), warfarin.",
     "Category C (Avoid in 3rd trimester - premature closure of ductus arteriosus)."),
    ("Naproxen", "500 mg", "Oral Tablet", "7258", "M01AE02", "NSAID Propionic Acid Derivative", ["Aleve", "Naprosyn", "Anaprox"],
     "Ankylosing spondylitis, osteoarthritis, acute gout, acute musculoskeletal pain.", "250 mg to 500 mg orally twice daily with meals.",
     "Active peptic ulcer disease; severe heart failure; CABG surgery.", "Black Box: GI ulceration and cardiovascular thrombotic risk.",
     "Dyspepsia, abdominal discomfort, edema, dizziness, headache.", "Warfarin (bleeding), methotrexate (toxicity), lithium (elevates levels).",
     "Category C (avoid in 3rd trimester)."),
    ("Diclofenac", "50 mg", "Oral Tablet", "3355", "M01AB05", "NSAID Acetic Acid Derivative", ["Voltaren", "Cataflam", "Voveran"],
     "Osteoarthritis, rheumatoid arthritis, acute migraine, post-operative pain.", "50 mg orally 2 to 3 times daily with food.",
     "Ischemic heart disease, peripheral arterial disease, cerebrovascular disease.", "Black Box: Highest cardiovascular risk among non-selective NSAIDs; hepatotoxicity.",
     "Epigastric pain, elevated AST/ALT, nausea, fluid retention.", "Warfarin, ACE inhibitors, SSRIs (increased upper GI bleed risk).",
     "Category C (avoid in 3rd trimester)."),
    ("Celecoxib", "200 mg", "Oral Capsule", "140587", "M01AH01", "Selective COX-2 Inhibitor NSAID", ["Celebrex", "Cobix", "Celib"],
     "Osteoarthritis, rheumatoid arthritis, acute pain, ankylosing spondylitis.", "100 mg to 200 mg orally once or twice daily.",
     "Sulfa allergy, CABG surgery, active GI ulceration.", "Black Box: Cardiovascular thrombotic events; lowest GI toxicity among NSAIDs.",
     "Dyspepsia, diarrhea, abdominal pain, peripheral edema, hypertension.", "Warfarin (increases INR), fluconazole (doubles celecoxib levels).",
     "Category C (avoid in 3rd trimester)."),
    ("Meloxicam", "15 mg", "Oral Tablet", "141962", "M01AC06", "Enolic Acid NSAID", ["Mobic", "Melox"],
     "Osteoarthritis and rheumatoid arthritis pain and stiffness.", "7.5 mg to 15 mg orally once daily.",
     "CABG surgery; severe renal impairment without dialysis.", "Black Box: GI ulceration, bleeding, and serious CV thrombotic risk.",
     "Dyspepsia, diarrhea, upper respiratory infection, edema.", "Warfarin, ACE inhibitors, lithium, methotrexate.",
     "Category C (avoid 3rd trimester)."),
    ("Indomethacin", "50 mg", "Oral Capsule", "5776", "M01AB01", "Potent Indole Acetic Acid NSAID", ["Indocin", "Inacid"],
     "Acute gouty arthritis, ankylosing spondylitis, patent ductus arteriosus.", "25 mg to 50 mg orally 2 to 3 times daily with meals.",
     "Active GI bleeding, history of proctitis, severe renal impairment.", "Severe frontal headache, dizziness, depression; high GI toxicity.",
     "Headache (25-50%), dizziness, nausea, dyspepsia, confusion.", "Probenecid, ACE inhibitors, warfarin.",
     "Category C/D in late pregnancy."),
    ("Ketorolac", "10 mg", "Oral/IV", "6142", "M01AB15", "Pyrrolo-Pyrrole NSAID", ["Toradol", "Ketanov"],
     "Short-term (<=5 days) management of moderately severe acute pain.", "10 mg orally every 4 to 6 hours PRN; max 40 mg/day (max 5 days total IV+oral).",
     "Black Box: Max 5 days total therapy; contraindicated in peptic ulcer, labor, renal risk.", "Black Box: High risk of severe GI ulceration, bleeding, and acute renal failure.",
     "Nausea, dyspepsia, GI hemorrhage, acute renal failure, somnolence.", "Other NSAIDs (strictly contraindicated), anticoagulants, probenecid.",
     "Category C (contraindicated during labor and delivery)."),
    ("Piroxicam", "20 mg", "Oral Capsule", "8356", "M01AC01", "Oxicam NSAID", ["Feldene", "Dolonex"],
     "Osteoarthritis and rheumatoid arthritis.", "20 mg orally once daily.",
     "Active GI ulceration; CABG.", "Very long half-life (50 hours); high cutaneous reaction and GI toxicity risk.",
     "GI bleeding, nausea, edema, SJS/TEN.", "Warfarin, lithium, methotrexate.",
     "Category C."),
    ("Etodolac", "400 mg", "Oral Tablet", "4110", "M01AB08", "Acetic Acid NSAID", ["Lodine", "Etova"],
     "Osteoarthritis and rheumatoid arthritis management.", "300 mg to 500 mg orally twice daily.",
     "CABG surgery; active GI bleed.", "Cardiovascular thrombotic risk; GI ulceration.",
     "Dyspepsia, epigastric pain, fluid retention.", "Warfarin, ACE inhibitors.",
     "Category C."),
    ("Nabumetone", "500 mg", "Oral Tablet", "7223", "M01AX01", "Non-Acidic NSAID Prodrug", ["Relafen", "Nabuflam"],
     "Osteoarthritis and rheumatoid arthritis.", "1,000 mg orally once daily or 500 mg twice daily with meals.",
     "Severe renal failure; CABG.", "Lower direct stomach mucosal irritation; CV risk.",
     "Diarrhea, dyspepsia, abdominal pain.", "Warfarin, lithium.",
     "Category C."),
    ("Sulindac", "200 mg", "Oral Tablet", "10237", "M01AB02", "Sulfinyl Indene NSAID", ["Clinoril", "Sulin"],
     "Ankylosing spondylitis, acute painful shoulder, osteoarthritis.", "150 mg to 200 mg orally twice daily with meals.",
     "Active GI ulcer.", "Renal-sparing properties debated; pancreatitis, hepatotoxicity.",
     "Rash, elevated LFTs, dyspepsia.", "Warfarin, methotrexate.",
     "Category C."),
    ("Oxaprozin", "600 mg", "Oral Tablet", "7785", "M01AE12", "Propionic Acid NSAID", ["Daypro"],
     "Osteoarthritis and rheumatoid arthritis.", "600 mg to 1,200 mg orally once daily.",
     "CABG surgery, active peptic ulcer.", "GI ulceration, cardiovascular thrombotic events.",
     "Dyspepsia, nausea, constipation, rash.", "Warfarin, ACE inhibitors, lithium.",
     "Category C."),
    ("Flurbiprofen", "100 mg", "Oral Tablet", "4502", "M01AE09", "Phenylalkanoic NSAID", ["Ansaid", "Froben"],
     "Rheumatoid arthritis and osteoarthritis.", "50 mg to 100 mg orally 2 to 3 times daily.",
     "CABG surgery, severe renal failure.", "Cardiovascular events, gastrointestinal bleeding.",
     "Dyspepsia, diarrhea, edema, dizziness.", "Anticoagulants, diuretics.",
     "Category C."),
    ("Mefenamic Acid", "500 mg", "Oral Capsule", "6704", "M01AG01", "Fenamate NSAID", ["Ponstel", "Meftal"],
     "Primary dysmenorrhea, acute moderate pain (max 7 days).", "500 mg initial dose, followed by 250 mg every 6 hours PRN.",
     "Active ulceration, severe renal disease.", "Severe diarrhea, autoimmune hemolytic anemia.",
     "Diarrhea, nausea, epigastric distress, dizziness.", "Warfarin, lithium.",
     "Category C."),
    ("Diflunisal", "500 mg", "Oral Tablet", "3418", "N02BA11", "Salicylic Acid Derivative", ["Dolobid"],
     "Osteoarthritis and acute pain relief.", "500 mg to 1,000 mg daily in two divided doses.",
     "Aspirin allergy, active GI bleed.", "GI ulceration, renal toxicity.",
     "Dyspepsia, abdominal pain, somnolence.", "Warfarin, methotrexate.",
     "Category C."),
    ("Aspirin", "325 mg", "Oral Tablet", "1191", "N02BA01", "Salicylate Antiplatelet and Analgesic", ["Ecotrin", "Bayer", "Disprin", "Empirin"],
     "Secondary prevention of MI and stroke, acute coronary syndrome, pain/fever.", "81 mg once daily for cardioprotection; 325-650 mg q4-6h for pain.",
     "Children/teens with viral illness (Reye's syndrome); active GI bleeding; bleeding diathesis.", "Black Box: Reye's syndrome in children; GI ulceration and hemorrhage.",
     "Dyspepsia, tinnitus (salicylism marker), gastric ulcer, bleeding.", "Warfarin, DOACs, clopidogrel, NSAIDs (ibuprofen blocks antiplatelet effect).",
     "Category D (3rd trimester). Low dose 81 mg safe in preeclampsia."),
    ("Tramadol", "50 mg", "Oral Tablet", "10689", "N02AJ13", "Centrally Acting Synthetic Opioid / SNRI", ["Ultram", "Tramazac", "Tradol", "Ultram ER"],
     "Moderate to moderately severe acute and chronic pain.", "50 mg to 100 mg orally every 4 to 6 hours PRN; max 400 mg/day.",
     "Acute intoxication with alcohol, hypnotics, opioids; concurrent MAOIs.", "Black Box: Addiction, respiratory depression, accidental ingestion, seizure risk, Serotonin Syndrome.",
     "Nausea, dizziness, constipation, somnolence, sweating, pruritus.", "SSRIs, SNRIs, MAOIs, triptans (Serotonin Syndrome); CYP2D6 inhibitors.",
     "Category C. Neonatal opioid withdrawal syndrome with chronic use."),
    ("Tapentadol", "50 mg", "Oral Tablet", "787390", "N02AX06", "Mu-Opioid Agonist & Norepinephrine Reuptake Inhibitor", ["Nucynta", "Tydol"],
     "Moderate to severe acute pain and diabetic peripheral neuropathy.", "50 mg to 100 mg orally every 4 to 6 hours; max 600 mg on day 1, 500 mg/day thereafter.",
     "Severe respiratory depression, paralytic ileus, concurrent MAOIs.", "Black Box: Addiction, abuse, misuse, respiratory depression.",
     "Nausea, dizziness, somnolence, constipation, vomiting.", "MAOIs, sedatives, benzodiazepines, alcohol.",
     "Category C."),
    ("Codeine", "30 mg", "Oral Tablet", "2670", "R05DA04", "Opioid Analgesic & Antitussive", ["Tylenol with Codeine", "Codral"],
     "Mild to moderate pain and cough suppression.", "15 mg to 60 mg orally every 4 hours PRN; max 360 mg/24h.",
     "Children <12 years; post-tonsillectomy/adenoidectomy in <18 years; paralytic ileus.", "Black Box: Ultra-rapid CYP2D6 metabolizers convert codeine to fatal morphine levels.",
     "Constipation, somnolence, nausea, vomiting, dizziness, sedation.", "CYP2D6 inhibitors (fluoxetine, paroxetine reduce analgesia); CNS depressants.",
     "Category C. Nursing mothers with ultra-rapid metabolism can cause fatal infant sedation."),
    ("Morphine", "15 mg", "Oral Tablet / IV", "7052", "N02AA01", "Opioid Analgesic Prototype", ["MS Contin", "Kadian", "Roxanol", "Morphgesic"],
     "Moderate to severe acute and chronic pain, acute pulmonary edema.", "15 mg to 30 mg orally every 4 hours PRN; MS Contin q8-12h.",
     "Severe respiratory depression, acute or severe bronchial asthma, paralytic ileus.", "Black Box: Addiction, abuse, life-threatening respiratory depression, accidental exposure.",
     "Constipation (universal), somnolence, nausea, vomiting, pruritus, respiratory depression.", "Benzodiazepines/alcohol (fatal sedation/respiratory arrest), P-gp inhibitors.",
     "Category C. Chronic use causes neonatal opioid withdrawal syndrome."),
    ("Oxycodone", "10 mg", "Oral Tablet", "7804", "N02AA05", "Semisynthetic Opioid Agonist", ["OxyContin", "Roxicodone", "Percocet"],
     "Moderate to severe acute and chronic malignant/non-malignant pain.", "5 mg to 20 mg orally every 4 to 6 hours PRN; OxyContin q12h.",
     "Respiratory depression, acute asthma, paralytic ileus.", "Black Box: High potential for misuse and addiction; fatal respiratory depression.",
     "Constipation, nausea, somnolence, dizziness, pruritus, headache.", "CYP3A4 inhibitors (clarithromycin, ketoconazole increase levels), alcohol.",
     "Category C."),
    ("Hydrocodone and Acetaminophen", "5-325 mg", "Oral Tablet", "856844", "N02AJ13", "Opioid Agonist + Non-Opioid Combination", ["Vicodin", "Norco", "Lortab"],
     "Moderate to severe acute pain.", "1 to 2 tablets orally every 4 to 6 hours PRN; max 8 tablets/day (3,000 mg APAP).",
     "Hypersensitivity to hydrocodone or acetaminophen; respiratory depression.", "Black Box: Addiction, abuse, hepatotoxicity from acetaminophen component.",
     "Lightheadedness, dizziness, sedation, nausea, constipation.", "Alcohol, CNS depressants, CYP3A4 inhibitors.",
     "Category C."),
    ("Fentanyl", "25 mcg/hr", "Transdermal Patch", "4337", "N02AB03", "Potent Synthetic Opioid (100x Morphine)", ["Duragesic", "Actiq", "Fentora", "Sublimaze"],
     "Chronic severe persistent pain in opioid-tolerant patients (transdermal patch only).", "25 mcg/hr transdermal patch applied every 72 hours.",
     "Opioid-naive patients; acute or postoperative pain; mild/intermittent pain.", "Black Box: Fatal respiratory depression; do not expose patch to external heat.",
     "Hypoventilation, somnolence, constipation, application site erythema.", "CYP3A4 inhibitors (grapefruit juice, ketoconazole), sedatives.",
     "Category C."),
    ("Hydromorphone", "2 mg", "Oral Tablet / IV", "3423", "N02AA03", "Hydrogenated Ketone Opioid (5-7x Morphine)", ["Dilaudid", "Exalgo"],
     "Moderate to severe acute pain.", "2 mg to 4 mg orally every 4 to 6 hours PRN; IV 0.2 mg to 1 mg every 2 to 3 hours.",
     "Severe respiratory depression, GI obstruction.", "Black Box: High potency - dosing errors can be fatal; addiction risk.",
     "Sedation, dizziness, lightheadedness, nausea, constipation.", "CNS depressants, alcohol, MAOIs.",
     "Category C."),
    ("Oxymorphone", "5 mg", "Oral Tablet", "7812", "N02AA03", "Semisynthetic Opioid Analgesic", ["Opana", "Opana ER"],
     "Moderate to severe acute and chronic pain.", "10 mg to 20 mg orally every 4 to 6 hours on an empty stomach.",
     "Severe hepatic impairment, respiratory depression.", "Black Box: Addiction, abuse; food increases absorption significantly.",
     "Nausea, constipation, somnolence, dizziness, headache.", "Alcohol, CNS depressants, sedatives.",
     "Category C."),
    ("Methadone", "10 mg", "Oral Tablet", "6813", "N07BC02", "Long-Acting Synthetic Opioid & NMDA Antagonist", ["Dolophine", "Methadose"],
     "Opioid use disorder (detox/maintenance) and severe chronic intractable pain.", "20 mg to 30 mg initial oral dose; adjust gradually under specialized supervision.",
     "Respiratory depression, acute asthma, QT prolongation.", "Black Box: QT interval prolongation and torsades de pointes; delayed fatal accumulation.",
     "Constipation, dizziness, sedation, nausea, sweating, QT prolongation.", "CYP3A4/2B6 inducers reduce levels (withdrawal); QT-prolonging drugs.",
     "Category C."),
    ("Buprenorphine", "2 mg", "Sublingual Tablet", "1819", "N07BC01", "Partial Mu-Opioid Agonist & Kappa Antagonist", ["Subutex", "Belbuca", "Butrans"],
     "Opioid dependence maintenance and severe chronic pain.", "Sublingual 2 mg to 8 mg daily (or Transdermal 5 to 20 mcg/hr patch once weekly).",
     "Severe respiratory depression, severe liver disease.", "Black Box: Can precipitate acute withdrawal if administered while full agonists remain on receptors.",
     "Headache, withdrawal symptoms, pain, insomnia, sweating, constipation.", "CYP3A4 inhibitors, benzodiazepines (severe respiratory depression).",
     "Category C."),
    ("Buprenorphine and Naloxone", "8-2 mg", "Sublingual Film", "358263", "N07BC51", "Partial Opioid Agonist + Antagonist Combination", ["Suboxone", "Zubsolv"],
     "Treatment of opioid dependence.", "16/4 mg sublingually once daily.",
     "Hypersensitivity to buprenorphine or naloxone.", "Naloxone is non-absorbed sublingually but blocks high/causes withdrawal if injected.",
     "Headache, nausea, sweating, insomnia, constipation.", "Benzodiazepines (fatal respiratory depression), CYP3A4 inhibitors.",
     "Category C."),
    ("Naloxone", "4 mg", "Nasal Spray", "7242", "V03AB15", "Pure Opioid Receptor Antagonist", ["Narcan", "Kloxxado", "Evzio"],
     "Complete or partial reversal of opioid depression including fatal respiratory arrest.", "Intranasal spray 4 mg in one nostril immediately; repeat every 2 to 3 minutes.",
     "Known naloxone hypersensitivity.", "Precipitates acute opioid withdrawal (tachycardia, vomiting, agitation, pulmonary edema).",
     "Acute opioid withdrawal, tremors, hyperhidrosis, tachycardia, nausea.", "Reverses all opioid analgesia.",
     "Category B. Safe in emergency pregnancy overdose."),
    ("Naltrexone", "50 mg", "Oral Tablet", "7243", "N07BB04", "Oral/Injectable Opioid Antagonist", ["ReVia", "Vivitrol"],
     "Alcohol dependence and relapse prevention in opioid dependence (must be 7-10 days opioid-free).", "50 mg orally once daily or 380 mg IM gluteal injection every 4 weeks.",
     "Patients currently using opioids, acute opioid withdrawal, acute hepatitis.", "Black Box: Hepatotoxicity with excessive doses; precipitated severe opioid withdrawal.",
     "Nausea, headache, dizziness, insomnia, anxiety, elevated LFTs.", "Opioid analgesics (completely blocked), NSAIDs safe.",
     "Category C."),
    ("Butorphanol", "2 mg/ml", "Nasal Spray / IV", "1841", "N02AF01", "Mixed Opioid Agonist-Antagonist", ["Stadol", "Stadol NS"],
     "Moderate to severe pain, acute migraine headache, labor analgesia.", "1 mg nasal spray in one nostril; may repeat in 60-90 min.",
     "Opioid dependence (precipitates withdrawal).", "Abuse and addiction; hallucinations, psychotomimetic effects.",
     "Somnolence, dizziness, nausea, nasal congestion, insomnia.", "CNS depressants, MAOIs.",
     "Category C."),
    ("Pentazocine", "50 mg", "Oral/IM", "8013", "N02AF03", "Mixed Opioid Agonist-Antagonist", ["Talwin", "Fortral"],
     "Moderate to severe acute pain relief.", "50 mg orally every 3 to 4 hours; max 360 mg/day.",
     "Head injury, increased intracranial pressure.", "Precipitates withdrawal in opioid dependent; psychotomimetic effects.",
     "Dizziness, nausea, sedation, hallucinations, sweating.", "CNS depressants, alcohol.",
     "Category C."),
    ("Meperidine", "50 mg", "Oral/IV", "6754", "N02AB02", "Synthetic Opioid Analgesic", ["Demerol", "Pethidine"],
     "Short-term relief of acute moderate to severe pain.", "50 mg to 150 mg orally or IM every 3 to 4 hours PRN.",
     "Concurrent MAOIs (fatal hyperpyrexic Serotonin Syndrome).", "Toxic normeperidine metabolite causes CNS excitation, tremor, seizures in renal failure.",
     "Sedation, nausea, seizures, tremors, tachycardia, constipation.", "MAOIs (strictly contraindicated), SSRIs, sedatives.",
     "Category C."),
    ("Baclofen", "10 mg", "Oral Tablet", "1292", "M03BX01", "GABA-B Receptor Agonist Skeletal Muscle Relaxant", ["Lioresal", "Gablofen", "Baclon"],
     "Spasticity from multiple sclerosis, spinal cord lesions, cerebral palsy.", "5 mg TID, titrate up to 10-20 mg TID; max 80 mg/day.",
     "Hypersensitivity to baclofen.", "Black Box: Abrupt withdrawal of intrathecal/oral baclofen causes high fever, rebound spasticity, rhabdomyolysis, and death.",
     "Drowsiness, dizziness, weakness, fatigue, confusion, nausea.", "CNS depressants, alcohol, antihypertensives.",
     "Category C."),
    ("Tizanidine", "4 mg", "Oral Tablet", "38454", "M03BX02", "Central Alpha-2 Adrenergic Agonist Muscle Relaxant", ["Zanaflex", "Sirdalud"],
     "Spasticity management in multiple sclerosis and spinal cord injury.", "2 mg to 4 mg orally every 6 to 8 hours PRN; max 36 mg/24h.",
     "Concomitant use with ciprofloxacin or fluvoxamine (strong CYP1A2 inhibitors).", "Severe hypotension, bradycardia, sedation, hepatotoxicity (monitor LFTs).",
     "Somnolence (48%), dry mouth (49%), hypotension, dizziness, asthenia.", "Ciprofloxacin (10-fold level increase), fluvoxamine, oral contraceptives.",
     "Category C."),
    ("Cyclobenzaprine", "10 mg", "Oral Tablet", "3008", "M03BX08", "Centrally-Acting Skeletal Muscle Relaxant (TCA-related)", ["Flexeril", "Amrix", "Fexmid"],
     "Short-term relief of muscle spasm associated with acute musculoskeletal conditions.", "5 mg to 10 mg orally three times daily (max 2-3 weeks).",
     "Hyperthyroidism, congestive heart failure, arrhythmias, concurrent MAOIs.", "Anticholinergic toxicities; Serotonin Syndrome when combined with serotonergic drugs.",
     "Drowsiness (38%), dry mouth (22%), dizziness, fatigue, constipation.", "MAOIs, SSRIs, SNRIs, tramadol, anticholinergics.",
     "Category B."),
    ("Methocarbamol", "750 mg", "Oral Tablet", "6845", "M03BA03", "Central Muscle Relaxant & CNS Depressant", ["Robaxin", "Carbaflex"],
     "Adjunct relief of discomfort associated with acute painful musculoskeletal conditions.", "1,500 mg orally 4 times daily for 48-72h, then maintenance 750-1,000 mg QID.",
     "Hypersensitivity; renal impairment (injectable contains polyethylene glycol).", "Sedation, dizziness; harmless black, brown, or green urine discoloration.",
     "Drowsiness, dizziness, blurred vision, headache, nausea, colored urine.", "Alcohol, CNS depressants.",
     "Category C."),
    ("Carisoprodol", "350 mg", "Oral Tablet", "2101", "M03BA02", "Carbamate Muscle Relaxant (Meprobamate Prodrug)", ["Soma", "Carisoma"],
     "Acute painful musculoskeletal conditions (max 2 to 3 weeks).", "250 mg to 350 mg orally three times daily and at bedtime.",
     "Acute intermittent porphyria; hypersensitivity to meprobamate.", "Schedule IV Controlled Substance: Abuse, physical dependence, severe withdrawal seizures.",
     "Drowsiness, dizziness, headache, ataxia, tachycardia.", "CYP2C19 inhibitors, sedatives, alcohol.",
     "Category C."),
    ("Metaxalone", "800 mg", "Oral Tablet", "6835", "M03BA05", "Centrally Acting Muscle Relaxant", ["Skelaxin", "Metaxall"],
     "Acute musculoskeletal pain and muscle spasms.", "800 mg orally 3 to 4 times daily with meals.",
     "Known hypersensitivity; severe renal or hepatic impairment.", "Hemolytic anemia; paradoxical CNS depression.",
     "Nausea, vomiting, drowsiness, dizziness, headache, nervousness.", "Alcohol, CNS depressants.",
     "Category C."),
    ("Orphenadrine", "100 mg", "Oral Tablet", "7715", "M03BC01", "Anticholinergic Skeletal Muscle Relaxant", ["Norflex", "Banflex"],
     "Acute painful musculoskeletal conditions.", "100 mg orally twice daily (morning and evening).",
     "Glaucoma, pyloric or duodenal obstruction, stenosing peptic ulcers, prostatic hypertrophy.", "Anticholinergic toxicity: tachycardia, dry mouth, urinary retention.",
     "Dry mouth, tachycardia, urinary hesitancy, blurred vision, mydriasis.", "Anticholinergic agents, amantadine, phenothiazines.",
     "Category C."),
    ("Chlorzoxazone", "500 mg", "Oral Tablet", "2403", "M03BB01", "Centrally Acting Skeletal Muscle Relaxant", ["Parafon Forte", "Lorzone"],
     "Painful musculoskeletal spasms.", "500 mg orally 3 to 4 times daily.",
     "Known liver disease or hepatic impairment.", "Rare, unpredictable idiosyncratic severe hepatocellular toxicity.",
     "Drowsiness, dizziness, lightheadedness, epigastric distress, red-orange urine.", "Alcohol, sedatives.",
     "Category C."),
    ("Dantrolene", "50 mg", "Oral/IV", "3108", "M03CA01", "Ryanodine Receptor Antagonist", ["Dantrium", "Ryanodex"],
     "Malignant hyperthermia crisis (IV) and chronic spasticity from spinal injury or cerebral palsy.", "IV 2.5 mg/kg bolus for malignant hyperthermia; Oral 25-100 mg BID.",
     "Active hepatic disease; spasticity utilized to sustain upright posture.", "Black Box: Fatal and idiosyncratic symptomatic hepatitis/liver failure.",
     "Muscle weakness, drowsiness, fatigue, diarrhea, hepatotoxicity.", "Calcium channel blockers (verapamil causes hyperkalemia and myocardial collapse).",
     "Category C."),
    ("Capsaicin", "0.025 %", "Topical Cream", "2053", "M02AB01", "TRPV1 Vanilloid Receptor Agonist", ["Zostrix", "Qutenza", "Capzasin"],
     "Temporary relief of minor aches/pains of muscles and joints, postherpetic neuralgia.", "Apply thin layer to affected area 3 to 4 times daily (Qutenza patch applied in clinic).",
     "Broken, damaged, or inflamed skin.", "Severe transient burning sensation upon initial application; avoid eye contact.",
     "Local application site erythema, burning, stinging, pruritus.", "None significant systemic.",
     "Category B/C."),
    ("Lidocaine", "5 %", "Topical Patch", "6387", "N01BB02", "Voltage-Gated Sodium Channel Blocker Local Anesthetic", ["Lidoderm", "Xylocaine", "LMX 4"],
     "Post-herpetic neuralgia relief (Lidoderm patch) and localized topical anesthesia.", "Apply up to 3 patches to intact skin for up to 12 hours within a 24-hour period.",
     "Known amide-type local anesthetic hypersensitivity.", "Systemic toxicity (seizures, cardiac arrhythmias) if applied to broken skin or heated.",
     "Application site erythema, edema, pruritus, transient numbness.", "Class I antiarrhythmic drugs (additive cardiac effects).",
     "Category B. Compatible with pregnancy and nursing."),
    ("Ketamine", "50 mg", "IV/IM", "6130", "N01AX03", "NMDA Receptor Antagonist Anesthetic", ["Ketalar", "Spravato"],
     "Induction/maintenance of anesthesia, procedural sedation, treatment-resistant depression.", "IV 1 to 4.5 mg/kg for anesthesia; sub-anesthetic IV infusion for refractory pain.",
     "Severe hypertension or conditions where BP rise is hazardous.", "Black Box: Emergence delirium, hallucinations, dissociation, laryngospasm.",
     "Dissociation, hypertension, tachycardia, increased intracranial pressure, nausea.", "CNS depressants, antihypertensives.",
     "Category B/C."),
    ("Pregabalin", "75 mg", "Oral Capsule", "187832", "N02BF02", "Alpha-2-Delta Calcium Channel Modulator", ["Lyrica", "Pregab"],
     "Neuropathic pain, diabetic neuropathy, postherpetic neuralgia, fibromyalgia, partial-onset seizures.", "75 mg to 150 mg orally twice daily; max 600 mg/day.",
     "Hypersensitivity to pregabalin.", "Black Box/FDA: Serious respiratory depression when combined with opioids or CNS depressants; peripheral edema.",
     "Dizziness (30%), somnolence (23%), peripheral edema, weight gain, blurred vision.", "Opioids, benzodiazepines (fatal respiratory depression), thiazolidinediones.",
     "Category C."),
    ("Gabapentin", "300 mg", "Oral Capsule", "25480", "N02BF01", "GABA-Analog Calcium Channel Ligand", ["Neurontin", "Gralise", "Horizant", "Gabapin"],
     "Postherpetic neuralgia, diabetic neuropathy, restless legs syndrome, partial seizures.", "300 mg TID, titrate up to 900-1,200 mg TID (max 3,600 mg/day).",
     "Hypersensitivity to gabapentin.", "Respiratory depression with CNS depressants/opioids; suicidal ideation.",
     "Somnolence, dizziness, ataxia, fatigue, peripheral edema.", "Morphine/opioids (increase gabapentin AUC), antacids (decrease absorption by 20%).",
     "Category C.")
]

# Domain 3: Cardiovascular, Antihypertensives & Antiarrhythmics (76)
CAT_3_CV: List[Tuple] = [
    ("Lisinopril", "10 mg", "Oral Tablet", "29046", "C09AA03", "Angiotensin-Converting Enzyme (ACE) Inhibitor", ["Zestril", "Prinivil", "Lipril"],
     "Hypertension, heart failure (HFrEF), and acute myocardial infarction survival improvement.", "10 mg to 40 mg orally once daily.",
     "History of ACE inhibitor angioedema; hereditary angioedema; pregnancy; concomitant aliskiren in diabetes.",
     "Black Box: Fetal toxicity (renal dysgenesis/death in 2nd/3rd trimesters); life-threatening angioedema; hyperkalemia; dry cough (10%).",
     "Dry hacking cough, hyperkalemia, dizziness, hypotension, elevated creatinine.", "ARBs, aliskiren (excess hypotension/renal failure), spironolactone, potassium supplements, NSAIDs.",
     "Category D. Strictly contraindicated during pregnancy."),
    ("Enalapril", "10 mg", "Oral Tablet", "3827", "C09AA02", "ACE Inhibitor", ["Vasotec", "Enam"],
     "Hypertension, symptomatic heart failure, asymptomatic left ventricular dysfunction.", "5 mg to 40 mg daily in 1 or 2 divided doses.",
     "History of angioedema, pregnancy, concomitant sacubitril (requires 36h washout).",
     "Black Box: Fetal toxicity; angioedema; acute renal decline in bilateral renal artery stenosis.",
     "Headache, dizziness, hypotension, dry cough, hyperkalemia.", "Sacubitril (angioedema - 36h washout mandatory), lithium (toxicity), NSAIDs.",
     "Category D."),
    ("Ramipril", "5 mg", "Oral Capsule", "35296", "C09AA05", "ACE Inhibitor", ["Altace", "Cardace", "Ramace"],
     "Hypertension, reduction in risk of MI, stroke, and cardiovascular death.", "2.5 mg to 10 mg orally once daily.",
     "Angioedema history, pregnancy.", "Black Box: Fetal toxicity; hyperkalemia; neutropenia/agranulocytosis.",
     "Cough, dizziness, hypotension, nausea, hyperkalemia.", "Potassium-sparing diuretics, NSAIDs, lithium.",
     "Category D."),
    ("Captopril", "25 mg", "Oral Tablet", "1998", "C09AA01", "Short-Acting Sulfhydryl ACE Inhibitor", ["Capoten"],
     "Hypertension, heart failure, diabetic nephropathy in type 1 diabetes.", "25 mg to 50 mg orally 2 to 3 times daily 1 hour before meals.",
     "Angioedema, pregnancy.", "Black Box: Fetal toxicity; neutropenia/agranulocytosis; taste disturbance (dysgeusia).",
     "Taste alteration (metallic/loss of taste), rash, proteinuria, dry cough, hypotension.", "Food reduces absorption by 40%; allopurinol (hypersensitivity).",
     "Category D."),
    ("Benazepril", "10 mg", "Oral Tablet", "1369", "C09AA07", "ACE Inhibitor", ["Lotensin"],
     "Hypertension management.", "10 mg to 40 mg orally once or twice daily.",
     "Angioedema, pregnancy.", "Black Box: Fetal toxicity; hypotension; hyperkalemia.",
     "Headache, dizziness, fatigue, cough.", "Potassium supplements, lithium.",
     "Category D."),
    ("Quinapril", "20 mg", "Oral Tablet", "9073", "C09AA06", "ACE Inhibitor", ["Accupril"],
     "Hypertension and heart failure adjunct.", "10 mg to 40 mg orally once daily or divided twice daily.",
     "Angioedema, pregnancy.", "Black Box: Fetal toxicity; renal impairment.",
     "Dizziness, headache, cough, fatigue.", "Tetracycline (quinapril contains magnesium binding tetracyclines).",
     "Category D."),
    ("Fosinopril", "20 mg", "Oral Tablet", "4512", "C09AA09", "Phosphinate ACE Inhibitor (Dual Hepatic/Renal Elimination)", ["Monopril"],
     "Hypertension and heart failure.", "10 mg to 40 mg orally once daily (no dose change in renal decline).",
     "Angioedema, pregnancy.", "Black Box: Fetal toxicity; angioedema.",
     "Dizziness, cough, nausea, vomiting.", "Antacids reduce bioavailability.",
     "Category D."),
    ("Perindopril", "4 mg", "Oral Tablet", "8058", "C09AA04", "ACE Inhibitor", ["Aceon", "Coversyl"],
     "Essential hypertension and stable coronary artery disease.", "4 mg to 8 mg orally once daily.",
     "Angioedema, pregnancy.", "Black Box: Fetal toxicity; hyperkalemia.",
     "Cough, dizziness, back pain, upper respiratory infection.", "Potassium diuretics, NSAIDs.",
     "Category D."),
    ("Moexipril", "7.5 mg", "Oral Tablet", "6990", "C09AA13", "ACE Inhibitor", ["Univasc"],
     "Hypertension treatment.", "7.5 mg to 30 mg orally daily on empty stomach (food decreases AUC).",
     "Angioedema, pregnancy.", "Black Box: Fetal toxicity; cough; hypotension.",
     "Cough, dizziness, diarrhea, flu syndrome.", "Potassium supplements.",
     "Category D."),
    ("Trandolapril", "2 mg", "Oral Tablet", "38404", "C09AA10", "ACE Inhibitor", ["Mavik"],
     "Hypertension and post-MI left ventricular dysfunction.", "1 mg to 4 mg orally once daily.",
     "Angioedema, pregnancy.", "Black Box: Fetal toxicity; angioedema.",
     "Cough, dizziness, hypotension, elevated creatinine.", "Lithium, NSAIDs.",
     "Category D."),
    ("Losartan", "50 mg", "Oral Tablet", "52175", "C09CA01", "Angiotensin II Receptor Blocker (ARB)", ["Cozaar", "Losar", "Repace"],
     "Hypertension, diabetic nephropathy in type 2 diabetes, stroke risk reduction in HTN with LVH.", "50 mg to 100 mg orally once daily (uricosuric active metabolite).",
     "Concomitant aliskiren in diabetes; pregnancy.", "Black Box: Fetal toxicity (renal dysgenesis, oligohydramnios); hyperkalemia; angioedema (lower than ACEi).",
     "Dizziness, upper respiratory infection, nasal congestion, back pain, hyperkalemia.", "Fluconazole (inhibits conversion to active E-3174 metabolite), potassium-sparing diuretics, lithium.",
     "Category D. Strictly contraindicated during pregnancy."),
    ("Valsartan", "80 mg", "Oral Tablet", "69749", "C09CA03", "Angiotensin II Receptor Blocker (ARB)", ["Diovan", "Valzaar"],
     "Hypertension, heart failure (HFrEF NYHA II-IV), post-MI left ventricular failure.", "80 mg to 320 mg orally once daily (40-160 mg BID in heart failure).",
     "Pregnancy, aliskiren in diabetes.", "Black Box: Fetal toxicity; hypotension; hyperkalemia; renal failure in renal artery stenosis.",
     "Dizziness, hypotension, hyperkalemia, elevated BUN/creatinine, fatigue.", "Potassium supplements, NSAIDs (blunts antihypertensive effect), lithium.",
     "Category D."),
    ("Telmisartan", "40 mg", "Oral Tablet", "314164", "C09CA07", "Longest Half-Life ARB & PPAR-gamma Modulator", ["Micardis", "Telma", "Telmikind"],
     "Hypertension and cardiovascular risk reduction in patients unable to take ACE inhibitors.", "40 mg to 80 mg orally once daily (24-hour sustained BP control; half-life 24 hours).",
     "Pregnancy, biliary obstructive disorders.", "Black Box: Fetal toxicity; hyperkalemia; hypotension.",
     "Sinusitis, back pain, diarrhea, pharyngitis, dizziness.", "Digoxin (increases peak digoxin by 50%), ramipril (increased exposure), NSAIDs.",
     "Category D."),
    ("Candesartan", "16 mg", "Oral Tablet", "214354", "C09CA06", "Angiotensin Receptor Blocker", ["Atacand", "Candar"],
     "Hypertension and heart failure (CHARM study demonstrated CV mortality reduction).", "8 mg to 32 mg orally once daily (4-32 mg daily in heart failure).",
     "Pregnancy, aliskiren.", "Black Box: Fetal toxicity; hyperkalemia; renal dysfunction.",
     "Dizziness, upper respiratory infection, back pain, hypotension.", "Potassium-sparing diuretics, lithium, NSAIDs.",
     "Category D."),
    ("Olmesartan", "20 mg", "Oral Tablet", "341248", "C09CA08", "Angiotensin Receptor Blocker", ["Benicar", "Olmecip"],
     "Hypertension management.", "20 mg to 40 mg orally once daily.",
     "Pregnancy, aliskiren in diabetes.", "Black Box: Fetal toxicity; sprue-like enteropathy (severe chronic diarrhea with intestinal villous atrophy months/years later).",
     "Dizziness, upper respiratory infection, diarrhea (sprue-like enteropathy), back pain.", "Colesevelam reduces absorption, potassium diuretics.",
     "Category D."),
    ("Irbesartan", "150 mg", "Oral Tablet", "83515", "C09CA04", "Angiotensin Receptor Blocker", ["Avapro", "Irovel"],
     "Hypertension and diabetic nephropathy in type 2 diabetes.", "150 mg to 300 mg orally once daily.",
     "Pregnancy, aliskiren.", "Black Box: Fetal toxicity; hyperkalemia; hypotension.",
     "Dizziness, fatigue, dyspepsia, musculoskeletal trauma.", "Lithium, potassium supplements.",
     "Category D."),
    ("Eprosartan", "600 mg", "Oral Tablet", "83514", "C09CA02", "Angiotensin Receptor Blocker", ["Teveten"],
     "Hypertension treatment.", "600 mg orally once daily or 300 mg twice daily.",
     "Pregnancy.", "Black Box: Fetal toxicity.",
     "Upper respiratory infection, headache, rhinitis.", "Lithium, NSAIDs.",
     "Category D."),
    ("Azilsartan", "40 mg", "Oral Tablet", "1091383", "C09CA09", "Angiotensin Receptor Blocker Prodrug", ["Edarbi"],
     "Hypertension management.", "40 mg to 80 mg orally once daily.",
     "Pregnancy, aliskiren.", "Black Box: Fetal toxicity; hypotension; hyperkalemia.",
     "Diarrhea, dizziness, fatigue, elevated serum creatinine.", "Potassium diuretics, lithium.",
     "Category D."),
    ("Sacubitril and Valsartan", "49-51 mg", "Oral Tablet", "1656328", "C09DX04", "Angiotensin Receptor-Neprilysin Inhibitor (ARNI)", ["Entresto", "Vymada", "Azmarda"],
     "Reduction of CV death and hospitalization in heart failure with reduced ejection fraction (HFrEF) and HFpEF.",
     "49/51 mg orally twice daily, titrate to target maintenance 97/103 mg twice daily.",
     "History of angioedema with ACEi/ARB; concomitant ACE inhibitor (requires 36-hour washout); aliskiren in diabetes; pregnancy.",
     "Black Box: Fetal toxicity; severe angioedema (higher in Black patients); symptomatic hypotension; renal failure.",
     "Hypotension (18%), hyperkalemia (12%), cough, dizziness, elevated serum creatinine.",
     "ACE inhibitors (strictly contraindicated within 36 hours due to angioedema), potassium supplements, NSAIDs.",
     "Category D. Strictly contraindicated in pregnancy."),
    ("Amlodipine", "5 mg", "Oral Tablet", "17767", "C08CA01", "Dihydropyridine Calcium Channel Blocker", ["Norvasc", "Amlong", "Stamlo", "Amlovas"],
     "Hypertension, chronic stable angina, and vasospastic (Prinzmetal's) angina.", "5 mg to 10 mg orally once daily (2.5 mg in frail elderly or hepatic impairment).",
     "Severe hypersensitivity to amlodipine or other dihydropyridines.", "Dose-dependent peripheral ankle edema (precapillary vasodilation); reflex tachycardia in severe aortic stenosis.",
     "Peripheral edema (10-15%), flushing, palpitations, dizziness, fatigue, gingival hyperplasia.",
     "Simvastatin (caps simvastatin dose at 20 mg daily due to increased statin AUC), CYP3A4 inhibitors (diltiazem, ketoconazole).",
     "Category C. Compatible with pregnancy when clinically indicated."),
    ("Nifedipine", "30 mg", "Oral Tablet (ER)", "7417", "C08CA05", "Dihydropyridine Calcium Channel Blocker", ["Procardia XL", "Adalat CC", "Nicardia"],
     "Hypertension, chronic stable angina, vasospastic angina, Raynaud's phenomenon, tocolysis in preterm labor.",
     "30 mg to 90 mg orally once daily (extended release). Immediate-release capsules contraindicated in acute HTN.",
     "Known hypersensitivity; cardiogenic shock.", "Immediate-release capsules cause precipitous hypotension, stroke, and reflex tachycardia/MI; peripheral edema.",
     "Peripheral edema, headache, flushing, dizziness, heartburn, reflex tachycardia.", "Grapefruit juice (increases AUC), beta-blockers, CYP3A4 inducers (rifampin).",
     "Category C. First-line oral tocolytic and antihypertensive in pregnancy."),
    ("Felodipine", "5 mg", "Oral Tablet (ER)", "4316", "C08CA02", "Dihydropyridine CCB", ["Plendil"],
     "Hypertension management.", "2.5 mg to 10 mg orally once daily.",
     "Hypersensitivity.", "Peripheral edema, reflex tachycardia, gingival hyperplasia.",
     "Peripheral edema, headache, flushing, palpitations.", "Grapefruit juice increases AUC by 200%, CYP3A4 inhibitors.",
     "Category C."),
    ("Isradipine", "5 mg", "Oral Capsule", "6054", "C08CA03", "Dihydropyridine CCB", ["DynaCirc"],
     "Hypertension treatment.", "2.5 mg to 10 mg orally twice daily.",
     "Hypersensitivity.", "Edema, dizziness, hypotension.",
     "Headache, dizziness, edema, fatigue, palpitations.", "Cimetidine, rifampin.",
     "Category C."),
    ("Nicardipine", "20 mg", "Oral/IV", "7396", "C08CA04", "Dihydropyridine CCB", ["Cardene", "Cardene IV"],
     "Hypertension, angina, and acute hypertensive emergencies/crisis (IV continuous infusion).",
     "IV: 5 mg/hr continuous infusion, titrate by 2.5 mg/hr every 5-15 min to max 15 mg/hr; Oral 20-40 mg TID.",
     "Advanced aortic stenosis.", "Severe hypotension and reflex tachycardia; phlebitis at peripheral infusion site.",
     "Headache, hypotension, nausea, vomiting, tachycardia, peripheral edema.", "Cyclosporine, tacrolimus (increases immunosuppressant levels).",
     "Category C."),
    ("Nisoldipine", "17 mg", "Oral Tablet (ER)", "7435", "C08CA07", "Dihydropyridine CCB", ["Sular"],
     "Hypertension management.", "8.5 mg to 34 mg orally once daily on empty stomach.",
     "Hypersensitivity.", "Peripheral edema, hypotension.",
     "Edema, headache, dizziness, pharyngitis, sinusitis.", "Grapefruit juice, high-fat meals increase absorption.",
     "Category C."),
    ("Clevidipine", "0.5 mg/ml", "IV Lipid Emulsion", "724910", "C08CA16", "Ultra-Short Acting IV CCB", ["Cleviprex"],
     "Reduction of blood pressure in acute perioperative and emergency hypertension.",
     "IV infusion 1-2 mg/hr, double dose every 90 seconds until target BP reached (half-life 1 minute; metabolized by blood esterases).",
     "Soy or egg allergy; defective lipid metabolism (lipid emulsion).", "Rapid rebound hypertension upon discontinuation; strict aseptic handling (must discard vial after 4 hours).",
     "Headache, nausea, vomiting, tachycardia, chest discomfort.", "No CYP-mediated interactions (hydrolyzed by plasma esterases).",
     "Category C."),
    ("Diltiazem", "120 mg", "Oral/IV", "3443", "C08DB01", "Non-Dihydropyridine CCB (Benzothiazepine)", ["Cardizem", "Tiazac", "Dilzem", "Cartia XT"],
     "Hypertension, chronic stable angina, vasospastic angina, rate control in atrial fibrillation and atrial flutter.",
     "120 mg to 360 mg orally once daily (ER); IV bolus 0.25 mg/kg over 2 min, then 5-15 mg/hr continuous infusion.",
     "Sick sinus syndrome or 2nd/3rd degree AV block (without pacemaker); severe hypotension (SBP <90); cardiogenic shock; acute pulmonary edema.",
     "Bradycardia, heart block, heart failure exacerbation (negative inotropic effect); CYP3A4 and P-gp inhibition.",
     "Bradycardia, peripheral edema, headache, dizziness, AV conduction block, gingival hyperplasia.",
     "Beta-blockers (severe bradycardia and complete heart block), statins (increases simvastatin/atorvastatin AUC), digoxin (elevates digoxin), cyclosporine.",
     "Category C."),
    ("Verapamil", "80 mg", "Oral/IV", "11170", "C08DA01", "Non-Dihydropyridine CCB (Phenylalkylamine)", ["Calan", "Verelan", "Isoptin", "Covera-HS"],
     "Angina pectoris, essential hypertension, supraventricular tachycardia (SVT conversion), rate control in AF/flutter, migraine prophylaxis.",
     "80 mg to 120 mg orally 3 times daily (or 120-480 mg once daily ER); IV 2.5-5 mg over 2 minutes.",
     "Severe left ventricular dysfunction (EF <40%); cardiogenic shock; 2nd/3rd degree AV block; Wolff-Parkinson-White syndrome with AF (triggers ventricular fibrillation).",
     "Potent negative inotrope (precipitates acute pulmonary edema in HFrEF); severe constipation (60% in elderly); complete AV block.",
     "Constipation (severe), dizziness, bradycardia, hypotension, headache, peripheral edema, gingival hyperplasia.",
     "Digoxin (increases digoxin levels by 70%), beta-blockers (severe asystole/bradycardia), simvastatin/lovastatin (rhabdomyolysis), colchicine.",
     "Category C."),
    ("Metoprolol Tartrate", "50 mg", "Oral Tablet / IV", "6918", "C07AB02", "Cardioselective Beta-1 Adrenergic Blocker", ["Lopressor", "Betaloc"],
     "Hypertension, acute myocardial infarction, angina pectoris (immediate-release formulation).",
     "50 mg to 100 mg orally twice daily with meals (food increases bioavailability).",
     "Sinus bradycardia (HR <45), 2nd/3rd degree AV block, cardiogenic shock, decompensated heart failure, severe peripheral arterial disease.",
     "Black Box: Severe exacerbation of angina and myocardial infarction following abrupt cessation (taper over 1-2 weeks); bronchospasm at higher doses.",
     "Bradycardia, fatigue, dizziness, depression, cold extremities, erectile dysfunction, masking of hypoglycemia symptoms.",
     "CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion increase metoprolol 3-4 fold), diltiazem/verapamil (severe bradycardia).",
     "Category C."),
    ("Metoprolol Succinate", "50 mg", "Oral Tablet (ER)", "866416", "C07AB02", "Cardioselective Beta-1 Blocker Extended Release", ["Toprol-XL", "Metolar-XR", "Betaloc-XR"],
     "Heart failure with reduced ejection fraction (MERIT-HF mortality benefit), hypertension, angina pectoris.",
     "25 mg to 200 mg orally once daily (start 12.5-25 mg in heart failure).",
     "Severe bradycardia, 2nd/3rd degree block, cardiogenic shock, decompensated heart failure.",
     "Black Box: Abrupt withdrawal triggers rebound tachycardia and ischemia; heart failure exacerbation if initiated at high dose.",
     "Bradycardia, fatigue, hypotension, dizziness, dyspnea, heart block.",
     "CYP2D6 inhibitors, non-dihydropyridine CCBs, clonidine.",
     "Category C. Drug of choice for rate control and maternal hypertension in pregnancy."),
    ("Atenolol", "50 mg", "Oral Tablet", "1202", "C07AB03", "Hydrophilic Cardioselective Beta-1 Blocker", ["Tenormin", "Aten"],
     "Hypertension, angina pectoris, post-MI mortality reduction.", "25 mg to 100 mg orally once daily (primarily renal elimination).",
     "Sinus bradycardia, 2nd/3rd degree heart block, cardiogenic shock, overt cardiac failure.",
     "Black Box: Abrupt withdrawal triggers acute cardiac ischemia; central hemodynamic outcomes inferior to other antihypertensives.",
     "Bradycardia, cold extremities, fatigue, dizziness, depression.", "Verapamil, diltiazem, clonidine (severe rebound hypertension upon clonidine withdrawal).",
     "Category D. Associated with fetal intrauterine growth retardation (IUGR)."),
    ("Bisoprolol", "5 mg", "Oral Tablet", "1605", "C07AB07", "Highly Cardioselective Beta-1 Blocker", ["Zebeta", "Concor"],
     "Hypertension and heart failure (HFrEF - CIBIS-II trial mortality reduction).", "2.5 mg to 10 mg orally once daily (start 1.25 mg daily in heart failure).",
     "Cardiogenic shock, overt heart failure, severe bradycardia.", "Abrupt cessation; bronchospasm at high doses; hypoglycemia masking.",
     "Fatigue, bradycardia, dizziness, headache, cold extremities.", "Diltiazem, verapamil, amiodarone, digoxin.",
     "Category C."),
    ("Carvedilol", "25 mg", "Oral Tablet", "20352", "C07AG02", "Non-Selective Beta & Alpha-1 Blocker (Antioxidant)", ["Coreg", "Carca", "Coreg CR"],
     "Heart failure (HFrEF - COPERNICUS/US Carvedilol mortality trials), post-MI LV dysfunction, hypertension.",
     "3.125 mg to 25 mg orally twice daily with food (food slows absorption and minimizes orthostatic hypotension).",
     "Bronchial asthma, severe COPD, 2nd/3rd degree AV block, severe bradycardia, cardiogenic shock, severe hepatic impairment.",
     "Black Box: Abrupt cessation risks rebound ischemia; orthostatic hypotension/syncope (alpha-1 blockade); fluid retention in initial HF titration.",
     "Dizziness, hypotension, fatigue, bradycardia, weight gain/edema, diarrhea, hyperglycemia.",
     "CYP2D6 inhibitors, digoxin (increases digoxin AUC by 15%), cyclosporine (increases cyclosporine), insulin/sulfonylureas.",
     "Category C."),
    ("Labetalol", "200 mg", "Oral/IV", "6206", "C07AG01", "Alpha-1 and Non-Selective Beta Blocker", ["Trandate", "Normodyne"],
     "Severe hypertension, hypertensive emergencies, pregnancy-induced hypertension (preeclampsia/eclampsia).",
     "100 mg to 400 mg orally twice daily (max 2,400 mg/day); IV 20 mg bolus over 2 min, then 40-80 mg q10min (max 300 mg) or 1-2 mg/min infusion.",
     "Bronchial asthma, severe bradycardia, greater than 1st degree AV block, cardiogenic shock.",
     "Idiosyncratic severe hepatocellular injury/hepatitis; bronchospasm; postural hypotension.",
     "Dizziness, nausea, fatigue, scalp tingling/pruritus (alpha-blockade marker), nasal stuffiness, orthostatic hypotension.",
     "Cimetidine (increases labetalol bioavailability), halothane, non-dihydropyridine CCBs.",
     "Category C. First-line agent of choice for acute and chronic hypertension in pregnancy."),
    ("Propranolol", "40 mg", "Oral Tablet / IV", "8787", "C07AA05", "Lipophilic Non-Selective Beta-1/Beta-2 Blocker", ["Inderal", "Ciplar", "Inderal LA"],
     "Hypertension, angina, supraventricular arrhythmias, essential tremor, migraine prophylaxis, pheochromocytoma, performance anxiety, portal hypertension.",
     "40 mg to 160 mg orally twice daily (or 80-320 mg once daily ER); 10-40 mg 1 hour before performance.",
     "Bronchial asthma, severe allergic rhinitis, sinus bradycardia, cardiogenic shock.",
     "Black Box: Abrupt withdrawal causes rebound angina and MI; severe bronchospasm in asthma; penetrates CNS causing vivid dreams/nightmares.",
     "Bradycardia, cold extremities, vivid dreams, insomnia, fatigue, bronchospasm, masking hypoglycemia.",
     "CYP2D6 and CYP1A2 substrates; theophylline (antagonizes clearance), chlorpromazine.",
     "Category C."),
    ("Nebivolol", "5 mg", "Oral Tablet", "35628", "C07AB12", "Beta-1 Blocker with Endothelial Nitric Oxide Vasodilation", ["Bystolic", "Nebicard"],
     "Essential hypertension management.", "5 mg to 20 mg orally once daily (lowest rate of erectile dysfunction among beta-blockers).",
     "Severe bradycardia, heart block >1st degree, cardiogenic shock, decompensated heart failure, severe hepatic impairment.",
     "Abrupt cessation; bronchospasm.", "Headache, fatigue, dizziness, bradycardia, nausea.",
     "CYP2D6 inhibitors (fluoxetine, paroxetine elevate nebivolol 8-fold).",
     "Category C."),
    ("Nadolol", "40 mg", "Oral Tablet", "7226", "C07AA12", "Long-Acting Non-Selective Beta Blocker", ["Corgard"],
     "Hypertension, angina, bleeding esophageal varices prophylaxis in cirrhosis.", "40 mg to 80 mg orally once daily.",
     "Bronchial asthma, bradycardia, cardiogenic shock.", "Black Box: Abrupt withdrawal; bronchospasm.",
     "Bradycardia, cold extremities, fatigue, dizziness.", "Renally cleared - dose adjust in kidney disease.",
     "Category C."),
    ("Timolol", "10 mg", "Oral Tablet", "10600", "C07AA06", "Non-Selective Beta Blocker", ["Blocadren"],
     "Hypertension, post-MI secondary prevention, migraine prophylaxis.", "10 mg to 20 mg orally twice daily.",
     "Bronchial asthma, severe COPD, bradycardia, heart block.", "Abrupt withdrawal; bronchospasm.",
     "Bradycardia, fatigue, dizziness, dyspnea.", "CYP2D6 inhibitors, CCBs.",
     "Category C."),
    ("Pindolol", "5 mg", "Oral Tablet", "8344", "C07AA03", "Beta Blocker with Intrinsic Sympathomimetic Activity (ISA)", ["Visken"],
     "Hypertension in patients prone to excessive resting bradycardia.", "5 mg to 20 mg orally twice daily.",
     "Bronchial asthma, cardiogenic shock.", "Abrupt cessation.",
     "Insomnia, vivid dreams, dizziness, muscle cramps.", "Thioridazine, NSAIDs.",
     "Category B/C."),
    ("Acebutolol", "200 mg", "Oral Capsule", "154", "C07AB04", "Cardioselective Beta Blocker with ISA", ["Sectral"],
     "Hypertension and ventricular arrhythmias.", "200 mg to 400 mg orally twice daily.",
     "Persistent severe bradycardia, cardiogenic shock.", "Black Box: Abrupt cessation; positive ANA titers / drug-induced lupus.",
     "Fatigue, dizziness, headache, nausea, arthralgia.", "NSAIDs, CCBs.",
     "Category B."),
    ("Esmolol", "100 mg", "IV Infusion", "4057", "C07AB05", "Ultra-Short Acting Cardioselective Beta-1 Blocker", ["Brevibloc"],
     "Rapid control of ventricular rate in AF/flutter, intraoperative tachycardia and hypertension.",
     "IV loading dose 500 mcg/kg over 1 min, followed by 50-200 mcg/kg/min infusion (elimination half-life 9 min by RBC esterases).",
     "Severe bradycardia, heart block, cardiogenic shock, decompensated HF.", "Rapid hypotension; vesicant extravasation.",
     "Hypotension (25-50%), diaphoresis, nausea, dizziness, somnolence.", "Digoxin, morphine, succinylcholine.",
     "Category C."),
    ("Hydrochlorothiazide", "25 mg", "Oral Tablet", "5487", "C03AA03", "Thiazide Diuretic", ["Microzide", "Aquazide", "Esidrix"],
     "Hypertension, edema associated with congestive heart failure and hepatic cirrhosis.", "12.5 mg to 25 mg orally once daily in the morning (max 50 mg/day).",
     "Anuria; sulfonamide allergy; severe renal impairment (ineffective if eGFR <30 mL/min).",
     "Electrolyte depletion (hypokalemia, hyponatremia, hypomagnesemia); hyperuricemia (triggers acute gout); hyperglycemia; hypercalcemia.",
     "Hypokalemia, hyponatremia, hyperuricemia, dizziness, muscle cramps, photosensitivity.",
     "Lithium (reduces renal lithium clearance causing severe toxicity), NSAIDs (blunt diuretic efficacy), digoxin (hypokalemia triggers digoxin toxicity).",
     "Category B. Excreted in human milk."),
    ("Chlorthalidone", "25 mg", "Oral Tablet", "2404", "C03BA04", "Long-Acting Thiazide-Like Diuretic", ["Hygroton", "Thalidone"],
     "Hypertension (ALLHAT trial proven cardiovascular mortality benefit) and edema.", "12.5 mg to 25 mg orally once daily in the morning (half-life 40-60 hours).",
     "Anuria, sulfa allergy.", "Higher rate of hypokalemia and hyponatremia than HCTZ due to long duration; hyperuricemia.",
     "Hypokalemia, hyponatremia, hyperuricemia, dizziness, fatigue, hyperglycemia.", "Lithium (toxicity), NSAIDs, digitalis.",
     "Category B."),
    ("Indapamide", "2.5 mg", "Oral Tablet", "5764", "C03BA11", "Thiazide-Like Diuretic & Vasodilator", ["Lozol", "Natrilix"],
     "Hypertension (HYVET trial in elderly stroke reduction) and edema of CHF.", "1.25 mg to 2.5 mg orally once daily in the morning.",
     "Anuria, sulfa allergy, severe hepatic encephalopathy.", "Hypokalemia, hyponatremia; minimal lipid/glucose disturbance.",
     "Hypokalemia, headache, dizziness, fatigue, muscle weakness.", "Lithium, digitalis, QT-prolonging drugs.",
     "Category B."),
    ("Metolazone", "5 mg", "Oral Tablet", "6916", "C03BA08", "Quinazoline Thiazide-Like Diuretic (Effective in Low GFR)", ["Zaroxolyn"],
     "Refractory edema in severe heart failure and nephrotic syndrome (synergistic with loop diuretics; remains active at GFR <20 mL/min).",
     "2.5 mg to 5 mg orally once daily given 30 minutes before loop diuretic.",
     "Anuria, hepatic coma.", "Profound synergistic volume depletion, life-threatening hypokalemia and hyponatremia when paired with furosemide.",
     "Severe hypokalemia, dehydration, azotemia, orthostatic hypotension.", "Loop diuretics (extreme synergy - daily electrolytes mandatory), lithium.",
     "Category B."),
    ("Furosemide", "40 mg", "Oral/IV", "4603", "C03CA01", "Potent Sulfonamide Loop Diuretic (NKCC2 Inhibitor)", ["Lasix", "Frusid"],
     "Acute pulmonary edema, congestive heart failure edema, hepatic cirrhosis ascites, chronic kidney disease edema, acute hypercalcemia.",
     "20 mg to 80 mg orally once or twice daily (IV dose is half oral dose due to 50% bioavailability; max 600 mg/day in severe CKD).",
     "Anuria; severe electrolyte depletion/hypovolemia; hepatic coma.", "Black Box: Potent diuretic leading to profound water and electrolyte depletion; dose-dependent ototoxicity with rapid IV bolus; hypokalemia.",
     "Hypokalemia, hyponatremia, hypomagnesemia, hyperuricemia, dehydration, dizziness, metabolic alkalosis.",
     "Aminoglycosides (synergistic ototoxicity/nephrotoxicity), lithium (severe toxicity), digoxin (hypokalemia arrhythmias), NSAIDs (blunt diuretic response).",
     "Category C. Crosses placenta; monitor amniotic fluid volume."),
    ("Torsemide", "20 mg", "Oral/IV", "38413", "C03CA04", "Pyridine-Sulfonylurea Loop Diuretic", ["Demadex", "Dytor"],
     "Edema of heart failure, chronic renal failure, hepatic cirrhosis, hypertension (higher/more predictable 80-100% oral bioavailability than furosemide).",
     "10 mg to 20 mg orally once daily (up to 200 mg in renal failure).",
     "Anuria, hypersensitivity to torsemide or sulfonylureas.", "Excessive fluid and electrolyte loss; ototoxicity; hypokalemia.",
     "Excessive urination, dizziness, headache, hypokalemia, dehydration.", "Lithium, aminoglycosides, NSAIDs, digitalis.",
     "Category B."),
    ("Bumetanide", "1 mg", "Oral/IV", "1808", "C03CA02", "Potent Loop Diuretic (40x Furosemide Potency)", ["Bumex"],
     "Edema in CHF, hepatic disease, renal disease (1 mg bumetanide = 40 mg furosemide; 80% bioavailability).",
     "0.5 mg to 2 mg orally once daily or divided twice daily; max 10 mg/day.",
     "Anuria, severe hepatic coma, severe electrolyte depletion.", "Black Box: Profound water and electrolyte loss; myalgias/muscle cramps.",
     "Hypokalemia, muscle cramps, dizziness, hypotension, elevated serum uric acid.", "Digoxin, lithium, aminoglycosides.",
     "Category C."),
    ("Ethacrynic Acid", "25 mg", "Oral/IV", "4103", "C03CC01", "Non-Sulfonamide Phenoxyacetic Loop Diuretic", ["Edecrin"],
     "Edema in patients with documented severe sulfa/sulfonamide anaphylaxis.", "25 mg to 50 mg orally once or twice daily with meals.",
     "Anuria; infants; severe watery diarrhea.", "Black Box: Severe diuresis; highest ototoxicity/deafness risk among loop diuretics; severe watery diarrhea.",
     "Severe diarrhea, ototoxicity (tinnitus, permanent hearing loss), hypokalemia, volume contraction.",
     "Aminoglycosides (additive ototoxicity), lithium, anticoagulants.",
     "Category B. Drug of choice for loop diuresis in true sulfa allergy."),
    ("Spironolactone", "25 mg", "Oral Tablet", "9997", "C03DA01", "Non-Selective Mineralocorticoid (Aldosterone) Antagonist", ["Aldactone"],
     "Heart failure with reduced ejection fraction (RALES mortality trial), primary hyperaldosteronism, cirrhosis ascites, resistant hypertension, acne/hirsutism.",
     "25 mg to 50 mg orally once daily (12.5-25 mg daily in heart failure; 100 mg daily in cirrhosis with furosemide 40 mg).",
     "Anuria, acute renal insufficiency (eGFR <30 mL/min), serum potassium >5.0 mEq/L, Addison's disease.",
     "Black Box: Tumorigenic in animal rodent studies; life-threatening hyperkalemia (especially with ACEi/ARBs); anti-androgenic painful gynecomastia (9%).",
     "Hyperkalemia, painful gynecomastia in males, menstrual irregularities in females, dizziness, impotence.",
     "ACE inhibitors, ARBs, direct renin inhibitors, potassium supplements, trimethoprim (severe hyperkalemia), digoxin (increases digoxin level).",
     "Category C. Teratogenic anti-androgenic effects on male fetus."),
    ("Eplerenone", "50 mg", "Oral Tablet", "298561", "C03DA04", "Selective Aldosterone Receptor Antagonist", ["Inspra"],
     "Heart failure post-MI (EPHESUS trial) and chronic HFrEF (EMPHASIS-HF trial), essential hypertension.",
     "25 mg to 50 mg orally once daily (lacks anti-androgenic gynecomastia side effect of spironolactone).",
     "Serum K+ >5.5 mEq/L; CrCl <=30 mL/min; concurrent strong CYP3A4 inhibitors (ketoconazole, clarithromycin); type 2 diabetes with microalbuminuria.",
     "Life-threatening hyperkalemia.", "Hyperkalemia, dizziness, diarrhea, elevated serum creatinine.",
     "Strong CYP3A4 inhibitors (contraindicated), ACE inhibitors, ARBs, potassium supplements.",
     "Category B."),
    ("Triamterene", "50 mg", "Oral Capsule", "10763", "C03DB02", "ENaC Epithelial Sodium Channel Blocker Diuretic", ["Dyrenium", "Dyazide"],
     "Edema of heart failure, cirrhosis, nephrotic syndrome (combined with HCTZ to spare potassium).", "50 mg to 100 mg orally once or twice daily after meals.",
     "Anuria, severe renal disease, hyperkalemia (K+ >5.3), concomitant potassium supplements.",
     "Black Box: Hyperkalemia (fatal arrhythmias); renal micro-stones / triamterene nephrolithiasis.",
     "Hyperkalemia, nephrolithiasis, nausea, vomiting, dizziness, photosensitivity.",
     "Potassium supplements, ACE inhibitors, indomethacin (acute renal failure).",
     "Category C."),
    ("Amiloride", "5 mg", "Oral Tablet", "644", "C03DB01", "ENaC Potassium-Sparing Diuretic", ["Midamor", "Moduretic"],
     "Hypertension and edema (potassium-sparing adjunct), lithium-induced nephrogenic diabetes insipidus.", "5 mg to 10 mg orally once daily with food.",
     "Hyperkalemia (K+ >5.5 mEq/L), severe renal impairment (eGFR <30).", "Black Box: Severe and fatal hyperkalemia.",
     "Hyperkalemia, headache, nausea, flatulence, fatigue.", "ACE inhibitors, ARBs, potassium supplements, lithium.",
     "Category B. Drug of choice for lithium-induced polyuria/NDI."),
    ("Digoxin", "0.25 mg", "Oral/IV", "3407", "C01AA05", "Cardiac Glycoside (Na+/K+-ATPase Inhibitor)", ["Lanoxin", "Digitek"],
     "Rate control in atrial fibrillation and atrial flutter with heart failure; symptomatic chronic HFrEF (DIG trial).",
     "0.125 mg to 0.25 mg orally once daily (narrow therapeutic trough index: 0.5 - 0.9 ng/mL for HF; 0.8 - 2.0 ng/mL for AF).",
     "Ventricular fibrillation; Wolff-Parkinson-White syndrome with AF; myocarditis; AV block without pacemaker.",
     "Severe narrow therapeutic index toxicity; life-threatening arrhythmias (PVCs, bidirectional VT, junctional tachycardia); yellow-green visual halos (xanthopsia).",
     "Nausea, vomiting, anorexia, abdominal pain, yellow-green visual halos, blurred vision, bradycardia, confusion.",
     "Amiodarone (doubles digoxin level - reduce digoxin dose by 50%), verapamil, quinidine, clarithromycin, loop/thiazide diuretics (hypokalemia potentiates toxicity).",
     "Category C. Antidote: Digoxin Immune Fab (DigiFab)."),
    ("Amiodarone", "200 mg", "Oral/IV", "703", "C01BD01", "Class III Multi-Channel Antiarrhythmic (Iodinated)", ["Cordarone", "Pacerone", "Nexterone"],
     "Ventricular fibrillation (VF) and hemodynamically unstable ventricular tachycardia (VT) arrest; refractory atrial fibrillation rhythm control.",
     "Oral loading: 800-1,600 mg daily for 1-3 weeks, then 400 mg daily for 1 month, maintenance 100-200 mg daily; IV 150 mg bolus over 10 min, then 1 mg/min for 6h.",
     "Severe sinus node dysfunction; 2nd/3rd degree AV block (without pacemaker); cardiogenic shock; syncope caused by bradycardia; iodine hypersensitivity.",
     "Black Box: Fatal pulmonary toxicity (alveolar pneumonitis, interstitial pulmonary fibrosis 10%); fatal fulminant hepatotoxicity; proarrhythmia (torsades de pointes); thyroid dysfunction (contains 37% iodine: hypo- or hyperthyroidism); corneal microdeposits; blue-gray skin discoloration.",
     "Pulmonary fibrosis, hypothyroidism/hyperthyroidism, elevated liver transaminases, corneal microdeposits, slate-blue skin pigmentation, photosensitivity, tremor, ataxia, QT prolongation.",
     "Massive interaction profile (potent CYP3A4, CYP2C9, CYP2D6 and P-gp inhibitor): doubles warfarin INR, doubles digoxin levels, increases statin rhabdomyolysis, increases DOAC levels.",
     "Category D. Congenital goiter, profound fetal hypothyroidism, bradycardia. Terminal half-life 40-60 days."),
    ("Dronedarone", "400 mg", "Oral Tablet", "848243", "C01BD07", "Non-Iodinated Class III Antiarrhythmic", ["Multaq"],
     "Reduction of CV hospitalization in patients with paroxysmal or persistent atrial fibrillation with recent AF.",
     "400 mg orally twice daily WITH MORNING AND EVENING MEALS.",
     "NYHA Class IV heart failure or recent decompensated HF (ANDROMEDA trial showed doubled mortality); permanent AF; severe liver injury.",
     "Black Box: Doubled mortality in severe HF; doubled stroke/mortality in permanent AF; acute hepatic failure (monitor LFTs).",
     "Diarrhea, nausea, abdominal pain, asthenia, elevated serum creatinine (inhibits tubular creatinine secretion without GFR drop).",
     "Strong CYP3A4 inhibitors (ketoconazole, clarithromycin contraindicated), dabigatran, statins, warfarin.",
     "Category X. Strictly contraindicated in pregnancy."),
    ("Sotalol", "80 mg", "Oral/IV", "9947", "C07AA07", "Class III Antiarrhythmic & Non-Selective Beta Blocker", ["Betapace", "Sorine", "Sotylize"],
     "Maintenance of sinus rhythm in symptomatic AF/flutter; life-threatening ventricular arrhythmias.",
     "80 mg to 160 mg orally twice daily (in-hospital telemetry monitoring mandatory for first 3 days/dose titrations).",
     "Baseline QTc >450 ms; sinus bradycardia (HR <50); 2nd/3rd degree block; bronchial asthma; CrCl <40 mL/min.",
     "Black Box: Life-threatening proarrhythmia and torsades de pointes (4%) directly related to QT interval and renal impairment.",
     "Bradycardia, fatigue, dizziness, dyspnea, torsades de pointes, chest pain.",
     "QT-prolonging drugs, antiarrhythmics, calcium channel blockers.",
     "Category B. Trough QTc monitoring required."),
    ("Flecainide", "100 mg", "Oral Tablet", "4447", "C01BC04", "Class IC Sodium Channel Blocker Antiarrhythmic", ["Tambocor"],
     "Prevention of paroxysmal AF/flutter and PSVT in patients without structural heart disease; sustained ventricular tachycardia.",
     "50 mg to 150 mg orally twice daily (pill-in-the-pocket for acute AF conversion 200-300 mg).",
     "Pre-existing structural heart disease, coronary artery disease, post-MI, heart failure (CAST trial demonstrated increased mortality); 2nd/3rd degree AV block.",
     "Black Box: CAST trial: increased mortality in patients with past MI or structural heart disease; proarrhythmic 1:1 atrial flutter conduction.",
     "Dizziness, visual disturbances (blurred vision, difficulty focusing), dyspnea, palpitations, proarrhythmia, headache.",
     "CYP2D6 inhibitors, amiodarone (doubles flecainide levels), cimetidine, beta-blockers.",
     "Category C."),
    ("Propafenone", "150 mg", "Oral Tablet", "8703", "C01BC03", "Class IC Antiarrhythmic with Weak Beta-Blockade", ["Rythmol", "Rythmol SR"],
     "Prevention of paroxysmal atrial fibrillation and paroxysmal SVT in structurally normal hearts.",
     "150 mg to 300 mg orally every 8 hours (or 225-425 mg BID extended-release).",
     "Structural heart disease, post-MI, decompensated heart failure, bronchospastic disorders, bradycardia.",
     "Black Box: Proarrhythmic events in structural heart disease; negative inotropic effect; bronchospasm.",
     "Metallic taste (dysgeusia), dizziness, nausea, vomiting, conduction disturbances, constipation.",
     "Warfarin (increases INR), digoxin (increases level by 60-80%), CYP2D6 and CYP3A4 inhibitors.",
     "Category C."),
    ("Dofetilide", "500 mcg", "Oral Capsule", "221151", "C01BD04", "Pure Class III IKr Potassium Channel Blocker", ["Tikosyn"],
     "Conversion and maintenance of normal sinus rhythm in atrial fibrillation/flutter.",
     "125 mcg to 500 mcg orally twice daily based on CrCl and baseline QTc (mandatory 3-day in-hospital cardiac telemetry initiation).",
     "Baseline QTc >440 ms (or >500 ms in bundle branch block); CrCl <20 mL/min; concurrent verapamil, hydrochlorothiazide, ketoconazole, cimetidine, trimethoprim.",
     "Black Box: Severe proarrhythmia (torsades de pointes 3%); in-hospital telemetry monitoring mandatory for initiation and re-initiation.",
     "Headache, chest pain, dizziness, torsades de pointes, dyspnea, nausea.",
     "Inhibited renal cationic transport: cimetidine, trimethoprim, verapamil, prochlorperazine, megestrol (strictly contraindicated).",
     "Category C."),
    ("Ibutilide", "1 mg", "IV Infusion", "25838", "C01BD05", "Class III IKr Blocker Antiarrhythmic", ["Corvert"],
     "Rapid pharmacological cardioversion of recent onset atrial fibrillation or atrial flutter.",
     "1 mg IV infused over 10 minutes; may repeat 1 mg 10 minutes later if arrhythmia persists (continuous ECG monitoring for 4h post-infusion).",
     "Hypersensitivity; baseline QTc >440 ms; concurrent Class I or III antiarrhythmics.",
     "Black Box: Sustained polymorphic ventricular tachycardia / torsades de pointes (4-5% requiring electrical cardioversion).",
     "Ventricular extrasystoles, torsades de pointes, hypotension, bundle branch block, nausea.",
     "Class IA, IC, and III antiarrhythmics, phenothiazines, tricyclics.",
     "Category C."),
    ("Procainamide", "250 mg", "Oral/IV", "8640", "C01BA02", "Class IA Sodium Channel Blocker", ["Pronestyl", "Procanbid"],
     "Ventricular arrhythmias, acute conversion of pre-excited AF in Wolff-Parkinson-White syndrome.",
     "IV loading 20-50 mg/min (max 17 mg/kg), followed by 1-4 mg/min continuous maintenance infusion.",
     "Complete heart block, systemic lupus erythematosus, torsades de pointes.",
     "Black Box: Drug-induced systemic lupus erythematosus (positive ANA in 60-70% after 1 year); agranulocytosis and bone marrow depression; proarrhythmia.",
     "Hypotension, lupus-like syndrome (arthralgia, fever, pleuritis), agranulocytosis, QTc prolongation, nausea.",
     "QT-prolonging drugs, neuromuscular blockers, trimethoprim.",
     "Category C."),
    ("Quinidine", "200 mg", "Oral/IV", "9068", "C01BA01", "Class IA Sodium/Potassium Channel Blocker", ["Quinidex", "Quinaglute"],
     "Maintenance of sinus rhythm in AF/flutter; malaria treatment (IV quinidine gluconate).",
     "200 mg to 400 mg orally every 6 to 8 hours.",
     "Complete AV block, thrombocytopenic purpura with quinidine, myasthenia gravis.",
     "Black Box: Increased mortality in chronic AF trials; cinchonism (tinnitus, hearing loss, vertigo, visual disturbances); severe thrombocytopenia.",
     "Cinchonism, diarrhea (35%), immune thrombocytopenia, QT prolongation, syncope.",
     "Potent CYP2D6 inhibitor: digoxin (doubles levels), warfarin, neuromuscular blockers.",
     "Category C."),
    ("Disopyramide", "100 mg", "Oral Capsule", "3504", "C01BA03", "Class IA Antiarrhythmic with Potent Anticholinergic Effects", ["Norpace", "Norpace CR"],
     "Suppression of ventricular arrhythmias, obstructive hypertrophic cardiomyopathy (LVOT gradient reduction).",
     "100 mg to 200 mg orally every 6 hours.",
     "Cardiogenic shock, pre-existing 2nd/3rd degree AV block, congenital QT prolongation.",
     "Black Box: Increased mortality in non-life-threatening arrhythmias; severe negative inotrope (triggers heart failure); severe anticholinergic urinary retention/glaucoma.",
     "Dry mouth, urinary retention (severe in BPH), constipation, blurred vision, heart failure exacerbation.",
     "Erythromycin, clarithromycin, anticholinergic drugs.",
     "Category C."),
    ("Mexiletine", "150 mg", "Oral Capsule", "6942", "C01BB02", "Class IB Sodium Channel Blocker (Oral Lidocaine Congener)", ["Mexitil"],
     "Suppression of documented life-threatening ventricular arrhythmias, myotonia congenita.",
     "150 mg to 300 mg orally every 8 hours with food or antacid.",
     "Cardiogenic shock, pre-existing 2nd/3rd degree AV block.",
     "Black Box: Increased mortality in structural heart disease; hepatotoxicity; neurotoxicity.",
     "Upper GI distress, nausea, tremor, ataxia, dizziness, nystagmus.",
     "CYP1A2 and CYP2D6 inducers/inhibitors (theophylline, rifampin).",
     "Category C."),
    ("Adenosine", "6 mg/2ml", "Rapid IV Push", "296", "C01EB01", "Purinergic P1 (A1) Receptor Agonist", ["Adenocard", "Adenoscan"],
     "Immediate conversion of Paroxysmal Supraventricular Tachycardia (PSVT) including AV nodal reentrant tachycardia (AVNRT) to sinus rhythm; pharmacologic myocardial perfusion stress testing.",
     "6 mg rapid IV push over 1-2 seconds directly into large vein followed immediately by 20 mL saline flush; if no response in 1-2 min, give 12 mg rapid IV push.",
     "2nd or 3rd degree AV block or sick sinus syndrome (without pacemaker); bronchospastic lung disease / severe asthma.",
     "Transient heart block/asystole (several seconds - self-limiting due to 10-second half-life); bronchospasm in asthmatics; sense of impending doom.",
     "Facial flushing (44%), dyspnea/chest pressure (36%), transient asystole/sinus pause, dizziness, headache.",
     "Theophylline/caffeine (competitive adenosine receptor antagonists - requires higher adenosine doses), dipyridamole (blocks uptake - potentiates effect 4-fold - reduce dose to 3 mg).",
     "Category C. Elimination half-life <10 seconds by erythrocyte uptake and adenosine deaminase."),
    ("Clonidine", "0.1 mg", "Oral Tablet / Transdermal", "2599", "C02AC01", "Central Alpha-2 Adrenergic Agonist", ["Catapres", "Arkamin", "Catapres-TTS"],
     "Hypertension, ADHD, opioid withdrawal symptom suppression, severe cancer pain (epidural).",
     "0.1 mg to 0.3 mg orally twice daily (or weekly transdermal patch TTS-1, TTS-2, TTS-3).",
     "Hypersensitivity to clonidine.", "Rebound hypertensive crisis following sudden abrupt discontinuation (rapid surge in catecholamines - must taper over 1 week); severe sedation.",
     "Dry mouth (40%), drowsiness (35%), dizziness, constipation, bradycardia, sedation, erectile dysfunction.",
     "Beta-blockers (exaggerates rebound hypertension upon clonidine withdrawal), CNS depressants, alcohol, tricyclic antidepressants.",
     "Category C."),
    ("Guanfacine", "1 mg", "Oral Tablet", "5032", "C02AC02", "Selective Central Alpha-2A Agonist", ["Tenex", "Intuniv"],
     "Hypertension and Attention Deficit Hyperactivity Disorder (ADHD monotherapy/adjunct).",
     "1 mg to 4 mg orally once daily at bedtime (Intuniv ER once daily in morning).",
     "Hypersensitivity.", "Rebound hypertension upon sudden discontinuation; somnolence and bradycardia.",
     "Somnolence, sedation, fatigue, dizziness, dry mouth, constipation.",
     "CYP3A4 inhibitors (ketoconazole increases levels), inducers.",
     "Category B."),
    ("Methyldopa", "250 mg", "Oral Tablet", "6876", "C02AB01", "Centrally Acting Alpha-2 Agonist Antihypertensive", ["Aldomet"],
     "Hypertension in pregnancy (chronic gestational hypertension / preeclampsia).", "250 mg to 500 mg orally 2 to 3 times daily.",
     "Active hepatic disease, direct Coombs-positive autoimmune hemolytic anemia, concurrent MAOIs.",
     "Black Box: Autoimmune hemolytic anemia (positive Coombs test in 20%); drug-induced hepatitis/hepatic necrosis; severe sedation.",
     "Sedation, positive direct Coombs test, drug fever, dry mouth, nasal congestion, orthostatic hypotension.",
     "MAO inhibitors, iron salts (decrease methyldopa absorption), lithium.",
     "Category B. Historical gold standard for chronic hypertension in pregnancy."),
    ("Doxazosin", "2 mg", "Oral Tablet", "3616", "C02CA04", "Long-Acting Alpha-1 Adrenergic Antagonist", ["Cardura", "Doxacard"],
     "Benign prostatic hyperplasia (BPH) urinary outflow obstruction and essential hypertension.", "1 mg to 8 mg orally once daily (max 16 mg/day).",
     "Hypersensitivity to quinazolines.", "First-dose phenomenon: profound orthostatic hypotension and syncope; Intraoperative Floppy Iris Syndrome (IFIS) during cataract surgery.",
     "Dizziness, orthostatic hypotension, headache, fatigue, somnolence, peripheral edema.",
     "PDE-5 inhibitors (sildenafil, tadalafil cause synergistic severe hypotension), antihypertensives.",
     "Category C."),
    ("Prazosin", "1 mg", "Oral Capsule", "8600", "C02CA01", "Short-Acting Alpha-1 Adrenergic Antagonist", ["Minipress"],
     "Hypertension and PTSD-related chronic nightmares / sleep disruption.", "1 mg to 5 mg orally 2 to 3 times daily (start 1 mg at bedtime to avoid first-dose syncope).",
     "Hypersensitivity to prazosin.", "Severe first-dose syncope; orthostatic hypotension.",
     "Orthostatic dizziness, syncope, headache, palpitations, drowsiness, weakness.",
     "PDE-5 inhibitors, beta-blockers.",
     "Category C."),
    ("Terazosin", "2 mg", "Oral Capsule", "10379", "C02CA03", "Alpha-1 Adrenergic Antagonist", ["Hytrin"],
     "Benign prostatic hyperplasia and hypertension.", "1 mg at bedtime, titrate to 2 mg, 5 mg, or 10 mg once daily.",
     "Hypersensitivity.", "First-dose syncope; floppy iris syndrome.",
     "Dizziness, asthenia, nasal congestion, peripheral edema, postural hypotension.",
     "PDE-5 inhibitors, other antihypertensives.",
     "Category C."),
    ("Hydralazine", "25 mg", "Oral/IV", "5457", "C02DB02", "Direct Arteriolar Vasodilator", ["Apresoline"],
     "Severe hypertension, hypertensive emergencies in pregnancy (preeclampsia), heart failure with reduced ejection fraction (combined with isosorbide dinitrate).",
     "10 mg to 50 mg orally 4 times daily (max 300 mg/day); IV 5-20 mg slow push every 20-30 min.",
     "Coronary artery disease (causes reflex tachycardia and angina); mitral valve rheumatic heart disease.",
     "Drug-Induced Lupus Erythematosus (DILE) syndrome (positive ANA, anti-histone antibodies in slow acetylators at doses >200 mg/day); reflex tachycardia and fluid retention.",
     "Headache, reflex tachycardia, palpitations, angina, lupus-like syndrome, peripheral edema, nausea.",
     "Beta-blockers and diuretics must be co-prescribed to prevent reflex tachycardia and renin-mediated fluid retention.",
     "Category C. Second-line IV agent for acute preeclampsia."),
    ("Minoxidil", "10 mg", "Oral Tablet", "6992", "C02DC01", "Potent Direct K-ATP Channel Vasodilator", ["Loniten"],
     "Severe refractory hypertension resistant to multiple antihypertensive agents.", "5 mg to 40 mg orally once daily or divided twice daily.",
     "Pheochromocytoma.", "Black Box: Serious adverse effects: pericardial effusion progressing to tamponade; severe reflex tachycardia and angina; hypertrichosis (90% hair growth).",
     "Hypertrichosis (hair elongation/pigmentation), severe fluid retention, pericardial effusion, reflex tachycardia.",
     "Requires concomitant loop diuretic and beta-blocker.",
     "Category C."),
    ("Isosorbide Mononitrate", "30 mg", "Oral Tablet (ER)", "6056", "C01DA14", "Organic Nitrate Vasodilator", ["Imdur", "Monoket"],
     "Prophylaxis and long-term treatment of angina pectoris due to coronary artery disease.", "30 mg to 120 mg orally once daily in the morning (provides mandatory 12-hour nitrate-free interval to prevent tolerance).",
     "Concomitant use with PDE-5 inhibitors (sildenafil, tadalafil) or soluble guanylate cyclase stimulators (riociguat); severe anemia; closed-angle glaucoma.",
     "Life-threatening severe hypotension and circulatory collapse when combined with PDE-5 inhibitors; nitrate tolerance with continuous dosing.",
     "Throbbing nitrate headache (50%), dizziness, hypotension, flushing, syncope.",
     "PDE-5 inhibitors (sildenafil contraindicated for 24h; tadalafil contraindicated for 48h - fatal refractory hypotension).",
     "Category C."),
    ("Isosorbide Dinitrate", "20 mg", "Oral Tablet", "6055", "C01DA08", "Organic Nitrate Vasodilator", ["Isordil", "Dilatrate-SR"],
     "Angina pectoris prevention and heart failure in African Americans (combined with hydralazine - A-HeFT trial).",
     "10 mg to 40 mg orally 2 to 3 times daily (last dose given at 5 PM to ensure nitrate-free interval).",
     "Concurrent PDE-5 inhibitors, severe hypotension.", "Fatal hypotension with PDE-5 inhibitors; severe nitrate headaches.",
     "Headache, orthostatic dizziness, flushing, tachycardia.", "PDE-5 inhibitors, alcohol.",
     "Category C."),
    ("Nitroglycerin", "0.4 mg", "Sublingual Tablet / Spray / IV", "7434", "C01DA02", "Organic Nitrate Vasodilator Prototype", ["Nitrostat", "Nitrolingual", "Nitro-Dur"],
     "Immediate relief and acute prophylaxis of angina pectoris; acute coronary syndrome (ACS); acute decompensated heart failure with pulmonary edema.",
     "Sublingual: 0.3 mg to 0.6 mg under tongue every 5 minutes (max 3 doses in 15 minutes; call 911 if pain persists); IV continuous infusion 5-200 mcg/min.",
     "Concomitant PDE-5 inhibitors (sildenafil within 24h, tadalafil within 48h); right ventricular myocardial infarction (preload dependent); severe aortic stenosis.",
     "Life-threatening hypotension/cardiogenic shock in RV infarction; severe cerebral hypoperfusion; nitrate tolerance.",
     "Throbbing headache, flushing, dizziness, reflex tachycardia, postural hypotension, syncope.",
     "PDE-5 inhibitors (strictly contraindicated), riociguat, alcohol, antihypertensives.",
     "Category C.")
]

def get_abx_pain_cv_records() -> List[Dict[str, Any]]:
    """Assemble all records from domains 1, 2, and 3."""
    records = []
    
    def process_group(group: List[Tuple]):
        for name, st, form, rxcui, atc, cls, aliases, ind, dos, con, war, adv, inter, prg in group:
            records.append({
                "name": name, "strength": st, "form": form, "rxcui": rxcui, "atc": atc,
                "class": cls, "aliases": aliases, "ind": ind, "dos": dos, "con": con,
                "war": war, "adv": adv, "int": inter, "prg": prg
            })

    process_group(CAT_1_ABX)
    process_group(CAT_2_PAIN)
    process_group(CAT_3_CV)
    return records

if __name__ == "__main__":
    r = get_abx_pain_cv_records()
    print(f"Domains 1-3 total records: {len(r)}")
