"""Clinical Knowledge Base: Domains 4, 5, 6, 7, and 8 (Metabolic, Lipids, Coagulation, GI, Respiratory).

Contains 198 authentic medicine monographs with US NLM RxNorm RxCUIs, ATC codes, and FDA labeling.
"""
from typing import Any, Dict, List, Tuple

# Domain 4: Antidiabetics, Metabolic & Endocrine (52)
CAT_4_METABOLIC: List[Tuple] = [
    ("Metformin", "500 mg", "Oral Tablet", "860975", "A10BA02", "Biguanide Antidiabetic Agent", ["Glucophage", "Glycomet", "Obimet", "Glucophage XR"],
     "First-line pharmacological therapy for type 2 diabetes mellitus; polycystic ovary syndrome (PCOS) insulin resistance.",
     "Starting 500 mg orally twice daily with meals or 850 mg once daily; titrate weekly to effective dose 2,000 mg/day (max 2,550 mg/day).",
     "Severe renal impairment (eGFR <30 mL/min); acute or chronic metabolic acidosis / diabetic ketoacidosis; tissue hypoperfusion/sepsis.",
     "Black Box: Fatal lactic acidosis risk (accumulates in severe renal impairment, hypoxemic conditions, acute heart failure, sepsis, excessive alcohol consumption); vitamin B12 deficiency with long-term use.",
     "Diarrhea (frequent - up to 30%), nausea, vomiting, flatulence, abdominal discomfort, metallic taste, B12 deficiency.",
     "Iodinated radiocontrast media (withhold metformin at time of or prior to procedure and for 48h after until renal function verified normal), alcohol (potentiates lactate effect), cimetidine (increases metformin exposure).",
     "Category B. First-line oral agent in gestational diabetes mellitus when insulin is not feasible."),
    ("Glimepiride", "2 mg", "Oral Tablet", "25789", "A10BB12", "Second-Generation Sulfonylurea", ["Amaryl", "Glimy", "Zoryl"],
     "Adjunct to diet and exercise to improve glycemic control in type 2 diabetes mellitus.",
     "1 mg to 2 mg orally once daily administered with breakfast or the first main meal; titrate by 1-2 mg every 1-2 weeks; max 8 mg/day.",
     "Hypersensitivity to sulfonylureas or sulfonamides; diabetic ketoacidosis; type 1 diabetes mellitus.",
     "Severe, prolonged, and life-threatening hypoglycemia; hemolytic anemia in patients with G6PD deficiency; increased cardiovascular mortality signal in sulfonylurea class.",
     "Hypoglycemia, weight gain, dizziness, headache, nausea, allergic skin reactions.",
     "Fluconazole, NSAIDs, sulfonamides, clarithromycin increase hypoglycemia risk; beta-blockers mask hypoglycemia warning signs (except sweating).",
     "Category C. Discontinue at least 2 weeks prior to anticipated delivery to avoid prolonged neonatal hypoglycemia."),
    ("Glipizide", "5 mg", "Oral Tablet", "4821", "A10BB07", "Second-Generation Sulfonylurea", ["Glucotrol", "Glucotrol XL"],
     "Glycemic control in type 2 diabetes mellitus.", "5 mg orally daily given 30 minutes before breakfast; titrate to max 40 mg/day (XL max 20 mg/day).",
     "Diabetic ketoacidosis, type 1 diabetes, sulfa allergy.", "Hypoglycemia (shorter half-life and inactive metabolites - lower accumulation in mild-moderate renal impairment than glyburide).",
     "Hypoglycemia, nausea, diarrhea, dizziness, weight gain.", "Fluconazole, ciprofloxacin, beta-blockers.",
     "Category C."),
    ("Gliclazide", "80 mg", "Oral Tablet", "4815", "A10BB09", "Second-Generation Sulfonylurea", ["Diamicron", "Reclimet", "Diamicron MR"],
     "Type 2 diabetes mellitus.", "40 mg to 80 mg orally daily, titrate up to 320 mg/day (or MR formulation 30 mg to 120 mg once daily with breakfast).",
     "Type 1 diabetes, severe renal or hepatic insufficiency, concomitant miconazole.", "Hypoglycemia; weight gain.",
     "Hypoglycemia, weight gain, dyspepsia, rash.", "Miconazole, phenylbutazone, alcohol.",
     "Category C."),
    ("Glyburide", "5 mg", "Oral Tablet", "4815", "A10BB01", "Second-Generation Sulfonylurea", ["Micronase", "Diabeta", "Daonil", "Glynase"],
     "Type 2 diabetes mellitus.", "2.5 mg to 5 mg orally daily with breakfast; max 20 mg/day.",
     "Severe renal impairment (active metabolites accumulate), sulfa allergy.", "Highest prolonged hypoglycemia risk among sulfonylureas; avoid in elderly (Beers Criteria Avoid).",
     "Hypoglycemia, weight gain, allergic skin reactions, cholestatic jaundice.", "Fluconazole, clarithromycin, NSAIDs.",
     "Category C."),
    ("Repaglinide", "1 mg", "Oral Tablet", "73074", "A10BX02", "Meglitinide Prandial Insulin Secretagogue", ["Prandin", "Eurepa"],
     "Postprandial glycemic control in type 2 diabetes mellitus.", "0.5 mg to 2 mg orally within 15 to 30 minutes before each meal (skip dose if skipping meal).",
     "Type 1 diabetes, DKA, concomitant gemfibrozil (contraindicated).", "Hypoglycemia; 8-fold increase in repaglinide AUC when combined with gemfibrozil.",
     "Hypoglycemia, weight gain, headache, upper respiratory infection.", "Gemfibrozil (strictly contraindicated - severe hypoglycemia), clopidogrel, cyclosporine.",
     "Category C."),
    ("Nateglinide", "120 mg", "Oral Tablet", "31565", "A10BX03", "D-Phenylalanine Meglitinide Secretagogue", ["Starlix"],
     "Prandial glycemic control in type 2 diabetes.", "120 mg orally three times daily 1 to 30 minutes before meals.",
     "Type 1 diabetes, diabetic ketoacidosis.", "Hypoglycemia.",
     "Hypoglycemia, upper respiratory infection, dizziness.", "NSAIDs, beta-blockers, alcohol.",
     "Category C."),
    ("Pioglitazone", "15 mg", "Oral Tablet", "33738", "A10BG03", "Thiazolidinedione (PPAR-gamma Agonist)", ["Actos", "Pioz"],
     "Type 2 diabetes mellitus insulin sensitizer (reduces peripheral and hepatic insulin resistance).",
     "15 mg to 30 mg orally once daily with or without food; titrate to max 45 mg/day.",
     "NYHA Class III or IV Heart Failure; active bladder cancer; history of bladder cancer; diabetic ketoacidosis.",
     "Black Box: Causes or exacerbates congestive heart failure (dose-related fluid retention/edema); bladder cancer risk; bone fractures in postmenopausal women; macular edema.",
     "Peripheral edema, weight gain, heart failure exacerbation, upper respiratory tract infection, anemia, bone fractures.",
     "Gemfibrozil (inhibits CYP2C8 - increases pioglitazone AUC 3-fold), rifampin (decreases pioglitazone by 50%), oral contraceptives.",
     "Category C. Restores ovulation in premenopausal anovulatory women with insulin resistance."),
    ("Rosiglitazone", "4 mg", "Oral Tablet", "84108", "A10BG02", "Thiazolidinedione (PPAR-gamma Agonist)", ["Avandia"],
     "Type 2 diabetes mellitus.", "4 mg orally once daily or divided twice daily; max 8 mg/day.",
     "Class III/IV Heart failure, concurrent insulin.", "Black Box: Heart failure risk; myocardial ischemia risk.",
     "Edema, hypercholesterolemia, weight gain, anemia.", "Gemfibrozil, rifampin.",
     "Category C."),
    ("Sitagliptin", "100 mg", "Oral Tablet", "593411", "A10BH01", "DPP-4 Inhibitor (Incretin Enhancer)", ["Januvia", "Janumet", "Istavel"],
     "Monotherapy or combination therapy in type 2 diabetes mellitus.",
     "100 mg orally once daily with or without food (reduce to 50 mg in CrCl 30-50; 25 mg in CrCl <30 mL/min).",
     "History of serious hypersensitivity reaction (anaphylaxis, angioedema) to sitagliptin.",
     "Acute pancreatitis (including hemorrhagic and necrotizing pancreatitis); severe and disabling arthralgia; bullous pemphigoid.",
     "Nasopharyngitis, upper respiratory tract infection, headache, acute pancreatitis, joint pain.",
     "Digoxin (slight increase in digoxin AUC), sulfonylureas/insulin (increased risk of hypoglycemia - reduce secretagogue dose).",
     "Category B. No teratogenic signals in animal models."),
    ("Linagliptin", "5 mg", "Oral Tablet", "1114195", "A10BH05", "DPP-4 Inhibitor (Non-Renal Elimination)", ["Tradjenta", "Ondero"],
     "Type 2 diabetes mellitus (primarily biliary/fecal excretion - NO DOSE ADJUSTMENT in renal disease).",
     "5 mg orally once daily with or without food.",
     "Hypersensitivity to linagliptin.", "Acute pancreatitis, severe joint pain, bullous pemphigoid.",
     "Nasopharyngitis, hyperuricemia, cough, pancreatitis.", "Strong CYP3A4/P-gp inducers (rifampin, carbamazepine reduce efficacy).",
     "Category B. Preferred DPP-4 inhibitor in severe chronic kidney disease."),
    ("Saxagliptin", "5 mg", "Oral Tablet", "855332", "A10BH03", "DPP-4 Inhibitor", ["Onglyza"],
     "Type 2 diabetes mellitus.", "2.5 mg to 5 mg orally once daily.",
     "Severe hypersensitivity.", "Heart failure risk (SAVOR-TIMI 53 showed increased heart failure hospitalization); acute pancreatitis.",
     "Peripheral edema, headache, urinary tract infection.", "Strong CYP3A4 inhibitors (clarithromycin, ketoconazole - limit saxagliptin to 2.5 mg).",
     "Category B."),
    ("Alogliptin", "25 mg", "Oral Tablet", "1368003", "A10BH04", "DPP-4 Inhibitor", ["Nesina"],
     "Type 2 diabetes mellitus.", "25 mg orally once daily (dose adjust in renal impairment).",
     "Hypersensitivity.", "Pancreatitis, fatal hepatic failure, heart failure hospitalization.",
     "Nasopharyngitis, headache, upper respiratory tract infection.", "Sulfonylureas.",
     "Category B."),
    ("Vildagliptin", "50 mg", "Oral Tablet", "384454", "A10BH02", "DPP-4 Inhibitor", ["Galvus", "Zomelis"],
     "Type 2 diabetes mellitus.", "50 mg orally once or twice daily (morning and evening with metformin).",
     "Severe hepatic impairment or ALT/AST >3x ULN.", "Hepatic dysfunction (monitor LFTs at baseline and every 3 months during 1st year).",
     "Dizziness, headache, nausea, peripheral edema, transaminase elevation.", "ACE inhibitors (increased angioedema risk).",
     "Category B."),
    ("Empagliflozin", "10 mg", "Oral Tablet", "1545653", "A10BK03", "Sodium-Glucose Co-Transporter 2 (SGLT2) Inhibitor", ["Jardiance", "Gibtulio"],
     "Type 2 diabetes mellitus, heart failure (HFrEF and HFpEF reduction of CV death/hospitalization - EMPEROR trials), chronic kidney disease progression delay (EMPA-KIDNEY).",
     "10 mg orally once daily in the morning with or without food; may increase to 25 mg once daily.",
     "Dialysis or end-stage kidney disease; severe hypersensitivity to empagliflozin.",
     "Euglycemic Diabetic Ketoacidosis (DKA with normal blood sugars); necrotizing fasciitis of the perineum (Fournier's gangrene); genital mycotic infections; volume depletion and hypotension; urosepsis.",
     "Female and male genital mycotic yeast infections, urinary tract infections, increased urination, hypotension, thirst, elevated LDL-C.",
     "Diuretics (additive volume depletion and hypotension), insulin and secretagogues (increased hypoglycemia risk).",
     "Avoid in 2nd and 3rd trimesters of pregnancy (potential adverse renal development in fetus)."),
    ("Dapagliflozin", "10 mg", "Oral Tablet", "1488564", "A10BK01", "SGLT2 Inhibitor", ["Farxiga", "Forxiga", "Oxra"],
     "Type 2 diabetes, heart failure (HFrEF/HFpEF - DAPA-HF trial), chronic kidney disease (DAPA-CKD trial).",
     "10 mg orally once daily in the morning with or without food.",
     "Dialysis, severe hypersensitivity.",
     "Euglycemic diabetic ketoacidosis, Fournier's gangrene, volume contraction, lower limb infections.",
     "Genital candidiasis, nasopharyngitis, UTI, polyuria, dysuria.",
     "Loop diuretics (hypotension/dehydration), insulin.",
     "Avoid in 2nd and 3rd trimesters."),
    ("Canagliflozin", "100 mg", "Oral Tablet", "1373458", "A10BK02", "SGLT2 Inhibitor", ["Invokana"],
     "Type 2 diabetes, reduction of major adverse CV events, diabetic nephropathy (CREDENCE trial).",
     "100 mg orally once daily before the first meal of the day; may increase to 300 mg daily.",
     "Dialysis.", "Black Box: Historical signal for lower limb amputation; bone fracture risk; ketoacidosis; hyperkalemia.",
     "Genital mycotic infections, UTI, thirst, hyperkalemia, polyuria.",
     "UGT inducers (rifampin, phenytoin decrease AUC), digoxin (increases digoxin level).",
     "Avoid in 2nd and 3rd trimesters."),
    ("Ertugliflozin", "5 mg", "Oral Tablet", "1992672", "A10BK04", "SGLT2 Inhibitor", ["Steglatro"],
     "Type 2 diabetes mellitus glycemic management.", "5 mg to 15 mg orally once daily in the morning.",
     "Dialysis.", "Ketoacidosis, Fournier's gangrene, volume depletion.",
     "Genital mycotic infections, polyuria, thirst, hypotension.", "Diuretics.",
     "Avoid in 2nd and 3rd trimesters."),
    ("Semaglutide", "0.5 mg", "SC Injection / Oral Tablet", "1991302", "A10BJ06", "GLP-1 Receptor Agonist", ["Ozempic", "Wegovy", "Rybelsus"],
     "Type 2 diabetes mellitus, reduction of major adverse cardiovascular events (MACE), chronic weight management.",
     "SC: 0.25 mg weekly for 4 weeks, then 0.5 mg weekly (titrate to 1-2 mg weekly). Oral (Rybelsus): 3 mg, 7 mg, 14 mg daily taken on empty stomach with <=4 oz plain water >=30 min before food.",
     "Personal or family history of Medullary Thyroid Carcinoma (MTC) or Multiple Endocrine Neoplasia syndrome type 2 (MEN 2).",
     "Black Box: Dose-dependent thyroid C-cell tumors in rodents; acute pancreatitis; diabetic retinopathy complications; gastroparesis/delayed gastric emptying causing pulmonary aspiration under general anesthesia.",
     "Nausea (20-30%), vomiting, diarrhea, abdominal pain, constipation, decreased appetite, dyspepsia, fatigue.",
     "Insulin/sulfonylureas (increased hypoglycemia risk); delays gastric absorption of co-administered oral medications.",
     "Contraindicated in pregnancy (discontinue at least 2 months prior to planned pregnancy due to long washout period)."),
    ("Liraglutide", "1.2 mg", "SC Injection", "897122", "A10BJ02", "Once-Daily GLP-1 Receptor Agonist", ["Victoza", "Saxenda"],
     "Type 2 diabetes mellitus, CV risk reduction (LEADER trial), and chronic weight management (Saxenda).",
     "0.6 mg SC daily for 1 week, then 1.2 mg daily (max 1.8 mg daily for T2D; 3.0 mg daily for Saxenda).",
     "Personal/family history of MTC or MEN 2.", "Black Box: Thyroid C-cell tumors; acute pancreatitis; acute gallbladder disease (cholelithiasis).",
     "Nausea, diarrhea, vomiting, constipation, headache, hypoglycemia.", "Sulfonylureas, insulin.",
     "Discontinue if pregnancy occurs."),
    ("Dulaglutide", "0.75 mg", "SC Injection", "1551291", "A10BJ05", "Once-Weekly GLP-1 Receptor Agonist", ["Trulicity"],
     "Type 2 diabetes and CV risk reduction in established cardiovascular disease (REWIND trial).",
     "0.75 mg SC once weekly, titrate to 1.5 mg, 3.0 mg, or 4.5 mg weekly.",
     "Personal or family history of MTC or MEN 2.", "Black Box: Thyroid C-cell tumors; pancreatitis; acute kidney injury secondary to dehydration.",
     "Nausea, diarrhea, vomiting, abdominal pain, decreased appetite, fatigue.", "Insulin, secretagogues.",
     "Avoid in pregnancy."),
    ("Exenatide", "5 mcg", "SC Injection", "60548", "A10BJ01", "GLP-1 Receptor Agonist (Exendin-4 Synthetic)", ["Byetta", "Bydureon"],
     "Type 2 diabetes mellitus.", "5 mcg SC twice daily within 60 minutes before morning and evening meals (Bydureon 2 mg once weekly).",
     "Severe renal impairment (eGFR <30 mL/min); history of drug-induced immune thrombocytopenia.", "Black Box: Thyroid C-cell tumors (extended-release); pancreatitis; severe renal decline.",
     "Nausea, vomiting, diarrhea, dyspepsia, injection site nodules (Bydureon).", "Warfarin (monitor INR), oral contraceptives, antibiotics.",
     "Category C."),
    ("Lixisenatide", "20 mcg", "SC Injection", "1370868", "A10BJ03", "Prandial GLP-1 Receptor Agonist", ["Adlyxin", "Soliqua"],
     "Type 2 diabetes mellitus prandial control.", "10 mcg SC daily for 14 days, then 20 mcg SC once daily within 1 hour before breakfast.",
     "Hypersensitivity.", "Pancreatitis, hypoglycemia with secretagogues.",
     "Nausea, vomiting, headache, diarrhea.", "Oral contraceptives (take 1h before or 11h after).",
     "Category C."),
    ("Tirzepatide", "5 mg", "SC Injection", "2601735", "A10BX16", "Dual GIP and GLP-1 Receptor Agonist (Twincretin)", ["Mounjaro", "Zepbound"],
     "Type 2 diabetes mellitus (SURPASS trials) and chronic weight management (SURMOUNT trials).",
     "2.5 mg SC once weekly for 4 weeks, titrate by 2.5 mg increments every 4 weeks to 5 mg, 10 mg, or max 15 mg once weekly.",
     "Personal or family history of Medullary Thyroid Carcinoma (MTC) or MEN 2.",
     "Black Box: Thyroid C-cell tumors in animal models; severe gastrointestinal disease; acute pancreatitis; acute gallbladder disease.",
     "Nausea (30%), diarrhea, decreased appetite, vomiting, constipation, dyspepsia, abdominal pain.",
     "Oral contraceptives (decreases AUC of oral hormonal contraceptives during dose escalation - switch to non-oral method or add barrier for 4 weeks after initiation/dose changes).",
     "Avoid in pregnancy."),
    ("Insulin Regular Human", "100 units/ml", "SC / IV Injection", "274783", "A10AB01", "Short-Acting Recombinant Human Insulin", ["Humulin R", "Novolin R", "Actrapid"],
     "Type 1 and type 2 diabetes mellitus, diabetic ketoacidosis (DKA), hyperosmolar hyperglycemic state (HHS), hyperkalemia emergency.",
     "Individualized SC dosing 30 minutes before meals; IV infusion for DKA (0.1 units/kg/hr continuous infusion).",
     "During episodes of hypoglycemia; systemic hypersensitivity.",
     "Life-threatening hypoglycemia; severe hypokalemia (insulin shifts potassium intracellularly); injection site lipodystrophy.",
     "Hypoglycemia, weight gain, injection site lipohypertrophy, peripheral edema, hypokalemia.",
     "Beta-blockers (mask hypoglycemic symptoms), thiazolidinediones (additive edema and heart failure), alcohol.",
     "Category B. Gold standard treatment for diabetes in pregnancy."),
    ("Insulin NPH", "100 units/ml", "SC Injection", "274784", "A10AC01", "Intermediate-Acting Neutral Protamine Hagedorn Insulin", ["Humulin N", "Novolin N", "Insulatard"],
     "Basal glycemic control in type 1 and type 2 diabetes mellitus.",
     "Individualized SC dosing once or twice daily (cloudy suspension - gently roll 10 times to resuspend before injecting).",
     "During episodes of hypoglycemia; hypersensitivity to protamine.",
     "Hypoglycemia (pronounced peak at 4-12 hours); lipodystrophy.",
     "Hypoglycemia, weight gain, injection site reactions, lipoatrophy.",
     "Oral antidiabetic agents, corticosteroids, beta-blockers.",
     "Category B. Preferred intermediate basal insulin in pregnancy."),
    ("Insulin Glargine", "100 units/ml", "SC Injection", "274785", "A10AE04", "Long-Acting Peakless Basal Insulin Analog", ["Lantus", "Basaglar", "Toujeo", "Lantus SoloStar"],
     "Once-daily basal glycemic control in type 1 and type 2 diabetes mellitus.",
     "Individualized SC once daily at the same time each day (acidic pH 4.0 - precipitates micro-crystals for steady release; DO NOT MIX with other insulins).",
     "During episodes of hypoglycemia.", "Hypoglycemia; DO NOT administer IV or in insulin infusion pumps; do not dilute or mix with other insulins.",
     "Hypoglycemia, lipodystrophy, injection site pain/stinging (due to acidic pH), weight gain.",
     "Oral antidiabetic drugs, beta-blockers, corticosteroids.",
     "Category B/C. Extensively used and documented in gestational diabetes."),
    ("Insulin Lispro", "100 units/ml", "SC / IV", "865098", "A10AB04", "Rapid-Acting Insulin Analog", ["Humalog", "Admelog"],
     "Prandial glycemic control in type 1 and type 2 diabetes mellitus.",
     "Inject SC 15 minutes before or immediately after a meal.",
     "Hypoglycemia episodes.", "Rapid onset hypoglycemia with improper meal timing.",
     "Hypoglycemia, weight gain, lipodystrophy, allergic reactions.",
     "Pramlintide, secretagogues, alcohol.",
     "Category B."),
    ("Insulin Aspart", "100 units/ml", "SC / IV", "260258", "A10AB05", "Rapid-Acting Insulin Analog", ["NovoLog", "Fiasp", "Novorapid"],
     "Prandial insulin therapy for diabetes mellitus.", "Inject SC within 5-10 minutes before meals (Fiasp at start of meal).",
     "Hypoglycemia.", "Rapid onset hypoglycemia.",
     "Hypoglycemia, injection site reactions, hypokalemia.", "Oral antidiabetic agents.",
     "Category B. Safe in pregnancy."),
    ("Insulin Detemir", "100 units/ml", "SC Injection", "516382", "A10AE05", "Long-Acting Basal Insulin (Albumin-Bound)", ["Levemir"],
     "Once or twice daily basal glycemic control.", "Individualized SC once or twice daily with evening meal or at bedtime.",
     "Hypoglycemia.", "Hypoglycemia; do not mix with other insulins.",
     "Hypoglycemia, weight gain, lipodystrophy.", "Oral antidiabetics.",
     "Category B. FDA pregnancy category B approved."),
    ("Insulin Degludec", "100 units/ml", "SC Injection", "1373449", "A10AE06", "Ultra-Long Acting Basal Insulin (Half-life 25h)", ["Tresiba"],
     "Once-daily basal glycemic control (duration of action >42 hours; flexible dosing timing).",
     "Individualized SC once daily at any time of day.",
     "Hypoglycemia.", "Hypoglycemia; do not administer IV.",
     "Hypoglycemia, lipodystrophy, weight gain, peripheral edema.", "Oral antidiabetics.",
     "Category B/C."),
    ("Insulin Glulisine", "100 units/ml", "SC / IV", "636527", "A10AB06", "Rapid-Acting Insulin Analog", ["Apidra"],
     "Prandial control in diabetes.", "Inject SC within 15 minutes before or 20 minutes after starting a meal.",
     "Hypoglycemia.", "Hypoglycemia.",
     "Hypoglycemia, injection site reactions.", "Oral secretagogues.",
     "Category C."),
    ("Levothyroxine", "100 mcg", "Oral Tablet / IV", "10582", "H03AA01", "Synthetic Thyroid Hormone (T4)", ["Synthroid", "Levoxyl", "Eltroxin", "Thyronorm"],
     "Primary, secondary, and tertiary hypothyroidism replacement therapy; TSH suppression in thyroid cancer and nodular goiter.",
     "1.6 mcg/kg/day orally once daily in the morning on an empty stomach with a full glass of water 30 to 60 minutes before breakfast.",
     "Uncorrected adrenal insufficiency, untreated thyrotoxicosis, acute myocardial infarction.",
     "Black Box: Not for treatment of obesity or weight loss (ineffective and dangerous in euthyroid); cardiac arrhythmias and angina in elderly / coronary artery disease.",
     "Symptoms of hyperthyroidism from overtreatment: palpitations, tachycardia, weight loss, heat intolerance, tremor, nervousness, insomnia, bone mineral density loss.",
     "Calcium carbonate, ferrous sulfate, antacids, PPIs, sucralfate, cholestyramine (decrease levothyroxine absorption by 50% - separate by 4 hours); increases warfarin effect.",
     "Category A. Essential in pregnancy; maternal thyroid hormone requirements increase 25-50% in pregnancy; monitor TSH every 4-6 weeks."),
    ("Liothyronine", "25 mcg", "Oral Tablet / IV", "10586", "H03AA02", "Synthetic Triiodothyronine (T3)", ["Cytomel", "Triostat"],
     "Hypothyroidism, myxedema coma (IV Triostat), T3 suppression test.", "25 mcg to 75 mcg orally once daily.",
     "Uncorrected adrenal insufficiency.", "Black Box: Not for weight loss; rapid cardiac stimulation in CAD.",
     "Arrhythmias, palpitations, headache, sweating, nervousness.", "Warfarin, antacids.",
     "Category A."),
    ("Methimazole", "10 mg", "Oral Tablet", "6872", "H03BB02", "Thionamide Antithyroid Agent", ["Tapazole", "Thiamazole"],
     "Hyperthyroidism, Graves' disease, toxic multinodular goiter, thyroid storm preparation.", "15 mg to 60 mg orally daily in 1 to 3 divided doses.",
     "Hypersensitivity; breastfeeding (relative); first trimester of pregnancy (causes aplasia cutis).",
     "Black Box/Clinical: Agranulocytosis (sudden onset; fever and sore throat mandatory reporting); hepatotoxicity (cholestatic jaundice); teratogenicity.",
     "Agranulocytosis (0.3%), rash, pruritus, arthralgia, fever, cholestatic jaundice, leukopenia.",
     "Warfarin (antithyroid reduces metabolism of clotting factors), digitalis.",
     "Category D. Embryopathy and aplasia cutis in 1st trimester - switch to PTU in 1st trimester."),
    ("Propylthiouracil", "50 mg", "Oral Tablet", "8823", "H03BA02", "Thionamide Antithyroid Agent (Blocks T4 to T3 Conversion)", ["PTU"],
     "Hyperthyroidism in 1st trimester of pregnancy; thyroid storm (blocks peripheral T4->T3 conversion); intolerance to methimazole.",
     "300 mg to 400 mg orally daily divided every 8 hours.",
     "Hypersensitivity.", "Black Box: Severe liver injury and acute hepatic failure (fatalities in children/adults); agranulocytosis; vasculitis.",
     "Hepatotoxicity, agranulocytosis, rash, arthralgia, leukopenia, ANCA-positive vasculitis.",
     "Warfarin, digitalis.",
     "Category D. Preferred antithyroid drug ONLY during the first trimester of pregnancy."),
    ("Potassium Iodide", "130 mg", "Oral Solution / Tablet", "8596", "H03CA", "Thyroid Blocking & Protection Agent", ["SSKI", "ThyroSafe", "Iosat"],
     "Radiation emergency thyroid blocking; thyroid storm preparation (Wolff-Chaikoff effect).",
     "130 mg orally once daily in radiation emergency; SSKI 1-2 drops TID.",
     "Iodine allergy, nodular thyroid disease with heart disease.", "Iodism (brassy taste, burning in mouth, swollen salivary glands).",
     "Rash, salivary gland swelling, metallic taste, nausea.", "ACE inhibitors, potassium-sparing diuretics.",
     "Category D."),
    ("Alendronate", "70 mg", "Oral Tablet", "10839", "M05BA04", "Aminobisphosphonate Bone Resorption Inhibitor", ["Fosamax", "Osteofos"],
     "Treatment and prevention of postmenopausal osteoporosis, male osteoporosis, glucocorticoid-induced osteoporosis, Paget's disease.",
     "70 mg orally once weekly (or 10 mg daily) taken with 8 oz of plain water FIRST THING in the morning >=30 min before any food, beverage, or other medications; MUST REMAIN UPRIGHT for >=30 min.",
     "Abnormalities of the esophagus delaying esophageal emptying (stricture, achalasia); inability to stand or sit upright for >=30 minutes; hypocalcemia; severe renal impairment (CrCl <35 mL/min).",
     "Severe esophageal irritation, ulceration, and perforation; Osteonecrosis of the Jaw (ONJ - oral dental exams recommended); Atypical subtrochanteric and diaphyseal femur fractures with long-term use (>5 years).",
     "Abdominal pain, dyspepsia, acid regurgitation, esophageal ulceration, musculoskeletal pain, hypocalcemia.",
     "Calcium, antacids, oral medications decrease absorption to zero (must separate by 30-60 min); NSAIDs increase GI ulceration.",
     "Category C. Long skeletal retention half-life (up to 10 years)."),
    ("Risedronate", "35 mg", "Oral Tablet", "35827", "M05BA07", "Pyridinyl Bisphosphonate", ["Actonel", "Atelvia"],
     "Postmenopausal osteoporosis and Paget's disease.", "35 mg orally once weekly with plain water >=30 min before food (remain upright 30 min).",
     "Esophageal abnormalities, inability to sit upright, hypocalcemia.", "Esophagitis, osteonecrosis of jaw, atypical femur fractures.",
     "Abdominal pain, dyspepsia, rash, arthralgia.", "Calcium, iron, antacids.",
     "Category C."),
    ("Ibandronate", "150 mg", "Oral / IV", "74885", "M05BA06", "Bisphosphonate Bone Resorption Inhibitor", ["Boniva"],
     "Postmenopausal osteoporosis treatment and prevention.", "150 mg orally once monthly with plain water 60 min before food (remain upright 60 min) or 3 mg IV every 3 months.",
     "Inability to stand/sit upright for 60 min, hypocalcemia, CrCl <30 mL/min.", "Esophagitis, ONJ, hypocalcemia.",
     "Dyspepsia, flu-like symptoms (IV), back pain, myalgia.", "Calcium supplements.",
     "Category C."),
    ("Zoledronic Acid", "5 mg", "IV Infusion", "284639", "M05BA08", "High-Potency Nitrogen-Containing Bisphosphonate", ["Reclast", "Zometa"],
     "Postmenopausal osteoporosis (5 mg IV once yearly), Paget's disease, hypercalcemia of malignancy (Zometa 4 mg IV), bone metastases.",
     "5 mg IV infusion over >=15 minutes once every 12 months for osteoporosis (ensure adequate hydration and normal calcium/vitamin D).",
     "Hypocalcemia; CrCl <35 mL/min or acute renal impairment.", "Severe acute renal failure/tubular necrosis; acute phase reaction (fever, myalgia, arthralgia within 72h); ONJ; hypocalcemia.",
     "Acute phase flu-like reaction (fever, chills, bone pain - 30%), hypocalcemia, headache, renal impairment.",
     "Aminoglycosides, loop diuretics, nephrotoxic agents.",
     "Category D. Teratogenic in animal models."),
    ("Denosumab", "60 mg", "SC Injection", "993450", "M05BX04", "RANK Ligand (RANKL) Human Monoclonal Antibody", ["Prolia", "Xgeva"],
     "Osteoporosis at high risk for fracture in postmenopausal women (Prolia 60 mg q6m); prevention of skeletal-related events in bone metastases (Xgeva 120 mg q4w).",
     "60 mg SC every 6 months in upper arm, thigh, or abdomen; administer with daily calcium 1,000 mg and Vitamin D 400 IU.",
     "Hypocalcemia (pre-existing hypocalcemia must be corrected prior to initiation); pregnancy.",
     "Severe life-threatening hypocalcemia (especially in CKD/dialysis); osteonecrosis of the jaw (ONJ); atypical femur fractures; serious skin infections (cellulitis); rebound vertebral fractures upon drug discontinuation (do not stop without transitioning to bisphosphonate).",
     "Back pain, extremity pain, musculoskeletal pain, hypercholesterolemia, cystitis, hypocalcemia.",
     "Immunosuppressants, calcimimetics.",
     "Category X. Strictly contraindicated in pregnancy (fetal harm)."),
    ("Teriparatide", "20 mcg", "SC Injection", "382741", "H05AA02", "Recombinant Human Parathyroid Hormone (PTH 1-34)", ["Forteo"],
     "Severe osteoporosis with high fracture risk (anabolic bone builder).", "20 mcg SC once daily into thigh or abdomen (max lifetime duration 2 years).",
     "Paget's disease of bone, unexplained alkaline phosphatase elevation, prior skeletal radiation therapy, bone metastases, hypercalcemia.",
     "Black Box: Osteosarcoma in rodent models (dose- and duration-dependent); transient orthostatic hypotension; hypercalcemia.",
     "Nausea, arthralgia, dizziness, leg cramps, hypercalcemia.", "Digoxin (hypercalcemia predisposes to digitalis toxicity).",
     "Category C."),
    ("Calcitriol", "0.25 mcg", "Oral Capsule / IV", "1895", "A11CC04", "Active Vitamin D3 (1,25-Dihydroxyvitamin D3)", ["Rocaltrol", "Calcijex"],
     "Hypocalcemia in chronic renal dialysis, secondary hyperparathyroidism, hypoparathyroidism.",
     "0.25 mcg to 1 mcg orally once daily.",
     "Hypercalcemia, vitamin D toxicity.", "Hypercalcemia and hyperphosphatemia leading to metastatic soft tissue calcification.",
     "Hypercalcemia symptoms (weakness, headache, nausea, constipation, polyuria), nephrocalcinosis.",
     "Thiazide diuretics (hypercalcemia), digitalis, magnesium antacids.",
     "Category C."),
    ("Cinacalcet", "30 mg", "Oral Tablet", "399946", "H05BX01", "Calcimimetic (Calcium-Sensing Receptor Allosteric Modulator)", ["Sensipar"],
     "Secondary hyperparathyroidism in CKD on dialysis, parathyroid carcinoma hypercalcemia.",
     "30 mg orally once daily with food; titrate every 2-4 weeks to target intact PTH.",
     "Hypocalcemia (serum calcium <8.4 mg/dL).", "Severe hypocalcemia (seizures, QT prolongation, fatal arrhythmias); adynamic bone disease.",
     "Hypocalcemia, nausea, vomiting, diarrhea, myalgia, QT prolongation.", "CYP2D6 substrates (potent inhibitor of CYP2D6: increases carvedilol, tricyclics), ketoconazole.",
     "Category C."),
    ("Desmopressin", "0.1 mg", "Oral / Nasal Spray / IV", "3249", "H01BA02", "Synthetic Vasopressin V2 Receptor Agonist", ["DDAVP", "Stimate", "Nocdurna"],
     "Central diabetes insipidus, nocturnal enuresis, hemophilia A and mild von Willebrand disease (releases vWF/Factor VIII).",
     "0.1 mg to 0.4 mg orally 2 to 3 times daily (or nasal spray 10-40 mcg daily).",
     "Hyponatremia or history of hyponatremia; moderate-to-severe renal impairment (CrCl <50 mL/min); polydipsia.",
     "Black Box: Severe, life-threatening hyponatremia and water intoxication leading to seizures, coma, and death; fluid restriction mandatory.",
     "Hyponatremia, headache, flushing, nausea, abdominal cramps, nasal congestion.",
     "SSRIs, carbamazepine, NSAIDs, loop diuretics (increase risk of fatal hyponatremia).",
     "Category B. Treatment of choice for central diabetes insipidus in pregnancy."),
    ("Octreotide", "100 mcg", "SC / IV / Depot IM", "7593", "H01CB02", "Long-Acting Somatostatin Analog", ["Sandostatin", "Sandostatin LAR"],
     "Acromegaly, severe diarrhea/flushing in carcinoid syndrome, acute bleeding esophageal varices (splanchnic vasoconstriction).",
     "50 mcg to 200 mcg SC/IV every 8 hours; IV bolus 50 mcg followed by 50 mcg/hr continuous infusion for 5 days in variceal bleed.",
     "Hypersensitivity to octreotide.", "Cholelithiasis/gallstones (50% with chronic use); cardiac conduction abnormalities/bradycardia; hypo- or hyperglycemia.",
     "Biliary sludge/cholelithiasis, diarrhea, abdominal pain, nausea, sinus bradycardia, injection site pain.",
     "Cyclosporine (decreases cyclosporine levels by 50%), bromocriptine, oral antidiabetics.",
     "Category B."),
    ("Cabergoline", "0.5 mg", "Oral Tablet", "25255", "N04BC06", "Dopamine D2 Receptor Agonist", ["Dostinex"],
     "Hyperprolactinemic disorders (prolactinoma, amenorrhea, galactorrhea, infertility).",
     "0.25 mg orally twice weekly; titrate by 0.25 mg twice weekly up to 1 mg twice weekly.",
     "Uncontrolled hypertension; history of cardiac valvular disorders.",
     "Cardiac valvular fibrosis (tricuspid/mitral regurgitation with high cumulative doses); impulsive/compulsive behaviors.",
     "Nausea, headache, dizziness, fatigue, orthostatic hypotension, constipation.",
     "Dopamine antagonists (antipsychotics, metoclopramide antagonize effect).",
     "Category B. High efficacy and safety in prolactinoma pregnancy restoration."),
    ("Bromocriptine", "2.5 mg", "Oral Tablet", "1738", "N04BC01", "Ergot Dopamine D2 Agonist", ["Parlodel", "Cycloset"],
     "Hyperprolactinemia, acromegaly, Parkinson's disease, type 2 diabetes adjunct (Cycloset).",
     "1.25 mg to 2.5 mg orally daily with food at bedtime.",
     "Uncontrolled hypertension, severe ischemic heart disease.", "Orthostatic hypotension, psychotic reactions, retroperitoneal fibrosis.",
     "Nausea (frequent), dizziness, fatigue, headache, vomiting, hypotension.", "Strong CYP3A4 inhibitors, sumatriptan, sympathomimetics.",
     "Category B."),
    ("Somatropin", "1 mg", "SC Injection", "9940", "H01AC01", "Recombinant Human Growth Hormone (rhGH)", ["Genotropin", "Nutropin", "Norditropin", "Humatrope"],
     "Growth hormone deficiency in children and adults, Turner syndrome, Prader-Willi syndrome, chronic kidney disease growth failure.",
     "Individualized SC dosing daily (0.16 to 0.24 mg/kg/week in children).",
     "Active malignancy, closed epiphyses in children, acute critical illness following open heart surgery or trauma, diabetic retinopathy.",
     "Slipped capital femoral epiphysis; intracranial hypertension (pseudotumor cerebri); glucose intolerance/diabetes; scoliosis progression.",
     "Peripheral edema, arthralgia, myalgia, headache, hyperglycemia, injection site pain.",
     "Glucocorticoids (inhibit growth response), estrogens, oral hypoglycemics.",
     "Category C.")
]

# Domain 5: Lipid-Lowering & Atherosclerosis Agents (25)
from scripts.domains_lipids_coag import CAT_5_LIPIDS, CAT_6_ANTICOAG, CAT_7_GI, CAT_8_RESP

def get_metabolic_gi_resp_records() -> List[Dict[str, Any]]:
    """Assemble all records from domains 4, 5, 6, 7, and 8."""
    records = []
    
    def process_group(group: List[Tuple]):
        for name, st, form, rxcui, atc, cls, aliases, ind, dos, con, war, adv, inter, prg in group:
            records.append({
                "name": name, "strength": st, "form": form, "rxcui": rxcui, "atc": atc,
                "class": cls, "aliases": aliases, "ind": ind, "dos": dos, "con": con,
                "war": war, "adv": adv, "int": inter, "prg": prg
            })

    process_group(CAT_4_METABOLIC)
    process_group(CAT_5_LIPIDS)
    process_group(CAT_6_ANTICOAG)
    process_group(CAT_7_GI)
    process_group(CAT_8_RESP)
    return records

if __name__ == "__main__":
    r = get_metabolic_gi_resp_records()
    print(f"Domains 4-8 total records: {len(r)}")
