"""Clinical Knowledge Base: Domains 12, 13, and 14 (Urological, Oncology, Dermatology/Specialty).

Contains 60+ authentic medicine monographs with US NLM RxNorm RxCUIs, ATC codes, and FDA labeling.
"""
from typing import Any, Dict, List, Tuple

# Domain 12: Urological, Renal & Bone/Mineral (25)
CAT_12_UROLOGY: List[Tuple] = [
    ("Tamsulosin", "0.4 mg", "Oral Capsule", "77492", "G04CA02", "Selective Alpha-1A Adrenergic Antagonist (Uroselective)", ["Flomax", "Urimax", "Veltam"],
     "Treatment of signs and symptoms of Benign Prostatic Hyperplasia (BPH); off-label facilitation of ureteral stone passage.",
     "0.4 mg orally once daily approximately 30 minutes following the same meal each day (swallow capsule whole; may increase to 0.8 mg daily after 2-4 weeks).",
     "Known hypersensitivity to tamsulosin hydrochloride.",
     "Intraoperative Floppy Iris Syndrome (IFIS) during cataract and glaucoma surgery (ophthalmologist must be informed prior to surgery); orthostatic hypotension and syncope; priapism.",
     "Dizziness, abnormal/retrograde ejaculation (8-18%), headache, rhinitis, asthenia, postural hypotension.",
     "Strong CYP3A4 inhibitors (ketoconazole increases tamsulosin AUC 2.8-fold), strong CYP2D6 inhibitors (paroxetine), other alpha-blockers, PDE-5 inhibitors (additive hypotension).",
     "Category B. Not indicated for use in females."),
    ("Finasteride", "5 mg", "Oral Tablet", "25025", "G04CB01", "Type II 5-Alpha Reductase Inhibitor", ["Proscar", "Propecia", "Finast"],
     "Treatment of symptomatic BPH in men with an enlarged prostate (reduces risk of acute urinary retention and TURP surgery - 5 mg daily); androgenetic alopecia (1 mg daily).",
     "BPH: 5 mg orally once daily with or without food; Male pattern hair loss: 1 mg once daily (requires >=6 months therapy to assess response).",
     "Pregnancy and women of childbearing potential (must not handle crushed or broken tablets due to risk of absorption and teratogenicity to male fetus); hypersensitivity.",
     "Black Box/FDA Warning: High-grade prostate cancer risk; halves serum PSA levels (multiply PSA by 2 for accurate screening); post-finasteride syndrome (persistent sexual dysfunction, depression).",
     "Erectile dysfunction, decreased libido, ejaculation disorder, gynecomastia, breast tenderness, depression.",
     "Minimal CYP interactions; no dose adjustment in renal impairment.",
     "Category X. Potent teratogen to male fetus (abnormal development of external genitalia). Women of childbearing age must not touch broken tablets."),
    ("Dutasteride", "0.5 mg", "Oral Capsule", "384457", "G04CB02", "Dual Type I & Type II 5-Alpha Reductase Inhibitor", ["Avodart", "Dutas"],
     "Benign prostatic hyperplasia (BPH) monotherapy or combined with tamsulosin (Duodart/Jalyn).",
     "0.5 mg orally once daily (swallow whole - content is mucosal irritant).",
     "Pregnancy, women of childbearing potential, pediatric patients.",
     "Halves serum PSA levels; high-grade prostate cancer signal; teratogenicity to male fetus.",
     "Impotence, decreased libido, ejaculation disorders, gynecomastia.",
     "CYP3A4 inhibitors (ketoconazole, diltiazem increase dutasteride exposure).",
     "Category X. Blood donation prohibited until >=6 months after last dose."),
    ("Alfuzosin", "10 mg", "Oral Tablet (ER)", "15372", "G04CA01", "Uroselective Alpha-1 Adrenergic Antagonist", ["Uroxatral", "Alfoo"],
     "Signs and symptoms of benign prostatic hyperplasia (BPH).",
     "10 mg orally once daily immediately following the same meal each day (swallow whole).",
     "Moderate or severe hepatic impairment (Child-Pugh B or C); concurrent strong CYP3A4 inhibitors.",
     "QT interval prolongation; orthostatic hypotension/syncope; Intraoperative Floppy Iris Syndrome (IFIS).",
     "Dizziness, headache, fatigue, upper respiratory tract infection.",
     "Potent CYP3A4 inhibitors (ketoconazole, itraconazole, ritonavir contraindicated), PDE5 inhibitors.",
     "Category B."),
    ("Silodosin", "8 mg", "Oral Capsule", "855324", "G04CA04", "Highly Selective Alpha-1A Adrenergic Antagonist", ["Rapaflo", "Silodal"],
     "Signs and symptoms of benign prostatic hyperplasia.",
     "8 mg orally once daily with a meal (reduce to 4 mg once daily in moderate renal impairment CrCl 30-50 mL/min).",
     "Severe renal impairment (CrCl <30 mL/min); severe hepatic impairment; strong CYP3A4 inhibitors.",
     "Highest rate of retrograde ejaculation among alpha blockers (28%); IFIS during cataract surgery.",
     "Retrograde ejaculation (28%), dizziness, diarrhea, orthostatic hypotension, nasopharyngitis.",
     "Strong CYP3A4 inhibitors (ketoconazole, clarithromycin contraindicated), strong P-gp inhibitors.",
     "Category B."),
    ("Oxybutynin", "5 mg", "Oral Tablet / Transdermal", "7788", "G04BD04", "Non-Selective Muscarinic Anticholinergic", ["Ditropan", "Ditropan XL", "Oxytrol"],
     "Overactive bladder with symptoms of urge urinary incontinence, urgency, and frequency; neurogenic detrusor overactivity.",
     "5 mg orally 2 to 3 times daily (or extended-release 5-30 mg once daily; Transdermal patch 3.9 mg/day twice weekly).",
     "Urinary retention, gastric retention, uncontrolled narrow-angle glaucoma, severe ulcerative colitis.",
     "Severe anticholinergic side effects (dry mouth 70%, cognitive impairment/delirium in elderly - Beers Criteria Avoid); heat prostration in high environmental temperatures.",
     "Dry mouth (severe), constipation, somnolence, blurred vision, dizziness, urinary hesitancy, confusion in elderly.",
     "Anticholinergic drugs, CYP3A4 inhibitors (ketoconazole), cholinesterase inhibitors.",
     "Category B."),
    ("Tolterodine", "2 mg", "Oral Tablet", "205934", "G04BD07", "Muscarinic Receptor Antagonist", ["Detrol", "Detrol LA", "Roliten"],
     "Overactive bladder with urge incontinence and frequency.", "2 mg orally twice daily (or 4 mg once daily LA formulation; reduce to 2 mg LA in renal/hepatic decline).",
     "Urinary retention, gastric retention, uncontrolled narrow-angle glaucoma.", "Dose-dependent QT prolongation; anticholinergic CNS delirium.",
     "Dry mouth (35%), headache, constipation, dry eyes, abdominal pain.",
     "Strong CYP3A4 inhibitors (limit to 2 mg daily LA), CYP2D6 inhibitors.",
     "Category C."),
    ("Solifenacin", "5 mg", "Oral Tablet", "404863", "G04BD08", "Competitive Muscarinic M3 Receptor Antagonist", ["Vesicare"],
     "Overactive bladder with symptoms of urgency, frequency, and urge incontinence.",
     "5 mg orally once daily with water; may increase to 10 mg once daily.",
     "Urinary retention, gastric retention, narrow-angle glaucoma.", "QT interval prolongation; angioedema; urinary retention.",
     "Dry mouth, constipation, blurred vision, dyspepsia, UTI.", "Strong CYP3A4 inhibitors (max dose 5 mg daily with ketoconazole).",
     "Category C."),
    ("Mirabegron", "25 mg", "Oral Tablet (ER)", "1306387", "G04BD12", "Beta-3 Adrenergic Receptor Agonist", ["Myrbetriq"],
     "Treatment of overactive bladder (OAB) with symptoms of urge urinary incontinence, urgency, and frequency (non-anticholinergic mechanism).",
     "25 mg orally once daily swallowed whole with water; may increase to 50 mg once daily after 4-8 weeks.",
     "Severe uncontrolled hypertension (SBP >=180 mm Hg or DBP >=110 mm Hg); hypersensitivity.",
     "Dose-dependent increase in blood pressure and heart rate (regular blood pressure monitoring mandatory); urinary retention in bladder outlet obstruction.",
     "Hypertension, nasopharyngitis, urinary tract infection, headache, tachycardia.",
     "Moderate CYP2D6 inhibitor: increases exposure of metoprolol, desipramine, propafenone.",
     "Category C. Preferred alternative when anticholinergic agents are contraindicated in elderly."),
    ("Sildenafil", "50 mg", "Oral Tablet", "214198", "G04BE03", "Phosphodiesterase-5 (PDE5) Inhibitor", ["Viagra", "Revatio"],
     "Erectile dysfunction (Viagra 25-100 mg PRN); Pulmonary Arterial Hypertension (PAH WHO Group 1 - Revatio 20 mg TID).",
     "Erectile dysfunction: 50 mg orally approximately 1 hour before sexual activity (max 100 mg once daily); PAH: 20 mg orally three times daily.",
     "Concomitant use of organic nitrates in any form (nitroglycerin, isosorbide mononitrate/dinitrate) or soluble guanylate cyclase stimulators (riociguat).",
     "Life-threatening severe hypotension and circulatory collapse with nitrates; non-arteritic anterior ischemic optic neuropathy (NAION - sudden irreversible vision loss); sudden sensorineural hearing loss; priapism (>4 hours - medical emergency).",
     "Headache (16%), flushing (10%), dyspepsia, nasal congestion, visual color tinge / cyanopsia (blue-tinted vision via PDE6 retinal inhibition), dizziness.",
     "Nitrates (strictly contraindicated for >=24 hours post-sildenafil), alpha-blockers (separate by >=4 hours to avoid hypotension), strong CYP3A4 inhibitors (start at 25 mg).",
     "Category B."),
    ("Tadalafil", "20 mg", "Oral Tablet", "358265", "G04BE08", "Long-Acting PDE5 Inhibitor (Half-life 17.5 hours)", ["Cialis", "Adcirca", "Megalis"],
     "Erectile dysfunction (PRN or daily 2.5-5 mg), Benign Prostatic Hyperplasia (5 mg once daily), Pulmonary Arterial Hypertension (Adcirca 40 mg daily).",
     "ED PRN: 10 mg to 20 mg orally at least 30 minutes before sexual activity (effective up to 36 hours); ED/BPH daily: 5 mg orally once daily.",
     "Concomitant nitrates or riociguat.",
     "Severe refractory hypotension with nitrates; NAION vision loss; priapism; back pain and myalgia (due to PDE11 inhibition).",
     "Headache, dyspepsia, back pain (frequent - 6%), myalgia, nasal congestion, flushing.",
     "Nitrates (strictly contraindicated for >=48 hours post-tadalafil due to long half-life), alpha-blockers, strong CYP3A4 inhibitors.",
     "Category B."),
    ("Sodium Polystyrene Sulfonate", "15 g", "Oral / Rectal Suspension", "9909", "V03AE01", "Cation-Exchange Resin (Hyperkalemia Binder)", ["Kayexalate", "Kionex"],
     "Treatment of hyperkalemia (slow onset - NOT for emergency life-threatening hyperkalemia).",
     "15 g orally 1 to 4 times daily in water/syrup (or 30-50 g as rectal retention enema).",
     "Hypokalemia, obstructive bowel disease, neonates with reduced gut motility.",
     "Black Box: Intestinal necrosis, bowel perforation, and ischemic colitis (especially when formulated with sorbitol); binds oral medications.",
     "Constipation, fecal impaction, nausea, vomiting, hypokalemia, sodium overload/edema.",
     "Binds oral medications non-specifically (must separate all oral drugs by >=3 hours before or after).",
     "Category C."),
    ("Patiromer", "8.4 g", "Oral Powder Packet", "1720585", "V03AE09", "Non-Absorbed Potassium-Binding Polymer", ["Veltassa"],
     "Treatment of chronic hyperkalemia in patients on RAAS inhibitors (CKD, heart failure).",
     "8.4 g orally once daily mixed in 3 oz water with food; titrate up to 25.2 g once daily.",
     "Hypersensitivity.", "Delayed onset (not for emergency hyperkalemia); hypomagnesemia; constipation.",
     "Constipation (7%), hypomagnesemia (5%), diarrhea, abdominal discomfort, flatulence.",
     "Binds other oral medications (separate all oral drugs by at least 2 hours).",
     "Category C. Safe non-absorbed polymer in chronic hyperkalemia."),
    ("Sodium Zirconium Cyclosilicate", "10 g", "Oral Powder Packet", "2044815", "V03AE10", "Selective Potassium Cation Inorganic Crystal Trap", ["Lokelma"],
     "Treatment of acute and chronic hyperkalemia (onset within 1 hour).",
     "10 g orally three times daily for up to 48 hours for acute phase; maintenance 5 g to 10 g once daily.",
     "Severe constipation, bowel obstruction.", "Sodium retention and peripheral edema (contains 400 mg sodium per 5 g dose); X-ray opacity artifact.",
     "Peripheral edema (6%), hypokalemia, constipation.", "Increases gastric pH (separate pH-dependent drugs by 2 hours).",
     "Category C. Fast potassium reduction within 1 hour."),
    ("Sevelamer Carbonate", "800 mg", "Oral Tablet / Powder", "748856", "V03AE02", "Non-Calcium Phosphate Binder", ["Renvela", "Renagel"],
     "Control of serum phosphorus in patients with chronic kidney disease on dialysis.",
     "800 mg to 1,600 mg orally three times daily with meals (titrate based on serum phosphorus).",
     "Bowel obstruction, severe GI motility disorders.", "Severe constipation and bowel perforation; decreases absorption of vitamins D, E, K.",
     "Nausea, vomiting, diarrhea, dyspepsia, abdominal pain, constipation, flatulence.",
     "Ciprofloxacin, levothyroxine, mycophenolate (separate administration by 1-2 hours).",
     "Category C. Non-absorbed phosphate binder."),
    ("Alendronate", "70 mg", "Oral Tablet", "647", "M05BA04", "Bisphosphonate Osteoclast Inhibitor", ["Fosamax", "Osteofos"],
     "Treatment and prevention of postmenopausal osteoporosis, osteoporosis in men, glucocorticoid-induced osteoporosis, Paget's disease of bone.",
     "70 mg orally ONCE WEEKLY (or 10 mg once daily) with a full 8 oz glass of plain water upon arising in the morning; must remain upright for >=30 minutes before food.",
     "Abnormalities of esophagus that delay esophageal emptying (stricture, achalasia); inability to stand or sit upright for at least 30 minutes; hypocalcemia; severe renal impairment (CrCl <35 mL/min).",
     "Severe esophageal irritation, ulceration, and erosions; Osteonecrosis of the Jaw (ONJ - dental exam before therapy); atypical subtrochanteric femur fractures with long-term use (>3-5 years); severe bone/joint pain.",
     "Abdominal pain, dyspepsia, acid regurgitation, esophageal ulcer, musculoskeletal pain, constipation, diarrhea.",
     "Calcium supplements, antacids, food, and all other oral medications drastically reduce bioavailability (take >=30 min prior to all other oral intake).",
     "Category C. Correct hypocalcemia prior to initiation."),
    ("Risedronate", "35 mg", "Oral Tablet", "8687", "M05BA07", "Pyridinyl Bisphosphonate", ["Actonel"],
     "Postmenopausal osteoporosis, male osteoporosis, glucocorticoid osteoporosis, Paget's disease.",
     "35 mg orally once weekly with 8 oz plain water >=30 min before breakfast (must sit/stand upright for 30 min).",
     "Esophageal abnormalities, inability to sit upright for 30 min, hypocalcemia, CrCl <30 mL/min.",
     "Esophagitis/ulceration, ONJ, atypical femur fractures, hypocalcemia.",
     "Dyspepsia, abdominal pain, diarrhea, arthralgia, headache.",
     "Calcium, antacids, food (separate by >=30 min).",
     "Category C."),
    ("Zoledronic Acid", "5 mg", "IV Infusion", "88480", "M05BA08", "High-Potency Nitrogen-Containing Bisphosphonate", ["Reclast", "Zometa"],
     "Postmenopausal osteoporosis (5 mg IV once yearly), Paget's disease, hypercalcemia of malignancy (Zometa 4 mg IV), bone metastases from solid tumors.",
     "Osteoporosis: 5 mg IV infusion over >=15 minutes ONCE YEARLY; ensure adequate calcium (1,200 mg/day) and vitamin D (800-1,000 IU/day).",
     "Hypocalcemia, severe renal impairment (CrCl <35 mL/min or acute renal failure).",
     "Acute phase reaction (flu-like symptoms, fever, myalgias in 30% within 3 days of infusion - premedicate with acetaminophen); acute renal failure; osteonecrosis of jaw (ONJ); severe hypocalcemia.",
     "Flu-like illness, fever, myalgia, bone pain, headache, nausea, hypocalcemia.",
     "Aminoglycosides, loop diuretics, nephrotoxic agents.",
     "Category D. Strictly contraindicated in pregnancy."),
    ("Denosumab", "60 mg", "SC Injection", "993452", "M05BX04", "RANK Ligand (RANKL) Human Monoclonal Antibody", ["Prolia", "Xgeva"],
     "Treatment of postmenopausal osteoporosis at high risk for fracture (Prolia 60 mg SC q6 months); prevention of skeletal-related events in bone metastases (Xgeva 120 mg SC q4 weeks).",
     "Osteoporosis: 60 mg SC in upper arm, thigh, or abdomen ONCE EVERY 6 MONTHS by healthcare provider (must take daily calcium 1,000 mg and vitamin D 400 IU).",
     "Hypocalcemia (must correct hypocalcemia before dosing); pregnancy (strictly contraindicated).",
     "Severe life-threatening hypocalcemia (especially in severe CKD/dialysis); osteonecrosis of jaw (ONJ); atypical femur fractures; serious skin infections (cellulitis); severe rebound vertebral fractures upon discontinuation.",
     "Back pain, extremity pain, musculoskeletal pain, hypercholesterolemia, cystitis.",
     "Immunosuppressants (additive infection risk).",
     "Category X. Absolute contraindication in pregnancy (causes fetal harm/bone abnormalities)."),
    ("Calcitriol", "0.25 mcg", "Oral Capsule", "1895", "A11CC04", "Active 1,25-Dihydroxyvitamin D3 (Calcitriol)", ["Rocaltrol"],
     "Hypocalcemia in chronic kidney disease on dialysis, secondary hyperparathyroidism in CKD, hypoparathyroidism.",
     "0.25 mcg orally once daily in the morning; titrate by 0.25 mcg/day every 4-8 weeks (does not require renal 1-alpha hydroxylation).",
     "Hypercalcemia, vitamin D toxicity.",
     "Hypercalcemia and hyperphosphatemia with metastatic calcification of soft tissues and blood vessels; narrow therapeutic index.",
     "Hypercalcemia symptoms (weakness, headache, somnolence, nausea, vomiting, constipation, polyuria, polydipsia).",
     "Thiazide diuretics (increased hypercalcemia risk), digitalis (hypercalcemia precipitates digitalis toxicity), magnesium antacids.",
     "Category C. Active hormone form of vitamin D."),
    ("Cinacalcet", "30 mg", "Oral Tablet", "399943", "H05BX01", "Type II Calcimimetic Agent (CaSR Allosteric Modulator)", ["Sensipar"],
     "Secondary hyperparathyroidism in adult patients with chronic kidney disease on dialysis; parathyroid carcinoma hypercalcemia.",
     "30 mg orally once daily with food or shortly after a meal; titrate every 2-4 weeks to target intact PTH levels.",
     "Serum calcium <8.4 mg/dL (hypocalcemia - do not initiate if serum calcium below normal range).",
     "Severe hypocalcemia / tetany / QT prolongation and ventricular arrhythmias (monitor serum calcium weekly during titration); adynamic bone disease.",
     "Nausea (31%), vomiting (27%), diarrhea, myalgia, hypocalcemia, dizziness.",
     "Strong CYP2D6 inhibitor (increases desipramine, metoprolol exposure), strong CYP3A4 inhibitors (ketoconazole doubles cinacalcet).",
     "Category C."),
    ("Desmopressin", "0.2 mg", "Oral Tablet / Nasal", "3257", "H01BA02", "Synthetic V2 Vasopressin Receptor Agonist", ["DDAVP", "Minirin"],
     "Central diabetes insipidus, primary nocturnal enuresis in children >=6 years, hemophilia A and mild von Willebrand disease type 1.",
     "Central diabetes insipidus: 0.1 mg to 0.2 mg orally 2 to 3 times daily (titrate to control polyuria/nocturia; restrict evening fluids).",
     "Moderate-to-severe renal impairment (CrCl <50 mL/min); hyponatremia or history of hyponatremia; syndrome of inappropriate ADH (SIADH).",
     "Black Box: Life-threatening severe water intoxication, profound hyponatremia, cerebral edema, seizures, and death (mandatory fluid restriction and serum sodium monitoring).",
     "Headache, nausea, abdominal cramps, hyponatremia, nasal congestion (nasal spray), facial flushing.",
     "Drugs predisposing to hyponatremia (SSRIs, TCAs, carbamazepine, NSAIDs, thiazides massively increase water intoxication risk).",
     "Category B. Treatment for hyponatremic encephalopathy: 3% Hypertonic Saline.")
]

# Domain 13: Hematology, Oncology & Supportive Care (25)
CAT_13_ONCO: List[Tuple] = [
    ("Fluorouracil", "500 mg", "IV Infusion", "4454", "L01BC02", "Pyrimidine Analog Antimetabolite (5-FU)", ["Adrucil", "Efudex"],
     "Colorectal cancer (FOLFOX/FOLFIRI regimens), gastric, pancreatic, and breast carcinoma; actinic keratosis (topical).",
     "IV continuous infusion 2,400 to 3,000 mg/m2 over 46 hours with Leucovorin; Topical 5% cream twice daily.",
     "Severe dihydropyrimidine dehydrogenase (DPD) enzyme deficiency (causes fatal toxicity); pregnancy.",
     "Black Box: Fatal toxicity in DPD deficiency (severe mucositis, neutropenia, diarrhea, neurotoxicity); coronary vasospasm/cardiotoxicity; palmar-plantar erythrodysesthesia (hand-foot syndrome).",
     "Diarrhea, mucositis/stomatitis, hand-foot syndrome (erythema/desquamation of palms/soles), neutropenia, cardiotoxicity (angina/arrhythmias).",
     "Warfarin (massively elevates INR), leucovorin (enhances 5-FU toxicity).",
     "Category D. Antidote for 5-FU toxicity / DPD overdose: Uridine triacetate (Vistogard)."),
    ("Capecitabine", "500 mg", "Oral Tablet", "1364431", "L01BC06", "Oral Fluoropyrimidine Prodrug of 5-FU", ["Xeloda"],
     "Colorectal cancer (adjuvant/metastatic), advanced gastric cancer, metastatic breast cancer.",
     "1,250 mg/m2 orally twice daily with water within 30 minutes after a meal for 14 days followed by 7-day rest.",
     "Severe renal impairment (CrCl <30 mL/min); known DPD deficiency; pregnancy.",
     "Black Box: Warfarin interaction leading to severe bleeding and death (monitor INR frequently); severe diarrhea/dehydration; severe hand-foot syndrome.",
     "Hand-foot syndrome (54%), diarrhea, hyperbilirubinemia, nausea, fatigue, abdominal pain.",
     "Warfarin (Black Box - massive INR spikes), antacids (increase capecitabine exposure), phenytoin.",
     "Category D. Absolute contraindication in pregnancy."),
    ("Cisplatin", "50 mg", "IV Infusion", "2555", "L01XA01", "Platinum Coordination Complex Alkylating-Like Agent", ["Platinol"],
     "Testicular cancer, ovarian cancer, advanced bladder cancer, head and neck carcinomas, non-small cell lung cancer.",
     "20 mg/m2 to 100 mg/m2 IV once every 3 to 4 weeks (vigorous pre- and post-hydration with 1-2 L saline mandatory).",
     "Pre-existing severe renal impairment, hearing impairment, myelosuppression.",
     "Black Box: Severe cumulative nephrotoxicity (acute tubular necrosis); severe auditory ototoxicity (irreversible high-frequency hearing loss, tinnitus); severe nausea/vomiting (highly emetogenic chemotherapy HEC - requires 3-drug antiemetic regimen); myelosuppression.",
     "Severe nausea/vomiting (near 100% without prophylaxis), nephrotoxicity, peripheral neuropathy, ototoxicity, hypomagnesemia, anemia.",
     "Aminoglycosides, amphotericin B (synergistic nephrotoxicity/ototoxicity), loop diuretics.",
     "Category D. Chemoprotectant for nephrotoxicity: Amifostine / aggressive saline diuresis."),
    ("Carboplatin", "150 mg", "IV Infusion", "2006", "L01XA02", "Second-Generation Platinum Chemotherapeutic", ["Paraplatin"],
     "Ovarian carcinoma, lung cancer, head and neck cancers (dosed by Calvert formula targeting AUC).",
     "Dose (mg) = Target AUC x (GFR + 25) administered IV once every 4 weeks.",
     "Severe bone marrow depression, severe bleeding.", "Black Box: Severe bone marrow suppression (dose-limiting thrombocytopenia); anaphylactic reactions.",
     "Thrombocytopenia (dose-limiting nadir at day 21), neutropenia, anemia, nausea, vomiting.",
     "Nephrotoxins, aminoglycosides.",
     "Category D."),
    ("Cyclophosphamide", "500 mg", "Oral / IV", "3004", "L01AA01", "Nitrogen Mustard Alkylating Agent", ["Cytoxan"],
     "Lymphomas, leukemias, breast and ovarian cancer, severe lupus nephritis, vasculitis.",
     "500 mg to 1,000 mg/m2 IV once monthly (or oral 1-2 mg/kg/day); ensure high fluid intake.",
     "Severe bone marrow suppression, urinary outflow obstruction.",
     "Black Box: Fatal hemorrhagic cystitis (acrolein metabolite toxicity - prevent with aggressive hydration and IV Mesna); severe myelosuppression; secondary malignancies (bladder cancer, AML); cardiotoxicity at high transplant doses.",
     "Nausea, vomiting, alopecia (complete 100%), leukopenia, hemorrhagic cystitis, amenorrhea/azoospermia.",
     "Allopurinol (increases bone marrow toxicity), doxorubicin (synergistic cardiotoxicity).",
     "Category D. Chemoprotectant for bladder toxicity: Mesna."),
    ("Doxorubicin", "50 mg", "IV Infusion", "3639", "L01DB01", "Anthracycline Topoisomerase II Inhibitor", ["Adriamycin"],
     "Breast cancer, Hodgkin's and non-Hodgkin's lymphoma, acute leukemias, soft tissue sarcomas.",
     "60 mg to 75 mg/m2 IV once every 21 days (cumulative lifetime dose cap of 450-550 mg/m2 to prevent irreversible cardiomyopathy).",
     "Severe baseline myocardial insufficiency / cardiomyopathy; severe hepatic impairment (bilirubin >5 mg/dL); severe persistent myelosuppression.",
     "Black Box: Dose-dependent irreversible congestive heart failure and cardiomyopathy (lifetime dose limit 550 mg/m2); severe local tissue necrosis with extravasation (vesicant); severe myelosuppression; secondary acute myeloid leukemia (AML).",
     "Cardiomyopathy, severe myelosuppression, complete alopecia, red-orange urine discoloration (harmless - 1-2 days post-dose), severe mucositis.",
     "Trastuzumab (massively increases heart failure risk - do not give concurrently), paclitaxel, CYP3A4 inhibitors.",
     "Category D. Cardioprotectant for anthracyclines: Dexrazoxane (Zinecard); Extravasation antidote: Totect."),
    ("Paclitaxel", "100 mg", "IV Infusion", "7802", "L01CD01", "Taxane Microtubule Stabilizer", ["Taxol"],
     "Ovarian, breast, non-small cell lung cancer, Kaposi's sarcoma.",
     "135 mg to 175 mg/m2 IV infused over 3 hours every 3 weeks (premedicate with dexamethasone, diphenhydramine, and H2 blocker).",
     "Severe baseline neutropenia (<1,500 cells/mm3); severe hypersensitivity to polyoxyethylated castor oil (Cremophor EL).",
     "Black Box: Severe hypersensitivity anaphylaxis (bronchospasm, hypotension due to Cremophor EL solvent - mandatory premedication); severe neutropenia; peripheral sensory neuropathy (stocking-glove distribution).",
     "Peripheral neuropathy, neutropenia, alopecia, myalgia, arthralgia, hypersensitivity reactions, bradycardia.",
     "Cisplatin (give paclitaxel BEFORE cisplatin to avoid reduced taxane clearance), strong CYP2C8/3A4 inhibitors.",
     "Category D."),
    ("Imatinib", "400 mg", "Oral Tablet", "282388", "L01EA01", "BCR-ABL Tyrosine Kinase Inhibitor (TKI)", ["Gleevec", "Glivec"],
     "Philadelphia chromosome-positive Chronic Myeloid Leukemia (Ph+ CML), Gastrointestinal Stromal Tumors (GIST c-KIT positive).",
     "400 mg to 600 mg orally once daily with a meal and large glass of water.",
     "Hypersensitivity to imatinib.", "Severe fluid retention and peripheral/periorbital edema; pleural and pericardial effusions; hepatotoxicity; gastrointestinal hemorrhage in GIST.",
     "Periorbital edema (70%), muscle cramps, musculoskeletal pain, diarrhea, nausea, rash, fatigue, cytopenias.",
     "Strong CYP3A4 inhibitors (ketoconazole, clarithromycin double imatinib levels), inducers (rifampin, carbamazepine halve levels), warfarin, acetaminophen.",
     "Category D. Teratogenic in animal models (cranial and skeletal defects)."),
    ("Trastuzumab", "440 mg", "IV Infusion", "224901", "L01FD01", "HER2/neu Humanized Monoclonal Antibody", ["Herceptin"],
     "HER2-overexpressing breast cancer (adjuvant and metastatic) and HER2-positive metastatic gastric adenocarcinoma.",
     "Loading dose 8 mg/kg IV infused over 90 min, then 6 mg/kg IV every 3 weeks (or weekly 2 mg/kg).",
     "Known severe hypersensitivity to trastuzumab.",
     "Black Box: Subclinical and clinical cardiac failure (congestive heart failure, cardiomyopathy, severe LVEF drop - baseline and regular echocardiograms mandatory); severe infusion reactions and pulmonary toxicity; embryo-fetal toxicity (oligohydramnios/pulmonary hypoplasia).",
     "Decreased LVEF, fever, chills, nausea, headache, diarrhea, infection, asthenia.",
     "Anthracyclines (concurrent use causes unacceptable 28% incidence of severe heart failure - do not combine).",
     "Category D. Fatal oligohydramnios and neonatal renal failure in pregnancy."),
    ("Rituximab", "500 mg", "IV Infusion", "121191", "L01FA01", "Chimeric Anti-CD20 Monoclonal Antibody", ["Rituxan", "MabThera"],
     "Non-Hodgkin's lymphoma (diffuse large B-cell, follicular), chronic lymphocytic leukemia (CLL), rheumatoid arthritis, granulomatosis with polyangiitis (GPA/Wegener's).",
     "375 mg/m2 IV infusion weekly for 4-8 doses (or RA: 1,000 mg IV on days 1 and 15 with methylprednisolone premedication).",
     "Known severe hypersensitivity to rituximab or murine proteins.",
     "Black Box: Fatal infusion-related reactions (bronchospasm, cardiogenic shock within 24h of first infusion - mandatory premedication with acetaminophen and antihistamine); severe mucocutaneous reactions (SJS/TEN); Hepatitis B virus reactivation (fatal fulminant hepatitis - screen HBsAg and anti-HBc prior to initiation); Progressive Multifocal Leukoencephalopathy (PML - JC virus reactivation).",
     "Infusion reactions (fever, chills, rigors 40%), lymphopenia, neutropenia, infection, asthenia, nausea.",
     "Antihypertensives (transient hypotension during infusion - consider withholding BP meds for 12 hours prior).",
     "Category C. Effective B-cell depleter."),
    ("Tamoxifen", "20 mg", "Oral Tablet", "10324", "L02BA01", "Selective Estrogen Receptor Modulator (SERM)", ["Nolvadex", "Tamodex"],
     "Adjuvant treatment of estrogen-receptor positive (ER+) breast cancer, metastatic breast cancer, reduction of breast cancer incidence in high-risk women.",
     "20 mg orally once daily for 5 to 10 years.",
     "Concurrent coumarin-type anticoagulant therapy (warfarin) or history of deep vein thrombosis / pulmonary embolism in prevention setting; pregnancy.",
     "Black Box: Uterine malignancies (endometrial adenocarcinoma and uterine sarcoma - prompt evaluation of abnormal vaginal bleeding mandatory); thromboembolic events (deep vein thrombosis, pulmonary embolism, stroke); retinopathy and corneal changes.",
     "Hot flashes (very common - 80%), vaginal discharge, irregular menses, fluid retention, nausea, mood swings, fatigue.",
     "Potent CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion prevent metabolic activation of tamoxifen to active endoxifen - severely reduces anti-cancer efficacy - avoid combination, use venlafaxine for hot flashes instead); warfarin (doubles bleeding risk).",
     "Category D. Teratogenic (craniofacial and genitourinary malformations)."),
    ("Anastrozole", "1 mg", "Oral Tablet", "84857", "L02BG03", "Non-Steroidal Aromatase Inhibitor (Third-Generation)", ["Arimidex", "Armotraz"],
     "Adjuvant treatment of postmenopausal women with hormone receptor-positive early breast cancer; first-line advanced breast cancer in postmenopause.",
     "1 mg orally once daily with or without food for 5 years.",
     "Premenopausal women (ineffective and contraindicated without ovarian suppression); pregnancy; lactation.",
     "Severe reduction in bone mineral density leading to osteoporosis and fragility fractures (baseline DEXA scan and calcium/vitamin D required); severe musculoskeletal arthralgias/myalgias ('aromatase inhibitor musculoskeletal syndrome'); hypercholesterolemia.",
     "Hot flashes (35%), arthralgia / joint stiffness (30%), osteoporosis, fatigue, nausea, hypertension, headache.",
     "Estrogen-containing therapies (antagonizes anastrozole efficacy), tamoxifen (decreases anastrozole plasma concentration).",
     "Category X. Absolute contraindication in pregnancy and in premenopausal women without GnRH analogs."),
    ("Letrozole", "2.5 mg", "Oral Tablet", "1364430", "L02BG04", "Potent Non-Steroidal Aromatase Inhibitor", ["Femara", "Letroz"],
     "Postmenopausal ER+ breast cancer (adjuvant/metastatic); off-label first-line ovulation induction in polycystic ovary syndrome (PCOS).",
     "Breast cancer: 2.5 mg orally once daily; Ovulation induction: 2.5 mg daily for 5 days on cycle days 3-7.",
     "Premenopausal endocrine status (for breast cancer); pregnancy.",
     "Bone loss/osteoporosis and fractures; severe arthralgias; hypercholesterolemia.",
     "Hot flashes, arthralgias, fatigue, dizziness, hypercholesterolemia.",
     "Tamoxifen (reduces letrozole levels), estrogen therapies.",
     "Category X."),
    ("Filgrastim", "300 mcg", "SC / IV Injection", "247894", "L03AA02", "Recombinant Granulocyte Colony-Stimulating Factor (G-CSF)", ["Neupogen", "Zarxio"],
     "Prevention and treatment of chemotherapy-induced severe neutropenia; bone marrow transplantation mobilization.",
     "5 mcg/kg/day SC or IV daily starting 24 hours after completion of chemotherapy until ANC normalizes.",
     "History of serious allergic reactions to proteins derived from E. coli or filgrastim.",
     "Splenic rupture (rare but fatal - report left upper quadrant abdominal/shoulder tip pain immediately); Acute Respiratory Distress Syndrome (ARDS); sickle cell crisis in sickle cell disease.",
     "Medullary bone pain (frequent - up to 30% due to bone marrow expansion), leukocytosis, elevated uric acid and LDH.",
     "Do not administer within 24 hours before or 24 hours after cytotoxic chemotherapy (stimulates proliferating myeloid cells).",
     "Category C."),
    ("Epoetin Alfa", "10,000 units", "SC / IV Injection", "225659", "B03XA01", "Recombinant Human Erythropoietin (ESA)", ["Epogen", "Procrit", "Eprex"],
     "Treatment of anemia due to chronic kidney disease (CKD), chemotherapy-induced anemia, zidovudine anemia in HIV.",
     "50 to 100 units/kg SC or IV 3 times weekly targeting hemoglobin <=11 g/dL (ensure adequate iron stores: ferritin >100 mcg/L, TSAT >20%).",
     "Uncontrolled hypertension; pure red cell aplasia (PRCA); severe allergic reactions.",
     "Black Box: Increased risk of death, stroke, venous thromboembolism, and myocardial infarction when dosed to target Hemoglobin >11 g/dL; shortened overall survival and tumor progression in cancer patients.",
     "Hypertension, headache, arthralgia, vascular access thrombosis in dialysis, deep vein thrombosis.",
     "Iron deficiency limits ESA response (iron supplementation mandatory).",
     "Category C. Strict hemoglobin monitoring capped at 10-11 g/dL."),
    ("Ferrous Sulfate", "325 mg", "Oral Tablet", "4332", "B03AA07", "Oral Iron Supplement (65 mg Elemental Iron)", ["Feosol", "Fer-In-Sol"],
     "Prevention and treatment of iron deficiency anemia.", "325 mg (65 mg elemental iron) orally 1 to 3 times daily on an empty stomach with Vitamin C (or with food if GI upset).",
     "Hemochromatosis, hemosiderosis, other anemias not caused by iron deficiency.",
     "Accidental overdose of iron-containing products is a leading cause of fatal poisoning in children under 6 (keep out of reach of children); dark black tarry stools (harmless).",
     "Constipation (very common), dark black stools, nausea, epigastric pain, diarrhea, teeth staining with liquid.",
     "Antacids, PPIs, calcium, tea/coffee, milk reduce iron absorption by 80%; iron chelates and blocks fluoroquinolones, tetracyclines, and levothyroxine (separate by 2-4 hours).",
     "Category A. Safe and universally indicated in gestational iron deficiency anemia. Overdose Antidote: Deferoxamine (Desferal)."),
    ("Allopurinol", "100 mg", "Oral Tablet", "519", "M04AA01", "Xanthine Oxidase Inhibitor (Uric Acid Lowering)", ["Zyloprim", "Aloprim", "Zyloric"],
     "Chronic gouty arthritis prevention (hyperuricemia), recurrent calcium oxalate renal stones, Tumor Lysis Syndrome prophylaxis in cancer chemotherapy.",
     "100 mg orally once daily after meals, titrate weekly by 100 mg up to 300-800 mg/day targeting serum uric acid <6.0 mg/dL (co-prescribe colchicine/NSAID flare prophylaxis for first 3-6 months).",
     "Hypersensitivity to allopurinol; HLA-B*5801 positive genotype (high prevalence in Han Chinese, Korean, and Thai ancestry).",
     "Allopurinol Hypersensitivity Syndrome (AHS: fatal toxic epidermal necrolysis, exfoliative dermatitis, hepatitis, renal failure, eosinophilia in HLA-B*5801 carriers); acute gout flare mobilization upon initiation; hepatotoxicity.",
     "Maculopapular rash (stop drug immediately), acute gout flares, diarrhea, elevated transaminases, nausea.",
     "Azathioprine / 6-Mercaptopurine (xanthine oxidase inhibition causes fatal 4-fold bone marrow aplasia - cut azathioprine dose by 75%), ampicillin/amoxicillin (high rash rate), warfarin (increases INR).",
     "Category C. HLA-B*5801 genetic screening recommended in high-risk ethnic populations.")
]

# Domain 14: Ophthalmology, Dermatology & Trace Elements (20)
CAT_14_SPECIALTY: List[Tuple] = [
    ("Latanoprost", "0.005 %", "Ophthalmic Drops", "111429", "S01EE01", "Prostaglandin F2-alpha Analog (Uveoscleral Outflow Enhancer)", ["Xalatan", "Latoprost"],
     "Reduction of elevated intraocular pressure in open-angle glaucoma and ocular hypertension.",
     "1 drop in the affected eye(s) once daily in the evening (more frequent dosing decreases IOP-lowering efficacy).",
     "Known hypersensitivity to latanoprost or benzalkonium chloride.",
     "Permanent increased brown iris pigmentation (heterochromia); hypertrichosis / eyelash darkening, thickening, and lengthening; macular edema in aphakic patients.",
     "Conjunctival hyperemia (eye redness - 30%), iris color change (permanent brown), eyelash growth, foreign body sensation, punctate keratitis.",
     "Do not administer while wearing contact lenses (benzalkonium chloride absorbs into soft contacts - wait 15 min before reinserting).",
     "Category C. Store unopened bottles in refrigerator (2-8°C)."),
    ("Timolol Ophthalmic", "0.5 %", "Ophthalmic Solution", "10600", "S01ED01", "Non-Selective Beta-Adrenergic Antagonist (Aqueous Flow Suppressor)", ["Timoptic", "Timolet", "Istalol"],
     "Elevated intraocular pressure in chronic open-angle glaucoma and ocular hypertension.",
     "1 drop of 0.25% or 0.5% in the affected eye(s) once or twice daily (nasolacrimal occlusion for 2 min reduces systemic absorption).",
     "Bronchial asthma or history of severe COPD; sinus bradycardia; second or third-degree AV block; overt cardiac failure.",
     "Systemic beta-blocker absorption causing fatal bronchospasm, severe bradycardia, heart failure exacerbation, and masked hypoglycemia symptoms in diabetics.",
     "Ocular stinging/burning, blurred vision, systemic bradycardia, bronchospasm, fatigue, depression.",
     "Systemic beta-blockers, oral calcium channel blockers (verapamil/diltiazem additive AV block), CYP2D6 inhibitors (quinidine).",
     "Category C. Punctal occlusion strongly recommended after eye drop instillation."),
    ("Brimonidine", "0.2 %", "Ophthalmic Drops", "25667", "S01EA05", "Selective Alpha-2 Adrenergic Agonist (Aqueous Suppressor)", ["Alphagan P", "Mirvaso"],
     "Elevated intraocular pressure in open-angle glaucoma (Alphagan); facial erythema of rosacea (Mirvaso topical gel).",
     "1 drop in the affected eye(s) three times daily approximately 8 hours apart.",
     "Neonates and infants <2 years (causes fatal CNS depression, somnolence, and apnea); concurrent MAOIs.",
     "Severe CNS depression, bradycardia, and hypotension in young children; allergic blepharoconjunctivitis (15%).",
     "Ocular hyperemia, burning, stinging, dry mouth, visual blurring, fatigue, somnolence.",
     "MAO inhibitors (contraindicated), CNS depressants, antihypertensives.",
     "Category B. Absolute contraindication in infants <2 years."),
    ("Dorzolamide", "2 %", "Ophthalmic Solution", "42353", "S01EC03", "Carbonic Anhydrase II Inhibitor (Ophthalmic)", ["Trusopt", "Dorzox"],
     "Elevated intraocular pressure in open-angle glaucoma and ocular hypertension (monotherapy or combined with timolol as Cosopt).",
     "1 drop in the affected eye(s) three times daily (or twice daily when combined with timolol).",
     "Hypersensitivity to dorzolamide or sulfonamides; severe renal impairment (CrCl <30 mL/min).",
     "Sulfonamide hypersensitivity (SJS/TEN); corneal edema / corneal decompensation in low endothelial cell counts; bitter taste.",
     "Bitter/sour taste in mouth (dysgeusia - 25%), ocular burning/stinging (30%), punctate keratitis, conjunctivitis.",
     "Oral carbonic anhydrase inhibitors (acetazolamide additive systemic toxicity).",
     "Category C."),
    ("Tretinoin", "0.05 %", "Topical Cream / Gel", "10759", "D10AD01", "All-Trans Retinoic Acid (Topical Retinoid)", ["Retin-A", "A-Ret"],
     "Acne vulgaris treatment and photoaging / fine facial wrinkles.",
     "Apply a pea-sized amount to clean, dry facial skin once daily at bedtime (avoid eyes, mouth, and mucous membranes).",
     "Hypersensitivity to retinoids.", "Severe photosensitivity and sunburn risk; severe local skin irritation, peeling, and redness; skin purging during first 2-4 weeks.",
     "Erythema, desquamation, skin burning, stinging, photosensitivity, dry skin.",
     "Concomitant topical drying agents (benzoyl peroxide, salicylic acid - apply at different times of day).",
     "Category C. Avoid in pregnancy as a precaution (oral tretinoin is Category X)."),
    ("Adapalene", "0.1 %", "Topical Gel / Cream", "1364432", "D10AD03", "Third-Generation Selective Retinoid (RAR-beta/gamma Agonist)", ["Differin", "Adaferin"],
     "Topical treatment of acne vulgaris in patients 12 years and older.",
     "Apply a thin layer over entire affected face once daily at bedtime after washing gently.",
     "Hypersensitivity to adapalene.",
     "Photosensitivity, local skin irritation/dryness (less irritating than first-generation tretinoin).",
     "Dry skin, scaling, erythema, burning/stinging sensations.",
     "Topical peeling agents, medicated soaps.",
     "Category C. Discontinue if pregnancy occurs."),
    ("Clobetasol Propionate", "0.05 %", "Topical Cream / Ointment", "2598", "D07AD01", "Super-High Potency Class I Topical Corticosteroid", ["Temovate", "Tenovate"],
     "Short-term relief of inflammatory and pruritic manifestations of moderate to severe corticosteroid-responsive dermatoses (plaque psoriasis, severe eczema, lichen planus).",
     "Apply thin layer to affected skin twice daily for max 2 consecutive weeks (max 50 g/week; NEVER apply to face, axillae, or groin).",
     "Cutaneous viral, fungal, or bacterial infections; rosacea; perioral dermatitis; children <12 years.",
     "Reversible hypothalamic-pituitary-adrenal (HPA) axis suppression; severe cutaneous skin atrophy / striae / telangiectasias; systemic Cushing's syndrome.",
     "Skin burning, stinging, skin atrophy, striae, telangiectasia, folliculitis.",
     "Do not use with occlusive dressings (increases systemic absorption 10-fold).",
     "Category C. Max 2 weeks continuous therapy."),
    ("Mupirocin", "2 %", "Topical Ointment", "7164", "D06AX09", "Isoleucyl-tRNA Synthetase Inhibitor Antibacterial", ["Bactroban", "T-Bact"],
     "Topical treatment of impetigo due to S. aureus and S. pyogenes; eradication of nasal MRSA colonization (nasal ointment).",
     "Apply small amount to affected skin 3 times daily for 5 to 10 days; Nasal: apply inside nostrils twice daily for 5 days.",
     "Known hypersensitivity to mupirocin or polyethylene glycol vehicle in open wounds.",
     "Polyethylene glycol vehicle can be systemically absorbed through extensive open wounds in renal impairment.",
     "Local burning, stinging, pain, pruritus, erythema.", "None significant.",
     "Category B. Treatment of choice for localized impetigo and MRSA nasal carriage eradication.")
]

def get_specialty_onco_records() -> List[Dict[str, Any]]:
    """Assemble all records from domains 12, 13, and 14."""
    records = []
    
    def process_group(group: List[Tuple]):
        for name, st, form, rxcui, atc, cls, aliases, ind, dos, con, war, adv, inter, prg in group:
            records.append({
                "name": name, "strength": st, "form": form, "rxcui": rxcui, "atc": atc,
                "class": cls, "aliases": aliases, "ind": ind, "dos": dos, "con": con,
                "war": war, "adv": adv, "int": inter, "prg": prg
            })

    process_group(CAT_12_UROLOGY)
    process_group(CAT_13_ONCO)
    process_group(CAT_14_SPECIALTY)
    return records

if __name__ == "__main__":
    r = get_specialty_onco_records()
    print(f"Domains 12-14 total records: {len(r)}")
