"""Clinical Knowledge Base: Expanded Catalog Module (Domains 9-14 Extension).

Contains 105 authentic medicine monographs with US NLM RxNorm RxCUIs, WHO ATC codes, and FDA labeling.
"""
from typing import Any, Dict, List, Tuple

EXPANDED_CLINICAL_DRUGS: List[Tuple] = [
    # ANTIFUNGALS, ANTIVIRALS & ANTIPARASITICS (30)
    ("Posaconazole", "300 mg", "Oral Tablet (DR) / IV", "612790", "J02AC04", "Second-Generation Extended-Spectrum Triazole", ["Noxafil"],
     "Prophylaxis of invasive Aspergillus and Candida in high-risk immunocompromised patients (GVHD, hematologic malignancy); treatment of oropharyngeal candidiasis.",
     "Prophylaxis: 300 mg (delayed-release tablets) orally twice on day 1, then 300 mg once daily with food; IV 300 mg BID day 1, then 300 mg once daily.",
     "Co-administration with CYP3A4 substrates that prolong QT (pimozide, quinidine), simvastatin, lovastatin, ergot alkaloids.",
     "QT interval prolongation and torsades de pointes; hepatotoxicity (monitor LFTs); tablets and oral suspension are NOT interchangeable due to bioequivalence differences.",
     "Diarrhea, nausea, vomiting, hypokalemia, elevated transaminases, headache, fever.",
     "Potent CYP3A4 inhibitor: massive elevation of tacrolimus, cyclosporine, midazolam, statins; rifampin and efavirenz decrease posaconazole levels.",
     "Category C. Embryofetal skeletal malformations in animal studies."),
    ("Isavuconazonium Sulfate", "372 mg", "Oral Capsule / IV", "1656895", "J02AC05", "Prodrug of Active Isavuconazole (Broad-Spectrum Azole)", ["Cresemba"],
     "Treatment of invasive aspergillosis and invasive mucormycosis in adults.",
     "Loading: 372 mg isavuconazonium (equiv 200 mg isavuconazole) orally or IV every 8 hours for 6 doses (48h), then 372 mg once daily.",
     "Familial short QT syndrome; concurrent strong CYP3A4 inducers (rifampin, carbamazepine, St. John's wort) or strong inhibitors (ketoconazole).",
     "Hepatic adverse reactions; infusion-related reactions (hypotension, dyspnea); shortens QT interval (unique among azoles).",
     "Nausea, vomiting, diarrhea, headache, elevated liver transaminases, hypokalemia, peripheral edema.",
     "CYP3A4 substrates (tacrolimus, sirolimus, cyclosporine require level monitoring), moderate CYP3A4 inhibitor.",
     "Category C. Avoid in pregnancy unless benefits outweigh potential risk."),
    ("Nystatin", "500,000 units", "Oral Suspension / Topical", "7549", "A07AA02", "Polyene Antifungal (Non-Absorbed Topical/Luminal)", ["Mycostatin", "Nilstat"],
     "Treatment of cutaneous, mucocutaneous, and oral cavity candidiasis (oral thrush, denture stomatitis, intestinal candidiasis).",
     "Oral thrush: 400,000 to 600,000 units (4-6 mL) swished in mouth and retained as long as possible before swallowing, 4 times daily for 7-14 days.",
     "Hypersensitivity to nystatin or formulation components.",
     "Not for systemic mycoses (not absorbed from intact skin or gastrointestinal tract).",
     "Oral: Diarrhea, nausea, vomiting, gastrointestinal distress; Topical: local irritation, burning, contact dermatitis.",
     "No significant systemic pharmacokinetic interactions due to lack of systemic absorption.",
     "Category C / Category A topical. First-line safe agent for neonatal and infant oral thrush."),
    ("Clotrimazole", "10 mg", "Oral Troche / Topical 1% / Vaginal", "2623", "A01AB18", "Imidazole Antifungal", ["Lotrimin", "Mycelex", "Candid"],
     "Treatment of oropharyngeal candidiasis (troche), tinea pedis, tinea cruris, tinea corporis, and vulvovaginal candidiasis.",
     "Oral thrush: 10 mg troche dissolved slowly in mouth 5 times daily for 14 days; Topical: apply twice daily for 2-4 weeks.",
     "Hypersensitivity to clotrimazole or imidazole derivatives.",
     "Troches must be dissolved slowly in mouth, not chewed or swallowed whole; monitor liver enzymes in patients with hepatic impairment on troches.",
     "Abnormal liver function tests with troches, nausea, vomiting, pruritus, erythema, stinging with topical application.",
     "Tacrolimus levels may increase modestly with high-dose troches via intestinal CYP3A4 inhibition.",
     "Category C / Category B topical. Safe topically during 2nd and 3rd trimesters."),
    ("Miconazole", "2 %", "Topical Cream / Vaginal Suppository", "6959", "D01AC02", "Imidazole Antifungal", ["Monistat", "Micatin", "Daktarin"],
     "Treatment of vulvovaginal candidiasis, tinea pedis, tinea cruris, and tinea corporis.",
     "Vaginal: 200 mg suppository intravaginally at bedtime for 3 days (or 100 mg for 7 days); Topical: apply twice daily for 2-4 weeks.",
     "Hypersensitivity to miconazole.",
     "Vaginal suppositories and creams contain mineral oil which may weaken latex condoms and diaphragms.",
     "Vaginal burning, pelvic cramps, vulvar itching, irritation, contact dermatitis.",
     "Warfarin (even topical/vaginal miconazole can cause significant CYP2C9 inhibition and life-threatening INR elevation).",
     "Category C. Safe topically/vaginally in 2nd and 3rd trimesters under clinical guidance."),
    ("Ketoconazole", "200 mg", "Oral Tablet / Topical 2%", "6135", "J02AB02", "Imidazole Antifungal & Steroidogenesis Inhibitor", ["Nizoral", "Extina"],
     "Topical: Seborrheic dermatitis, tinea versicolor, dandruff; Oral: Endogenous Cushing's syndrome (blocks cortisol synthesis); severe systemic fungal infections only when other therapies fail.",
     "Topical shampoo: 2% twice weekly; Oral (Cushing's / refractory): 200 mg to 400 mg orally once daily with food (requires acidic stomach).",
     "Co-administration with CYP3A4 substrates that cause QT prolongation (terfenadine, astemizole, pimozide); acute or chronic liver disease.",
     "Black Box: Fatal hepatotoxicity (acute liver failure, cirrhosis, transplant); severe QT prolongation; potent inhibition of adrenal corticosteroid and testosterone synthesis (gynecomastia, adrenal insufficiency).",
     "Topical: Application site burning, dry skin; Oral: Severe hepatotoxicity, nausea, gynecomastia, erectile dysfunction, decreased libido.",
     "Potent CYP3A4 and P-gp inhibitor (contraindicated with dozens of drugs); PPIs/H2 blockers completely block oral absorption.",
     "Category C. Oral use strictly restricted by FDA due to hepatotoxicity."),
    ("Ganciclovir", "500 mg", "IV Infusion / Ophthalmic", "4684", "J05AB06", "Nucleoside Analog Antiviral (CMV DNA Polymerase Inhibitor)", ["Cytovene", "Zirgan"],
     "Treatment and prevention of Cytomegalovirus (CMV) retinitis and CMV disease in immunocompromised patients and transplant recipients.",
     "Induction: 5 mg/kg IV every 12 hours for 14 to 21 days; Maintenance: 5 mg/kg IV once daily 7 days/week (hydrate and adjust for renal decline).",
     "Hypersensitivity to ganciclovir or valganciclovir; severe absolute neutrophil count <500/microL or platelet count <25,000/microL.",
     "Black Box: Severe hematologic toxicity (granulocytopenia, severe anemia, thrombocytopenia); temporary or permanent female and male infertility; potential carcinogen and teratogen.",
     "Leukopenia (40%), thrombocytopenia (20%), anemia, fever, diarrhea, nausea, elevated creatinine, neuropathy.",
     "Zidovudine (severe additive bone marrow toxicity - avoid combination), imipenem (increased risk of generalized seizures), probenecid.",
     "Category C. Highly embryotoxic and teratogenic."),
    ("Valganciclovir", "450 mg", "Oral Tablet", "258326", "J05AB14", "L-Valyl Ester Prodrug of Ganciclovir (10x Bioavailability)", ["Valcyte"],
     "Treatment of CMV retinitis in AIDS; prevention of CMV disease in high-risk solid organ transplant recipients (donor CMV+/recipient CMV-).",
     "Induction: 900 mg orally twice daily with food for 21 days; Maintenance/Prophylaxis: 900 mg orally once daily with food (reduce dose in renal impairment).",
     "Severe neutropenia (ANC <500/microL), severe thrombocytopenia (platelets <25,000/microL), hypersensitivity.",
     "Black Box: Severe myelosuppression (neutropenia, anemia, thrombocytopenia); impaired fertility; embryofetal toxicity.",
     "Diarrhea (30%), neutropenia (25%), pyrexia, anemia, nausea, vomiting, insomnia, tremor.",
     "Zidovudine (severe additive myelosuppression), probenecid (increases ganciclovir levels), mycophenolate mofetil.",
     "Category C. Effective oral alternative to IV ganciclovir."),
    ("Foscarnet", "24 mg/mL", "IV Infusion", "4515", "J05AD01", "Pyrophosphate Analog Antiviral (Inorganic)", ["Foscavir"],
     "Acyclovir-resistant HSV infections in immunocompromised patients; CMV retinitis in patients with AIDS refractory to ganciclovir.",
     "CMV Induction: 60 mg/kg IV every 8 hours or 90 mg/kg every 12 hours for 14-21 days (with 1-2 L saline pre-hydration).",
     "Severe hypersensitivity to foscarnet.",
     "Black Box: Severe cumulative renal impairment (acute tubular necrosis, interstitial nephritis in up to 30%); severe electrolyte disturbances (hypocalcemia, hypomagnesemia, hypokalemia, hypophosphatemia leading to tetany and seizures); genital ulcerations.",
     "Elevated serum creatinine / acute renal failure, hypocalcemia (paresthesias, seizures), hypokalemia, fever, nausea, vomiting, anemia, penile/vulvar ulcers.",
     "Nephrotoxic drugs (aminoglycosides, amphotericin B, IV pentamidine - fatal hypocalcemia when combined with pentamidine), ciprofloxacin.",
     "Category C. Aggressive normal saline IV hydration mandatory with every infusion."),
    ("Remdesivir", "100 mg", "IV Infusion", "2284718", "J05AB16", "Nucleotide Analog RNA-Dependent RNA Polymerase Inhibitor", ["Veklury"],
     "Treatment of COVID-19 in adults and pediatric patients (>=28 days and >=3 kg) with positive direct SARS-CoV-2 viral testing.",
     "Loading dose: 200 mg IV on Day 1, followed by 100 mg IV once daily for 3 to 5 days (infused over 30 to 120 minutes).",
     "History of severe hypersensitivity reactions to remdesivir or excipient sulfobutylether-beta-cyclodextrin (SBECD).",
     "Hypersensitivity and infusion-related reactions (angioedema, hypotension, bradycardia); hepatic transaminase elevations (monitor ALT/AST).",
     "Nausea, elevated ALT, elevated AST, hypersensitivity reactions, headache, prolonged prothrombin time.",
     "Chloroquine or hydroxychloroquine (antagonizes antiviral activity - co-administration not recommended).",
     "Category B. Favorable safety profile in pregnant patients hospitalized with COVID-19."),
    ("Entecavir", "0.5 mg", "Oral Tablet / Solution", "544075", "J05AF10", "Guanosine Nucleoside Reverse Transcriptase Inhibitor", ["Baraclude", "Entavir"],
     "Treatment of chronic Hepatitis B virus (HBV) infection in adults and pediatric patients with evidence of active viral replication.",
     "Nucleoside-naive: 0.5 mg orally once daily ON AN EMPTY STOMACH (at least 2 hours before or 2 hours after a meal); Lamivudine-refractory: 1.0 mg once daily.",
     "Hypersensitivity to entecavir.",
     "Black Box: Severe acute exacerbations of Hepatitis B upon discontinuation (monitor hepatic function for several months); lactic acidosis and severe hepatomegaly with steatosis; emergence of resistant HIV in unrecognized untreated HIV co-infection.",
     "Headache, fatigue, dizziness, nausea, elevated transaminases, diarrhea.",
     "Drugs that reduce renal function or compete for active tubular secretion (increases entecavir concentration).",
     "Category C. Potent high genetic barrier first-line anti-HBV agent."),
    ("Tenofovir Disoproxil Fumarate", "300 mg", "Oral Tablet", "284385", "J05AF07", "Nucleotide Reverse Transcriptase Inhibitor (NRTI)", ["Viread", "Tenof"],
     "Treatment of HIV-1 infection (in combination with other antiretrovirals); chronic Hepatitis B infection; HIV-1 Pre-Exposure Prophylaxis (PrEP with emtricitabine).",
     "300 mg orally once daily with or without food (reduce dosing interval in renal impairment CrCl <50 mL/min).",
     "Hypersensitivity to tenofovir.",
     "Black Box: Severe acute exacerbations of Hepatitis B upon discontinuation; lactic acidosis/severe hepatomegaly with steatosis; renal impairment including acute renal failure and Fanconi syndrome (proximal renal tubulopathy); decreases in bone mineral density (osteopenia/osteoporosis).",
     "Nausea, diarrhea, asthenia, headache, renal impairment (proteinuria, elevated creatinine), hypophosphatemia, decreased bone density.",
     "Ledipasvir/sofosbuvir (increases tenofovir exposure), NSAIDs and nephrotoxic drugs, didanosine.",
     "Category B. Extensively verified safety record throughout pregnancy and in HIV/HBV perinatal transmission prevention."),
    ("Tenofovir Alafenamide", "25 mg", "Oral Tablet", "1721603", "J05AF13", "Targeted Phosphonamidate Prodrug of Tenofovir", ["Vemlidy"],
     "Treatment of chronic Hepatitis B virus infection in adults with compensated liver disease; component of modern HIV regimens (Biktarvy, Descovy, Genvoya).",
     "25 mg orally once daily with food (provides 90% lower systemic tenofovir plasma levels with superior renal and bone safety compared to TDF).",
     "End-stage renal disease (CrCl <15 mL/min) not on chronic hemodialysis.",
     "Black Box: Severe acute exacerbations of Hepatitis B after discontinuation; lactic acidosis/severe hepatomegaly; weight gain.",
     "Headache, abdominal pain, fatigue, cough, nausea, back pain, arthralgia, modest lipid elevations.",
     "P-gp and CYP3A inducers (carbamazepine, rifampin, St. John's wort reduce TAF levels - avoid combination).",
     "Category B. High intracellular target delivery with reduced renal/bone toxicity."),
    ("Emtricitabine", "200 mg", "Oral Capsule", "356447", "J05AF09", "Fluorinated Cytidine Nucleoside Analog NRTI", ["Emtriva"],
     "Treatment of HIV-1 infection in combination with other antiretrovirals; Pre-Exposure Prophylaxis (PrEP with TDF as Truvada or with TAF as Descovy).",
     "200 mg orally once daily with or without food (adjust interval in renal decline CrCl <50 mL/min).",
     "Hypersensitivity to emtricitabine.",
     "Black Box: Post-treatment acute exacerbations of Hepatitis B; lactic acidosis/severe hepatomegaly; skin hyperpigmentation (palms/soles).",
     "Headache, diarrhea, nausea, fatigue, dizziness, rash, skin hyperpigmentation (mostly on palms and soles).",
     "Lamivudine (competes for same intracellular phosphorylation - do not combine).",
     "Category B. Safe and widely used in pregnancy."),
    ("Lamivudine", "150 mg", "Oral Tablet", "28439", "J05AF05", "Cytidine Nucleoside Analog NRTI (3TC)", ["Epivir", "Lamivir"],
     "Treatment of HIV-1 infection in combination with other antiretroviral agents; chronic Hepatitis B infection (Epivir-HBV 100 mg daily).",
     "HIV: 300 mg once daily or 150 mg twice daily with or without food; HBV: 100 mg once daily.",
     "Hypersensitivity to lamivudine.",
     "Black Box: Lactic acidosis and severe hepatomegaly with steatosis; severe acute exacerbations of Hepatitis B upon withdrawal; emergence of lamivudine-resistant HBV variants.",
     "Headache, nausea, malaise, fatigue, nasal signs and symptoms, diarrhea, cough.",
     "Trimethoprim/sulfamethoxazole (increases lamivudine levels by 40%), emtricitabine (do not co-administer).",
     "Category C. Longest safety record in prevention of mother-to-child HIV transmission."),
    ("Abacavir", "300 mg", "Oral Tablet", "190007", "J05AF06", "Guanosine Nucleoside Analog NRTI", ["Ziagen"],
     "Treatment of HIV-1 infection in combination with other antiretroviral agents (Triumeq, Epzicom).",
     "300 mg orally twice daily or 600 mg once daily with or without food.",
     "Presence of HLA-B*5701 genetic allele (mandatory pre-treatment genetic screening); moderate-to-severe hepatic impairment; previous abacavir hypersensitivity.",
     "Black Box: Fatal hypersensitivity reactions (multi-organ failure, fever, rash, GI distress, respiratory symptoms - NEVER rechallenge after reaction); HLA-B*5701 screening mandatory before initiation; myocardial infarction signal in some cohorts.",
     "Hypersensitivity reaction (fever, rash, nausea, malaise), nausea, headache, fatigue, vomiting, diarrhea, insomnia.",
     "Alcohol (competes for alcohol dehydrogenase - increases abacavir levels by 41%), methadone.",
     "Category C. HLA-B*5701 negative testing required before prescription."),
    ("Dolutegravir", "50 mg", "Oral Tablet", "1433868", "J05AJ03", "Second-Generation HIV Integrase Strand Transfer Inhibitor (INSTI)", ["Tivicay"],
     "Treatment of HIV-1 infection in combination with other antiretrovirals (first-line global preferred WHO regimen: DTG + 3TC + TDF / TLD).",
     "50 mg orally once daily with or without food (50 mg twice daily in INSTI-resistant HIV or with efavirenz/rifampin).",
     "Concurrent administration with dofetilide; hypersensitivity to dolutegravir.",
     "Hypersensitivity reactions (severe rash, constitutional symptoms, liver injury); immune reconstitution inflammatory syndrome (IRIS); early neural tube defect signal resolved by Tsepamo study (now confirmed safe).",
     "Insomnia (3%), headache (2%), fatigue, weight gain, diarrhea, elevated serum creatinine (benign OCT2 inhibition without affecting actual GFR).",
     "Polyvalent cations (calcium, iron, magnesium, aluminum antacids bind and prevent absorption - take DTG 2 hours before or 6 hours after); rifampin, carbamazepine (double DTG to 50 mg BID); dofetilide (contraindicated).",
     "Category B. WHO preferred first-line antiretroviral for all adults, adolescents, and pregnant women."),
    ("Bictegravir", "50 mg", "Oral Tablet (Combined)", "1999554", "J05AJ04", "Second-Generation High-Barrier INSTI (Component of Biktarvy)", ["Biktarvy"],
     "Complete single-tablet regimen for the treatment of HIV-1 infection in adults and pediatric patients >=14 kg.",
     "1 tablet (Bictegravir 50 mg / Emtricitabine 200 mg / Tenofovir Alafenamide 25 mg) orally once daily with or without food.",
     "Co-administration with dofetilide, rifampin, carbamazepine, St. John's wort.",
     "Post-treatment acute exacerbations of Hepatitis B in HBV-coinfected patients; immune reconstitution syndrome; benign serum creatinine elevation via OCT2/MATE1 inhibition.",
     "Diarrhea, headache, nausea, abnormal dreams, fatigue, weight gain.",
     "Polyvalent metal cations (antacids/iron reduce absorption - take under fasting conditions or 2 hours prior), dofetilide contraindicated.",
     "Category B. Leading first-line single-tablet HIV regimen."),
    ("Efavirenz", "600 mg", "Oral Tablet", "194682", "J05AG03", "Non-Nucleoside Reverse Transcriptase Inhibitor (NNRTI)", ["Sustiva", "Efavir"],
     "Treatment of HIV-1 infection in combination with other antiretrovirals.",
     "600 mg orally once daily ON AN EMPTY STOMACH AT BEDTIME (high-fat meals increase absorption and toxicity).",
     "Concurrent administration of elbasvir/grazoprevir; hypersensitivity.",
     "Severe neuropsychiatric symptoms (vivid dreams, nightmares, dizziness, depression, suicidal ideation, psychosis in 50% during weeks 1-4); QT prolongation; rash / SJS; false-positive cannabinoid urine screen.",
     "Vivid dreams, dizziness, insomnia, impaired concentration, rash, elevated cholesterol, somnolence.",
     "Mixed inducer/inhibitor of CYP3A4: decreases levels of statins, methadone, hormonal contraceptives, voriconazole (contraindicated).",
     "Category D. Formerly avoided in 1st trimester; modern data shows safe when alternative unavailable."),
    ("Raltegravir", "400 mg", "Oral Tablet", "698246", "J05AJ01", "First-Generation HIV-1 Integrase Inhibitor", ["Isentress", "Isentress HD"],
     "Treatment of HIV-1 infection in combination with other antiretroviral agents; preferred for post-exposure prophylaxis (PEP).",
     "400 mg orally twice daily with or without food (or 1,200 mg [two 600 mg tablets] once daily HD formulation).",
     "Hypersensitivity.", "Severe cutaneous and hypersensitivity reactions (SJS/TEN/DRESS); rhabdomyolysis and myopathy; immune reconstitution syndrome.",
     "Nausea, headache, diarrhea, insomnia, fatigue, elevated creatine kinase (CK).",
     "Aluminum/magnesium antacids (contraindicated - massive chelation); calcium antacids; rifampin (induces UGT1A1 - increase dose to 800 mg BID).",
     "Category B. Preferred INSTI for HIV post-exposure prophylaxis (PEP) and during pregnancy."),
    ("Darunavir", "800 mg", "Oral Tablet", "617993", "J05AE10", "Second-Generation Non-Peptidic Protease Inhibitor (High Genetic Barrier)", ["Prezista"],
     "Treatment of HIV-1 infection in adults and pediatric patients >=3 years (must be co-administered with ritonavir or cobicistat as pharmacokinetic booster).",
     "Treatment-naive: 800 mg darunavir orally once daily with 100 mg ritonavir (or 150 mg cobicistat) WITH FOOD; Treatment-experienced: 600 mg BID with 100 mg ritonavir BID.",
     "Co-administration with drugs highly dependent on CYP3A for clearance (alfuzosin, colchicine, dronedarone, ivabradine, lovastatin, simvastatin, rifampin, St. John's wort).",
     "Severe cutaneous reactions (SJS/TEN/erythema multiforme); hepatotoxicity (monitor LFTs); new-onset diabetes and hyperglycemia; fat redistribution; sulfa cross-allergy.",
     "Diarrhea, nausea, rash (10%), headache, abdominal pain, hyperlipidemia, elevated transaminases.",
     "Massive CYP3A4 inhibition via booster (contraindicated with statins, DOACs, sildenafil for PAH); antacids; PPIs.",
     "Category C. Preferred boosted protease inhibitor during pregnancy."),
    ("Atazanavir", "300 mg", "Oral Capsule", "343047", "J05AE08", "Azapeptide HIV-1 Protease Inhibitor", ["Reyataz"],
     "Treatment of HIV-1 infection in combination with other antiretrovirals (boosted with ritonavir 100 mg or cobicistat 150 mg).",
     "300 mg atazanavir orally once daily with ritonavir 100 mg WITH A FULL MEAL (requires gastric acid for absorption).",
     "Co-administration with alfuzosin, rifampin, irinotecan, lovastatin, simvastatin, indinavir, pimozide.",
     "Asymptomatic indirect (unconjugated) hyperbilirubinemia and clinical jaundice / scleral icterus (reversible UGT1A1 inhibition in 35-50%); PR interval prolongation and AV block; nephrolithiasis / cholelithiasis (kidney stones).",
     "Indirect hyperbilirubinemia (jaundice/yellow eyes), nausea, diarrhea, headache, abdominal pain, rash, nephrolithiasis.",
     "PPIs and H2 blockers drastically decrease atazanavir absorption (separate PPI by 12h, max omeprazole 20 mg equivalent); statins.",
     "Category B. Jaundice is cosmetic/benign due to Gilbert-like UGT1A1 blockade."),
    ("Ivermectin", "3 mg", "Oral Tablet / Topical 1%", "6054", "P02CF01", "Avermectin Antiparasitic (Glutamate-Gated Chloride Channel Agonist)", ["Stromectol", "Soolantra", "Ivecop"],
     "Strongyloidiasis of intestinal tract, onchocerciasis (river blindness), scabies (crusted and refractory), rosacea (topical cream).",
     "Strongyloidiasis: 200 mcg/kg orally as a single dose with water on an empty stomach; Scabies: 200 mcg/kg repeated once after 7-14 days.",
     "Hypersensitivity to ivermectin.",
     "Mazzotti reaction in onchocerciasis (fever, pruritus, arthralgia, tachycardia, hypotension due to dying microfilariae); severe encephalopathy in patients co-infected with high Loa loa microfilariae counts.",
     "Pruritus, fever, rash, dizziness, somnolence, diarrhea, nausea, Mazzotti-type systemic reactions.",
     "Warfarin (modest INR increase), P-glycoprotein inhibitors.",
     "Category C. Treatment of choice for community crusted scabies outbreaks and strongyloides."),
    ("Albendazole", "400 mg", "Oral Tablet", "609", "P02CA03", "Benzimidazole Broad-Spectrum Anthelmintic", ["Albenza", "Zentel", "Bandikind"],
     "Neurocysticercosis (Taenia solium tapeworm larvae in CNS), hydatid disease (Echinococcus granulosus), ascariasis, hookworm, pinworm.",
     "Neurocysticercosis: 400 mg orally twice daily WITH FATTY MEALS for 8 to 30 days (mandatory co-administration with corticosteroids and anticonvulsants); Pinworm: 400 mg single dose repeated in 2 weeks.",
     "Hypersensitivity to benzimidazoles; pregnancy (teratogenic).",
     "Black Box/Warning: Severe bone marrow suppression (fatal aplastic anemia, agranulocytosis, pancytopenia with prolonged use - monitor CBC every 2 weeks); severe hepatotoxicity (monitor LFTs); intracranial hypertension and retinal damage in neurocysticercosis (ophthalmic exam before starting).",
     "Abnormal liver function tests, abdominal pain, nausea, vomiting, headache, dizziness, reversible alopecia, leukopenia.",
     "Dexamethasone, cimetidine, and praziquantel increase albendazole active sulfoxide metabolite blood levels; high-fat meals increase absorption 5-fold.",
     "Category C. Teratogenic and embryotoxic (negative pregnancy test required before starting multi-week courses)."),
    ("Mebendazole", "100 mg", "Oral Chewable Tablet", "6672", "P02CA01", "Synthetic Benzimidazole Anthelmintic (Tubulin Inhibitor)", ["Vermox", "Emverm"],
     "Treatment of Enterobius vermicularis (pinworm), Trichuris trichiura (whipworm), Ascaris lumbricoides (roundworm), and hookworm infections.",
     "Pinworm: 100 mg orally single chewable dose (repeat in 2-3 weeks to prevent reinfection); Roundworm/Hookworm: 100 mg twice daily for 3 consecutive days.",
     "Hypersensitivity to mebendazole.",
     "Stevens-Johnson syndrome and toxic epidermal necrolysis when combined with metronidazole; not absorbed systemically (luminal action).",
     "Transient abdominal pain, diarrhea, flatulence (due to worm expulsion), rash, elevated liver enzymes.",
     "Metronidazole (severe SJS/TEN interaction - avoid concurrent use), carbamazepine and phenytoin (inducers reduce mebendazole levels).",
     "Category C. Safe and effective chewable therapy for school-aged pinworm infections."),
    ("Praziquantel", "600 mg", "Oral Tablet", "8617", "P02BA01", "Pyrazinoisoquinoline Anthelmintic (Calcium Permeability Enhancer)", ["Biltricide", "Distocide"],
     "Treatment of all species of Schistosoma (schistosomiasis/bilharzia), Clonorchis sinensis, Opisthorchis viverrini (liver flukes).",
     "Schistosomiasis: 20 mg/kg orally 3 times in 1 day (total 60 mg/kg) at 4-6 hour intervals swallowed with water during meals.",
     "Ocular cysticercosis (parasite destruction in the eye causes permanent blindness); concurrent strong CYP inducers (rifampin).",
     "Central nervous system exacerbations (seizures, intracranial hypertension in patients with undiagnosed neurocysticercosis); cardiac arrhythmias.",
     "Malaise, headache, dizziness, abdominal discomfort, nausea, pyrexia, urticaria, drowsiness.",
     "Rifampin (contraindicated - reduces praziquantel plasma levels by 80-99%), CYP3A4 inhibitors (cimetidine, ketoconazole increase levels).",
     "Category B. Drug of choice for schistosomiasis and fluke infections worldwide."),
    ("Permethrin", "5 %", "Topical Cream / 1% Lotion", "8094", "P03AC04", "Synthetic Pyrethroid Neurotoxin (Sodium Channel Disruptor)", ["Elimite", "Nix", "Permite"],
     "Treatment of infestation with Sarcoptes scabiei (scabies - 5% cream) and Pediculus humanus capitis (head lice - 1% lotion).",
     "Scabies: Massage 5% cream thoroughly into entire skin from neck to soles of feet; leave on for 8 to 14 hours then wash off completely (single application curative in >90%).",
     "Hypersensitivity to synthetic pyrethroids or chrysanthemums.",
     "Transient exacerbation of pruritus and erythema following application due to dead mite proteins (not a sign of treatment failure).",
     "Pruritus, mild burning, stinging, erythema, numbness, tingling.",
     "None significant topically.",
     "Category B. First-line safe treatment of scabies in pregnant women, infants >=2 months, and nursing mothers."),
    ("Dapsone", "100 mg", "Oral Tablet / Topical Gel", "3138", "J04BA02", "Sulfone Antibacterial & Anti-Inflammatory (Folate Synthesis Inhibitor)", ["Aczone", "Dapsone USP"],
     "Treatment of dermatitis herpetiformis (celiac rash), Hansen's disease (leprosy combination), Pneumocystis jirovecii (PCP) prophylaxis.",
     "Dermatitis herpetiformis: 50 mg orally once daily, titrate to 100-300 mg/day; Leprosy: 100 mg once daily with rifampin and clofazimine.",
     "Severe hypersensitivity to dapsone or sulfones.",
     "Black Box/Warning: Dose-dependent hemolytic anemia (especially severe in glucose-6-phosphate dehydrogenase G6PD deficiency - mandatory G6PD testing); methemoglobinemia (cyanosis, dyspnea); Dapsone Hypersensitivity Syndrome (fever, rash, hepatitis, lymphadenopathy); agranulocytosis.",
     "Hemolysis / hemolytic anemia, methemoglobinemia (blue-slate skin color), nausea, vomiting, headache, peripheral motor neuropathy.",
     "Probenecid (reduces dapsone clearance), trimethoprim (increases levels of both drugs), rifampin (induces dapsone clearance).",
     "Category C. Mandatory G6PD enzyme testing prior to initiation."),
    ("Artemether and Lumefantrine", "20-120 mg", "Oral Tablet", "831533", "P01BF01", "Artemisinin-Based Combination Therapy (ACT)", ["Coartem"],
     "Treatment of acute uncomplicated malaria caused by Plasmodium falciparum in adults and pediatric patients.",
     "Standard 6-dose regimen: 4 tablets orally at 0h, 8h, 24h, 36h, 48h, and 60h WITH FOOD OR A FULL-FAT DRINK (essential for lumefantrine absorption).",
     "Known hypersensitivity; concurrent administration of strong CYP3A4 inducers (rifampin, carbamazepine, phenytoin); baseline QT prolongation.",
     "QT interval prolongation and torsades de pointes; must administer with fatty meals/milk to ensure absorption; not for severe complicated malaria (use IV artesunate).",
     "Headache, dizziness, anorexia, arthralgia, myalgia, nausea, vomiting, fatigue, QT prolongation.",
     "CYP3A4 inducers (rifampin halves lumefantrine levels - treatment failure), QT-prolonging drugs, antiretrovirals.",
     "Category C / WHO First-Line. Recommended by WHO for 2nd and 3rd trimesters of pregnancy for malaria."),
    ("Atovaquone and Proguanil", "250-100 mg", "Oral Tablet", "218274", "P01BB52", "Mitochondrial Electron Transport + Dihydrofolate Reductase Inhibitor", ["Malarone"],
     "Prevention and treatment of acute uncomplicated Plasmodium falciparum malaria (especially in chloroquine-resistant areas).",
     "Prophylaxis: 1 tablet (250/100 mg) orally once daily with food or milk starting 1-2 days before travel, daily during, and for 7 days after leaving endemic area.",
     "Severe renal impairment (CrCl <30 mL/min) for malaria prophylaxis; hypersensitivity.",
     "Must take with food or milk (increases atovaquone bioavailability 2- to 3-fold); vomiting within 1 hour requires repeat full dose.",
     "Abdominal pain, nausea, vomiting, headache, diarrhea, elevated transaminases, mouth ulcers.",
     "Rifampin and metoclopramide reduce atovaquone plasma concentrations by 50%; warfarin (increases INR and bleeding risk).",
     "Category C. Ideal short-duration malaria prophylaxis regimen."),

    # ONCOLOGY, HORMONAL & TARGETED THERAPEUTICS (25)
    ("Bicalutamide", "50 mg", "Oral Tablet", "17154", "L02BB03", "Non-Steroidal Antiandrogen (Androgen Receptor Antagonist)", ["Casodex", "Calutide"],
     "Treatment of metastatic prostate cancer (Stage D2) in combination with a luteinizing hormone-releasing hormone (LHRH) analog.",
     "50 mg orally once daily in morning or evening taken concurrently with an LHRH analog (e.g. leuprolide or goserelin).",
     "Hypersensitivity; women and children; pregnancy.",
     "Severe hepatotoxicity / acute liver failure (monitor serum transaminases every 3 months for first year); gynecomastia and breast pain (in up to 38%); glucose intolerance in diabetics.",
     "Hot flashes (50%), gynecomastia (38%), breast tenderness, back pain, pelvic pain, asthenia, constipation, infection.",
     "Warfarin (displaces warfarin from protein-binding sites - massively increases prothrombin time and INR).",
     "Category X. Absolute contraindication in females."),
    ("Enzalutamide", "40 mg", "Oral Capsule / Tablet", "1310656", "L02BB04", "Second-Generation Androgen Receptor Inhibitor", ["Xtandi"],
     "Castration-resistant prostate cancer (CRPC) and metastatic castration-sensitive prostate cancer (mCSPC).",
     "160 mg (four 40 mg capsules) orally once daily with or without food swallowed whole.",
     "Hypersensitivity; pregnancy and women of childbearing potential.",
     "Dose-dependent seizures (0.5-1% - avoid in patients with pre-existing seizure history); Posterior Reversible Encephalopathy Syndrome (PRES); severe fatigue and falls/fractures; ischemic heart disease.",
     "Asthenia / severe fatigue (34%), back pain, hot flashes, constipation, arthralgia, decreased appetite, hypertension.",
     "Strong CYP2C8 inhibitors (gemfibrozil doubles enzalutamide AUC - reduce dose to 80 mg); strong CYP3A4 inducers (rifampin halves levels); potent CYP3A4 inducer itself.",
     "Category X. Potent teratogen."),
    ("Abiraterone Acetate", "250 mg", "Oral Tablet", "1100699", "L02BX03", "CYP17 (17-alpha Hydroxylase / C17,20-Lyase) Inhibitor", ["Zytiga", "Abirapro"],
     "Metastatic castration-resistant and metastatic high-risk castration-sensitive prostate cancer (combined with prednisone).",
     "1,000 mg (four 250 mg tablets) orally ONCE DAILY ON AN EMPTY STOMACH (at least 1 hour before or 2 hours after meals) in combination with Prednisone 5 mg BID.",
     "Severe hepatic impairment (Child-Pugh Class C); pregnancy.",
     "Black Box/Warning: Severe mineralocorticoid excess (hypertension, hypokalemia, fluid retention - co-administered prednisone is mandatory to suppress ACTH); severe hepatotoxicity (monitor ALT/AST/bilirubin every 2 weeks for 3 months); adrenocortical insufficiency upon prednisone taper.",
     "Hypokalemia (17%), hypertension (22%), peripheral edema, elevated ALT/AST, hot flashes, diarrhea, fatigue.",
     "Strong CYP3A4 inducers (rifampin halves abiraterone exposure), CYP2D6 substrates (dextromethorphan).",
     "Category X. Empty stomach dosing mandatory (food increases exposure up to 10-fold with unpredictable toxicity)."),
    ("Leuprolide Acetate", "7.5 mg", "IM Depot Injection", "6373", "L02AE02", "GnRH / LHRH Agonist (Gonadotropin Suppressor)", ["Lupron", "Lupron Depot", "Eligard"],
     "Palliative treatment of advanced prostate cancer, endometriosis, uterine leiomyomata (fibroids) pre-op, central precocious puberty.",
     "Prostate cancer: 7.5 mg IM once monthly (or 22.5 mg q3 months / 30 mg q4 months / 45 mg q6 months depot).",
     "Hypersensitivity to GnRH analogs; pregnancy and undiagnosed abnormal vaginal bleeding.",
     "Initial transient testosterone surge ('tumor flare' phenomenon during weeks 1-2 causing acute bone pain, spinal cord compression, or bladder outlet obstruction - co-prescribe antiandrogen like bicalutamide); loss of bone mineral density / osteoporosis; cardiovascular risk / QT prolongation; hyperglycemia.",
     "Hot flashes (57%), diaphoresis, erectile dysfunction, testicular atrophy, fatigue, bone pain, injection site reactions.",
     "QT-prolonging antiarrhythmics (quinidine, amiodarone increase torsades risk).",
     "Category X. Absolute contraindication in pregnancy."),
    ("Goserelin", "3.6 mg", "SC Implant", "4930", "L02AE03", "Synthetic Decapeptide LHRH Agonist", ["Zoladex"],
     "Palliative treatment of advanced prostate cancer; ER+ advanced breast cancer in pre- and perimenopausal women; endometriosis.",
     "Prostate/Endometriosis: 3.6 mg SC implant injected into upper abdominal wall once every 28 days (or 10.8 mg q12 weeks).",
     "Hypersensitivity to LHRH agonists; pregnancy.",
     "Tumor flare phenomenon in prostate cancer; bone mineral density loss; hypercalcemia in breast cancer patients with bone metastases.",
     "Hot flashes, decreased libido, erectile dysfunction, vaginal dryness, breast tenderness, lethargy, headache.",
     "QT-prolonging drugs.",
     "Category X. Teratogenic."),
    ("Erlotinib", "150 mg", "Oral Tablet", "358263", "L01EB02", "EGFR (HER1) Tyrosine Kinase Inhibitor", ["Tarceva", "Erlocip"],
     "Metastatic non-small cell lung cancer (NSCLC) with EGFR exon 19 deletions or exon 21 (L858R) substitution; advanced pancreatic cancer with gemcitabine.",
     "150 mg orally once daily ON AN EMPTY STOMACH (at least 1 hour before or 2 hours after food) until disease progression.",
     "Severe hypersensitivity to erlotinib.",
     "Interstitial Lung Disease (ILD / pneumonitis - fatal in 1% - discontinue immediately if unexplained acute dyspnea occurs); severe acneiform rash (correlates with clinical response); gastrointestinal perforation; ocular disorders / corneal ulceration.",
     "Acneiform rash / dermatitis (85%), diarrhea (62%), anorexia, fatigue, dyspnea, stomatitis, paronychia.",
     "PPIs and H2 blockers completely block erlotinib solubility/absorption (avoid PPIs, separate antacids by 2h); strong CYP3A4 inhibitors (ketoconazole doubles levels); smoking increases clearance 2-fold.",
     "Category D. Discontinue during pregnancy."),
    ("Gefitinib", "250 mg", "Oral Tablet", "343048", "L01EB01", "Selective EGFR Tyrosine Kinase Inhibitor", ["Iressa", "Geftinat"],
     "First-line treatment of metastatic NSCLC whose tumors have EGFR exon 19 deletions or exon 21 (L858R) mutations.",
     "250 mg orally once daily with or without food.",
     "Hypersensitivity.", "Interstitial lung disease (ILD); severe hepatotoxicity; gastrointestinal perforation; ocular keratitis.",
     "Skin rash / acne (54%), diarrhea (47%), elevated ALT/AST, pruritus, dry skin, anorexia, stomatitis.",
     "Gastric acid reducers (PPIs reduce gefitinib AUC by 44%), strong CYP3A4 inducers (rifampin reduces AUC by 83%), warfarin (elevated INR).",
     "Category D."),
    ("Osimertinib", "80 mg", "Oral Tablet", "1719286", "L01EB04", "Third-Generation Mutant-Selective & EGFR T790M TKI", ["Tagrisso"],
     "First-line treatment of metastatic NSCLC with EGFR exon 19 deletions or L858R mutations; adjuvant NSCLC; EGFR T790M resistance mutation-positive NSCLC.",
     "80 mg orally once daily with or without food (swallow whole or disperse in water).",
     "Hypersensitivity.",
     "Interstitial Lung Disease / pneumonitis (fatal in 1%); QTc interval prolongation and Torsades de Pointes; Cardiomyopathy / congestive heart failure (decreased LVEF); keratitis.",
     "Diarrhea (58%), rash (58%), dry skin, paronychia / nail toxicity, stomatitis, fatigue, decreased appetite, leukopenia.",
     "Strong CYP3A4 inducers (rifampin, carbamazepine decrease osimertinib AUC by 78% - avoid combination), QT-prolonging drugs.",
     "Category D. Standard of care first-line EGFR-mutated NSCLC therapy."),
    ("Palbociclib", "125 mg", "Oral Capsule / Tablet", "1601380", "L01EF01", "Cyclin-Dependent Kinase 4 and 6 (CDK4/6) Inhibitor", ["Ibrance"],
     "Treatment of HR-positive, HER2-negative advanced or metastatic breast cancer in combination with an aromatase inhibitor or fulvestrant.",
     "125 mg orally once daily WITH FOOD for 21 consecutive days followed by 7 days off treatment (28-day cycle).",
     "Hypersensitivity to palbociclib.",
     "Severe neutropenia (Grade 3/4 neutropenia in 66% - dose-limiting toxicity - monitor CBC prior to each cycle and on day 15 of first 2 cycles); interstitial lung disease / pneumonitis; venous thromboembolism.",
     "Neutropenia (79%), leukopenia, fatigue, anemia, upper respiratory infection, stomatitis, alopecia, diarrhea, thrombocytopenia.",
     "Strong CYP3A4 inhibitors (ketoconazole, clarithromycin - reduce palbociclib to 75 mg), strong inducers (rifampin decreases AUC by 85%).",
     "Category D. Embryo-fetal lethality in animal models."),
    ("Ribociclib", "200 mg", "Oral Tablet", "1873983", "L01EF02", "Selective CDK4 and CDK6 Inhibitor", ["Kisqali"],
     "Treatment of HR-positive, HER2-negative advanced or metastatic breast cancer in combination with an aromatase inhibitor (proven overall survival benefit).",
     "600 mg (three 200 mg tablets) orally once daily in morning WITH OR WITHOUT FOOD for 21 days followed by 7 days off (28-day cycle).",
     "Hypersensitivity.",
     "QTcF interval prolongation (baseline ECG and on Day 14 of cycle 1 mandatory); severe hepatobiliary toxicity (monitor LFTs every 2 weeks for first 2 cycles); neutropenia (Grade 3/4 in 60%); interstitial lung disease.",
     "Neutropenia, nausea, fatigue, diarrhea, leukopenia, elevated transaminases, vomiting, alopecia, prolonged QT.",
     "Strong CYP3A4 inhibitors, strong inducers, QT-prolonging drugs (amiodarone, tamoxifen contraindicated).",
     "Category D. Only CDK4/6 inhibitor with statistically significant overall survival benefit across multiple Phase III trials."),
    ("Olaparib", "150 mg", "Oral Tablet", "1598284", "L01XX46", "Poly (ADP-Ribose) Polymerase (PARP1, PARP2, PARP3) Inhibitor", ["Lynparza"],
     "Advanced deleterious BRCA-mutated or homologous recombination repair (HRR) deficient ovarian, breast, pancreatic, and prostate cancers.",
     "300 mg (two 150 mg tablets) orally twice daily with or without food swallowed whole.",
     "Hypersensitivity to olaparib.",
     "Myelodysplastic Syndrome / Acute Myeloid Leukemia (MDS/AML - fatal in 1.5%); severe prolonged bone marrow suppression; pneumonitis; venous thromboembolic events.",
     "Anemia (46%), nausea (77%), fatigue, vomiting, diarrhea, thrombocytopenia, neutropenia, decreased appetite, elevated creatinine.",
     "Strong or moderate CYP3A4 inhibitors (reduce olaparib to 100-150 mg BID), strong or moderate inducers (rifampin, carbamazepine avoid).",
     "Category D. Synthetic lethality in BRCA1/2 deficient cancers."),
    ("Pembrolizumab", "100 mg", "IV Infusion", "1547545", "L01FF02", "Humanized Anti-PD-1 Monoclonal Antibody (Immune Checkpoint Inhibitor)", ["Keytruda"],
     "Melanoma, non-small cell lung cancer (NSCLC), head and neck cancer, classical Hodgkin lymphoma, urothelial carcinoma, MSI-H/dMMR solid tumors, triple-negative breast cancer.",
     "200 mg IV every 3 weeks or 400 mg IV every 6 weeks infused over 30 minutes until disease progression or up to 24 months.",
     "Severe hypersensitivity to pembrolizumab.",
     "Immune-Mediated Adverse Reactions (imARs) affecting ANY organ system: Immune-mediated pneumonitis (fatal in 0.2%), colitis / diarrhea, hepatitis, endocrinopathies (hypophysitis, thyroiditis, adrenal insufficiency, Type 1 diabetes), nephritis, severe dermatologic reactions (SJS/TEN), myocarditis; infusion reactions.",
     "Fatigue (40%), musculoskeletal pain, decreased appetite, pruritus, diarrhea, nausea, rash, cough, dyspnea, hypothyroidism.",
     "Systemic corticosteroids or immunosuppressants before starting pembrolizumab may interfere with anti-tumor immune response (except when treating severe imARs).",
     "Category D. Breakthrough immunotherapy; manage severe immune toxicities promptly with high-dose IV methylprednisolone 1-2 mg/kg/day."),
    ("Nivolumab", "100 mg", "IV Infusion", "1597876", "L01FF01", "Fully Human Anti-PD-1 Immune Checkpoint Inhibitor", ["Opdivo"],
     "Unresectable or metastatic melanoma, metastatic NSCLC, renal cell carcinoma (RCC), classical Hodgkin lymphoma, hepatocellular carcinoma, esophageal cancer.",
     "240 mg IV every 2 weeks or 480 mg IV every 4 weeks infused over 30 minutes.",
     "Hypersensitivity.",
     "Severe immune-mediated pneumonitis, colitis, hepatitis, endocrinopathies, nephritis/renal failure, encephalitis, and myocarditis; graft-versus-host disease (GVHD) in allogeneic HSCT.",
     "Fatigue (30%), rash, musculoskeletal pain, pruritus, diarrhea, nausea, asthenia, cough, dyspnea, elevated transaminases.",
     "Systemic corticosteroids at baseline attenuate immune response.",
     "Category D. Management of Grade 3/4 toxicity requires withholding nivolumab and administering high-dose systemic steroids."),
    ("Bevacizumab", "400 mg", "IV Infusion", "358262", "L01FG01", "Humanized Anti-VEGF-A Monoclonal Antibody (Angiogenesis Inhibitor)", ["Avastin", "Bryxta"],
     "Metastatic colorectal cancer, non-squamous non-small cell lung cancer, glioblastoma multiforme, metastatic renal cell carcinoma, cervical and ovarian cancers.",
     "5 mg/kg to 15 mg/kg IV once every 2 or 3 weeks in combination with cytotoxic chemotherapy regimens (FOLFOX, FOLFIRI, carboplatin/paclitaxel).",
     "Severe hypersensitivity to bevacizumab; surgical incision within past 28 days.",
     "Black Box: Gastrointestinal perforations and fistula formation (fatal in 2-3%); severe surgical wound dehiscence and impaired wound healing (withhold bevacizumab for >=28 days before and after elective surgery); fatal pulmonary hemorrhage / hemoptysis (avoid in squamous cell lung cancer); severe arterial thromboembolic events (stroke, MI); severe hypertension and hypertensive crisis; proteinuria / nephrotic syndrome; PRES encephalopathy.",
     "Hypertension (34%), epistaxis (bleeding from nose - 35%), proteinuria, headache, taste alteration, dry skin, lacrimation disorder.",
     "Anthracyclines (additive cardiotoxicity).",
     "Category D. Anti-angiogenic agent; withhold 4 weeks prior to elective surgery."),
    ("Cetuximab", "100 mg", "IV Infusion", "384459", "L01FE01", "Chimeric Anti-EGFR (HER1) Monoclonal Antibody", ["Erbitux"],
     "KRAS/NRAS wild-type metastatic colorectal cancer (mCRC) and squamous cell carcinoma of the head and neck (SCCHN).",
     "Loading dose: 400 mg/m2 IV infused over 120 min, then weekly 250 mg/m2 infused over 60 min (premedicate with H1-antihistamine).",
     "Severe hypersensitivity to cetuximab; tumors with known KRAS or NRAS codon 12, 13, 59, 61, 117, 146 mutations (completely ineffective and harmful).",
     "Black Box: Fatal infusion reactions and anaphylactoid shock (3% - higher incidence in Southeastern US due to alpha-gal tick bite IgE antibodies); cardiopulmonary arrest / sudden death; severe acneiform follicular rash; severe hypomagnesemia / electrolyte wasting (monitor Mg2+ and Ca2+ for 8 weeks post-therapy).",
     "Acneiform skin rash (88%), hypomagnesemia (55%), diarrhea, nausea, vomiting, fatigue, paronychia, dry skin, pruritus.",
     "Do not use in KRAS/NRAS mutated mCRC.",
     "Category D. Strict RAS biomarker wild-type testing mandatory prior to use."),
    ("Bortezomib", "3.5 mg", "SC / IV Injection", "358261", "L01XG01", "Reversible 26S Proteasome Inhibitor", ["Velcade", "Bortecad"],
     "Treatment of multiple myeloma (induction, consolidation, maintenance) and mantle cell lymphoma.",
     "1.3 mg/m2 SC (preferred) or IV on Days 1, 4, 8, and 11 of a 21-day cycle (subcutaneous route reduces severe peripheral neuropathy by 50%).",
     "Hypersensitivity to bortezomib, boron, or mannitol; intrathecal administration (ABSOLUTE CONTRAINDICATION - fatal ascending myeloradiculopathy).",
     "Black Box: Fatal intrathecal administration (dispense in syringe labeled ONLY FOR SC/IV USE); severe peripheral sensory and motor neuropathy; cardiac toxicity (heart failure, arrhythmias); acute diffuse infiltrative pulmonary disease; severe thrombocytopenia / neutropenia; Herpes zoster reactivation (mandatory acyclovir prophylaxis).",
     "Peripheral neuropathy (38% with IV vs 24% SC), fatigue, diarrhea, thrombocytopenia, nausea, constipation, vomiting, fever.",
     "Strong CYP3A4 inhibitors (ketoconazole increases exposure by 35%), strong inducers (rifampin decreases exposure by 84%), green tea extract (polyphenols bind and inactivate bortezomib).",
     "Category D. Acyclovir/valacyclovir antiviral prophylaxis mandatory during therapy to prevent shingles."),
    ("Lenalidomide", "25 mg", "Oral Capsule", "612792", "L04AX04", "Thalidomide Analog Immunomodulatory Drug (IMiD / Cereblon E3 Ligase Modulator)", ["Revlimid", "Lenalid"],
     "Treatment of multiple myeloma (in combination with dexamethasone); myelodysplastic syndromes (MDS) associated with a deletion 5q cytogenetic abnormality; mantle cell lymphoma.",
     "Multiple myeloma: 25 mg orally once daily with water on Days 1-21 of repeated 28-day cycles (reduce dose strictly in renal impairment based on CrCl).",
     "Pregnancy (absolute contraindication - catastrophic teratogen); hypersensitivity.",
     "Black Box: Severe teratogenicity and life-threatening human birth defects (severe phocomelia, amelia, limb shortening - mandatory Lenalidomide REMS restricted distribution); severe venous and arterial thromboembolism (deep vein thrombosis, PE, MI, stroke - mandatory thromboprophylaxis with aspirin or DOAC/LMWH); severe myelosuppression (Grade 3/4 neutropenia and thrombocytopenia).",
     "Neutropenia (53%), thrombocytopenia (21%), diarrhea, constipation, fatigue, muscle cramps, anemia, rash, DVT/PE.",
     "Digoxin (increases digoxin Cmax by 14%), erythropoiesis-stimulating agents / estrogen (synergistic thromboembolism risk).",
     "Category X. Lenalidomide REMS program. Mandatory 2 negative pregnancy tests prior to initiation."),
    ("Hydroxyurea", "500 mg", "Oral Capsule", "5526", "L01XX05", "Ribonucleotide Reductase Inhibitor", ["Hydrea", "Droxia", "Siklos"],
     "Reduction in painful sickle cell crises and acute chest syndrome in sickle cell anemia; chronic myelogenous leukemia (CML); polycythemia vera; essential thrombocythemia.",
     "Sickle cell disease: 15 mg/kg orally once daily, titrate by 5 mg/kg every 12 weeks to max tolerated dose (max 35 mg/kg/day; target HbF increase).",
     "Severe bone marrow suppression (platelets <100,000/microL or ANC <2,000/microL); pregnancy.",
     "Black Box: Severe life-threatening myelosuppression (neutropenia, thrombocytopenia, severe anemia); secondary malignancies (acute leukemia, skin cancers); cutaneous vasculitic toxicities / leg ulcers; macrocytosis (mean corpuscular volume MCV elevation - marker of adherence).",
     "Myelosuppression, leukopenia, macrocytosis (high MCV), nausea, stomatitis, cutaneous leg ulcers, hyperpigmentation of nails/skin, alopecia.",
     "Didanosine, stavudine (fatal pancreatitis and peripheral neuropathy when combined), live vaccines.",
     "Category D. Cytotoxic hazard; handle with gloves. Highly effective in sickle cell disease to induce fetal hemoglobin (HbF)."),
    ("Etoposide", "50 mg", "Oral Capsule / IV", "4177", "L01CB01", "Epipodophyllotoxin Topoisomerase II Inhibitor", ["Toposar", "VePesid", "Lastet"],
     "Small cell lung cancer (first-line with cisplatin/carboplatin - EP regimen), refractory testicular cancer, lymphomas.",
     "IV: 50 mg to 100 mg/m2/day on Days 1 to 5 every 3-4 weeks (infuse over >=30-60 minutes to prevent acute hypotension); Oral dose is 2x IV dose.",
     "Hypersensitivity to etoposide.",
     "Black Box: Severe dose-dependent myelosuppression (severe leukopenia and thrombocytopenia - monitor CBC); acute severe hypotension and bronchospasm with rapid IV infusion; secondary acute myeloid leukemia (t-AML with 11q23 translocation).",
     "Neutropenia (dose-limiting nadir at days 7-14), alopecia (reversible - 66%), nausea, vomiting, anorexia, stomatitis, hypotension during infusion.",
     "Warfarin (increases INR), cyclosporine (increases etoposide exposure by 80%), CYP3A4 inducers/inhibitors.",
     "Category D. Embryotoxic and teratogenic in animals."),
    ("Vincristine", "1 mg/mL", "IV Infusion", "11202", "L01CA02", "Vinca Alkaloid Microtubule Disruptor (Tubulin Depolymerizer)", ["Oncovin", "Vincristin"],
     "Acute lymphoblastic leukemia (ALL induction in pediatric/adult), Hodgkin's and non-Hodgkin's lymphomas (CHOP, ABVD), Wilms tumor, neuroblastoma.",
     "1.4 mg/m2 IV once weekly (individual dose CAPPED AT 2.0 mg per single dose to prevent fatal neurotoxicity).",
     "Intrathecal administration (FATAL MEDICAL EMERGENCY); Charcot-Marie-Tooth disease; severe hypersensitivity.",
     "Black Box: FOR INTRAVENOUS USE ONLY - FATAL IF GIVEN BY OTHER ROUTES (intrathecal administration causes ascending encephalopathy, severe paralysis, and 100% agonizing death - must dispense in minibag, NEVER in a syringe); severe dose-limiting peripheral and autonomic neurotoxicity (foot drop, loss of deep tendon reflexes, severe paralytic ileus / obstipation); severe vesicant extravasation necrosis.",
     "Peripheral neuropathy (numbness, paresthesias, motor weakness, foot drop), severe constipation, paralytic ileus, abdominal colic, alopecia (mild), jaw pain.",
     "Strong CYP3A4 inhibitors (itraconazole, voriconazole cause severe neurotoxicity and ileus), strong inducers (phenytoin decreases vincristine levels).",
     "Category D. Individual single dose must NEVER exceed 2.0 mg cap."),
    ("Gemcitabine", "1 g", "IV Infusion", "12574", "L01BC05", "Difluorodeoxycytidine Antimetabolite (DNA Synthesis Inhibitor)", ["Gemzar", "Cytogem"],
     "Pancreatic adenocarcinoma (first-line), non-small cell lung cancer, metastatic breast cancer, advanced ovarian cancer, bladder carcinoma.",
     "1,000 mg/m2 IV infused over 30 minutes on Days 1, 8, and 15 of each 28-day cycle (prolonging infusion time >60 min increases severe toxicity).",
     "Severe hypersensitivity to gemcitabine.",
     "Black Box: Severe myelosuppression (neutropenia, thrombocytopenia, anemia); Hemolytic Uremic Syndrome / Thrombotic Microangiopathy (HUS/TMA); severe hepatotoxicity (acute liver failure); pulmonary toxicity / non-cardiogenic pulmonary edema / ARDS; Posterior Reversible Encephalopathy Syndrome (PRES).",
     "Neutropenia (dose-limiting), thrombocytopenia, nausea, vomiting, flu-like syndrome (fever, chills, myalgias in 20%), elevated LFTs, proteinuria, peripheral edema.",
     "Bleomycin (synergistic pulmonary toxicity), live vaccines, radiation therapy (potent radiosensitizer - separate by >=1 week).",
     "Category D. Embryo-fetal lethality in animal models."),
    ("Cytarabine", "100 mg", "IV / SC / Intrathecal", "3054", "L01BC01", "Cytosine Arabinoside (ara-C) Pyrimidine Antimetabolite", ["Cytosar-U", "DepoCyt"],
     "Induction and consolidation remission in Acute Myeloid Leukemia (AML '7+3' regimen with daunorubicin); acute lymphoblastic leukemia; meningeal leukemia (IT).",
     "Standard AML induction: 100 mg to 200 mg/m2/day continuous IV infusion for 7 consecutive days; High-Dose ara-C (HiDAC): 1.5 g to 3 g/m2 IV q12h on days 1, 3, 5.",
     "Hypersensitivity to cytarabine.",
     "Black Box: Severe bone marrow suppression (profound pancytopenia and infection); High-Dose ara-C neurotoxicity (cerebellar toxicity, ataxia, dysarthria, nystagmus - perform pre-dose neurologic exam); severe chemical conjunctivitis / keratitis with high doses (mandatory prophylactic dexamethasone 0.1% eye drops QID); Cytarabine syndrome (fever, myalgia, bone pain, maculopapular rash).",
     "Severe myelosuppression (100%), nausea, vomiting, stomatitis, chemical conjunctivitis, cerebellar toxicity, elevated transaminases, fever.",
     "Digoxin (decreases digoxin absorption), gentamicin, fluorocytosine.",
     "Category D. Dexamethasone steroid ophthalmic eye drops mandatory during high-dose therapy."),
    ("Temozolomide", "100 mg", "Oral Capsule / IV", "73044", "L01AX03", "Oral Imidazotetrazine Methylating Alkylating Agent", ["Temodar", "Temonat"],
     "Newly diagnosed Glioblastoma Multiforme (GBM - Stupp protocol concurrent with radiotherapy, then maintenance) and refractory anaplastic astrocytoma.",
     "Newly diagnosed GBM: 75 mg/m2 orally once daily continuously for 42 days with focal radiotherapy, then maintenance 150-200 mg/m2 daily for 5 days of each 28-day cycle.",
     "Severe hypersensitivity to temozolomide or dacarbazine (shares same active MTIC metabolite).",
     "Severe myelosuppression (severe neutropenia and thrombocytopenia - monitor weekly CBC during focal RT); high risk of Pneumocystis jirovecii pneumonia (PCP - mandatory PCP prophylaxis with Bactrim during concomitant RT); secondary myelodysplasia / AML; severe hepatotoxicity.",
     "Nausea (frequent - premedicate with ondansetron), vomiting, fatigue, headache, constipation, thrombocytopenia, neutropenia, anorexia, alopecia.",
     "Valproic acid (decreases temozolomide clearance by 5%), live vaccines.",
     "Category D. Take on an empty stomach at bedtime to reduce nausea."),
     ("Bleomycin", "15 units", "IV / IM / SC / Intrapleural", "1618", "L01DC01", "Glycopeptide Antibiotic Chemotherapeutic (DNA Strand Scission)", ["Blenoxane"],
     "Hodgkin's lymphoma (ABVD regimen), testicular germ cell tumors (BEP regimen), malignant pleural effusion pleurodesis.",
     "10 to 20 units/m2 IV, IM, or SC weekly or twice weekly (cumulative lifetime dose cap of 400 units to prevent fatal pulmonary fibrosis).",
     "Severe hypersensitivity or idiosyncratic reaction to bleomycin.",
     "Black Box: Severe pulmonary toxicity and fatal pulmonary fibrosis (in 10% - risk spikes sharply above cumulative dose 400 units, age >70, renal decline, or with high inspired oxygen FiO2 during anesthesia); idiosyncratic anaphylactoid reactions (fever, hypotension, mental confusion in 1% of lymphoma patients - give 2-unit test dose).",
     "Pulmonary fibrosis / pneumonitis (cough, dyspnea, basilar crackles), hyperpigmentation / flagellate erythema of skin, hyperkeratosis, fever, chills, alopecia.",
     "High fractional inspired oxygen (FiO2 >30% during anesthesia triggers catastrophic pulmonary damage in bleomycin-exposed patients - warn anesthesiologist), cisplatin (decreases bleomycin clearance).",
     "Category D. Cumulative lifetime exposure capped strictly at 400 units."),

    # UROLOGICAL, MINERAL, OPHTHALMIC & DERMATOLOGIC SPECIALTIES (21)
    ("Fesoterodine", "4 mg", "Oral Tablet (ER)", "795458", "G04BD11", "Competitive Muscarinic Receptor Antagonist Prodrug", ["Toviaz"],
     "Treatment of overactive bladder (OAB) with symptoms of urge urinary incontinence, urgency, and frequency.",
     "4 mg orally once daily with liquid swallowed whole (may increase to 8 mg once daily; max 4 mg with CYP3A4 inhibitors or renal decline).",
     "Urinary retention, gastric retention, uncontrolled narrow-angle glaucoma.",
     "Angioedema of face/lips/tongue; severe anticholinergic effects (dry mouth, constipation, blurred vision, urinary retention); heat prostration.",
     "Dry mouth (28-34%), constipation, dry eyes, dyspepsia, urinary retention.",
     "Strong CYP3A4 inhibitors (ketoconazole, clarithromycin - limit dose to 4 mg daily).",
     "Category C. Prodrug rapidly cleaved by plasma esterases into 5-HMT."),
    ("Darifenacin", "7.5 mg", "Oral Tablet (ER)", "404862", "G04BD10", "Selective Muscarinic M3 Receptor Antagonist", ["Enablex"],
     "Treatment of overactive bladder with symptoms of urge urinary incontinence, urgency, and frequency.",
     "7.5 mg orally once daily swallowed whole with liquid with or without food (may increase to 15 mg once daily after 2 weeks).",
     "Urinary retention, gastric retention, uncontrolled narrow-angle glaucoma.",
     "High M3 bladder selectivity reduces cognitive central CNS penetration; severe constipation and urinary retention.",
     "Dry mouth (20-35%), constipation (14-21%), dyspepsia, abdominal pain, nausea, dry eyes.",
     "Strong CYP3A4 inhibitors (ketoconazole - max dose 7.5 mg daily), moderate CYP2D6 inhibitor.",
     "Category C."),
    ("Trospium Chloride", "20 mg", "Oral Tablet / ER Capsule", "384458", "G04BD09", "Quaternary Ammonium Anticholinergic (Lacks CNS Penetration)", ["Sanctura", "Sanctura XR"],
     "Treatment of overactive bladder with symptoms of urge urinary incontinence, urgency, and frequency.",
     "20 mg orally twice daily ON AN EMPTY STOMACH at least 1 hour before meals (or 60 mg once daily XR in the morning).",
     "Urinary retention, gastric retention, uncontrolled narrow-angle glaucoma.",
     "Quaternary amine structure does NOT cross blood-brain barrier (ideal for elderly with cognitive impairment/dementia risk); food reduces bioavailability by 70-80%.",
     "Dry mouth (20%), constipation (10%), headache, abdominal pain, dyspepsia, dry eyes.",
     "Alcohol (XR formulation causes rapid dose-dumping - avoid alcohol within 2 hours of XR); excreted renally by active tubular secretion (metformin, morphine).",
     "Category C. Preferred anticholinergic when cognitive preservation in elderly is critical."),
    ("Potassium Chloride", "20 mEq", "Oral Tablet (ER) / Solution / IV", "8591", "A12BA01", "Essential Electrolyte Cation Supplement", ["K-Dur", "Klor-Con", "Micro-K", "Potklor"],
     "Treatment and prophylaxis of hypokalemia with or without metabolic alkalosis (frequently caused by loop and thiazide diuretics).",
     "Prophylaxis: 20 mEq orally daily with meals; Treatment: 40 mEq to 100 mEq daily divided with meals and a full glass of water (never give undiluted IV).",
     "Hyperkalemia (serum K+ >5.0 mEq/L); acute renal failure; concurrent potassium-sparing diuretics; esophageal compression/stricture.",
     "Black Box/Warning: Severe gastrointestinal ulcerative, stenotic, and bleeding lesions (swallow tablet whole with full 8 oz water during meals); life-threatening cardiac arrest with rapid IV administration (NEVER give IV bolus or push - max IV peripheral infusion rate 10-20 mEq/hr).",
     "Nausea, vomiting, flatulence, abdominal discomfort, diarrhea, hyperkalemia (paresthesias, peaked T waves, heart block, cardiac arrest).",
     "Potassium-sparing diuretics (spironolactone, triamterene), ACE inhibitors, ARBs, NSAIDs, direct renin inhibitors (synergistic life-threatening hyperkalemia).",
     "Category C. IV potassium must ALWAYS be diluted in IV fluids and infused via rate-controlling pump."),
    ("Sodium Bicarbonate", "650 mg", "Oral Tablet / IV 8.4%", "9863", "B05CB04", "Systemic Alkalinizing Agent & Electrolyte Buffer", ["Neut", "Sodac"],
     "Metabolic acidosis (chronic kidney disease eGFR <30, cardiac arrest, severe diarrhea); urinary alkalinization (salicylate / methotrexate toxicity).",
     "CKD acidosis: 650 mg to 1,300 mg orally 2 to 3 times daily (titrate to serum bicarbonate 22-26 mEq/L); Cardiac arrest / severe acidosis: 1 mEq/kg IV slow infusion.",
     "Metabolic or respiratory alkalosis; hypocalcemia; severe pulmonary edema or hypernatremia.",
     "Severe sodium fluid overload and heart failure exacerbation; hypokalemia (shifts potassium intracellularly); hypocalcemia / tetany; milk-alkali syndrome with calcium.",
     "Metabolic alkalosis, fluid retention / edema, hypernatremia, hypokalemia, abdominal distension, flatulence.",
     "Increases gastric pH (decreases absorption of ketoconazole, iron); increases renal clearance of salicylates, phenobarbital, methotrexate; decreases clearance of amphetamines, quinidine, ephedrine.",
     "Category C. First-line antidote for tricyclic antidepressant (TCA) cardiac sodium channel toxicity and wide QRS."),
    ("Ergocalciferol", "50,000 IU", "Oral Capsule", "4038", "A11CC01", "Vitamin D2 (Plant-Derived Fat-Soluble Secosteroid)", ["Drisdol", "Calciferol"],
     "Treatment of severe nutritional vitamin D deficiency (serum 25(OH)D <20 ng/mL), hypoparathyroidism, refractory rickets.",
     "Severe deficiency: 50,000 IU orally ONCE WEEKLY with a fat-containing meal for 8 to 12 weeks, followed by maintenance 1,000-2,000 IU daily.",
     "Hypercalcemia, malabsorption syndrome, vitamin D toxicity, abnormal sensitivity to vitamin D.",
     "Hypercalcemia and metastatic tissue calcification with chronic overdosage; narrow therapeutic index; requires hepatic 25-hydroxylation and renal 1-alpha-hydroxylation.",
     "Hypercalcemia symptoms (nausea, vomiting, anorexia, polyuria, weakness, constipation, nephrocalcinosis).",
     "Thiazide diuretics (increased hypercalcemia), cholestyramine/mineral oil (decreases absorption by 50%), antiepileptics (phenytoin, carbamazepine induce vitamin D catabolism).",
     "Category C / Category A at RDA doses. Fat-soluble vitamin requiring biliary lipid absorption."),
    ("Cholecalciferol", "2,000 IU", "Oral Tablet / Drops", "2418", "A11CC05", "Vitamin D3 (Human/Animal Endogenous Form)", ["D3-50", "Calcirol", "Bio-D3"],
     "Prevention and treatment of vitamin D deficiency, maintenance of bone health, adjunct in osteoporosis prevention.",
     "1,000 IU to 2,000 IU (25-50 mcg) orally once daily with a meal (or 50,000 IU once weekly for 8 weeks in severe deficiency).",
     "Hypercalcemia, hypervitaminosis D.",
     "Hypercalcemia with chronic supratherapeutic doses (>10,000 IU/day for months); superior potency and sustained 25(OH)D elevation compared to D2 ergocalciferol.",
     "Rare at recommended doses; hypercalcemia, headache, nausea, constipation in massive overdose.",
     "Thiazides, digitalis, bile acid sequestrants, mineral oil.",
     "Category A / C. Natural human form of vitamin D with superior bioavailability."),
    ("Teriparatide", "20 mcg", "SC Injection Pen", "358266", "H05AA02", "Recombinant Human Parathyroid Hormone Fragment (PTH 1-34)", ["Forteo"],
     "Treatment of postmenopausal women with severe osteoporosis at high risk for fracture; increase bone mass in men with primary or hypogonadal osteoporosis; glucocorticoid-induced osteoporosis.",
     "20 mcg subcutaneously into thigh or abdominal wall ONCE DAILY for a lifetime maximum duration of 2 years (requires daily calcium 1,000 mg and vitamin D 400 IU).",
     "Pre-existing hypercalcemia; metabolic bone diseases other than osteoporosis (Paget's disease of bone); unexplained elevated alkaline phosphatase; pediatric patients / open epiphyses; prior skeletal radiation therapy.",
     "Black Box: Potential risk of osteosarcoma (bone cancer - in rat studies, dependent on dose and duration - lifetime treatment duration capped at 24 months); orthostatic hypotension and dizziness (within 4 hours of injection); transient hypercalcemia (measure serum calcium >=16h post-dose); hyperuricemia.",
     "Hypercalcemia, arthralgia, pain in extremities, nausea, dizziness, orthostatic hypotension, injection site bruising.",
     "Digitalis (transient hypercalcemia predisposes to digitalis toxicity).",
     "Category C. Anabolic bone-forming agent; lifetime maximum limit of 24 months."),
    ("Raloxifene", "60 mg", "Oral Tablet", "35827", "G03XC01", "Selective Estrogen Receptor Modulator (Bone Agonist / Breast Antagonist)", ["Evista", "Ralista"],
     "Treatment and prevention of osteoporosis in postmenopausal women; reduction in risk of invasive breast cancer in postmenopausal women with osteoporosis or at high risk.",
     "60 mg orally once daily at any time of day with or without food (ensure adequate calcium and vitamin D).",
     "Active or past history of venous thromboembolism (deep vein thrombosis, pulmonary embolism, retinal vein thrombosis); pregnancy and women of childbearing potential.",
     "Black Box: Increased risk of venous thromboembolism (DVT/PE risk elevated 2- to 3-fold - discontinue >=72 hours prior to and during prolonged immobilization/surgery); increased risk of fatal stroke in postmenopausal women with coronary heart disease; hot flashes (does NOT relieve vasomotor symptoms).",
     "Hot flashes (very common - 25%), leg cramps (7%), peripheral edema, flu-like symptoms, arthralgia, thromboembolic events.",
     "Cholestyramine (reduces raloxifene absorption by 60%), highly protein-bound drugs, warfarin (modest prothrombin time reduction).",
     "Category X. Absolute contraindication in pregnancy (teratogenic)."),
    ("Betaxolol", "0.5 %", "Ophthalmic Drops / Oral Tablet", "1512", "S01ED02", "Cardioselective Beta-1 Adrenergic Antagonist (Ophthalmic & Oral)", ["Betoptic", "Kerlone"],
     "Reduction of intraocular pressure in chronic open-angle glaucoma and ocular hypertension; oral treatment of hypertension.",
     "Ophthalmic: 1 drop of 0.25% suspension or 0.5% solution in affected eye(s) twice daily; Oral: 10 mg to 20 mg once daily.",
     "Sinus bradycardia, greater than first-degree AV block, cardiogenic shock, overt cardiac failure.",
     "Cardioselective beta-1 blockade provides superior pulmonary safety compared to non-selective timolol in patients with mild reactive airway disease/asthma; punctal occlusion reduces systemic absorption.",
     "Ocular stinging/discomfort (frequent), blurred vision, foreign body sensation, mild systemic bradycardia, fatigue.",
     "Oral beta-blockers, verapamil, diltiazem (additive bradycardia and AV block), reserpine.",
     "Category C. Preferred ophthalmic beta-blocker when mild pulmonary disease is present."),
    ("Brinzolamide", "1 %", "Ophthalmic Suspension", "1364429", "S01EC04", "Ophthalmic Carbonic Anhydrase II Inhibitor", ["Azopt"],
     "Treatment of elevated intraocular pressure in patients with ocular hypertension or open-angle glaucoma (monotherapy or combined with brimonidine as Simbrinza).",
     "1 drop in the affected eye(s) three times daily (shake well before use; comfort profile superior to dorzolamide with less stinging/burning).",
     "Hypersensitivity to brinzolamide or sulfonamides ('sulfa' allergy); severe renal impairment (CrCl <30 mL/min).",
     "Sulfonamide hypersensitivity reactions; corneal endothelial decompensation and edema; transient visual blurring upon instillation due to suspension vehicle.",
     "Blurred vision (temporary upon drop instillation - 5-10%), bitter/dysgeusia taste (5%), ocular discomfort, blepharitis, foreign body sensation.",
     "Oral carbonic anhydrase inhibitors (acetazolamide causes additive systemic toxicity).",
     "Category C. Suspension formulation causes less ocular stinging than dorzolamide solution."),
    ("Bimatoprost", "0.01 %", "Ophthalmic Drops / 0.03% Lash Solution", "284400", "S01EE03", "Synthetic Prostamide Analog (Dual Outflow Enhancer)", ["Lumigan", "Latisse"],
     "Reduction of elevated intraocular pressure in open-angle glaucoma and ocular hypertension; treatment of hypotrichosis of the eyelashes (Latisse 0.03%).",
     "Glaucoma: 1 drop in affected eye(s) once daily in the evening (remove contact lenses prior to application); Latisse: 1 drop applied with sterile applicator along upper eyelid margin nightly.",
     "Hypersensitivity to bimatoprost or benzalkonium chloride.",
     "Permanent brown iris pigmentation; eyelid skin darkening (reversible); hypertrichosis (eyelash darkening, lengthening, thickening); macular edema in aphakic/pseudophakic patients with torn posterior lens capsule; intraocular inflammation (uveitis/iritis).",
     "Conjunctival hyperemia (eye redness - 45%), ocular pruritus, eyelash growth, eyelid skin hyperpigmentation, dry eyes.",
     "Prostaglandin analogs (using multiple prostaglandin drops simultaneously reduces IOP-lowering efficacy).",
     "Category C. Store at 2-25°C; remove contact lenses and wait 15 minutes before reinserting."),
    ("Pilocarpine", "2 %", "Ophthalmic Solution / Oral Tablet", "8330", "S01EB01", "Direct-Acting Muscarinic Cholinergic Agonist (Parasympathomimetic)", ["Isopto Carpine", "Salagen", "Pilocar"],
     "Emergency acute angle-closure glaucoma (rapid miosis opens trabecular meshwork), chronic open-angle glaucoma; oral Salagen for radiation xerostomia (dry mouth) and Sjogren's syndrome.",
     "Glaucoma: 1 to 2 drops of 1%, 2%, or 4% in affected eye(s) up to 3 to 4 times daily; Salagen: 5 mg orally 3 to 4 times daily with meals.",
     "Conditions where pupillary constriction is undesirable (acute anterior uveitis/iritis); uncontrolled asthma; severe narrow-angle glaucoma before iridotomy.",
     "Miosis causes severe impairment of dark adaptation and night vision / night driving; retinal detachment (retinal exam mandatory before starting); frontal brow ache and ciliary spasm in young patients; cholinergic systemic toxicity (diaphoresis, salivation, bronchospasm, bradycardia).",
     "Brow ache / ciliary spasm (very common in young patients), dimness of vision / poor night vision, eye irritation, sweating (oral 30%), nausea, urinary frequency.",
     "Anticholinergic drugs (atropine, benztropine directly antagonize pilocarpine), beta-blockers (synergistic conduction slowing).",
     "Category C. Antidote for systemic toxicity: Parenteral Atropine."),
    ("Olopatadine", "0.2 %", "Ophthalmic Solution / Nasal Spray", "1364428", "S01GX09", "Dual Action Selective H1 Receptor Antagonist & Mast Cell Stabilizer", ["Patanol", "Pataday", "Pazeo", "Patanase"],
     "Treatment of ocular itching associated with allergic conjunctivitis (Pataday 0.2% once daily); seasonal allergic rhinitis (Patanase nasal spray).",
     "Allergic conjunctivitis: 1 drop of 0.2% solution in each affected eye ONCE DAILY (or 0.1% twice daily 6-8 hours apart).",
     "Hypersensitivity to olopatadine or benzalkonium chloride.",
     "Do not instill while wearing contact lenses (wait >=10-15 minutes after instillation before inserting soft contacts); rapid relief within 30 minutes.",
     "Cold syndrome / pharyngitis, eye burning/stinging, headache, foreign body sensation, taste perversion (dysgeusia - nasal spray).",
     "None significant topically.",
     "Category C. Highly effective once-daily dual-action ocular antiallergic agent."),
    ("Azelastine", "0.05 %", "Ophthalmic Drops / 0.1% Nasal Spray", "1219", "R01AC03", "Second-Generation H1 Antihistamine & Mast Cell Stabilizer", ["Optivar", "Astelin", "Astepro"],
     "Treatment of itching of the eye associated with allergic conjunctivitis; seasonal and perennial allergic rhinitis / vasomotor rhinitis (nasal spray).",
     "Allergic conjunctivitis: 1 drop in each affected eye twice daily; Allergic rhinitis: 1 to 2 sprays per nostril twice daily.",
     "Hypersensitivity to azelastine.",
     "Bitter taste in mouth / dysgeusia (in up to 20% with nasal spray due to posterior pharyngeal drainage); mild somnolence / drowsiness; nasal ulceration/epistaxis with nasal spray.",
     "Bitter taste (20%), transient ocular stinging/burning, headache, somnolence, nasal mucosal irritation, dry mouth.",
     "Alcohol and other CNS depressants (additive sedation), cimetidine (increases azelastine exposure).",
     "Category C. Fast onset of nasal and ocular allergy relief within 15-30 minutes."),
    ("Tacrolimus Topical", "0.1 %", "Topical Ointment", "284402", "D11AH01", "Topical Calcineurin Inhibitor (Non-Steroidal Immunomodulator)", ["Protopic", "Tacroz"],
     "Second-line moderate-to-severe atopic dermatitis (eczema) in non-immunocompromised patients unresponsive to or intolerant of topical corticosteroids.",
     "Apply a thin layer of 0.03% (pediatric >=2 years) or 0.1% (adults) to affected skin twice daily; rub in completely (safe for facial and eyelid eczema).",
     "Hypersensitivity; children <2 years; immunocompromised patients; Netherton's syndrome (massive systemic absorption).",
     "Black Box: Rare cases of malignancy (skin carcinoma and lymphoma - avoid continuous long-term use and apply only to affected areas); application site skin burning and stinging (very common in first few days - decreases with repeated use); avoid sun exposure / tanning beds.",
     "Skin burning / heat sensation (46-58% during initial days), pruritus, skin erythema, folliculitis, alcohol intolerance (facial flushing/burning with alcohol).",
     "CYP3A4 inhibitors (ketoconazole, erythromycin may increase levels if extensive skin absorption occurs).",
     "Category C. Steroid-sparing agent safe for long-term use on delicate facial, neck, and intertriginous skin without causing skin atrophy or striae."),
    ("Calcipotriene", "0.005 %", "Topical Cream / Ointment / Foam", "1888", "D05AX02", "Synthetic Vitamin D3 Derivative (Keratinocyte Differentiation Regulator)", ["Dovonex", "Sorilux", "Calcitrene"],
     "Treatment of plaque psoriasis of the scalp and body in adults and pediatric patients (monotherapy or combined with betamethasone dipropionate as Taclonex/Wynzora).",
     "Apply a thin layer to affected psoriatic plaques twice daily and rub in gently (maximum 100 g per week to prevent systemic hypercalcemia).",
     "Known hypercalcemia or evidence of vitamin D toxicity; application to face (causes facial dermatitis).",
     "Systemic hypercalcemia and hypercalciuria if weekly dose exceeds 100 g/week (monitor serum calcium in extensive disease); skin irritation; not for facial or intertriginous psoriasis.",
     "Skin burning, pruritus, skin irritation, erythema, dry skin, worsening of psoriasis, hypercalcemia.",
     "Topical salicylic acid (acidic pH inactivates calcipotriene - do NOT apply together; apply at separate times).",
     "Category C. Inactivated by acidic preparations like salicylic acid."),
    ("Benzoyl Peroxide", "5 %", "Topical Gel / Wash / Cream", "1443", "D10AE01", "Topical Oxidizing Antibacterial & Keratolytic Agent", ["Benzac AC", "Brevoxyl", "PanOxyl", "Persa-Gel"],
     "Topical treatment of mild to moderate acne vulgaris (generates reactive oxygen species that destroy Cutibacterium acnes without bacterial resistance).",
     "Apply a thin layer to affected skin once or twice daily after washing with mild cleanser (start once daily to minimize peeling and erythema).",
     "Hypersensitivity to benzoyl peroxide.",
     "Bleaches colored fabrics, clothing, towels, and hair upon contact; severe contact dermatitis and excessive dryness/peeling in sensitive skin; photosensitivity.",
     "Skin peeling, erythema, dryness, burning, stinging, allergic contact dermatitis, fabric bleaching.",
     "Topical tretinoin (benzoyl peroxide oxidizes and degrades first-generation tretinoin - apply tretinoin at night and BPO in the morning; adapalene is stable with BPO).",
     "Category C. Zero bacterial resistance; gold standard topical antibacterial for acne."),
    ("Salicylic Acid", "2 %", "Topical Gel / Lotion / Shampoo", "9524", "D01AE12", "Beta-Hydroxy Acid Keratolytic & Desquamating Agent", ["Compound W", "Sebulex", "Salicylix"],
     "Treatment of acne vulgaris (0.5-2%), psoriasis, seborrheic dermatitis, dandruff, calluses, and common/plantar warts (17-40%).",
     "Acne: apply thin layer 1 to 3 times daily; Warts (Compound W 17%): apply 1 drop directly to wart once daily after soaking in warm water for 5 minutes.",
     "Hypersensitivity to salicylates; application to extensive open wounds or large surface areas in infants/children (systemic salicylism toxicity).",
     "Systemic salicylate toxicity / salicylism (tinnitus, nausea, vomiting, tachypnea, metabolic acidosis, confusion) with high-concentration large-surface application, especially in children; local chemical irritation.",
     "Local skin burning, erythema, peeling, dryness, skin irritation, contact dermatitis.",
     "Inactivates topical calcipotriene.",
     "Category C. Lipophilic beta-hydroxy acid penetrates sebaceous follicles effectively."),
    ("Isotretinoin", "20 mg", "Oral Capsule", "6064", "D10BA01", "13-cis-Retinoic Acid (Systemic Retinoid)", ["Accutane", "Claravis", "Absorica", "Zenatane", "Sotret"],
     "Treatment of severe recalcitrant nodular acne, cystic acne, and acne unresponsive to conventional therapy including systemic antibiotics.",
     "0.5 mg/kg to 1.0 mg/kg/day orally divided in 2 doses WITH A HIGH-FAT MEAL for 15 to 20 weeks (target cumulative lifetime dose 120 - 150 mg/kg to achieve long-term remission).",
     "Pregnancy and women of childbearing potential unless complying with iPLEDGE REMS program; severe hepatic impairment; hyperlipidemia.",
     "Black Box: Severe life-threatening teratogenicity and major human fetal deformities (craniofacial, cardiac, thymus, and CNS defects - strict iPLEDGE program with 2 negative pregnancy tests and 2 forms of contraception); Pseudotumor Cerebri / idiopathic intracranial hypertension (especially when combined with tetracyclines); severe depression, psychosis, and suicidal ideation; severe hypertriglyceridemia and acute pancreatitis; premature epiphyseal plate closure in adolescents; severe mucocutaneous dryness; inflammatory bowel disease.",
     "Cheilitis / cracked lips (100%), severe dry skin / xerosis (90%), dry eyes / conjunctivitis (40%), epistaxis, hypertriglyceridemia, elevated liver transaminases, myalgias, back pain, alopecia, photosensitivity.",
     "Tetracyclines (doxycycline, minocycline strictly contraindicated - additive risk of pseudotumor cerebri/benign intracranial hypertension); Vitamin A supplements (hypervitaminosis A toxicity); micro-dosed progestin-only birth control pills ('minipill' - unreliable).",
     "Category X / iPLEDGE REMS program. Absolute contraindication in pregnancy. Highly teratogenic. High-fat meals double oral absorption."),
    ("Minoxidil", "5 %", "Topical Solution / Foam / 2.5 mg Oral", "7004", "D11AX01", "ATP-Sensitive Potassium Channel Opener & Vasodilator", ["Rogaine", "Mintop", "Loniten"],
     "Topical: Androgenetic alopecia in men and women (male/female pattern baldness); Oral (Loniten): severe refractory hypertension (with loop diuretic and beta-blocker); off-label low-dose oral minoxidil for hair loss (0.625-2.5 mg daily).",
     "Topical: Apply 1 mL of 5% solution or 1/2 capful of 5% foam directly to scalp twice daily on completely dry hair (requires continuous use to maintain hair growth); Oral hair loss (off-label): 1.25 mg to 2.5 mg once daily.",
     "Pheochromocytoma (oral); hypersensitivity to minoxidil or propylene glycol vehicle.",
     "Topical: Transient shedding of resting hairs during weeks 2-6 ('minoxidil dread shed' - normal transition to anagen phase); hypertrichosis on face/forehead if applied improperly; Black Box (Oral): Severe fluid and sodium retention causing congestive heart failure and massive pericardial effusion / tamponade (requires co-prescribed loop diuretic); reflex tachycardia (requires beta-blocker); angina exacerbation.",
     "Topical: Scalp itching, erythema, scaling, hypertrichosis on face/arms, temporary hair shedding; Oral: Fluid retention / peripheral edema (very common), reflex tachycardia, palpitations, hypertrichosis, headache.",
     "Oral: Guanethidine (severe orthostatic hypotension), antihypertensives; Topical: no significant systemic drug interactions.",
     "Category C. Continuous lifelong therapy required; hair loss resumes within 3-4 months if discontinued.")
]

def get_expanded_catalog_records() -> List[Dict[str, Any]]:
    """Convert expanded tuple data into standardized dictionary records."""
    records = []
    for name, st, form, rxcui, atc, cls, aliases, ind, dos, con, war, adv, inter, prg in EXPANDED_CLINICAL_DRUGS:
        records.append({
            "name": name, "strength": st, "form": form, "rxcui": rxcui, "atc": atc,
            "class": cls, "aliases": aliases, "ind": ind, "dos": dos, "con": con,
            "war": war, "adv": adv, "int": inter, "prg": prg
        })
    return records

if __name__ == "__main__":
    r = get_expanded_catalog_records()
    print(f"Expanded catalog records count: {len(r)}")
