"""Clinical Knowledge Base: Domains 9, 10, and 11 (Corticosteroids, Psychiatric/CNS, Antifungals/Antivirals).

Contains 105+ authentic medicine monographs with US NLM RxNorm RxCUIs, ATC codes, and FDA labeling.
"""
from typing import Any, Dict, List, Tuple

# Domain 9: Corticosteroids & Immunosuppressants (20)
CAT_9_IMMUNO: List[Tuple] = [
    ("Prednisone", "20 mg", "Oral Tablet", "8640", "H02AB07", "Systemic Glucocorticoid Anti-Inflammatory", ["Deltasone", "Wysolone", "Prednisone Intensol"],
     "Severe inflammatory conditions, allergic states, autoimmune disorders (SLE, rheumatoid arthritis, IBD), acute asthma exacerbations, organ transplant immunosuppression.",
     "5 mg to 60 mg orally once daily in the morning with food (taper gradually if used for >2 weeks to avoid acute adrenal crisis).",
     "Systemic fungal infections; administration of live viral vaccines while on immunosuppressive doses.",
     "Hypothalamic-Pituitary-Adrenal (HPA) axis suppression (taper required); immunosuppression and masking of infection; Cushingoid syndrome; hyperglycemia; peptic ulceration; osteoporosis; psychiatric disturbances (steroid psychosis).",
     "Hyperglycemia, insomnia, fluid retention, hypertension, weight gain, dyspepsia, mood swings, skin thinning, cushingoid moon facies.",
     "NSAIDs (significantly increases peptic ulceration and GI bleeding), antidiabetics (antagonizes glycemic control), live vaccines, CYP3A4 inducers (phenytoin, rifampin increase clearance).",
     "Category C. Crosses placenta; minimal active prednisolone enters breast milk. Taper mandatory after chronic use."),
    ("Prednisolone", "15 mg", "Oral Tablet / Syrup", "8638", "H02AB06", "Active Glucocorticoid (Active Form of Prednisone)", ["Prelone", "Orapred", "Omnipred"],
     "Asthma exacerbations in pediatric patients, severe allergic conditions, autoimmune diseases (preferred in hepatic impairment - does not require liver activation).",
     "5 mg to 60 mg orally daily with meals (pediatric asthma: 1-2 mg/kg/day for 3-5 days).",
     "Systemic fungal infections, live vaccines.", "Adrenal suppression, growth suppression in children, immunosuppression.",
     "Nausea, insomnia, hyperglycemia, fluid retention, mood changes.", "NSAIDs, antidiabetics, CYP3A4 inducers.",
     "Category C."),
    ("Methylprednisolone", "4 mg", "Oral / IV / Depot IM", "6902", "H02AB04", "Intermediate-Acting Glucocorticoid", ["Medrol", "Solu-Medrol", "Depo-Medrol"],
     "Acute spinal cord injury, severe acute asthma, anaphylaxis adjunct, pulse therapy in lupus nephritis.",
     "Medrol Dosepak (21 tablets tapered over 6 days) or IV 40 mg to 125 mg every 6 hours (pulse therapy 1,000 mg IV daily for 3 days).",
     "Systemic fungal infections, intrathecal administration (Depo-Medrol contraindicated intrathecally).",
     "Severe infection risk; acute psychosis; peptic ulceration; hypertension; aseptic necrosis of femoral head.",
     "Hyperglycemia, hypertension, insomnia, leukocytosis (benign demargination), sodium retention.",
     "NSAIDs, ketoconazole, rifampin.",
     "Category C."),
    ("Dexamethasone", "4 mg", "Oral Tablet / IV", "3264", "H02AB02", "High-Potency Long-Acting Glucocorticoid (25-30x Hydrocortisone)", ["Decadron", "Dexona"],
     "Cerebral edema associated with brain tumors/metastases, severe COVID-19 with respiratory support (RECOVERY trial), antiemetic in chemotherapy, croup in pediatrics, fetal lung maturation in preterm labor.",
     "0.75 mg to 9 mg orally or IV daily (COVID-19: 6 mg daily for up to 10 days; Croup: 0.6 mg/kg single dose).",
     "Systemic fungal infections; live vaccines.", "Lacks mineralocorticoid activity (pure glucocorticoid); profound HPA axis suppression; severe hyperglycemia; avascular bone necrosis.",
     "Insomnia, hyperglycemia, agitation, increased appetite, fluid retention, muscle weakness.",
     "CYP3A4 inducers (phenytoin, carbamazepine double dexamethasone clearance), NSAIDs, antidiabetics.",
     "Category C. Crosses the placenta freely (used intentionally for fetal lung surfactant maturation)."),
    ("Hydrocortisone", "20 mg", "Oral Tablet / IV", "5492", "H02AB09", "Short-Acting Glucocorticoid & Mineralocorticoid", ["Cortef", "Solu-Cortef"],
     "Primary and secondary adrenocortical insufficiency (Addison's disease), septic shock refractory to vasopressors, acute adrenal crisis.",
     "Replacement: 15 mg to 20 mg in the morning and 5 mg to 10 mg in the late afternoon (mimics circadian cortisol rhythm); Septic shock: 50 mg IV q6h or 200 mg/day continuous.",
     "Systemic fungal infections.", "Adrenal crisis upon acute withdrawal; sodium retention and edema (has intrinsic mineralocorticoid activity).",
     "Sodium retention, edema, hypertension, hypokalemia, hyperglycemia, insomnia.",
     "Antidiabetics, NSAIDs, CYP3A4 inducers.",
     "Category C. Physiological replacement mandatory throughout pregnancy and increased during labor (stress dose)."),
    ("Betamethasone", "6 mg", "IM Injection", "1514", "H02AB01", "Long-Acting Fluorinated Glucocorticoid", ["Celestone", "Diprosone"],
     "Antenatal fetal lung maturation in threatened preterm labor (accelerates surfactant production), severe inflammatory conditions.",
     "Fetal lung maturation: 12 mg IM repeated once 24 hours later (2 doses total between 24 and 34 weeks gestation).",
     "Systemic fungal infections; systemic administration in idiopathic thrombocytopenic purpura.",
     "Transient maternal hyperglycemia and leukocytosis; HPA suppression.",
     "Transient hyperglycemia, insomnia, injection site discomfort.",
     "Antidiabetics (requires insulin titration in gestational diabetes).",
     "Category C. Drug of choice for antenatal fetal lung maturation."),
    ("Triamcinolone", "4 mg", "Oral / Intra-Articular / Topical", "10753", "H02AB08", "Intermediate Glucocorticoid", ["Kenalog", "Aristocort", "Nasacort"],
     "Intra-articular injection for osteoarthritis/rheumatoid arthritis, dermatoses, keloids, allergic rhinitis.",
     "Intra-articular: 5 mg to 40 mg injected into joint every 3 to 6 months; Topical: 0.1% cream applied 2-3 times daily.",
     "Systemic fungal infection, local infection at injection site.", "Joint destruction with excessive repeated injections; local cutaneous atrophy/hypopigmentation.",
     "Local joint pain post-injection, skin depigmentation, transient hyperglycemia.",
     "NSAIDs, antidiabetics.",
     "Category C."),
    ("Fludrocortisone", "0.1 mg", "Oral Tablet", "4450", "H02AA02", "Potent Mineralocorticoid (Aldosterone Congener)", ["Florinef"],
     "Partial replacement therapy for primary adrenocortical insufficiency (Addison's disease), severe neurogenic orthostatic hypotension.",
     "0.05 mg to 0.2 mg orally once daily in the morning.",
     "Systemic fungal infections.", "Severe sodium retention, severe hypertension, hypokalemia, congestive heart failure.",
     "Hypokalemia, hypertension, peripheral edema, headache, cardiac enlargement.",
     "Diuretics (exaggerates hypokalemia), digoxin (hypokalemic digitalis toxicity).",
     "Category C. Essential mineralocorticoid replacement in Addisonian pregnancy."),
    ("Methotrexate", "2.5 mg", "Oral Tablet / SC / IM", "6851", "L01BA01", "Dihydrofolate Reductase Inhibitor & Antimetabolite", ["Rheumatrex", "Trexall", "Otrexup", "Rasuvo"],
     "Rheumatoid arthritis, severe psoriasis, Crohn's disease, acute lymphoblastic leukemia, ectopic pregnancy medical termination.",
     "Rheumatoid Arthritis: 7.5 mg to 25 mg orally or SC ONCE WEEKLY (NEVER daily); always co-prescribe Folic Acid 1-5 mg daily (except on day of MTX).",
     "Pregnancy and lactation (absolute contraindication in non-malignant disease); alcoholism, alcoholic liver disease, or chronic liver disease; pre-existing blood dyscrasias.",
     "Black Box: Teratogenic/fetal death; fatal hepatotoxicity (fibrosis/cirrhosis - monitor LFTs); bone marrow suppression (leukopenia, thrombocytopenia); opportunistic infections (PCP); fatal pneumonitis / lung fibrosis; fatal dosing errors (fatal when taken daily instead of weekly).",
     "Nausea, stomatitis/mouth ulcers, fatigue, elevated transaminases, alopecia, leukopenia.",
     "NSAIDs, aspirin, sulfonamides (Bactrim), penicillins, PPIs (inhibit renal MTX clearance causing fatal bone marrow suppression - avoid co-administration).",
     "Category X. Potent teratogen and abortifacient (discontinue >=3 months before conception in both females and males). Antidote: Leucovorin (folinic acid)."),
    ("Hydroxychloroquine", "200 mg", "Oral Tablet", "5521", "P01BA02", "4-Aminoquinoline Antimalarial & DMARD", ["Plaquenil", "HCQS"],
     "Systemic lupus erythematosus (SLE - reduces disease flares and organ damage), rheumatoid arthritis, malaria prophylaxis/treatment.",
     "200 mg to 400 mg orally once daily with food or milk (max 5.0 mg/kg actual body weight/day to prevent retinal toxicity).",
     "Pre-existing retinal disease or maculopathy; known hypersensitivity to 4-aminoquinolines.",
     "Irreversible retinal toxicity / bulls-eye retinopathy (baseline and annual ophthalmologic optical coherence tomography OCT screening mandatory after 5 years); QT interval prolongation; cardiomyopathy; hemolytic anemia in G6PD deficiency.",
     "Retinopathy, nausea, abdominal cramps, diarrhea, headache, cutaneous hyperpigmentation, QT prolongation.",
     "QT-prolonging agents (amiodarone, azithromycin, moxifloxacin increase torsades risk), digoxin (increases digoxin level), insulin (hypoglycemia).",
     "Category C. Recommended and safe throughout pregnancy in SLE to prevent catastrophic maternal flares and neonatal heart block."),
    ("Leflunomide", "20 mg", "Oral Tablet", "136443", "L04AA13", "Pyrimidine Synthesis Inhibitor (DHODH Inhibitor)", ["Arava", "Lefno"],
     "Active rheumatoid arthritis in adults (reduces signs/symptoms and structural joint damage).",
     "100 mg orally once daily for 3 days (optional loading), then 10 mg to 20 mg once daily.",
     "Pregnancy (strictly contraindicated); severe hepatic impairment; pre-existing severe hypoproteinemia.",
     "Black Box: Severe teratogenicity/embryofetal death; fatal hepatotoxicity/acute hepatic failure (monitor ALT/AST monthly for first 6 months); extremely long active metabolite (teriflunomide) half-life of 2 weeks (requires 11-day cholestyramine washout protocol to eliminate).",
     "Diarrhea, elevated ALT/AST, alopecia (hair thinning), hypertension, rash, headache.",
     "Hepatotoxic drugs (methotrexate), rifampin, warfarin (increases INR).",
     "Category X. Absolute contraindication in pregnancy (requires verified cholestyramine washout before conception in women and men)."),
    ("Azathioprine", "50 mg", "Oral Tablet / IV", "1256", "L04AX01", "Purine Antimetabolite Immunosuppressant (6-MP Prodrug)", ["Imuran", "Azasan"],
     "Kidney transplant rejection prophylaxis, severe active rheumatoid arthritis, systemic lupus erythematosus, inflammatory bowel disease (Crohn's/UC).",
     "1 mg/kg to 3 mg/kg orally once daily (titrate to clinical response and CBC monitoring).",
     "Pregnancy in rheumatoid arthritis; known hypersensitivity to azathioprine; pre-existing severe bone marrow suppression.",
     "Black Box: Chronic immunosuppression increases risk of malignancy (lymphomas, skin cancers); life-threatening bone marrow suppression (severe leukopenia, thrombocytopenia); severe myelosuppression in patients with genetic TPMT (thiopurine methyltransferase) or NUDT15 deficiency (testing recommended).",
     "Leukopenia, thrombocytopenia, nausea, vomiting, hepatotoxicity, pancreatitis (3%), opportunistic infections.",
     "Allopurinol / Febuxostat (potent xanthine oxidase inhibitors block 6-MP breakdown - severe fatal bone marrow aplasia - REDUCE azathioprine dose by 75% if combined), warfarin (antagonizes warfarin effect).",
     "Category D. Extensively used in maternal lupus and organ transplantation when benefits outweigh risks."),
    ("Mycophenolate Mofetil", "500 mg", "Oral / IV", "68149", "L04AA06", "Inosine Monophosphate Dehydrogenase (IMPDH) Inhibitor", ["CellCept", "Myfortic"],
     "Prophylaxis of organ rejection in kidney, heart, and liver transplantation; lupus nephritis induction and maintenance.",
     "1 g to 1.5 g orally twice daily on an empty stomach (1 hour before or 2 hours after meals).",
     "Pregnancy (absolute contraindication - highly teratogenic); hypersensitivity to mycophenolate mofetil.",
     "Black Box: High risk of first-trimester pregnancy loss (45%) and severe congenital malformations (facial clefts, microtia, cardiac anomalies); increased risk of opportunistic infections (CMV, PML); increased lymphoma and skin malignancy risk.",
     "Diarrhea (frequent - 30%), nausea, vomiting, abdominal pain, leukopenia, anemia, tremor, peripheral edema.",
     "Antacids (aluminum/magnesium) and cholestyramine decrease absorption; oral contraceptives (decreases contraceptive efficacy - requires 2 reliable forms of birth control); acyclovir.",
     "Category D / REMS program. Absolute contraindication in pregnancy (switch to azathioprine >=6 weeks prior to conception)."),
    ("Tacrolimus", "1 mg", "Oral Capsule / IV", "42355", "L04AD02", "Calcineurin Inhibitor (Macrolide Immunosuppressant)", ["Prograf", "Advagraf", "Envarsus XR"],
     "Prophylaxis of organ rejection in kidney, liver, and heart transplantation; refractory autoimmune diseases.",
     "0.05 mg/kg to 0.15 mg/kg orally divided twice daily (narrow therapeutic 12-hour trough level monitoring mandatory: target trough 5 - 15 ng/mL).",
     "Hypersensitivity to tacrolimus or polyoxyl 60 hydrogenated castor oil (IV formulation).",
     "Black Box: Increased susceptibility to serious opportunistic infections and lymphomas; nephrotoxicity (afferent arteriolar vasoconstriction); neurotoxicity (tremor, seizures, posterior reversible encephalopathy syndrome PRES); new-onset post-transplant diabetes mellitus (PTDM - 20%); hyperkalemia; hypertension.",
     "Fine tremor (50%), elevated serum creatinine / nephrotoxicity, hypertension, hyperglycemia / diabetes, headache, hyperkalemia, hypomagnesemia, diarrhea.",
     "Strong CYP3A4 and P-gp inhibitors (ketoconazole, voriconazole, diltiazem, erythromycin massive level increases - reduce tacrolimus by 75%); strong inducers (rifampin, phenytoin, St. John's wort cause graft rejection); cyclosporine (synergistic nephrotoxicity - avoid combination).",
     "Category C. Extensively managed in pregnant transplant recipients under strict trough monitoring."),
    ("Cyclosporine", "100 mg", "Oral Capsule / IV", "3002", "L04AD01", "Calcineurin Inhibitor", ["Neoral", "Sandimmune", "Gengraf"],
     "Kidney, liver, and heart transplant rejection prophylaxis; severe rheumatoid arthritis; severe psoriasis; nephrotic syndrome.",
     "Neoral microemulsion 2.5 mg/kg to 7.5 mg/kg orally divided twice daily (narrow therapeutic 12h trough monitoring mandatory: target 100-300 ng/mL).",
     "Uncontrolled hypertension; renal dysfunction; cutaneous malignancies in psoriasis.",
     "Black Box: Nephrotoxicity and chronic progressive interstitial fibrosis; severe hypertension; opportunistic infections and lymphomas; gingival hyperplasia and hirsutism.",
     "Renal impairment, hypertension, hirsutism/hypertrichosis (45%), gingival hyperplasia (15%), tremor, hyperlipidemia, hyperkalemia.",
     "Extensive CYP3A4 and P-gp interactions (statins cause severe rhabdomyolysis, diltiazem, ketoconazole, grapefruit juice increase levels), NSAIDs.",
     "Category C. Compatible in pregnant transplant recipients under therapeutic drug monitoring."),
    ("Sirolimus", "1 mg", "Oral Tablet / Solution", "225658", "L04AA10", "mTOR (FKBP12-mTOR) Inhibitor", ["Rapamune"],
     "Prophylaxis of kidney transplant rejection (non-calcineurin inhibitor regimen), lymphangioleiomyomatosis (LAM).",
     "2 mg to 5 mg orally once daily consistently with or without food (target trough 4 - 12 ng/mL; half-life 60 hours).",
     "Hypersensitivity to sirolimus.",
     "Black Box: Liver and lung transplantation (excess mortality/graft loss); impaired wound healing and dehiscence (avoid in early post-op); hyperlipidemia/hypertriglyceridemia (50%); interstitial pneumonitis; proteinuria.",
     "Hypertriglyceridemia, hypercholesterolemia, peripheral edema, hypertension, mouth ulcers/stomatitis, thrombocytopenia, anemia, impaired wound healing.",
     "Strong CYP3A4/P-gp inhibitors/inducers, cyclosporine (increases sirolimus exposure - take sirolimus 4h after cyclosporine).",
     "Category C. Discontinue during pregnancy."),
    ("Everolimus", "0.75 mg", "Oral Tablet", "256943", "L04AA18", "mTOR Inhibitor (Rapamycin Derivative)", ["Zortress", "Afinitor"],
     "Prophylaxis of organ rejection in kidney and liver transplantation; advanced renal cell carcinoma; subependymal giant cell astrocytoma (SEGA).",
     "0.75 mg orally twice daily combined with cyclosporine/tacrolimus (target trough level 3 - 8 ng/mL).",
     "Hypersensitivity to everolimus, sirolimus, or rapamycin derivatives.",
     "Black Box: Non-infectious pneumonitis; severe stomatitis; delayed wound healing; graft thrombosis in heart/kidney transplantation; nephrotoxicity when combined with standard-dose cyclosporine.",
     "Mouth ulcers / stomatitis (44%), hyperlipidemia, anemia, hypertension, peripheral edema, proteinuria.",
     "Strong CYP3A4 inhibitors (ketoconazole increases AUC 15-fold), strong inducers (rifampin decreases AUC 60%), cyclosporine (increases everolimus levels).",
     "Category D. Embryo-fetal toxicity in animal studies."),
    ("Sulfasalazine", "500 mg", "Oral Tablet (EC)", "10214", "A07EC01", "Aminosalicylate DMARD & Anti-Inflammatory", ["Azulfidine", "Salazopyrin"],
     "Rheumatoid arthritis, ulcerative colitis induction and maintenance.",
     "Ulcerative colitis: 1 g orally 3 to 4 times daily; Rheumatoid arthritis: 500 mg twice daily, titrate to 2 g/day (co-prescribe Folic Acid 1 mg daily).",
     "Sulfa or salicylate allergy; intestinal or urinary obstruction; porphyria.",
     "Severe cutaneous reactions (SJS/TEN/DRESS syndrome); agranulocytosis / aplastic anemia; reversible oligospermia/male infertility (60%); orange-yellow skin/urine discoloration.",
     "Nausea, dyspepsia, headache, abdominal discomfort, reversible male oligospermia, orange urine/skin.",
     "Digoxin (reduces digoxin bioavailability), folic acid (inhibits folic acid absorption), iron supplements.",
     "Category B. Safe in pregnancy and lactation with mandatory supplemental folic acid."),
    ("Tofacitinib", "5 mg", "Oral Tablet", "1359133", "L04AF01", "Janus Kinase (JAK1 / JAK3) Inhibitor", ["Xeljanz", "Xeljanz XR"],
     "Moderate to severe active rheumatoid arthritis, psoriatic arthritis, ulcerative colitis, ankylosing spondylitis refractory to TNF blockers.",
     "5 mg orally twice daily (or 11 mg once daily XR; reduce to 5 mg once daily in moderate renal/hepatic impairment or with CYP3A4 inhibitors).",
     "Severe hepatic impairment; active serious systemic infections.",
     "Black Box: Increased risk of serious infections (tuberculosis, fungal, viral reactivation herpes zoster); major adverse cardiovascular events (MACE: MI, stroke); malignancies (lymphomas, lung cancer); thrombosis (deep vein thrombosis and pulmonary embolism); gastrointestinal perforations.",
     "Upper respiratory tract infection, nasopharyngitis, headache, diarrhea, elevated cholesterol/transaminases, herpes zoster reactivation.",
     "Strong CYP3A4 inhibitors (ketoconazole - reduce to 5 mg once daily), strong inducers (rifampin reduces response), biologic DMARDs (contraindicated due to profound immunosuppression).",
     "Category C. Discontinue prior to planned pregnancy."),
    ("Baricitinib", "2 mg", "Oral Tablet", "2044816", "L04AF02", "Selective JAK1 and JAK2 Inhibitor", ["Olumiant"],
     "Moderate to severe rheumatoid arthritis refractory to TNF inhibitors; severe alopecia areata; hospitalized COVID-19 with oxygen requirement.",
     "2 mg orally once daily (or 4 mg once daily for COVID-19/alopecia areata; reduce in renal decline).",
     "Severe renal impairment (eGFR <30 mL/min); severe hepatic impairment; active tuberculosis.",
     "Black Box: Serious infections, mortality, malignancy, MACE cardiovascular events, and thromboembolism; screen for latent TB and viral hepatitis prior to initiation.",
     "Upper respiratory tract infections, hypercholesterolemia, elevated ALT/AST, herpes zoster.",
     "Strong OAT3 inhibitors (probenecid decreases baricitinib clearance - cut baricitinib dose by 50%).",
     "Category C.")
]

# Domain 10: Psychiatric, Neurological & CNS Agents (50)
CAT_10_PSYCH: List[Tuple] = [
    ("Fluoxetine", "20 mg", "Oral Capsule", "4493", "N06AB03", "Selective Serotonin Reuptake Inhibitor (SSRI)", ["Prozac", "Flunil", "Sarafem"],
     "Major depressive disorder, obsessive-compulsive disorder (OCD), bulimia nervosa, panic disorder, premenstrual dysphoric disorder.",
     "20 mg orally once daily in the morning; may titrate up to max 60-80 mg/day.",
     "Concurrent MAO inhibitors (requires 5-week washout after stopping fluoxetine before starting MAOI due to 16-day active norfluoxetine half-life); pimozide; thioridazine.",
     "Black Box: Increased risk of suicidal thoughts and behaviors in children, adolescents, and young adults (<=24 years); Serotonin Syndrome; long half-life (active metabolite persists for weeks); QT prolongation; hyponatremia/SIADH.",
     "Nausea, insomnia, anxiety, anorexia, sexual dysfunction (anorgasmia/decreased libido 30%), fine tremor, diaphoresis, diarrhea.",
     "Potent CYP2D6 inhibitor: dramatically elevates tricyclics, beta-blockers (metoprolol), antiarrhythmics, tamoxifen (blocks metabolic activation to endoxifen); serotonergic agents.",
     "Category C. Late 3rd trimester exposure associated with persistent pulmonary hypertension of the newborn (PPHN) and neonatal behavioral syndrome."),
    ("Sertraline", "50 mg", "Oral Tablet", "36437", "N06AB06", "Selective Serotonin Reuptake Inhibitor (SSRI)", ["Zoloft", "Daxid", "Serta"],
     "Major depressive disorder, panic disorder, post-traumatic stress disorder (PTSD), social anxiety disorder, OCD, PMDD.",
     "50 mg orally once daily in the morning or evening; titrate by 25-50 mg increments to max 200 mg/day.",
     "Concurrent MAO inhibitors (requires 14-day washout); pimozide; disulfiram (with liquid concentrate containing alcohol).",
     "Black Box: Suicidality in children and young adults; Serotonin Syndrome; upper gastrointestinal bleeding risk when combined with NSAIDs.",
     "Diarrhea (most frequent GI side effect among SSRIs - 20%), nausea, insomnia, dizziness, somnolence, sexual dysfunction.",
     "MAO inhibitors, linezolid, triptans, NSAIDs/aspirin (increased bleeding), mild CYP2D6 inhibitor.",
     "Category C. First-line preferred antidepressant during pregnancy and breastfeeding (lowest breast milk excretion)."),
    ("Escitalopram", "10 mg", "Oral Tablet", "321988", "N06AB10", "Pure S-Enantiomer SSRI", ["Lexapro", "Cipralex", "Nexito"],
     "Major depressive disorder and generalized anxiety disorder (GAD).",
     "10 mg orally once daily in the morning or evening; may increase to max 20 mg/day.",
     "Concurrent MAOI, pimozide, hypersensitivity to citalopram or escitalopram.",
     "Black Box: Suicidality in children/young adults; dose-dependent QT interval prolongation; Serotonin Syndrome.",
     "Nausea, insomnia, ejaculation disorder, somnolence, increased sweating, fatigue.",
     "MAOIs, QT-prolonging drugs, serotonergic agents, aspirin/NSAIDs.",
     "Category C."),
    ("Citalopram", "20 mg", "Oral Tablet", "2556", "N06AB04", "Racemic SSRI", ["Celexa", "Citalec", "Celica"],
     "Major depressive disorder.",
     "20 mg orally once daily in the morning; max 40 mg/day (max 20 mg/day in age >60 years, poor CYP2C19 metabolizers, or with cimetidine due to QT prolongation).",
     "Concurrent MAO inhibitors, pimozide, congenital long QT syndrome.",
     "Black Box: Suicidality; dose-dependent QT interval prolongation and Torsades de Pointes (FDA warning capped dose at 40 mg/day; 20 mg in elderly).",
     "Nausea, dry mouth, somnolence, insomnia, diaphoresis, sexual dysfunction, QT prolongation.",
     "MAOIs, QT-prolonging drugs (amiodarone, moxifloxacin), CYP2C19 inhibitors (cimetidine, omeprazole increase citalopram levels).",
     "Category C."),
    ("Paroxetine", "20 mg", "Oral Tablet / CR", "32937", "N06AB05", "Potent SSRI (Highest Anticholinergic Activity)", ["Paxil", "Paxil CR", "Pexep"],
     "Major depressive disorder, OCD, panic disorder, social anxiety disorder, PTSD, generalized anxiety disorder, vasomotor menopausal symptoms.",
     "20 mg orally once daily in the morning with food; may increase to max 50-60 mg/day (CR: 12.5-62.5 mg/day).",
     "Concurrent MAOIs, thioridazine, pimozide, pregnancy.",
     "Black Box: Suicidality; severe withdrawal / discontinuation syndrome (electric shock sensations, vivid nightmares, nausea due to short 21h half-life); highest anticholinergic and weight gain among SSRIs; cardiac congenital malformations (ventricular septal defects).",
     "Somnolence, sexual dysfunction (highest rate among SSRIs - 50%), dry mouth, constipation, weight gain, asthenia.",
     "Potent CYP2D6 inhibitor: blocks tamoxifen activation, massively elevates tricyclics, metoprolol, and atomoxetine.",
     "Category D. Congenital cardiac malformations (VSD/ASD) in 1st trimester. Avoid in pregnancy."),
    ("Fluvoxamine", "50 mg", "Oral Tablet", "42354", "N06AB08", "SSRI & Sigma-1 Receptor Agonist", ["Luvox", "Luvox CR"],
     "Obsessive-compulsive disorder (OCD) and social anxiety disorder.",
     "50 mg orally once daily at bedtime; titrate by 50 mg increments to max 300 mg/day (divided doses >100 mg).",
     "Concurrent MAOIs, tizanidine, ramelteon, alosetron, pimozide, thioridazine.",
     "Black Box: Suicidality; extremely potent CYP1A2 and CYP2C19 inhibition (causing severe toxicities with co-prescribed substrates).",
     "Nausea (very common - 40%), somnolence, insomnia, asthenia, dry mouth, dyspepsia, tremor.",
     "Contraindicated with tizanidine (massive hypotension) and ramelteon; massively elevates theophylline, clozapine, warfarin, and duloxetine.",
     "Category C."),
    ("Duloxetine", "60 mg", "Oral Capsule", "284634", "N06AX21", "Serotonin-Norepinephrine Reuptake Inhibitor (SNRI)", ["Cymbalta", "Duzela", "Symbal"],
     "Major depressive disorder, generalized anxiety disorder, diabetic peripheral neuropathic pain, fibromyalgia, chronic musculoskeletal pain.",
     "30 mg to 60 mg orally once daily with or without food; max 120 mg/day.",
     "Uncontrolled narrow-angle glaucoma; concurrent MAOIs; severe hepatic impairment or heavy alcohol use; end-stage renal disease (CrCl <30 mL/min).",
     "Black Box: Suicidality in youth; hepatotoxicity (avoid in chronic liver disease or heavy alcohol use); orthostatic hypotension/syncope; severe discontinuation syndrome upon sudden missed dose.",
     "Nausea (most common - 25%), dry mouth, somnolence, constipation, decreased appetite, hyperhidrosis, erectile dysfunction.",
     "Potent CYP1A2 inhibitors (fluvoxamine, ciprofloxacin contraindicated - massive duloxetine elevation), CYP2D6 substrates (moderate 2D6 inhibitor), serotonergic drugs.",
     "Category C. Discontinue gradually."),
    ("Venlafaxine", "75 mg", "Oral Capsule (XR)", "39786", "N06AX16", "Serotonin-Norepinephrine Reuptake Inhibitor", ["Effexor", "Effexor XR", "Venlor"],
     "Major depressive disorder, generalized anxiety disorder, social anxiety disorder, panic disorder.",
     "75 mg orally once daily with food; titrate to max 225 mg/day (XR).",
     "Concurrent MAOIs (requires 14-day washout).",
     "Black Box: Suicidality; dose-dependent sustained diastolic hypertension (at doses >150 mg/day due to noradrenergic tone); severe withdrawal/discontinuation syndrome.",
     "Nausea, dizziness, dry mouth, sweating, insomnia, elevated blood pressure, sexual dysfunction.",
     "MAOIs, serotonergic drugs, CYP2D6 and CYP3A4 inhibitors.",
     "Category C."),
    ("Desvenlafaxine", "50 mg", "Oral Tablet (ER)", "744863", "N06AX23", "Active Major Metabolite of Venlafaxine", ["Pristiq"],
     "Major depressive disorder.",
     "50 mg orally once daily swallowed whole with or without food (doses up to 400 mg show no added efficacy but higher adverse effects).",
     "Concurrent MAO inhibitors.",
     "Black Box: Suicidality; sustained hypertension; discontinuation syndrome; hyponatremia/SIADH.",
     "Nausea, dry mouth, hyperhidrosis, dizziness, insomnia, constipation, somnolence.",
     "MAOIs, serotonergic drugs, NSAIDs/anticoagulants (bleeding risk).",
     "Category C."),
    ("Bupropion", "150 mg", "Oral Tablet (XL)", "42347", "N06AX12", "Norepinephrine-Dopamine Reuptake Inhibitor (NDRI)", ["Wellbutrin XL", "Zyban", "Bupron"],
     "Major depressive disorder, seasonal affective disorder, smoking cessation aid (Zyban).",
     "150 mg orally once daily in the morning (XL); may increase to 300 mg once daily (max 450 mg/day; avoid taking at bedtime).",
     "Seizure disorders; current or prior diagnosis of bulimia or anorexia nervosa; abrupt discontinuation of alcohol or sedatives; concurrent MAOIs.",
     "Black Box: Suicidality; dose-dependent seizure risk (0.4% at <=450 mg/day, spikes sharply above 450 mg or with eating disorders); neuropsychiatric reactions in smoking cessation; hypertension (no sexual dysfunction, no weight gain).",
     "Insomnia (very common), dry mouth, agitation, headache, nausea, tachycardia, weight loss, tremor.",
     "Potent CYP2D6 inhibitor (elevates metoprolol, flecainide, tricyclics); MAOIs (hypertensive crisis); drugs lowering seizure threshold (tramadol, antipsychotics).",
     "Category C. Antidepressant of choice when avoiding sexual dysfunction or weight gain is desired."),
    ("Mirtazapine", "15 mg", "Oral Tablet / ODT", "15996", "N06AX11", "Noradrenergic and Specific Serotonergic Antidepressant (NaSSA)", ["Remeron", "Remeron SolTab", "Mirnite"],
     "Major depressive disorder (especially with comorbid severe insomnia and marked weight loss / anorexia).",
     "15 mg orally once daily at bedtime; titrate to 30-45 mg/day (lower doses of 7.5-15 mg are MORE sedating due to H1 affinity; higher doses increase noradrenergic wakefulness).",
     "Concurrent MAO inhibitors.",
     "Black Box: Suicidality; profound somnolence; marked increase in appetite and significant weight gain (8-15 kg); agranulocytosis / severe neutropenia (rare - monitor fever/sore throat).",
     "Somnolence (54%), increased appetite (17%), marked weight gain (12%), dry mouth, constipation, dizziness, elevated cholesterol/triglycerides.",
     "MAOIs, CNS depressants, alcohol (synergistic sedation), strong CYP3A4 inducers (phenytoin, carbamazepine halve mirtazapine levels).",
     "Category C. Favored in elderly with depression, severe anorexia, and insomnia."),
    ("Trazodone", "50 mg", "Oral Tablet", "10737", "N06AX05", "Serotonin Antagonist and Reuptake Inhibitor (SARI)", ["Desyrel", "Oleptro", "Trazonil"],
     "Major depressive disorder; off-label low-dose therapy for major insomnia (25-100 mg at bedtime).",
     "Depression: 150 mg to 300 mg/day divided; Insomnia (off-label): 25 mg to 100 mg orally at bedtime.",
     "Concurrent MAO inhibitors.",
     "Black Box: Suicidality; priapism (painful prolonged penile erection requiring emergency surgical intervention/aspiration); orthostatic hypotension and syncope (strong alpha-1 adrenergic blockade); cardiac arrhythmias.",
     "Profound sedation / somnolence, dizziness, orthostatic hypotension, dry mouth, blurred vision, headache, nausea.",
     "MAOIs, CNS depressants, antihypertensives (severe additive hypotension), strong CYP3A4 inhibitors (ketoconazole, erythromycin double trazodone levels).",
     "Category C. Emergency priapism requires immediate intracavernosal phenylephrine injection."),
    ("Vortioxetine", "10 mg", "Oral Tablet", "1441865", "N06AX26", "Multimodal Serotonergic Antidepressant (SSRI + 5-HT Modulator)", ["Trintellix", "Brintellix"],
     "Major depressive disorder in adults (demonstrated cognitive benefit in processing speed).",
     "10 mg orally once daily with or without food; may titrate to 20 mg once daily.",
     "Concurrent MAO inhibitors, linezolid, methylene blue.",
     "Black Box: Suicidality; Serotonin Syndrome; bleeding risk with antiplatelets/NSAIDs.",
     "Nausea (dose-dependent - 30%), vomiting, constipation, dizziness, flatulence, sexual dysfunction (low rate).",
     "CYP2D6 inhibitors (bupropion, fluoxetine - reduce vortioxetine dose by 50%), strong CYP inducers (rifampin), MAOIs.",
     "Category C."),
    ("Amitriptyline", "25 mg", "Oral Tablet", "704", "N06AA09", "Tertiary Amine Tricyclic Antidepressant (TCA)", ["Elavil", "Tryptomer"],
     "Major depression, neuropathic pain, chronic migraine prophylaxis, fibromyalgia, tension headache.",
     "25 mg to 50 mg orally at bedtime; titrate to 100-150 mg/day (max 300 mg/day for inpatients).",
     "Concurrent MAOIs; acute recovery phase following myocardial infarction; severe cardiac conduction blocks.",
     "Black Box: Suicidality; fatal cardiac arrhythmias in overdose (wide QRS complex, sodium channel blockade, ventricular tachycardia, torsades); severe anticholinergic delirium and urinary retention in elderly (Beers Criteria Avoid).",
     "Sedation (strong H1 blockade), dry mouth, blurred vision, urinary retention, constipation, weight gain, orthostatic hypotension, tachycardia.",
     "MAOIs (fatal hyperpyrexia), anticholinergics, CYP2D6 inhibitors, antiarrhythmics, tramadol.",
     "Category C. Antidote for cardiac toxicity in overdose is IV Sodium Bicarbonate (narrows QRS)."),
    ("Nortriptyline", "25 mg", "Oral Capsule", "7531", "N06AA10", "Secondary Amine TCA (Active Metabolite of Amitriptyline)", ["Pamelor", "Aventyl"],
     "Major depressive disorder, neuropathic pain, chronic tension headache, post-herpetic neuralgia.",
     "25 mg orally 3 to 4 times daily (or 50-100 mg at bedtime; therapeutic plasma window 50 - 150 ng/mL; less sedating and lower orthostatic risk than amitriptyline).",
     "Concurrent MAOIs; acute post-MI phase.",
     "Black Box: Suicidality; narrow therapeutic window (doses above 150 ng/mL lose efficacy and increase cardiac arrhythmias); anticholinergic toxicity.",
     "Dry mouth, sedation, blurred vision, constipation, urinary retention, tachycardia.",
     "MAOIs, CYP2D6 inhibitors (fluoxetine, quinidine), sympathomimetics.",
     "Category C."),
    ("Clomipramine", "25 mg", "Oral Capsule", "2599", "N06AA04", "Potent Serotonergic Tricyclic Antidepressant", ["Anafranil", "Clofranil"],
     "Obsessive-compulsive disorder (OCD - gold standard TCA efficacy) and cataplexy associated with narcolepsy.",
     "25 mg orally daily at bedtime, titrate to 100-250 mg/day (max 250 mg/day).",
     "Concurrent MAOIs; acute post-MI.",
     "Black Box: Suicidality; highest seizure risk among TCAs (0.5% at <=250 mg/day, spikes above 250 mg); cardiac arrhythmias.",
     "Dry mouth, somnolence, constipation, dizziness, tremor, excessive sweating, sexual dysfunction, weight gain.",
     "MAOIs (fatal serotonin toxicity), CYP2D6 inhibitors, anticholinergics.",
     "Category C."),
    ("Lithium Carbonate", "300 mg", "Oral Tablet / Capsule", "6448", "N05AN01", "Mood Stabilizer (Inositol Monophosphatase Inhibitor)", ["Eskalith", "Lithobid", "Licab"],
     "Manic episodes and maintenance therapy for Bipolar I Disorder (reduces suicide risk in bipolar disorder).",
     "300 mg orally 2 to 3 times daily (titrate strictly to narrow therapeutic trough serum level 0.6 - 1.2 mEq/L for acute mania; 0.6 - 0.8 mEq/L for maintenance).",
     "Severe renal disease, severe cardiovascular disease, severe dehydration, sodium depletion, concurrent thiazide diuretics.",
     "Black Box: Lithium toxicity occurs near therapeutic levels (toxicity signs: coarse tremor, ataxia, confusion, seizures, coma); narrow therapeutic index; nephrogenic diabetes insipidus (polyuria/polydipsia); chronic tubulointerstitial nephritis; hypothyroidism; hyperparathyroidism.",
     "Fine hand tremor, polyuria, polydipsia, weight gain, hypothyroidism, goiter, nausea, cognitive dulling, acne.",
     "Thiazide diuretics (dramatically reduce lithium renal clearance - increases levels by 40% - severe toxicity), NSAIDs (reduce renal clearance), ACE inhibitors/ARBs.",
     "Category D. Ebstein's anomaly (congenital cardiac tricuspid valve downward displacement) with 1st trimester exposure; neonatal hypotonia (floppy infant syndrome)."),
    ("Valproic Acid / Divalproex", "500 mg", "Oral Tablet (ER) / IV", "358272", "N03AG01", "Broad-Spectrum Anticonvulsant & Mood Stabilizer", ["Depakote", "Depakene", "Epilim", "Valparin"],
     "Complex partial seizures, absence seizures, bipolar mania, migraine headache prophylaxis.",
     "10 mg/kg to 15 mg/kg/day orally; titrate to therapeutic trough serum concentration 50 - 100 mcg/mL (max 60 mg/kg/day).",
     "Hepatic disease or significant hepatic impairment; urea cycle disorders; mitochondrial disorders caused by POLG mutations; pregnancy for migraine prophylaxis.",
     "Black Box: Fatal hepatic failure (highest in children <2 years); life-threatening acute pancreatitis; major congenital malformations (neural tube defects: spina bifida 10%); severe hyperammonemic encephalopathy in urea cycle disorders.",
     "Weight gain, transient alopecia (hair loss), fine tremor, thrombocytopenia, nausea, vomiting, hyperammonemia, somnolence.",
     "Carbapenem antibiotics (meropenem, imipenem cause 90% rapid loss of valproate levels - avoid combination); lamotrigine (valproate inhibits glucuronidation - doubles lamotrigine half-life - severe SJS risk).",
     "Category D / Category X for migraine. Highest teratogenic risk among antiepileptics (10% neural tube defects and decreased childhood IQ)."),
    ("Levetiracetam", "500 mg", "Oral Tablet / IV", "39097", "N03AX14", "SV2A Synaptic Vesicle Glycoprotein Ligand", ["Keppra", "Levipil", "Keppra XR"],
     "Partial onset seizures, myoclonic seizures in juvenile myoclonic epilepsy, primary generalized tonic-clonic seizures.",
     "500 mg orally or IV twice daily; titrate every 2 weeks by 500 mg BID to max 1,500 mg twice daily (3,000 mg/day).",
     "Hypersensitivity to levetiracetam.",
     "Behavioral and psychiatric adverse reactions (irritability, aggression, depression, psychosis, suicidal ideation - 13%); somnolence and fatigue.",
     "Somnolence, asthenia, dizziness, behavioral agitation/hostility, infection, nasopharyngitis.",
     "Does not induce or inhibit hepatic CYP enzymes (very clean pharmacokinetic interaction profile).",
     "Category C. Favored first-line antiepileptic in pregnancy due to low major congenital malformation rates."),
    ("Lamotrigine", "100 mg", "Oral Tablet", "28439", "N03AX09", "Voltage-Gated Sodium Channel Anticonvulsant", ["Lamictal", "Lamitor", "Lamictal XR"],
     "Epilepsy (partial seizures, primary generalized tonic-clonic), Bipolar I Disorder maintenance (delays depressive episodes).",
     "Standard titration: 25 mg daily for weeks 1-2, 50 mg daily for weeks 3-4, then 100 mg daily, maintenance 200 mg daily (slow titration mandatory).",
     "Known hypersensitivity to lamotrigine.",
     "Black Box: Severe cutaneous adverse reactions including toxic epidermal necrolysis (TEN) and Stevens-Johnson syndrome (SJS) (rate 0.8% in pediatrics; 0.3% in adults; risk increased by fast titration or valproate co-therapy); aseptic meningitis.",
     "Dizziness, headache, diplopia, ataxia, nausea, benign skin rash, somnolence.",
     "Valproate (inhibits glucuronidation - doubles lamotrigine levels - cut initial dose by 50%); carbamazepine/phenytoin (inducers - halve lamotrigine levels); estrogen oral contraceptives (halve lamotrigine levels).",
     "Category C. Low malformation rate; pregnancy clearance increases 2-3 fold requiring therapeutic drug monitoring and dose escalation."),
    ("Carbamazepine", "200 mg", "Oral Tablet", "2002", "N03AF01", "Iminostilbene Voltage-Gated Sodium Channel Blocker", ["Tegretol", "Tegretol-XR", "Mazetol"],
     "Partial seizures with complex symptomatology, generalized tonic-clonic seizures, trigeminal neuralgia (first-line drug of choice), bipolar disorder.",
     "200 mg orally twice daily, titrate to therapeutic trough level 4 - 12 mcg/mL (max 1,200 mg/day; auto-induces its own metabolism).",
     "Bone marrow depression; concurrent MAOIs; HLA-B*1502 positive genotype (in Asian ancestry); hypersensitivity.",
     "Black Box: Fatal dermatologic reactions (SJS/TEN in HLA-B*1502 allele carriers); aplastic anemia and agranulocytosis (monitor baseline and periodic CBC); auto-induction of CYP3A4.",
     "Dizziness, ataxia, somnolence, nausea, vomiting, hyponatremia (SIADH-like effect), leukopenia, diplopia.",
     "Extremely potent CYP1A2, 2C9, 2C19, 3A4 inducer: lowers warfarin, oral contraceptives, DOACs, statins; erythromycin, fluconazole double carbamazepine.",
     "Category D. Neural tube defects and craniofacial anomalies. HLA-B*1502 screening mandatory in Asian patients."),
    ("Oxcarbazepine", "300 mg", "Oral Tablet", "32624", "N03AF02", "10-Keto Voltage-Gated Sodium Channel Blocker", ["Trileptal", "Oxetol"],
     "Partial seizures in adults and children >=2 years.",
     "300 mg orally twice daily; titrate weekly to 600-1,200 mg twice daily (max 2,400 mg/day).",
     "Hypersensitivity to oxcarbazepine or carbamazepine (25-30% cross-reactivity).",
     "Clinically significant hyponatremia (serum sodium <125 mEq/L in 2.5-5% - higher rate than carbamazepine); SJS/TEN (screen HLA-B*1502).",
     "Somnolence, dizziness, diplopia, ataxia, nausea, vomiting, hyponatremia (headache, confusion, seizures), tremor.",
     "Oral contraceptives (induces CYP3A4 - reduces contraceptive efficacy), phenytoin (increases phenytoin levels by 40%), alcohol.",
     "Category C."),
    ("Topiramate", "50 mg", "Oral Tablet / Sprinkle", "38404", "N03AX11", "Sulfamate-Substituted Monosaccharide Anticonvulsant", ["Topamax", "Trokendi XR", "Topamac"],
     "Epilepsy (partial onset, generalized tonic-clonic, Lennox-Gastaut), migraine headache prophylaxis in adults.",
     "Epilepsy: 100 mg to 200 mg orally twice daily; Migraine: 25 mg to 50 mg twice daily (slow weekly titration).",
     "Hypersensitivity; metabolic acidosis with concurrent metformin.",
     "Cognitive impairment ('Dopamax': word-finding difficulty, slowed processing, psychomotor slowing); non-anion gap metabolic acidosis (carbonic anhydrase inhibition); oligohidrosis and hyperthermia in children; acute secondary angle-closure glaucoma and acute myopia; nephrolithiasis (kidney stones).",
     "Paresthesias (pins/needles in extremities - 50%), anorexia / weight loss, cognitive dulling, somnolence, dizziness, taste perversion (carbonated beverages taste flat).",
     "Carbonic anhydrase inhibitors (acetazolamide, zonisamide increase nephrolithiasis risk), oral contraceptives (reduces estrogen efficacy at >200 mg/day), valproate (hyperammonemia).",
     "Category D. High risk of oral clefts (cleft lip/cleft palate) with 1st trimester exposure."),
    ("Gabapentin", "300 mg", "Oral Capsule / Tablet", "25480", "N02BF01", "Voltage-Gated Calcium Channel Alpha-2-Delta Ligand", ["Neurontin", "Gabalep", "Gabapin"],
     "Postherpetic neuralgia (PHN), adjunctive treatment of partial onset seizures; off-label neuropathic pain, diabetic neuropathy, restless legs syndrome.",
     "300 mg orally on day 1, 300 mg BID on day 2, 300 mg TID on day 3; titrate to 900-1,800 mg/day (max 3,600 mg/day; dose reduce strictly in renal decline).",
     "Hypersensitivity to gabapentin.",
     "Severe respiratory depression when combined with opioids or in COPD/elderly; somnolence and dizziness; misuse/abuse liability; peripheral edema; suicidal behavior.",
     "Somnolence (21%), dizziness (28%), ataxia, fatigue, peripheral edema, weight gain, nystagmus.",
     "Opioids (morphine, oxycodone increase gabapentin levels and synergistic respiratory depression), antacids (aluminum/magnesium reduce bioavailability by 20%).",
     "Category C. 100% renally excreted unchanged."),
    ("Pregabalin", "75 mg", "Oral Capsule", "187832", "N02BF02", "High-Affinity Alpha-2-Delta Calcium Channel Ligand", ["Lyrica", "Pregeb", "Maxgalin"],
     "Neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, spinal cord injury neuropathic pain, partial seizures.",
     "75 mg orally twice daily (or 50 mg TID); titrate to 150 mg twice daily (max 600 mg/day; reduce dose in renal impairment).",
     "Hypersensitivity to pregabalin.",
     "Schedule V controlled substance (euphoria, abuse potential); life-threatening respiratory depression with CNS depressants/opioids; angioedema; peripheral edema and weight gain.",
     "Dizziness (29%), somnolence (22%), dry mouth, edema, blurred vision, weight gain, cognitive difficulty.",
     "Opioids, benzodiazepines, alcohol (severe additive sedation and fatal respiratory depression), ACE inhibitors (additive angioedema risk), thiazolidinediones.",
     "Category C. Renally eliminated unchanged."),
    ("Phenytoin", "100 mg", "Oral Capsule / IV", "8183", "N03AB02", "Hydantoin Sodium Channel Blocker Anticonvulsant", ["Dilantin", "Epanutin"],
     "Tonic-clonic (grand mal) and psychomotor (temporal lobe) seizures; status epilepticus (IV loading).",
     "100 mg orally 3 times daily (titrate to narrow therapeutic level 10 - 20 mcg/mL total, or 1-2 mcg/mL free; non-linear Michaelis-Menten kinetics).",
     "Sinus bradycardia, 2nd/3rd degree AV block, sinoatrial block (IV Dilantin); HLA-B*1502 positive.",
     "Black Box: Cardiovascular collapse, severe hypotension, and arrhythmias with IV infusion rate >50 mg/min (fosphenytoin prodrug preferred); Purple Glove Syndrome (limb ischemia with IV extravasation); SJS/TEN; gingival hyperplasia.",
     "Gingival hyperplasia (20-40%), hirsutism, coarsening of facial features, peripheral neuropathy, cerebellar ataxia, nystagmus, osteomalacia.",
     "Potent CYP inducer; highly protein-bound (displaced by valproate, aspirin, uremia); narrow non-linear elimination.",
     "Category D. Fetal hydantoin syndrome (cleft lip/palate, microcephaly, hypoplastic nails, developmental delay)."),
    ("Quetiapine", "100 mg", "Oral Tablet", "35640", "N05AH04", "Atypical Antipsychotic (D2 & 5-HT2A Antagonist)", ["Seroquel", "Seroquel XR", "Qutipin"],
     "Schizophrenia, Bipolar I Disorder mania and depression, major depressive disorder adjunct.",
     "25 mg to 300 mg orally twice daily (or 300-800 mg once daily at bedtime XR).",
     "Hypersensitivity.",
     "Black Box: Increased mortality in elderly patients with dementia-related psychosis; suicidal thoughts in young adults; severe sedation; metabolic syndrome (weight gain, dyslipidemia, diabetes); cataracts.",
     "Somnolence (sedation frequent - 50%), dizziness, dry mouth, weight gain, constipation, orthostatic hypotension, dyspepsia.",
     "CYP3A4 inhibitors (ketoconazole increases quetiapine 5-fold), inducers (phenytoin decreases level by 80%), antihypertensives.",
     "Category C."),
    ("Olanzapine", "10 mg", "Oral Tablet / IM", "28374", "N05AH03", "Thienobenzodiazepine Atypical Antipsychotic", ["Zyprexa", "Oleanz"],
     "Schizophrenia, Bipolar I mania, mixed episodes, acute agitation.", "5 mg to 20 mg orally once daily in the evening.",
     "Hypersensitivity.",
     "Black Box: Increased mortality in elderly with dementia; highest metabolic risk (extreme weight gain 10-20 kg, severe hypertriglyceridemia, DKA); post-injection delirium sedation syndrome with depot pamoate.",
     "Weight gain (massive), somnolence, increased appetite, dizziness, orthostatic hypotension, dry mouth, constipation, hyperprolactinemia.",
     "Fluoxetine, carbamazepine, fluvoxamine (doubles olanzapine levels), smoking (CYP1A2 induction reduces olanzapine levels by 40%).",
     "Category C."),
    ("Risperidone", "2 mg", "Oral Tablet / ODT / Depot IM", "35636", "N05AX08", "Benzisoxazole Atypical Antipsychotic (High D2 Affinity)", ["Risperdal", "Sizodon"],
     "Schizophrenia, Bipolar I acute mania, irritability associated with autistic disorder in children.",
     "1 mg to 6 mg orally daily in 1 or 2 divided doses (doses >6 mg/day increase extrapyramidal symptoms to typical antipsychotic levels).",
     "Hypersensitivity.",
     "Black Box: Dementia-related psychosis mortality; highest hyperprolactinemia risk among atypicals (galactorrhea, amenorrhea, gynecomastia); extrapyramidal symptoms; tardive dyskinesia.",
     "Hyperprolactinemia (up to 70%), EPS/parkinsonism at higher doses, somnolence, weight gain, fatigue, dizziness.",
     "CYP2D6 inhibitors (fluoxetine, paroxetine double active moiety), carbamazepine, levodopa.",
     "Category C."),
    ("Aripiprazole", "10 mg", "Oral Tablet / IM", "89905", "N05AX12", "Dopamine D2 Partial Agonist & 5-HT1A Agonist", ["Abilify", "Arip MT"],
     "Schizophrenia, Bipolar I mania/mixed, MDD adjunctive therapy, Tourette's disorder, autism irritability.",
     "10 mg to 30 mg orally once daily (lowest weight gain and metabolic disturbance among atypicals).",
     "Hypersensitivity.",
     "Black Box: Dementia mortality; suicidality; impulse control disorders (pathological gambling, binge eating, compulsive shopping); akathisia.",
     "Akathisia (motor restlessness - 15-20%), insomnia, headache, nausea, vomiting, lightheadedness.",
     "CYP2D6 and CYP3A4 inhibitors (fluoxetine, clarithromycin - reduce aripiprazole dose by 50%), inducers.",
     "Category C."),
    ("Clozapine", "100 mg", "Oral Tablet / ODT", "2626", "N05AH02", "Dibenzodiazepine Atypical Antipsychotic (Gold Standard Refractory)", ["Clozaril", "Sizopin", "Fazaclo"],
     "Treatment-resistant schizophrenia (failed >=2 antipsychotics) and reduction in recurrent suicidal behavior in schizophrenia/schizoaffective disorder.",
     "12.5 mg to 25 mg on day 1; titrate slowly to 300-450 mg/day in divided doses (max 900 mg/day; strict Absolute Neutrophil Count ANC monitoring mandatory).",
     "History of clozapine-induced severe neutropenia or agranulocytosis; uncontrolled epilepsy; paralytic ileus; severe bone marrow depression.",
     "Black Box: Severe life-threatening agranulocytosis / neutropenia (mandatory REMS program; stop if ANC <1,000/microL); fatal myocarditis / cardiomyopathy (monitor troponin/echocardiogram); fatal paralytic ileus / severe gastrointestinal hypomotility; dose-dependent seizures (3-5% at >600 mg/day); orthostatic hypotension and syncope.",
     "Severe hypersalivation / drooling (sialorrhea - 30-50%), sedation, marked weight gain, tachycardia, constipation (potentially fatal), dizziness.",
     "Bone marrow suppressants (carbamazepine contraindicated), strong CYP1A2 inhibitors (fluvoxamine, ciprofloxacin massive 5-fold clozapine increase), smoking (CYP1A2 induction halves clozapine).",
     "Category B. The only antipsychotic with proven superiority in refractory schizophrenia and suicide reduction."),
    ("Haloperidol", "5 mg", "Oral / IV / Depot IM", "5093", "N05AD01", "High-Potency Typical Butyrophenone Antipsychotic", ["Haldol", "Serenace"],
     "Schizophrenia, acute psychotic agitation, Tourette's motor and vocal tics, severe delirium in ICU.",
     "0.5 mg to 5 mg orally 2 to 3 times daily (or IM/IV 2-10 mg for acute agitation; Haldol Decanoate IM monthly).",
     "Severe toxic CNS depression, comatose states, Parkinson's disease, dementia with Lewy bodies.",
     "Black Box: Dementia mortality; high rate of Extrapyramidal Symptoms (acute dystonia 10-20%, pseudoparkinsonism, akathisia); Tardive Dyskinesia; Neuroleptic Malignant Syndrome (NMS: hyperthermia, lead-pipe rigidity, autonomic instability, elevated CK); QT prolongation/torsades with IV route.",
     "Extrapyramidal symptoms (acute muscle spasms, tremor, rigidity), akathisia, tardive dyskinesia, hyperprolactinemia, drowsiness.",
     "CYP2D6 and CYP3A4 inhibitors, QT-prolonging agents, anticholinergics, levodopa (antagonizes dopamine).",
     "Category C. Treatment for acute dystonia: IV Benztropine 1-2 mg or Diphenhydramine 50 mg."),
    ("Lorazepam", "1 mg", "Oral Tablet / IV / IM", "6470", "N05BA06", "Intermediate-Acting High-Potency Benzodiazepine (GABA-A Allosteric Modulator)", ["Ativan", "Trapex", "Lopez"],
     "Acute anxiety disorders, panic attacks, status epilepticus (IV first-line drug of choice), acute alcohol withdrawal delirium, preoperative sedation.",
     "Anxiety: 1 mg to 3 mg orally 2 to 3 times daily; Status epilepticus: 4 mg IV slow bolus over 2 minutes (may repeat once after 5-10 min).",
     "Severe respiratory insufficiency, myasthenia gravis, acute narrow-angle glaucoma, severe hepatic insufficiency.",
     "Black Box: Concomitant use with opioids may result in profound sedation, respiratory depression, coma, and death; physical dependence and severe withdrawal syndrome (seizures, psychosis upon abrupt cessation); anterograde amnesia; Beers Criteria Avoid in elderly (falls/fractures/delirium).",
     "Sedation (very common), dizziness, muscle weakness, unsteadiness / ataxia, confusion, amnesia.",
     "Opioids, alcohol, other CNS depressants (fatal respiratory arrest), probenecid (doubles lorazepam half-life via glucuronidation inhibition).",
     "Category D. Antidote for benzodiazepine overdose: IV Flumazenil (caution: can precipitate acute withdrawal seizures in chronic users)."),
    ("Clonazepam", "0.5 mg", "Oral Tablet / ODT", "2598", "N03AE01", "High-Potency Long-Acting Benzodiazepine", ["Klonopin", "Rivotril", "Clonafit"],
     "Panic disorder with or without agoraphobia, Lennox-Gastaut syndrome, akinetic and myoclonic seizures.",
     "Panic disorder: 0.25 mg orally twice daily, titrate to 1 mg/day (max 4 mg/day); Seizures: 0.5 mg TID up to 20 mg/day.",
     "Severe liver disease, acute narrow-angle glaucoma.",
     "Black Box: Opioid co-use (fatal respiratory depression); high abuse and physical dependence; severe withdrawal seizures upon abrupt taper.",
     "Somnolence, ataxia, dizziness, fatigue, behavioral changes, upper respiratory tract infection.",
     "Opioids, alcohol, CYP3A4 inhibitors (fluconazole, clarithromycin).",
     "Category D."),
    ("Diazepam", "5 mg", "Oral Tablet / IV / Rectal Gel", "3322", "N05BA01", "Long-Acting Benzodiazepine (Active Metabolite Desmethyldiazepam)", ["Valium", "Diastat", "Calmpose"],
     "Anxiety disorders, acute ethanol withdrawal (delirium tremens), skeletal muscle spasm, status epilepticus, acute febrile seizure breakthrough (rectal gel).",
     "Anxiety: 2 mg to 10 mg orally 2 to 4 times daily; Acute alcohol withdrawal: 10 mg 3-4 times daily during first 24 hours.",
     "Myasthenia gravis, severe respiratory insufficiency, severe hepatic insufficiency, sleep apnea.",
     "Black Box: Fatal respiratory depression with opioids; physical dependence; prolonged active metabolites (half-life up to 100 hours in elderly/cirrhosis).",
     "Drowsiness, fatigue, muscle weakness, ataxia, confusion, headache.",
     "Opioids, alcohol, strong CYP2C19/3A4 inhibitors (omeprazole, cimetidine prolong clearance).",
     "Category D."),
    ("Alprazolam", "0.5 mg", "Oral Tablet / XR", "596", "N05BA12", "Short-Acting High-Potency Triazolobenzodiazepine", ["Xanax", "Xanax XR", "Restyl", "Alprax"],
     "Generalized anxiety disorder and panic disorder with or without agoraphobia.",
     "0.25 mg to 0.5 mg orally 3 times daily; titrate to target (max 4 mg/day for anxiety; up to 10 mg/day for panic disorder).",
     "Concurrent ketoconazole or itraconazole (contraindicated); acute narrow-angle glaucoma.",
     "Black Box: Fatal opioid respiratory depression; highest addiction and dependence liability among benzodiazepines; severe rebound anxiety and breakthrough withdrawal between doses.",
     "Sedation, drowsiness, fatigue, ataxia, memory impairment, irritability.",
     "Strong CYP3A4 inhibitors (ketoconazole, itraconazole contraindicated; clarithromycin, erythromycin, fluvoxamine double levels).",
     "Category D."),
    ("Donepezil", "10 mg", "Oral Tablet / ODT", "135447", "N06DA02", "Reversible Acetylcholinesterase Inhibitor", ["Aricept", "Donecept"],
     "Treatment of mild, moderate, and severe dementia of the Alzheimer's type.",
     "5 mg orally once daily at bedtime; after 4-6 weeks increase to 10 mg once daily (may increase to 23 mg daily in moderate-to-severe disease).",
     "Hypersensitivity to donepezil or piperidine derivatives.",
     "Vagotonic effects / severe bradycardia and syncope (sick sinus syndrome, heart block); gastrointestinal bleeding and peptic ulceration (increases gastric acid); weight loss; nightmares/insomnia.",
     "Nausea (very common), diarrhea, insomnia, muscle cramps, fatigue, anorexia, vomiting, bradycardia.",
     "Anticholinergic drugs (benztropine, oxybutynin - direct pharmacodynamic antagonism), NSAIDs (increased GI ulcer bleeding), beta-blockers (severe bradycardia).",
     "Category C. Cholinergic crisis antidote: Atropine."),
    ("Memantine", "10 mg", "Oral Tablet / ER", "6719", "N06DX01", "Uncompetitive NMDA Receptor Antagonist", ["Namenda", "Namenda XR", "Admenta"],
     "Moderate to severe dementia of the Alzheimer's type (monotherapy or combined with donepezil).",
     "5 mg orally once daily, titrate weekly by 5 mg up to 10 mg twice daily (or 28 mg once daily XR; reduce to 5 mg BID in CrCl <30 mL/min).",
     "Hypersensitivity to memantine.", "Conditions that raise urine pH (carbonic anhydrase inhibitors, sodium bicarbonate) reduce renal clearance and increase memantine levels.",
     "Dizziness, headache, confusion, constipation, hypertension, somnolence.",
     "Carbonic anhydrase inhibitors, sodium bicarbonate, other NMDA antagonists (amantadine, ketamine, dextromethorphan).",
     "Category B. Neuroprotective against glutamate excitotoxicity."),
    ("Levodopa and Carbidopa", "100-25 mg", "Oral Tablet / CR", "217011", "N04BA02", "Dopamine Precursor + Peripheral DOPA Decarboxylase Inhibitor", ["Sinemet", "Sinemet CR", "Tidomet", "Syndopa"],
     "Idiopathic Parkinson's disease, post-encephalitic parkinsonism, and symptomatic parkinsonism.",
     "Starting dose: 1 tablet Sinemet 25/100 mg orally three times daily with meals (carbidopa >=70-100 mg/day required to inhibit peripheral decarboxylation and prevent severe nausea/vomiting).",
     "Non-selective MAO inhibitors within 14 days (hypertensive crisis); narrow-angle glaucoma; undiagnosed skin lesions (may activate malignant melanoma).",
     "Motor fluctuations and peak-dose dyskinesias (chorea/dystonia in 50-80% after 5-10 years therapy - 'wearing off' and 'on-off' phenomena); visual hallucinations and psychosis; impulse control disorders; sudden sleep attacks.",
     "Nausea, orthostatic hypotension, dyskinesias, vivid dreams/hallucinations, somnolence, dry mouth, dark sweat/urine discoloration (harmless).",
     "Non-selective MAOIs (hypertensive crisis), dopamine antagonists (haloperidol, metoclopramide block therapeutic effect), high-protein meals and iron supplements (compete with amino acid gut absorption - take 30 min before meals).",
     "Category C. Gold standard therapy for Parkinson's disease motor symptoms."),
    ("Baclofen", "10 mg", "Oral Tablet / Intrathecal", "1292", "M03BX01", "GABA-B Receptor Agonist Skeletal Muscle Relaxant", ["Lioresal", "Baclosign"],
     "Severe chronic spasticity resulting from multiple sclerosis, spinal cord lesions/injuries, or cerebral palsy.",
     "5 mg orally three times daily, titrate by 5 mg TID every 3 days up to 40-80 mg/day in divided doses.",
     "Hypersensitivity to baclofen.",
     "Black Box: Abrupt withdrawal of intrathecal or oral baclofen can precipitate high fever, altered mental status, exaggerated rebound spasticity, muscle rigidity, rhabdomyolysis, multi-organ failure, and death (mandatory slow taper); severe CNS sedation.",
     "Sedation / drowsiness (very common - 60%), dizziness, muscle weakness, confusion, fatigue, nausea, urinary frequency.",
     "CNS depressants, alcohol, opioids (synergistic sedation and respiratory depression), antihypertensives.",
     "Category C. Renally eliminated (reduce dose in kidney impairment)."),
    ("Tizanidine", "4 mg", "Oral Tablet / Capsule", "38407", "M03BX02", "Central Alpha-2 Adrenergic Agonist Muscle Relaxant", ["Zanaflex", "Sirdalud"],
     "Management of spasticity associated with multiple sclerosis, spinal cord injury, or acute painful musculoskeletal conditions.",
     "2 mg to 4 mg orally every 6 to 8 hours as needed (max 36 mg/day in 3 divided doses).",
     "Concomitant use of potent CYP1A2 inhibitors (ciprofloxacin, fluvoxamine strictly contraindicated); severe hepatic impairment.",
     "Profound hypotension, severe bradycardia, and syncope (due to alpha-2 agonism); severe sedation; hepatotoxicity (monitor ALT/AST baseline and periodic).",
     "Somnolence (48%), dry mouth (49%), dizziness, hypotension, asthenia, elevated transaminases.",
     "Contraindicated with ciprofloxacin (increases tizanidine AUC 10-fold and Cmax 7-fold) and fluvoxamine (AUC 33-fold increase - profound hypotension/coma); oral contraceptives.",
     "Category C.")
]

# Domain 11: Antifungals & Antivirals (35)
CAT_11_INFECTIOUS: List[Tuple] = [
    ("Fluconazole", "150 mg", "Oral Tablet / IV", "4452", "J02AC01", "Triazole Antifungal (14-alpha Demethylase Inhibitor)", ["Diflucan", "Forcan", "Zocon"],
     "Vaginal candidiasis (150 mg single dose), oropharyngeal/esophageal candidiasis, cryptococcal meningitis maintenance, systemic candidemia.",
     "100 mg to 400 mg orally or IV once daily (vaginal yeast infection: 150 mg single oral dose).",
     "Concomitant terfenadine, cisapride, astemizole, pimozide, quinidine; hypersensitivity to azoles.",
     "QT interval prolongation and torsades de pointes; hepatotoxicity (monitor LFTs); severe cutaneous reactions (SJS/TEN); high single doses in pregnancy cause congenital craniofacial anomalies.",
     "Headache, nausea, abdominal pain, diarrhea, elevated liver transaminases, rash.",
     "Potent CYP2C9 and CYP2C19 inhibitor, moderate CYP3A4 inhibitor: doubles warfarin INR, doubles phenytoin levels, increases sulfonylureas, increases statin levels.",
     "Category D for high-dose systemic use (craniosynostosis/cleft palate); Category C for single 150 mg dose (avoid repeated doses in 1st trimester)."),
    ("Itraconazole", "100 mg", "Oral Capsule", "6058", "J02AC02", "Lipophilic Triazole Antifungal", ["Sporanox", "Canditral", "Itrasys"],
     "Blastomycosis, histoplasmosis, aspergillosis, onychomycosis of toenails/fingernails.",
     "200 mg orally once or twice daily WITH A FULL MEAL and acidic beverage (capsules require gastric acid).",
     "Ventricular dysfunction / congestive heart failure; co-administration with strong CYP3A4 substrates (statins, pimozide, midazolam); pregnancy for onychomycosis.",
     "Black Box: Congestive heart failure (negative inotropic effect); potent CYP3A4 inhibition; severe hepatotoxicity.",
     "Nausea, diarrhea, abdominal pain, elevated transaminases, peripheral edema, hypokalemia, rash.",
     "Potent CYP3A4 and P-gp inhibitor: massive elevation of statins, DOACs, tacrolimus, cyclosporine; antacids reduce absorption.",
     "Category C. Contraindicated for onychomycosis in pregnancy."),
    ("Voriconazole", "200 mg", "Oral Tablet / IV", "121243", "J02AC03", "Second-Generation Broad-Spectrum Triazole", ["Vfend", "Voritek"],
     "Invasive aspergillosis (first-line drug of choice), severe Scedosporium and Fusarium infections, esophageal candidiasis.",
     "400 mg (or 6 mg/kg IV) every 12h for 2 doses, then 200 mg orally twice daily on an empty stomach (trough target 1.5 - 5.5 mcg/mL).",
     "Co-administration with CYP3A4 substrates (pimozide, rifampin, carbamazepine, St. John's wort).",
     "Visual disturbances (photopsia, altered color perception, blurred vision in 30% within 30 min of dose); visual hallucinations; severe photosensitivity squamous cell skin cancer; hepatotoxicity; QT prolongation.",
     "Visual disturbances (altered light perception 30%), hallucinations, skin photosensitivity, elevated LFTs, rash, headache.",
     "Extensive CYP2C19, 2C9, 3A4 interactions: rifampin/carbamazepine contraindication; increases immunosuppressants (tacrolimus/sirolimus).",
     "Category D. Embryotoxic and teratogenic in animal models."),
    ("Terbinafine", "250 mg", "Oral Tablet / Topical Cream", "37801", "D01BA02", "Allylamine Squalene Epoxidase Inhibitor", ["Lamisil", "Sebifin", "Tyza"],
     "Onychomycosis of the toenail or fingernail due to dermatophytes (tinea unguium); tinea capitis, tinea pedis (athlete's foot), tinea corporis.",
     "250 mg orally once daily with or without food (fingernails: 6 weeks; toenails: 12 weeks; baseline and periodic LFT monitoring mandatory).",
     "Chronic or active hepatic disease; known hypersensitivity to terbinafine.",
     "Black Box/FDA Warning: Severe drug-induced hepatotoxicity leading to liver failure, transplant, or death; taste and smell disturbances (ageusia/anosmia - sometimes permanent); depressive symptoms; severe neutropenia.",
     "Headache, diarrhea, dyspepsia, abdominal pain, elevated LFTs, taste disturbance (dysgeusia), rash.",
     "Potent CYP2D6 inhibitor: doubles or triples blood levels of tricyclic antidepressants, beta-blockers, and dextromethorphan; rifampin halves terbinafine levels.",
     "Category B. Defer oral onychomycosis treatment until after pregnancy."),
    ("Amphotericin B Liposomal", "50 mg", "IV Infusion", "205932", "J02AA01", "Polyene Antifungal (Membrane Ergosterol Disruptor)", ["AmBisome"],
     "Severe invasive fungal infections (mucormycosis, cryptococcal meningitis, systemic candidiasis, invasive aspergillosis, visceral leishmaniasis).",
     "3 mg/kg to 5 mg/kg IV once daily infused over 2 hours (up to 10 mg/kg/day for mucormycosis; liposomal lipid vehicle reduces nephrotoxicity).",
     "Known hypersensitivity to amphotericin B.",
     "Dose-dependent nephrotoxicity (distal renal tubular acidosis, acute tubular necrosis, severe hypokalemia, hypomagnesemia); infusion-related reactions (fever, rigors, chills, hypotension - premedicate with acetaminophen/diphenhydramine/hydrocortisone).",
     "Infusion-related fever/rigors ('shake and bake'), hypokalemia (severe), hypomagnesemia, elevated creatinine/BUN, anemia.",
     "Aminoglycosides, cisplatin, cyclosporine, vancomycin (synergistic severe nephrotoxicity), digitalis.",
     "Category B. Antifungal of choice for life-threatening systemic mycoses in pregnancy."),
    ("Caspofungin", "50 mg", "IV Infusion", "282464", "J02AX04", "Echinocandin Antifungal (1,3-beta-D-Glucan Synthesis Inhibitor)", ["Cancidas"],
     "Invasive candidiasis, candidemia, esophageal candidiasis, invasive aspergillosis refractory to other therapies, empirical therapy in febrile neutropenia.",
     "70 mg IV loading dose on Day 1, then 50 mg IV once daily infused over 1 hour (reduce to 35 mg daily in moderate hepatic impairment Child-Pugh 7-9).",
     "Known hypersensitivity to caspofungin.",
     "Histamine-mediated symptoms (rash, facial swelling, pruritus, sensation of warmth, bronchospasm); elevated liver transaminases when combined with cyclosporine.",
     "Fever, chills, phlebitis, elevated AST/ALT, hypokalemia, nausea, diarrhea, rash.",
     "Cyclosporine (increases caspofungin AUC by 35% - monitor liver enzymes), tacrolimus (caspofungin reduces tacrolimus levels by 26%), rifampin/efavirenz (inducers require 70 mg daily).",
     "Category C. Embryofetal toxicity in animal studies."),
    ("Acyclovir", "400 mg", "Oral / IV / Topical", "296", "J05AB01", "Guanosine Nucleoside Analog Antiviral (DNA Polymerase Inhibitor)", ["Zovirax", "Acivir"],
     "Herpes simplex virus (HSV-1 and HSV-2 genital herpes, mucocutaneous herpes), herpes simplex encephalitis (IV), varicella-zoster (chickenpox/shingles).",
     "400 mg orally 3 to 5 times daily (or 800 mg 5 times daily for shingles for 7-10 days; IV 10 mg/kg q8h infused over 1 hour with IV hydration).",
     "Hypersensitivity to acyclovir or valacyclovir.",
     "Renal tubular precipitation of acyclovir crystals and acute renal failure with rapid IV injection (slow 1-hour infusion and aggressive hydration mandatory); neurotoxicity (confusion, hallucinations, myoclonus in renal impairment).",
     "Nausea, vomiting, diarrhea, headache, acute kidney injury / crystal nephropathy, phlebitis at IV site.",
     "Nephrotoxic drugs, probenecid (decreases acyclovir renal clearance).",
     "Category B. Drug of choice for maternal and neonatal HSV infections in pregnancy."),
    ("Valacyclovir", "500 mg", "Oral Tablet", "35826", "J05AB11", "L-Valyl Ester Prodrug of Acyclovir (3-5x Bioavailability)", ["Valtrex", "Valcivir"],
     "Herpes zoster (shingles), genital herpes treatment and suppression, herpes labialis (cold sores), chickenpox.",
     "Shingles: 1,000 mg orally 3 times daily for 7 days; Cold sores: 2,000 mg twice daily for 1 day; Genital suppression: 500-1,000 mg once daily.",
     "Hypersensitivity to valacyclovir or acyclovir.",
     "Thrombotic Thrombocytopenic Purpura / Hemolytic Uremic Syndrome (TTP/HUS) in high-dose therapy in immunocompromised patients; acute renal failure.",
     "Headache, nausea, abdominal pain, dizziness, elevated transaminases.",
     "Probenecid, cimetidine, nephrotoxins.",
     "Category B. First-line oral suppressive therapy for recurrent genital herpes in late pregnancy to prevent neonatal transmission."),
    ("Oseltamivir", "75 mg", "Oral Capsule", "247895", "J05AH02", "Neuraminidase Inhibitor (Influenza A and B)", ["Tamiflu", "Antiflu"],
     "Treatment and prophylaxis of acute uncomplicated influenza A and B (must initiate within 48 hours of symptom onset).",
     "Treatment: 75 mg orally twice daily for 5 days (with food to reduce GI upset); Prophylaxis: 75 mg once daily for 10-14 days.",
     "Known hypersensitivity to oseltamivir.",
     "Neuropsychiatric events (delirium, abnormal behavior, self-injury in pediatric patients with influenza); not a substitute for annual influenza vaccination.",
     "Nausea (10%), vomiting (9%), headache, abdominal pain, insomnia.",
     "Live attenuated influenza vaccine (LAIV / FluMist - avoid antiviral within 48h before or 2 weeks after live vaccine).",
     "Category C / CDC Preferred. Recommended for all pregnant women with suspected or confirmed influenza regardless of trimester."),
    ("Nirmatrelvir and Ritonavir", "300-100 mg", "Oral Dose Pack", "2587842", "J05AE30", "SARS-CoV-2 Main Protease (Mpro/3CLpro) Inhibitor + CYP3A4 Booster", ["Paxlovid"],
     "Treatment of mild-to-moderate COVID-19 in adults at high risk for progression to severe disease, hospitalization, or death (initiate within 5 days of symptom onset).",
     "300 mg nirmatrelvir (two 150 mg tablets) with 100 mg ritonavir (one 100 mg tablet) taken together orally twice daily for 5 days (reduce to 150/100 mg BID in eGFR 30-60 mL/min).",
     "Severe renal impairment (eGFR <30 mL/min); severe hepatic impairment; concurrent use of drugs highly dependent on CYP3A4 for clearance (statins, amiodarone, rivaroxaban, carbamazepine, St. John's wort).",
     "Massive life-threatening drug-drug interaction profile (ritonavir is an extremely potent CYP3A4 and P-gp inhibitor); COVID-19 rebound phenomenon (mild recurrence of symptoms/positivity 2-8 days after completion); dysgeusia.",
     "Dysgeusia (metallic/bitter taste - 6%), diarrhea, hypertension, myalgia, headache.",
     "Contraindicated with: rivaroxaban, simvastatin, lovastatin, amiodarone, dronedarone, carbamazepine, rifampin, midazolam, sildenafil (for PAH). Must review all patient medications prior to prescribing.",
     "EUA authorization; beneficial risk-benefit in high-risk pregnant patients with COVID-19.")
]

def get_psych_immuno_cns_records() -> List[Dict[str, Any]]:
    """Assemble all records from domains 9, 10, and 11."""
    records = []
    
    def process_group(group: List[Tuple]):
        for name, st, form, rxcui, atc, cls, aliases, ind, dos, con, war, adv, inter, prg in group:
            records.append({
                "name": name, "strength": st, "form": form, "rxcui": rxcui, "atc": atc,
                "class": cls, "aliases": aliases, "ind": ind, "dos": dos, "con": con,
                "war": war, "adv": adv, "int": inter, "prg": prg
            })

    process_group(CAT_9_IMMUNO)
    process_group(CAT_10_PSYCH)
    process_group(CAT_11_INFECTIOUS)
    return records

if __name__ == "__main__":
    r = get_psych_immuno_cns_records()
    print(f"Domains 9-11 total records: {len(r)}")
