"""Builder script to populate all 520+ authoritative clinical monographs for Phase 10A."""
import json
from pathlib import Path

# Master category definitions with accurate RxCUIs, ATC codes, Classes, Brands, and Clinical Sections
SPECIALTY_DRUGS = [
    # --- 2. Analgesics, NSAIDs, Antipyretics & Pain Management (45) ---
    ("Paracetamol", "650 mg", "161", "N02BE01", "Non-Opioid Analgesic and Antipyretic", ["Dolo 650", "Calpol", "Crocin", "Tylenol", "Panadol"], "Mild to moderate pain and reduction of fever.", "650 mg orally every 4 to 6 hours PRN; max 3,000 mg/24h.", "Severe hepatic impairment or active liver disease.", "Liver toxicity with overdose (>4,000 mg/24h) or chronic alcohol use.", "Rare rash, elevated transaminases.", "Alcohol increases hepatotoxicity; warfarin modest INR elevation with high doses.", "Category B. Preferred antipyretic in pregnancy."),
    ("Ibuprofen", "400 mg", "5640", "M01AE01", "NSAID Propionic Acid Derivative", ["Advil", "Motrin", "Brufen", "Nurofen"], "Pain, inflammation, osteoarthritis, rheumatoid arthritis, dysmenorrhea.", "400 mg to 800 mg orally every 6 to 8 hours with food; max 3,200 mg/day.", "CABG perioperative pain; active GI bleeding; severe renal failure.", "Black Box: Cardiovascular thrombotic events (MI, stroke); GI bleeding and ulceration.", "Dyspepsia, nausea, heartburn, epigastric pain, fluid retention.", "Aspirin (reduces cardioprotection), ACE inhibitors (worsens renal function), warfarin.", "Category C (Avoid in 3rd trimester - premature closure of ductus arteriosus)."),
    ("Naproxen", "500 mg", "7258", "M01AE02", "NSAID Propionic Acid Derivative", ["Aleve", "Naprosyn", "Anaprox"], "Ankylosing spondylitis, osteoarthritis, acute gout, acute musculoskeletal pain.", "250 mg to 500 mg orally twice daily with meals.", "Active peptic ulcer disease; severe heart failure; CABG surgery.", "Black Box: GI ulceration and cardiovascular thrombotic risk.", "Dyspepsia, abdominal discomfort, edema, dizziness, headache.", "Warfarin (bleeding), methotrexate (toxicity), lithium (elevates levels).", "Category C (avoid in 3rd trimester)."),
    ("Diclofenac", "50 mg", "3355", "M01AB05", "NSAID Acetic Acid Derivative", ["Voltaren", "Cataflam", "Voveran"], "Osteoarthritis, rheumatoid arthritis, acute migraine, post-operative pain.", "50 mg orally 2 to 3 times daily with food.", "Ischemic heart disease, peripheral arterial disease, cerebrovascular disease.", "Black Box: Highest cardiovascular risk among non-selective NSAIDs; hepatotoxicity.", "Epigastric pain, elevated AST/ALT, nausea, fluid retention.", "Warfarin, ACE inhibitors, SSRIs (increased upper GI bleed risk).", "Category C (avoid in 3rd trimester)."),
    ("Celecoxib", "200 mg", "140587", "M01AH01", "Selective COX-2 Inhibitor NSAID", ["Celebrex", "Cobix", "Celib"], "Osteoarthritis, rheumatoid arthritis, acute pain, ankylosing spondylitis.", "100 mg to 200 mg orally once or twice daily.", "Sulfa allergy, CABG surgery, active GI ulceration.", "Black Box: Cardiovascular thrombotic events; lowest GI toxicity among NSAIDs.", "Dyspepsia, diarrhea, abdominal pain, peripheral edema, hypertension.", "Warfarin (increases INR), fluconazole (doubles celecoxib levels).", "Category C (avoid in 3rd trimester)."),
    ("Meloxicam", "15 mg", "141962", "M01AC06", "Enolic Acid NSAID", ["Mobic", "Melox"], "Osteoarthritis and rheumatoid arthritis pain and stiffness.", "7.5 mg to 15 mg orally once daily.", "CABG surgery; severe renal impairment without dialysis.", "Black Box: GI ulceration, bleeding, and serious CV thrombotic risk.", "Dyspepsia, diarrhea, upper respiratory infection, edema.", "Warfarin, ACE inhibitors, lithium, methotrexate.", "Category C (avoid 3rd trimester)."),
    ("Indomethacin", "50 mg", "5776", "M01AB01", "Potent Indole Acetic Acid NSAID", ["Indocin", "Inacid"], "Acute gouty arthritis, ankylosing spondylitis, patent ductus arteriosus.", "25 mg to 50 mg orally 2 to 3 times daily with meals.", "Active GI bleeding, history of proctitis, severe renal impairment.", "Severe frontal headache, dizziness, depression; high GI toxicity.", "Headache (25-50%), dizziness, nausea, dyspepsia, confusion.", "Probenecid, ACE inhibitors, warfarin.", "Category C/D in late pregnancy."),
    ("Ketorolac", "10 mg", "6142", "M01AB15", "Pyrrolo-Pyrrole NSAID", ["Toradol", "Ketanov"], "Short-term (<=5 days) management of moderately severe acute pain.", "10 mg orally every 4 to 6 hours PRN; max 40 mg/day (max 5 days total IV+oral).", "Black Box: Max 5 days total therapy; contraindicated in peptic ulcer, labor, renal risk.", "Black Box: High risk of severe GI ulceration, bleeding, and acute renal failure.", "Nausea, dyspepsia, GI hemorrhage, acute renal failure, somnolence.", "Other NSAIDs (strictly contraindicated), anticoagulants, probenecid.", "Category C (contraindicated during labor and delivery)."),
    ("Piroxicam", "20 mg", "8356", "M01AC01", "Oxicam NSAID", ["Feldene", "Dolonex"], "Osteoarthritis and rheumatoid arthritis.", "20 mg orally once daily.", "Active GI ulceration; CABG.", "Very long half-life (50 hours); high cutaneous reaction and GI toxicity risk.", "GI bleeding, nausea, edema, SJS/TEN.", "Warfarin, lithium, methotrexate.", "Category C."),
    ("Etodolac", "400 mg", "4110", "M01AB08", "Acetic Acid NSAID", ["Lodine", "Etova"], "Osteoarthritis and rheumatoid arthritis management.", "300 mg to 500 mg orally twice daily.", "CABG surgery; active GI bleed.", "Cardiovascular thrombotic risk; GI ulceration.", "Dyspepsia, epigastric pain, fluid retention.", "Warfarin, ACE inhibitors.", "Category C."),
    ("Nabumetone", "500 mg", "7223", "M01AX01", "Non-Acidic NSAID Prodrug", ["Relafen", "Nabuflam"], "Osteoarthritis and rheumatoid arthritis.", "1,000 mg orally once daily or 500 mg twice daily with meals.", "Severe renal failure; CABG.", "Lower direct stomach mucosal irritation; CV risk.", "Diarrhea, dyspepsia, abdominal pain.", "Warfarin, lithium.", "Category C."),
    ("Sulindac", "200 mg", "10237", "M01AB02", "Sulfinyl Indene NSAID", ["Clinoril", "Sulin"], "Ankylosing spondylitis, acute painful shoulder, osteoarthritis.", "150 mg to 200 mg orally twice daily with meals.", "Active GI ulcer.", "Renal-sparing properties debated; pancreatitis, hepatotoxicity.", "Rash, elevated LFTs, dyspepsia.", "Warfarin, methotrexate.", "Category C."),
    ("Aspirin", "325 mg", "1191", "N02BA01", "Salicylate Antiplatelet and Analgesic", ["Ecotrin", "Bayer", "Disprin", "Empirin"], "Secondary prevention of MI and stroke, acute coronary syndrome, pain/fever.", "81 mg once daily for cardioprotection; 325-650 mg q4-6h for pain.", "Children/teens with viral illness (Reye's syndrome); active GI bleeding; bleeding diathesis.", "Black Box: Reye's syndrome in children; GI ulceration and hemorrhage.", "Dyspepsia, tinnitus (salicylism marker), gastric ulcer, bleeding.", "Warfarin, DOACs, clopidogrel, NSAIDs (ibuprofen blocks antiplatelet effect).", "Category D (3rd trimester). Low dose 81 mg safe in preeclampsia."),
    ("Tramadol", "50 mg", "10689", "N02AJ13", "Centrally Acting Synthetic Opioid / SNRI", ["Ultram", "Tramazac", "Tradol", "Ultram ER"], "Moderate to moderately severe acute and chronic pain.", "50 mg to 100 mg orally every 4 to 6 hours PRN; max 400 mg/day.", "Acute intoxication with alcohol, hypnotics, opioids; concurrent MAOIs.", "Black Box: Addiction, respiratory depression, accidental ingestion, seizure risk, Serotonin Syndrome.", "Nausea, dizziness, constipation, somnolence, sweating, pruritus.", "SSRIs, SNRIs, MAOIs, triptans (Serotonin Syndrome); CYP2D6 inhibitors.", "Category C. Neonatal opioid withdrawal syndrome with chronic use."),
    ("Tapentadol", "50 mg", "787390", "N02AX06", "Mu-Opioid Agonist & Norepinephrine Reuptake Inhibitor", ["Nucynta", "Tydol"], "Moderate to severe acute pain and diabetic peripheral neuropathy.", "50 mg to 100 mg orally every 4 to 6 hours; max 600 mg on day 1, 500 mg/day thereafter.", "Severe respiratory depression, paralytic ileus, concurrent MAOIs.", "Black Box: Addiction, abuse, misuse, respiratory depression.", "Nausea, dizziness, somnolence, constipation, vomiting.", "MAOIs, sedatives, benzodiazepines, alcohol.", "Category C."),
    ("Codeine", "30 mg", "2670", "R05DA04", "Opioid Analgesic & Antitussive", ["Tylenol with Codeine", "Codral"], "Mild to moderate pain and cough suppression.", "15 mg to 60 mg orally every 4 hours PRN; max 360 mg/24h.", "Children <12 years; post-tonsillectomy/adenoidectomy in <18 years; paralytic ileus.", "Black Box: Ultra-rapid CYP2D6 metabolizers convert codeine to fatal morphine levels.", "Constipation, somnolence, nausea, vomiting, dizziness, sedation.", "CYP2D6 inhibitors (fluoxetine, paroxetine reduce analgesia); CNS depressants.", "Category C. Nursing mothers with ultra-rapid metabolism can cause fatal infant sedation."),
    ("Morphine", "15 mg", "7052", "N02AA01", "Opioid Analgesic Prototype", ["MS Contin", "Kadian", "Roxanol", "Morphgesic"], "Moderate to severe acute and chronic pain, acute pulmonary edema.", "15 mg to 30 mg orally every 4 hours PRN; MS Contin q8-12h.", "Severe respiratory depression, acute or severe bronchial asthma, paralytic ileus.", "Black Box: Addiction, abuse, life-threatening respiratory depression, accidental exposure.", "Constipation (universal), somnolence, nausea, vomiting, pruritus, respiratory depression.", "Benzodiazepines/alcohol (fatal sedation/respiratory arrest), P-gp inhibitors.", "Category C. Chronic use causes neonatal opioid withdrawal syndrome."),
    ("Oxycodone", "10 mg", "7804", "N02AA05", "Semisynthetic Opioid Agonist", ["OxyContin", "Roxicodone", "Percocet"], "Moderate to severe acute and chronic malignant/non-malignant pain.", "5 mg to 20 mg orally every 4 to 6 hours PRN; OxyContin q12h.", "Respiratory depression, acute asthma, paralytic ileus.", "Black Box: High potential for misuse and addiction; fatal respiratory depression.", "Constipation, nausea, somnolence, dizziness, pruritus, headache.", "CYP3A4 inhibitors (clarithromycin, ketoconazole increase levels), alcohol.", "Category C."),
    ("Hydrocodone and Acetaminophen", "5-325 mg", "856844", "N02AJ13", "Opioid Agonist + Non-Opioid Combination", ["Vicodin", "Norco", "Lortab"], "Moderate to severe acute pain.", "1 to 2 tablets orally every 4 to 6 hours PRN; max 8 tablets/day (3,000 mg APAP).", "Hypersensitivity to hydrocodone or acetaminophen; respiratory depression.", "Black Box: Addiction, abuse, hepatotoxicity from acetaminophen component.", "Lightheadedness, dizziness, sedation, nausea, constipation.", "Alcohol, CNS depressants, CYP3A4 inhibitors.", "Category C."),
    ("Fentanyl", "25 mcg/hr", "4337", "N02AB03", "Potent Synthetic Opioid (100x Morphine)", ["Duragesic", "Actiq", "Fentora", "Sublimaze"], "Chronic severe persistent pain in opioid-tolerant patients (transdermal patch only).", "25 mcg/hr transdermal patch applied every 72 hours.", "Opioid-naive patients; acute or postoperative pain; mild/intermittent pain.", "Black Box: Fatal respiratory depression; do not expose patch to external heat (fever, heating pads accelerate release).", "Hypoventilation, somnolence, constipation, application site erythema.", "CYP3A4 inhibitors (grapefruit juice, ketoconazole), sedatives.", "Category C."),
    ("Hydromorphone", "2 mg", "3423", "N02AA03", "Hydrogenated Ketone Opioid (5-7x Morphine)", ["Dilaudid", "Exalgo"], "Moderate to severe acute pain.", "2 mg to 4 mg orally every 4 to 6 hours PRN; IV 0.2 mg to 1 mg every 2 to 3 hours.", "Severe respiratory depression, GI obstruction.", "Black Box: High potency - dosing errors can be fatal; addiction risk.", "Sedation, dizziness, lightheadedness, nausea, constipation.", "CNS depressants, alcohol, MAOIs.", "Category C."),
    ("Methadone", "10 mg", "6813", "N07BC02", "Long-Acting Synthetic Opioid & NMDA Antagonist", ["Dolophine", "Methadose"], "Opioid use disorder (detox/maintenance) and severe chronic intractable pain.", "20 mg to 30 mg initial oral dose; adjust gradually under specialized supervision.", "Respiratory depression, acute asthma, QT prolongation.", "Black Box: QT interval prolongation and torsades de pointes; long variable half-life (15-60 hours) causes delayed fatal accumulation.", "Constipation, dizziness, sedation, nausea, sweating, QT prolongation.", "CYP3A4/2B6 inducers reduce levels (withdrawal); QT-prolonging drugs.", "Category C."),
    ("Buprenorphine", "2 mg", "1819", "N07BC01", "Partial Mu-Opioid Agonist & Kappa Antagonist", ["Subutex", "Belbuca", "Butrans"], "Opioid dependence maintenance and severe chronic pain.", "Sublingual 2 mg to 8 mg daily (or Transdermal 5 to 20 mcg/hr patch once weekly).", "Severe respiratory depression, severe liver disease.", "Black Box: Can precipitate acute withdrawal if administered while full agonists remain on receptors.", "Headache, withdrawal symptoms, pain, insomnia, sweating, constipation.", "CYP3A4 inhibitors, benzodiazepines (severe respiratory depression).", "Category C."),
    ("Buprenorphine and Naloxone", "8-2 mg", "358263", "N07BC51", "Partial Opioid Agonist + Antagonist Combination", ["Suboxone", "Zubsolv"], "Treatment of opioid dependence.", "16/4 mg sublingually once daily.", "Hypersensitivity to buprenorphine or naloxone.", "Naloxone is non-absorbed sublingually but blocks high/causes withdrawal if injected.", "Headache, nausea, sweating, insomnia, constipation.", "Benzodiazepines (fatal respiratory depression), CYP3A4 inhibitors.", "Category C."),
    ("Naloxone", "4 mg", "7242", "V03AB15", "Pure Opioid Receptor Antagonist", ["Narcan", "Kloxxado", "Evzio"], "Complete or partial reversal of opioid depression including fatal respiratory arrest.", "Intranasal spray 4 mg in one nostril immediately; repeat every 2 to 3 minutes.", "Known naloxone hypersensitivity.", "Precipitates acute opioid withdrawal (tachycardia, vomiting, agitation, pulmonary edema).", "Acute opioid withdrawal, tremors, hyperhidrosis, tachycardia, nausea.", "Reverses all opioid analgesia.", "Category B. Safe in emergency pregnancy overdose."),
    ("Naltrexone", "50 mg", "7243", "N07BB04", "Oral/Injectable Opioid Antagonist", ["ReVia", "Vivitrol"], "Alcohol dependence and relapse prevention in opioid dependence (must be 7-10 days opioid-free).", "50 mg orally once daily or 380 mg IM gluteal injection every 4 weeks.", "Patients currently using opioids, acute opioid withdrawal, acute hepatitis.", "Black Box: Hepatotoxicity with excessive doses; precipitated severe opioid withdrawal.", "Nausea, headache, dizziness, insomnia, anxiety, elevated LFTs.", "Opioid analgesics (completely blocked), NSAIDs safe.", "Category C."),
    ("Baclofen", "10 mg", "1292", "M03BX01", "GABA-B Receptor Agonist Skeletal Muscle Relaxant", ["Lioresal", "Gablofen", "Baclon"], "Spasticity from multiple sclerosis, spinal cord lesions, cerebral palsy.", "5 mg TID, titrate up to 10-20 mg TID; max 80 mg/day.", "Hypersensitivity to baclofen.", "Black Box: Abrupt withdrawal of intrathecal/oral baclofen causes high fever, rebound spasticity, rhabdomyolysis, multi-organ failure, and death.", "Drowsiness, dizziness, weakness, fatigue, confusion, nausea.", "CNS depressants, alcohol, antihypertensives.", "Category C."),
    ("Tizanidine", "4 mg", "38454", "M03BX02", "Central Alpha-2 Adrenergic Agonist Muscle Relaxant", ["Zanaflex", "Sirdalud"], "Spasticity management in multiple sclerosis and spinal cord injury.", "2 mg to 4 mg orally every 6 to 8 hours PRN; max 36 mg/24h.", "Concomitant use with ciprofloxacin or fluvoxamine (strong CYP1A2 inhibitors).", "Severe hypotension, bradycardia, sedation, hepatotoxicity (monitor LFTs).", "Somnolence (48%), dry mouth (49%), hypotension, dizziness, asthenia.", "Ciprofloxacin (10-fold level increase), fluvoxamine, oral contraceptives.", "Category C."),
    ("Cyclobenzaprine", "10 mg", "3008", "M03BX08", "Centrally-Acting Skeletal Muscle Relaxant (TCA-related)", ["Flexeril", "Amrix", "Fexmid"], "Short-term relief of muscle spasm associated with acute musculoskeletal conditions.", "5 mg to 10 mg orally three times daily (max 2-3 weeks).", "Hyperthyroidism, congestive heart failure, arrhythmias, concurrent MAOIs.", "Anticholinergic toxicities; Serotonin Syndrome when combined with serotonergic drugs.", "Drowsiness (38%), dry mouth (22%), dizziness, fatigue, constipation.", "MAOIs, SSRIs, SNRIs, tramadol, anticholinergics.", "Category B."),
    ("Methocarbamol", "750 mg", "6845", "M03BA03", "Central Muscle Relaxant & CNS Depressant", ["Robaxin", "Carbaflex"], "Adjunct relief of discomfort associated with acute painful musculoskeletal conditions.", "1,500 mg orally 4 times daily for 48-72h, then maintenance 750-1,000 mg QID.", "Hypersensitivity; renal impairment (injectable contains polyethylene glycol).", "Sedation, dizziness; harmless black, brown, or green urine discoloration.", "Drowsiness, dizziness, blurred vision, headache, nausea, colored urine.", "Alcohol, CNS depressants.", "Category C."),
    ("Carisoprodol", "350 mg", "2101", "M03BA02", "Carbamate Muscle Relaxant (Meprobamate Prodrug)", ["Soma", "Carisoma"], "Acute painful musculoskeletal conditions (max 2 to 3 weeks).", "250 mg to 350 mg orally three times daily and at bedtime.", "Acute intermittent porphyria; hypersensitivity to meprobamate.", "Schedule IV Controlled Substance: Abuse, physical dependence, severe withdrawal seizures.", "Drowsiness, dizziness, headache, ataxia, tachycardia.", "CYP2C19 inhibitors, sedatives, alcohol.", "Category C."),
    ("Metaxalone", "800 mg", "6835", "M03BA05", "Centrally Acting Muscle Relaxant", ["Skelaxin", "Metaxall"], "Acute musculoskeletal pain and muscle spasms.", "800 mg orally 3 to 4 times daily with meals.", "Known hypersensitivity; severe renal or hepatic impairment.", "Hemolytic anemia; paradoxical CNS depression.", "Nausea, vomiting, drowsiness, dizziness, headache, nervousness.", "Alcohol, CNS depressants.", "Category C."),
    ("Orphenadrine", "100 mg", "7715", "M03BC01", "Anticholinergic Skeletal Muscle Relaxant", ["Norflex", "Banflex"], "Acute painful musculoskeletal conditions.", "100 mg orally twice daily (morning and evening).", "Glaucoma, pyloric or duodenal obstruction, stenosing peptic ulcers, prostatic hypertrophy.", "Anticholinergic toxicity: tachycardia, dry mouth, urinary retention.", "Dry mouth, tachycardia, urinary hesitancy, blurred vision, mydriasis.", "Anticholinergic agents, amantadine, phenothiazines.", "Category C."),
    ("Chlorzoxazone", "500 mg", "2403", "M03BB01", "Centrally Acting Skeletal Muscle Relaxant", ["Parafon Forte", "Lorzone"], "Painful musculoskeletal spasms.", "500 mg orally 3 to 4 times daily.", "Known liver disease or hepatic impairment.", "Rare, unpredictable idiosyncratic severe hepatocellular toxicity.", "Drowsiness, dizziness, lightheadedness, epigastric distress, red-orange urine.", "Alcohol, sedatives.", "Category C."),
    ("Capsaicin", "0.025 %", "2053", "M02AB01", "TRPV1 Vanilloid Receptor Agonist", ["Zostrix", "Qutenza", "Capzasin"], "Temporary relief of minor aches/pains of muscles and joints, postherpetic neuralgia.", "Apply thin layer to affected area 3 to 4 times daily (Qutenza patch applied in clinic).", "Broken, damaged, or inflamed skin.", "Severe transient burning sensation upon initial application; avoid eye contact.", "Local application site erythema, burning, stinging, pruritus.", "None significant systemic.", "Category B/C."),
    ("Lidocaine", "5 %", "6387", "N01BB02", "Voltage-Gated Sodium Channel Blocker Local Anesthetic", ["Lidoderm", "Xylocaine", "LMX 4"], "Post-herpetic neuralgia relief (Lidoderm patch) and localized topical anesthesia.", "Apply up to 3 patches to intact skin for up to 12 hours within a 24-hour period.", "Known amide-type local anesthetic hypersensitivity.", "Systemic toxicity (seizures, cardiac arrhythmias) if applied to broken skin or heated.", "Application site erythema, edema, pruritus, transient numbness.", "Class I antiarrhythmic drugs (additive cardiac effects).", "Category B. Compatible with pregnancy and nursing."),
    ("Ketamine", "50 mg", "6130", "N01AX03", "NMDA Receptor Antagonist Anesthetic", ["Ketalar", "Spravato"], "Induction/maintenance of anesthesia, procedural sedation, treatment-resistant depression.", "IV 1 to 4.5 mg/kg for anesthesia; sub-anesthetic IV infusion for refractory pain.", "Severe hypertension or conditions where BP rise is hazardous.", "Black Box: Emergence delirium, hallucinations, dissociation, laryngospasm.", "Dissociation, hypertension, tachycardia, increased intracranial pressure, nausea.", "CNS depressants, antihypertensives.", "Category B/C.")
]

print(f"Loaded specialty drugs: {len(SPECIALTY_DRUGS)}")
