"""Clinical Knowledge Base: Domains 5, 6, 7, and 8 (Lipids, Coagulation, GI, Respiratory).

Contains authentic medicine monographs with US NLM RxNorm RxCUIs, ATC codes, and FDA labeling.
"""
from typing import List, Tuple

# Domain 5: Lipid-Lowering & Atherosclerosis Agents (25)
CAT_5_LIPIDS: List[Tuple] = [
    ("Atorvastatin", "10 mg", "Oral Tablet", "310798", "C10AA05", "HMG-CoA Reductase Inhibitor (Statin)", ["Lipitor", "Atorva", "Storvas"],
     "Primary hypercholesterolemia, mixed dyslipidemia, primary and secondary prevention of CV events (ACS, stroke, MI).",
     "10 mg to 80 mg orally once daily at any time of day with or without food (high-intensity statin: 40-80 mg daily).",
     "Active liver disease, unexplained persistent elevations of hepatic transaminases, pregnancy, breastfeeding.",
     "Myopathy and rhabdomyolysis (muscle pain + CPK >10x ULN + myoglobinuria leading to acute renal failure); immune-mediated necrotizing myopathy; hepatotoxicity; new-onset type 2 diabetes.",
     "Myalgia, arthralgia, diarrhea, nasopharyngitis, dyspepsia, elevated liver transaminases.",
     "Strong CYP3A4 inhibitors (clarithromycin, itraconazole, protease inhibitors increase atorvastatin exposure and rhabdomyolysis), gemfibrozil, cyclosporine.",
     "Contraindicated in pregnancy (Category X. Discontinue statin immediately if pregnancy occurs)."),
    ("Rosuvastatin", "10 mg", "Oral Tablet", "308047", "C10AA07", "Hydrophilic Statin (HMG-CoA Reductase Inhibitor)", ["Crestor", "Rosuvas", "Rozavel"],
     "Severe hypercholesterolemia, hypertriglyceridemia, slowing progression of atherosclerosis (JUPITER trial).",
     "5 mg to 20 mg orally once daily (high-intensity: 20-40 mg daily; max 20 mg in Asian ancestry due to 2-fold higher median exposure).",
     "Active liver disease, severe renal impairment (CrCl <30 mL/min not on dialysis), pregnancy.",
     "Rhabdomyolysis and renal failure; proteinuria/hematuria at 40 mg dose; higher systemic exposure in Asian ancestry (start at 5 mg).",
     "Myalgia, abdominal pain, headache, nausea, asthenia, proteinuria.",
     "Cyclosporine (increases rosuvastatin AUC 7-fold - max dose 5 mg), gemfibrozil (max 10 mg), antacids (decrease absorption by 50%).",
     "Contraindicated in pregnancy (Category X)."),
    ("Simvastatin", "20 mg", "Oral Tablet", "36567", "C10AA01", "Lipophilic Statin", ["Zocor", "Simvas"],
     "Hyperlipidemia and reduction of CV mortality.", "10 mg to 40 mg orally once daily in the evening (80 mg dose restricted due to high myopathy risk).",
     "Active liver disease, concurrent strong CYP3A4 inhibitors, pregnancy.", "Highest rhabdomyolysis risk among common statins; dose cap of 10-20 mg with amiodarone/amlodipine.",
     "Upper respiratory infection, headache, abdominal pain, myalgia, eczema.", "Strong CYP3A4 inhibitors (contraindicated), amiodarone (max 20 mg), amlodipine (max 20 mg), diltiazem (max 10 mg).",
     "Contraindicated in pregnancy."),
    ("Pravastatin", "40 mg", "Oral Tablet", "8591", "C10AA03", "Hydrophilic Statin (Non-CYP Metabolism)", ["Pravachol", "Pravator"],
     "Hyperlipidemia and primary/secondary CV prevention.", "40 mg to 80 mg orally once daily in the evening.",
     "Active liver disease, pregnancy.", "Myopathy; lowest drug interaction profile among statins (metabolized by sulfation, not CYP450).",
     "Myalgia, nausea, vomiting, diarrhea, headache, rash.", "Cyclosporine, clarithromycin.",
     "Contraindicated in pregnancy."),
    ("Lovastatin", "20 mg", "Oral Tablet", "6472", "C10AA02", "Natural Statin (Mevacor)", ["Mevacor", "Altoprev"],
     "Hypercholesterolemia and CAD prevention.", "20 mg to 80 mg orally once daily with the evening meal (food enhances absorption).",
     "Active liver disease, strong CYP3A4 inhibitors, pregnancy.", "Myopathy, rhabdomyolysis, hepatotoxicity.",
     "Abdominal pain, myalgia, flatulence, headache.", "Strong CYP3A4 inhibitors, gemfibrozil, amiodarone.",
     "Contraindicated in pregnancy."),
    ("Pitavastatin", "2 mg", "Oral Tablet", "861634", "C10AA08", "Moderate-Intensity Statin", ["Livalo", "Zypitamag"],
     "Primary hyperlipidemia and mixed dyslipidemia.", "1 mg to 4 mg orally once daily at any time of day.",
     "Active liver disease, concomitant cyclosporine.", "Myopathy, rhabdomyolysis (minimally metabolized by CYP2C9; safe with CYP3A4 drugs).",
     "Back pain, constipation, arthralgia, headache, myalgia.", "Cyclosporine (contraindicated), erythromycin, rifampin.",
     "Contraindicated in pregnancy."),
    ("Fluvastatin", "40 mg", "Oral Capsule", "41127", "C10AA04", "Synthetic Statin", ["Lescol", "Lescol XL"],
     "Hypercholesterolemia and secondary CAD prevention.", "20 mg to 80 mg orally in the evening.",
     "Active liver disease, pregnancy.", "Myopathy, elevated transaminases.",
     "Dyspepsia, abdominal pain, myalgia, headache.", "CYP2C9 inhibitors (fluconazole), gemfibrozil.",
     "Contraindicated in pregnancy."),
    ("Ezetimibe", "10 mg", "Oral Tablet", "341249", "C10AX09", "Niemann-Pick C1-Like 1 (NPC1L1) Cholesterol Absorption Inhibitor", ["Zetia", "Ezetrol", "Ezentia"],
     "Primary hyperlipidemia adjunct to statin therapy to lower LDL-C (IMPROVE-IT trial demonstrated CV event reduction).",
     "10 mg orally once daily with or without food.",
     "Concomitant statin in active liver disease or pregnancy; severe hepatic impairment.",
     "Myopathy and rhabdomyolysis when combined with statins; elevated hepatic transaminases.",
     "Upper respiratory tract infection, diarrhea, arthralgia, sinusitis, myalgia.",
     "Cyclosporine (increases ezetimibe exposure 12-fold), fibrates (cholelithiasis risk), cholestyramine (decreases absorption).",
     "Category C. Compatible when used as monotherapy if clinically necessary."),
    ("Evolocumab", "140 mg", "SC Autoinjector", "1665091", "C10AX13", "PCSK9 Monoclonal Antibody (LDL-C Lowering 60%)", ["Repatha"],
     "Heterozygous/Homozygous familial hypercholesterolemia, established ASCVD risk reduction (FOURIER trial).",
     "140 mg SC every 2 weeks or 420 mg SC once monthly.",
     "Hypersensitivity to evolocumab.", "Immunogenicity; hypersensitivity reactions (rash, urticaria); nasopharyngitis.",
     "Nasopharyngitis, upper respiratory tract infection, injection site reactions, back pain, flu-like symptoms.",
     "No pharmacokinetic drug interactions.",
     "Avoid in pregnancy."),
    ("Alirocumab", "75 mg", "SC Pen", "1659149", "C10AX14", "PCSK9 Monoclonal Antibody", ["Praluent"],
     "ASCVD risk reduction and heterozygous familial hypercholesterolemia (ODYSSEY Outcomes trial).",
     "75 mg to 150 mg SC every 2 weeks or 300 mg every 4 weeks.",
     "Hypersensitivity.", "Hypersensitivity, injection site reactions.",
     "Injection site reactions, nasopharyngitis, myalgia, influenza.", "None significant.",
     "Avoid in pregnancy."),
    ("Inclisiran", "284 mg", "SC Injection", "2587841", "C10AX16", "Small Interfering RNA (siRNA) PCSK9 Inhibitor", ["Leqvio"],
     "Primary hyperlipidemia in heterozygous familial hypercholesterolemia or ASCVD.",
     "284 mg SC initially, again at 3 months, then once every 6 months administered by healthcare professional.",
     "Hypersensitivity.", "Injection site reactions; joint pain.",
     "Injection site reaction (erythema, pain 8%), arthralgia, urinary tract infection, diarrhea.", "No CYP-mediated interactions.",
     "Discontinue during pregnancy."),
    ("Bempedoic Acid", "180 mg", "Oral Tablet", "2282570", "C10AX15", "ATP Citrate Lyase (ACL) Inhibitor", ["Nexletol", "Nexlizet"],
     "ASCVD and heterozygous familial hypercholesterolemia in statin-intolerant patients (CLEAR Outcomes trial).",
     "180 mg orally once daily with or without food.",
     "Hypersensitivity.", "Hyperuricemia and acute gout flares; tendon rupture (Achilles, rotator cuff, biceps tendon).",
     "Hyperuricemia (26%), gout attacks, muscle spasms, abdominal pain, elevated transaminases.",
     "Simvastatin (caps simvastatin at 20 mg), pravastatin (caps pravastatin at 40 mg).",
     "Discontinue in pregnancy."),
    ("Fenofibrate", "145 mg", "Oral Tablet", "4322", "C10AB05", "PPAR-alpha Agonist (Fibrate)", ["Tricor", "Lipanthyl", "Fenoglide"],
     "Severe hypertriglyceridemia (reduces pancreatitis risk) and primary hypercholesterolemia.",
     "48 mg to 145 mg orally once daily with meals.",
     "Severe renal dysfunction (eGFR <30 mL/min); active liver disease; gallbladder disease; nursing mothers.",
     "Cholelithiasis (gallstones); myopathy/rhabdomyolysis (lower risk than gemfibrozil with statins); reversible serum creatinine elevation.",
     "Abdominal pain, back pain, headache, elevated liver transaminases, elevated serum creatinine, gallstones.",
     "Warfarin (potentiates warfarin anticoagulation - reduce warfarin dose by 50%), statins, ezetimibe, bile acid resins.",
     "Category C."),
    ("Gemfibrozil", "600 mg", "Oral Tablet", "4719", "C10AB02", "Fibric Acid Derivative (Fibrate)", ["Lopid"],
     "Severe hypertriglyceridemia (Type IV and V dyslipidemia) at high risk of pancreatitis.",
     "600 mg orally twice daily 30 minutes before morning and evening meals.",
     "Concomitant statin therapy (severe rhabdomyolysis); concurrent repaglinide; gallbladder disease; severe renal disease.",
     "Severe rhabdomyolysis when combined with statins; 8-fold increase in repaglinide exposure causing fatal hypoglycemia; cholelithiasis.",
     "Dyspepsia, abdominal pain, diarrhea, nausea, fatigue, myopathy.",
     "Statins (contraindicated - severe rhabdomyolysis), repaglinide (contraindicated - severe hypoglycemia), warfarin.",
     "Category C."),
    ("Cholestyramine", "4 g", "Oral Powder", "2407", "C10AC01", "Bile Acid Sequestrant Resin", ["Questran", "Prevalite"],
     "Primary hypercholesterolemia and pruritus associated with partial biliary obstruction; bile acid diarrhea.",
     "4 g orally 1 to 2 times daily mixed with 4-6 oz of non-carbonated liquid, titrate to max 24 g/day.",
     "Complete biliary obstruction; bowel obstruction.", "Severe constipation and fecal impaction; binds and blocks absorption of almost all oral medications and fat-soluble vitamins (A, D, E, K).",
     "Constipation (severe), flatulence, nausea, abdominal bloating, fecal impaction.",
     "Binds warfarin, levothyroxine, digoxin, thiazides, fat-soluble vitamins (must give all other drugs 1h before or 4-6h after).",
     "Category B. Safe in pregnancy (not systemically absorbed)."),
    ("Colesevelam", "625 mg", "Oral Tablet / Powder", "253272", "C10AC04", "Bile Acid Sequestrant & Glycemic Lowering Agent", ["Welchol"],
     "Primary hyperlipidemia and glycemic improvement in type 2 diabetes mellitus.",
     "3.75 g daily (6 tablets once daily with a meal and liquid or 3 tablets twice daily).",
     "Serum triglycerides >500 mg/dL; history of bowel obstruction; history of hypertriglyceridemia-induced pancreatitis.",
     "Significant worsening of hypertriglyceridemia; constipation.",
     "Constipation, dyspepsia, nausea, hypertriglyceridemia.",
     "Oral contraceptives, levothyroxine, cyclosporine (separate by 4 hours).",
     "Category B. Non-absorbed; safe in pregnancy."),
    ("Colestipol", "1 g", "Oral Tablet / Granules", "2698", "C10AC02", "Bile Acid Sequestrant", ["Colestid"],
     "Primary hypercholesterolemia management.", "2 g to 16 g orally daily in divided doses.",
     "Complete biliary obstruction.", "Severe constipation; vitamin malabsorption.",
     "Constipation, abdominal discomfort, flatulence.", "Digitalis, oral anticoagulants, diuretics.",
     "Category B."),
    ("Icosapent Ethyl", "1 g", "Oral Capsule", "1306385", "C10AX06", "Highly Purified EPA Ethyl Ester (REDUCE-IT Proven)", ["Vascepa"],
     "CV event reduction in patients with elevated triglycerides (>=150 mg/dL) and established CVD or diabetes + 2 risk factors.",
     "2 g orally twice daily (4 capsules daily) with food.",
     "Severe fish or shellfish hypersensitivity.", "Increased risk of atrial fibrillation/flutter requiring hospitalization (5.3% vs 3.9%); increased bleeding risk.",
     "Atrial fibrillation, peripheral edema, constipation, musculoskeletal pain, bleeding.",
     "Anticoagulants and antiplatelets (increased bleeding risk).",
     "Category C."),
    ("Omega-3-Acid Ethyl Esters", "1 g", "Oral Capsule", "643093", "C10AX06", "EPA + DHA Omega-3 Combination", ["Lovaza", "Omtryg"],
     "Severe hypertriglyceridemia (triglycerides >=500 mg/dL).", "4 g orally daily as single dose or 2 g twice daily with food.",
     "Fish allergy.", "May increase LDL-C levels (DHA effect); atrial fibrillation; bleeding.",
     "Eructation (fish burp/taste 5%), dyspepsia, taste perversion, constipation.",
     "Anticoagulants.",
     "Category C."),
    ("Niacin", "500 mg", "Oral Tablet (ER)", "7414", "C10AD02", "Nicotinic Acid (Vitamin B3 / Lipid Lowering)", ["Niaspan"],
     "Hypertriglyceridemia and primary hyperlipidemia.", "500 mg at bedtime with low-fat snack, titrate up to 1,000-2,000 mg at bedtime.",
     "Active liver disease, active peptic ulcer disease, arterial bleeding.", "Severe prostaglandins-mediated cutaneous flushing (mitigated with aspirin 325 mg 30 min prior); hepatotoxicity; hyperglycemia; hyperuricemia.",
     "Cutaneous flushing/warmth (88%), pruritus, headache, nausea, hyperglycemia, gout flares.",
     "Statins (increased myopathy risk), alcohol, bile acid resins.",
     "Category C."),
    ("Lomitapide", "10 mg", "Oral Capsule", "1369324", "C10AX11", "Microsomal Triglyceride Transfer Protein (MTP) Inhibitor", ["Juxtapid"],
     "Homozygous familial hypercholesterolemia (HoFH).", "5 mg to 60 mg orally once daily on an empty stomach with a glass of water.",
     "Pregnancy; concurrent strong/moderate CYP3A4 inhibitors; moderate-severe hepatic impairment.",
     "Black Box: Hepatotoxicity (steatohepatitis and severe hepatic steatosis); REMS program.",
     "Diarrhea, nausea, vomiting, dyspepsia, elevated transaminases, abdominal pain.",
     "CYP3A4 inhibitors, warfarin, statins.",
     "Contraindicated in pregnancy (Category X).")
]

# Domain 6: Anticoagulants, Antiplatelets & Thrombolytics (22)
CAT_6_ANTICOAG: List[Tuple] = [
    ("Warfarin", "5 mg", "Oral Tablet", "11289", "B01AA03", "Vitamin K Epoxide Reductase Antagonist", ["Coumadin", "Jantoven", "Warf"],
     "Prophylaxis and treatment of venous thrombosis, pulmonary embolism, thromboembolism in atrial fibrillation, mechanical prosthetic heart valves.",
     "Individualized daily oral dosing (typically 2 mg to 5 mg daily) adjusted to target INR (target INR 2.0-3.0 for AF/DVT/PE; 2.5-3.5 for mechanical mitral valves).",
     "Uncontrolled severe hypertension, active pathological bleeding, hemorrhagic stroke, pregnancy (except high-risk mechanical heart valves), severe liver disease.",
     "Black Box: Major and fatal hemorrhage; frequent INR monitoring mandatory; calciphylaxis / systemic atheroemboli (purple toes syndrome); warfarin-induced skin necrosis (due to rapid Protein C depletion).",
     "Hemorrhage, hematuria, epistaxis, gastrointestinal bleeding, bruising, alopecia, skin necrosis.",
     "Massive interaction profile: Bactrim, metronidazole, fluconazole, amiodarone, ciprofloxacin double INR; rifampin, carbamazepine, St. John's wort halve INR; NSAIDs.",
     "Category X. Major teratogen (fetal warfarin syndrome: nasal hypoplasia, stippled epiphyses, CNS defects). Reversal: Vitamin K1 / 4-Factor PCC (Kcentra)."),
    ("Apixaban", "5 mg", "Oral Tablet", "1364430", "B01AF02", "Direct Factor Xa Inhibitor (DOAC)", ["Eliquis", "Apigat"],
     "Stroke prevention in non-valvular atrial fibrillation, treatment and secondary prevention of DVT and PE, DVT prophylaxis post-hip/knee replacement.",
     "5 mg orally twice daily (reduce dose to 2.5 mg BID if >=2 of: age >=80 years, body weight <=60 kg, or serum creatinine >=1.5 mg/dL).",
     "Active pathological bleeding, severe hypersensitivity.",
     "Black Box: Premature discontinuation increases risk of thrombotic events; spinal/epidural hematoma with permanent paralysis following neuraxial anesthesia.",
     "Bleeding, epistaxis, hematoma, anemia, gastrointestinal hemorrhage.",
     "Combined strong CYP3A4 and P-gp inhibitors (ketoconazole, itraconazole reduce apixaban dose by 50%); strong inducers (rifampin, carbamazepine avoid).",
     "Avoid in pregnancy. Specific reversal agent: Andexanet alfa (Andexxa)."),
    ("Rivaroxaban", "20 mg", "Oral Tablet", "1114197", "B01AF01", "Direct Factor Xa Inhibitor (DOAC)", ["Xarelto", "Rivo"],
     "Stroke prevention in non-valvular AF, DVT/PE treatment and secondary prophylaxis, CAD/PAD vascular protection (with aspirin 81 mg).",
     "20 mg orally once daily WITH THE EVENING MEAL (15 mg and 20 mg tablets require food for absorption; 2.5 mg BID for CAD/PAD).",
     "Active pathological bleeding, moderate/severe hepatic impairment with coagulopathy.",
     "Black Box: Spinal/epidural hematoma risk; rebound thrombotic events upon premature cessation.",
     "Bleeding, abdominal pain, dyspepsia, epistaxis, elevated transaminases.",
     "Strong dual CYP3A4 and P-gp inhibitors/inducers, NSAIDs, antiplatelet agents.",
     "Avoid in pregnancy. Specific reversal agent: Andexanet alfa."),
    ("Dabigatran", "150 mg", "Oral Capsule", "1037046", "B01AE07", "Direct Thrombin (Factor IIa) Inhibitor", ["Pradaxa"],
     "Stroke prevention in non-valvular AF, DVT and PE treatment and secondary prevention.",
     "150 mg orally twice daily with or without food (swallow capsule whole - DO NOT open, chew, or crush; increases bioavailability by 75%).",
     "Mechanical prosthetic heart valves (contraindicated - RE-ALIGN trial); active bleeding; severe renal failure (CrCl <15 mL/min).",
     "Black Box: Epidural/spinal hematoma risk; rebound thrombosis upon withdrawal; high gastrointestinal bleeding rate in elderly.",
     "Dyspepsia and gastritis (35% due to tartaric acid core), major GI bleeding, bruising.",
     "P-gp inhibitors (dronedarone, ketoconazole, amiodarone), rifampin.",
     "Avoid in pregnancy. Specific reversal agent: Idarucizumab (Praxbind - immediate 5 g IV push)."),
    ("Edoxaban", "60 mg", "Oral Tablet", "1599538", "B01AF03", "Direct Factor Xa Inhibitor", ["Savaysa", "Lixiana"],
     "Stroke prevention in non-valvular AF and DVT/PE treatment.", "60 mg orally once daily (reduce to 30 mg in CrCl 15-50 mL/min or weight <=60 kg).",
     "Active bleeding; non-valvular AF patients with CrCl >95 mL/min (increased ischemic stroke rate due to enhanced renal clearance).",
     "Black Box: Reduced efficacy in non-valvular AF with CrCl >95 mL/min; spinal hematoma.",
     "Bleeding, anemia, abnormal liver function tests, epistaxis.", "P-gp inhibitors.",
     "Avoid in pregnancy."),
    ("Heparin Sodium", "5,000 units/ml", "IV / SC", "5224", "B01AB01", "Unfractionated Heparin Anticoagulant (Antithrombin III Activator)", ["Heparin"],
     "Prophylaxis and treatment of venous thrombosis, PE, acute coronary syndromes (STEMI/NSTEMI), cardiopulmonary bypass.",
     "IV weight-based protocol: 80 units/kg bolus, then 18 units/kg/hr infusion targeting aPTT 1.5 - 2.5x control (60-80 seconds); SC 5,000 units q8-12h for prophylaxis.",
     "Severe thrombocytopenia, active bleeding, history of Heparin-Induced Thrombocytopenia (HIT).",
     "Black Box/Clinical: Heparin-Induced Thrombocytopenia (HIT type II - life-threatening paradoxical arterial/venous thrombosis 1-5%); major bleeding; osteoporosis with prolonged use (>3 months).",
     "Hemorrhage, thrombocytopenia, injection site hematoma, hyperkalemia (aldosterone suppression), alopecia.",
     "NSAIDs, antiplatelets, thrombolytics, cephalosporins with NMTT side chain.",
     "Category C. Does not cross the placenta; anticoagulant of choice for acute thromboembolism in pregnancy. Reversal: Protamine sulfate (1 mg per 100 units heparin)."),
    ("Enoxaparin", "40 mg", "SC / IV Injection", "67112", "B01AB05", "Low Molecular Weight Heparin (LMWH)", ["Lovenox", "Clexane"],
     "Prophylaxis and treatment of DVT/PE, treatment of acute STEMI and NSTEMI/unstable angina, bridging anticoagulation.",
     "DVT/PE treatment: 1 mg/kg SC every 12 hours (or 1.5 mg/kg once daily); DVT prophylaxis: 40 mg SC once daily (reduce to 30 mg once daily if CrCl <30 mL/min).",
     "Active major bleeding; history of immune-mediated heparin-induced thrombocytopenia (HIT) within past 100 days; pork allergy.",
     "Black Box: Spinal/epidural hematomas causing permanent paralysis in patients undergoing spinal puncture or epidural anesthesia.",
     "Bleeding, anemia, thrombocytopenia (lower HIT risk than UFH <1%), injection site bruising, elevated liver enzymes.",
     "Antiplatelets, NSAIDs, oral anticoagulants, thrombolytics.",
     "Category B. Drug of choice for outpatient anticoagulation during pregnancy. Reversal: Protamine sulfate (partially neutralizes anti-Xa activity)."),
    ("Dalteparin", "5,000 units", "SC Injection", "67109", "B01AB04", "Low Molecular Weight Heparin", ["Fragmin"],
     "DVT/PE treatment in cancer patients (CLOT trial), VTE prophylaxis, acute coronary syndrome.",
     "200 units/kg SC once daily for 1 month, then 150 units/kg once daily for cancer-associated thrombosis.",
     "Active bleeding, HIT history.", "Black Box: Spinal/epidural hematoma risk.",
     "Bleeding, hematoma, pain at injection site, transient LFT elevation.", "Antiplatelets, NSAIDs.",
     "Category B."),
    ("Fondaparinux", "2.5 mg", "SC Injection", "321208", "B01AX05", "Synthetic Pentasaccharide Factor Xa Inhibitor", ["Arixtra"],
     "DVT/PE treatment and prophylaxis, acute coronary syndromes, alternative in history of HIT.",
     "2.5 mg SC once daily (prophylaxis); 7.5 mg SC once daily (treatment for weight 50-100 kg).",
     "Severe renal impairment (CrCl <30 mL/min); body weight <50 kg (prophylaxis); active bleeding.",
     "Black Box: Spinal/epidural hematoma risk; does not cross-react with HIT antibodies.",
     "Bleeding, anemia, thrombocytopenia, fever, nausea.", "Anticoagulants, antiplatelets.",
     "Category B. Safe in confirmed Heparin-Induced Thrombocytopenia."),
    ("Bivalirudin", "250 mg", "IV Infusion", "61028", "B01AE06", "Direct Thrombin Inhibitor (Hirudin Analog)", ["Angiomax"],
     "Anticoagulation in patients undergoing Percutaneous Coronary Intervention (PCI) with or at risk of HIT.",
     "IV bolus 0.75 mg/kg, then 1.75 mg/kg/hr infusion for duration of PCI procedure.",
     "Active major bleeding.", "Bleeding, acute stent thrombosis.",
     "Bleeding, back pain, nausea, hypotension, headache.", "Heparin, antiplatelets.",
     "Category B."),
    ("Argatroban", "250 mg", "IV Infusion", "88249", "B01AE03", "Direct Thrombin Inhibitor (Synthetic L-Arginine Derivative)", ["Acova"],
     "Treatment and prophylaxis of thrombosis in Heparin-Induced Thrombocytopenia (HIT); PCI in HIT.",
     "2 mcg/kg/min continuous IV infusion, adjusted to target aPTT 1.5 - 3.0x control (reduce to 0.5 mcg/kg/min in hepatic impairment).",
     "Major active bleeding.", "Hemorrhage; significantly elevates PT/INR assays (complicates transition to warfarin).",
     "Bleeding, hypotension, fever, diarrhea, nausea.", "Warfarin (falsely prolongs INR assays - requires specialized bridging algorithms).",
     "Category B. Drug of choice for HIT with renal impairment (hepatic clearance)."),
    ("Clopidogrel", "75 mg", "Oral Tablet", "32968", "B01AC04", "P2Y12 Platelet Adenosine Diphosphate Receptor Antagonist Prodrug", ["Plavix", "Deplatt", "Clopilet"],
     "Acute coronary syndrome (ACS: STEMI/NSTEMI), recent MI, recent ischemic stroke, established peripheral arterial disease, post-coronary stenting (DAPT).",
     "75 mg orally once daily (with 300 mg or 600 mg loading dose in acute coronary syndromes / PCI).",
     "Active pathological bleeding (peptic ulcer, intracranial hemorrhage).",
     "Black Box: Diminished antiplatelet effect in CYP2C19 poor metabolizers (cannot activate prodrug to active thiol metabolite - higher rate of stent thrombosis and death); Thrombotic Thrombocytopenic Purpura (TTP).",
     "Bleeding, purpura, bruising, epistaxis, hematoma, diarrhea, rash.",
     "CYP2C19 inhibitors (omeprazole, esomeprazole significantly reduce active metabolite levels - use pantoprazole instead), NSAIDs, anticoagulants.",
     "Category B."),
    ("Ticagrelor", "90 mg", "Oral Tablet", "1117096", "B01AC24", "Direct-Acting Reversible P2Y12 Platelet Inhibitor (Cyclopentyltriazolopyrimidine)", ["Brilinta", "Brilique"],
     "Acute coronary syndrome (PLATO trial demonstrated superior reduction in CV death vs clopidogrel), coronary stenting, high-risk CAD/stroke prevention.",
     "180 mg oral loading dose, then 90 mg orally twice daily (with maintenance aspirin capped at <=100 mg daily).",
     "History of intracranial hemorrhage; active pathological bleeding; severe hepatic impairment.",
     "Black Box: Bleeding risk; maintenance aspirin doses >100 mg daily decrease ticagrelor efficacy; dyspnea (15% due to adenosine reuptake inhibition).",
     "Dyspnea (15-20% - self-limiting sensation), bleeding, epistaxis, ventricular pauses, hyperuricemia (elevates serum uric acid).",
     "Aspirin >100 mg daily (contraindicated - blunts efficacy), strong CYP3A4 inhibitors/inducers, simvastatin/lovastatin (max 40 mg).",
     "Category C. Does not require metabolic activation."),
    ("Prasugrel", "10 mg", "Oral Tablet", "849727", "B01AC22", "Potent Irreversible P2Y12 Platelet Inhibitor", ["Effient"],
     "Reduction of thrombotic CV events in patients with acute coronary syndrome undergoing PCI (TRITON-TIMI 38 trial).",
     "60 mg oral loading dose, then 10 mg orally once daily with aspirin (reduce to 5 mg daily if body weight <60 kg).",
     "Prior transient ischemic attack (TIA) or stroke (strictly contraindicated - net clinical harm/fatal intracranial hemorrhage); active bleeding.",
     "Black Box: Fatal bleeding; strictly contraindicated in patients with history of TIA or stroke; age >=75 years (generally not recommended due to high bleed risk).",
     "Bleeding, epistaxis, hematoma, thrombocytopenia, purpura.", "Anticoagulants, NSAIDs, thrombolytics.",
     "Category B."),
    ("Dipyridamole", "75 mg", "Oral Tablet / IV", "3444", "B01AC07", "Phosphodiesterase Inhibitor & Adenosine Reuptake Blocker", ["Persantine", "Aggrenox"],
     "Secondary prevention of stroke/TIA (combined with aspirin), pharmacologic cardiac stress testing (IV).",
     "75 mg to 100 mg orally 4 times daily (or Aggrenox 200 mg ER / 25 mg aspirin BID).",
     "Hypersensitivity.", "Severe headache; coronary steal phenomenon and angina in CAD; bronchospasm.",
     "Headache (frequent), dizziness, dyspepsia, diarrhea, flushing, angina.", "Adenosine (potentiates adenosine effect 4-fold), cholinesterase inhibitors.",
     "Category B."),
    ("Cilostazol", "100 mg", "Oral Tablet", "235473", "B01AC23", "Selective Phosphodiesterase-3 (PDE3) Inhibitor", ["Pletal"],
     "Reduction of symptoms of intermittent claudication in peripheral arterial disease (improves maximal walking distance).",
     "100 mg orally twice daily taken at least 30 minutes before or 2 hours after breakfast and dinner.",
     "Congestive heart failure of any severity (PDE3 inhibitors increase mortality in heart failure patients); active bleeding.",
     "Black Box: Contraindicated in patients with heart failure of any severity; bleeding risk.",
     "Headache (30%), diarrhea, palpitations, tachycardia, dizziness, peripheral edema.",
     "Strong CYP3A4/2C19 inhibitors (omeprazole, ketoconazole, diltiazem - reduce cilostazol dose to 50 mg BID).",
     "Category C."),
    ("Alteplase", "100 mg", "IV Infusion", "8410", "B01AD02", "Recombinant Tissue Plasminogen Activator (tPA)", ["Activase", "Cathflo Activase"],
     "Acute ischemic stroke (within 3 to 4.5 hours of symptom onset), acute massive pulmonary embolism, acute STEMI myocardial infarction.",
     "Acute Ischemic Stroke: 0.9 mg/kg IV (max 90 mg) with 10% given as initial IV bolus over 1 min and remaining 90% infused over 60 min.",
     "Active internal bleeding; history of recent stroke (within 3 mo); severe head trauma (within 3 mo); intracranial neoplasm or AVM; intracranial surgery; severe uncontrolled HTN (SBP >185 or DBP >110); INR >1.7 or platelet count <100,000.",
     "Severe and fatal intracranial hemorrhage (6% in acute stroke); major systemic hemorrhage; angioedema (orolingual angioedema with ACEi).",
     "Intracranial hemorrhage, GI hemorrhage, ecchymosis, epistaxis, orolingual angioedema, hypotension.",
     "Anticoagulants, antiplatelets (do not administer aspirin/heparin within 24 hours of stroke tPA).",
     "Category C. Reversal: Cryoprecipitate / Tranexamic acid."),
    ("Tenecteplase", "50 mg", "IV Bolus", "258327", "B01AD11", "Genetically Engineered Tissue Plasminogen Activator", ["TNKase", "Elaxim"],
     "Acute STEMI myocardial infarction and acute ischemic stroke (single rapid 5-second IV bolus).",
     "Weight-based IV bolus over 5 seconds: 30 mg (<60 kg) to 50 mg (>=90 kg).",
     "Active bleeding, stroke history, intracranial aneurysm, severe hypertension.",
     "Fatal intracranial and systemic hemorrhage; reperfusion arrhythmias.",
     "Hemorrhage, hematoma, reperfusion arrhythmias, epistaxis.", "Anticoagulants, antiplatelets.",
     "Category C."),
    ("Idarucizumab", "5 g/50ml", "IV Push", "1720584", "V03AB37", "Specific Dabigatran Reversal Humanized Fab Fragment", ["Praxbind"],
     "Rapid emergency reversal of the anticoagulant effects of dabigatran in life-threatening bleeding or emergency surgery.",
     "5 g IV administered as two consecutive 2.5 g / 50 mL IV infusions or bolus injections (completely normalizes clotting parameters within minutes).",
     "None in life-threatening emergency.", "Rebound thromboembolic events (due to underlying disease); hereditary fructose intolerance (contains sorbitol).",
     "Hypokalemia, delirium, constipation, pyrexia, pneumonia.", "Binds specifically and exclusively to dabigatran (350x higher affinity than thrombin).",
     "Category B. Immediate reversal of dabigatran."),
    ("Andexanet Alfa", "400 mg", "IV Infusion", "2044814", "V03AB38", "Recombinant Inactive Decoy Factor Xa Protein", ["Andexxa"],
     "Reversal of anticoagulation due to apixaban or rivaroxaban in patients with life-threatening or uncontrolled bleeding.",
     "Low dose: 400 mg IV bolus at 30 mg/min, then 4 mg/min infusion for 2 hours; High dose: 800 mg bolus, then 8 mg/min infusion.",
     "None in life-threatening bleeding.", "Black Box: Arterial and venous thromboembolic events (ischemic stroke, MI, DVT/PE); ischemic events; sudden death.",
     "Thromboembolism, stroke, deep vein thrombosis, urinary tract infection, pneumonia.", "Neutralizes Factor Xa inhibitors (apixaban, rivaroxaban, enoxaparin).",
     "Avoid in pregnancy unless emergency."),
    ("Protamine Sulfate", "50 mg/5ml", "Slow IV Push", "8827", "V03AB14", "Heparin Neutralizing Agent (Basic Polypeptide)", ["Protamine"],
     "Reversal and neutralization of unfractionated heparin (and partial neutralization of LMWH enoxaparin).",
     "1 mg IV per 100 units of heparin remaining; administer slow IV push not exceeding 50 mg in 10 minutes.",
     "Hypersensitivity to protamine.", "Black Box: Severe hypotension, cardiovascular collapse, pulmonary hypertension, and anaphylactoid reactions with rapid IV injection; high risk in fish allergy and prior vasectomy (anti-protamine antibodies).",
     "Severe hypotension, bradycardia, pulmonary hypertension, flushing, nausea.", "Neutralizes acidic heparin molecules via stable salt formation.",
     "Category C."),
    ("Phytonadione", "10 mg", "Oral / Slow IV", "8283", "B02BA01", "Synthetic Vitamin K1", ["Mephyton", "AquaMEPHYTON"],
     "Warfarin-induced hypoprothrombinemia, neonatal hemorrhagic disease prophylaxis, vitamin K deficiency bleeding.",
     "Warfarin reversal: 2.5 mg to 10 mg orally (or 5-10 mg slow IV in 50 mL saline over 20 min with 4-Factor PCC for major bleeding); Neonatal: 0.5-1 mg IM at birth.",
     "Hypersensitivity.", "Black Box: Severe, fatal anaphylactoid shock and cardiac arrest with rapid IV/IM administration (dilute and infuse over 20-30 min).",
     "Anaphylaxis, flushing, diaphoresis, dyspnea, hypotension, pain at injection site.", "Antagonizes warfarin anticoagulation.",
     "Category C. Essential for all neonates at birth.")
]

# Domain 7: Gastrointestinal, Antiemetic & Acid-Suppressive (46)
CAT_7_GI: List[Tuple] = [
    ("Pantoprazole", "40 mg", "Oral Tablet / IV", "312615", "A02BC02", "Proton Pump Inhibitor (PPI)", ["Protonix", "Pan 40", "Pantocid"],
     "Erosive esophagitis associated with GERD, pathological hypersecretion (Zollinger-Ellison), peptic ulcer bleeding (IV continuous infusion).",
     "40 mg orally once daily in the morning 30 minutes before breakfast for up to 8 weeks (IV bolus 80 mg then 8 mg/hr in acute GI bleed).",
     "Known hypersensitivity to substituted benzimidazoles; concomitant use with rilpivirine-containing products.",
     "Clostridioides difficile-associated diarrhea (CDAD); hypomagnesemia; vitamin B12 deficiency; osteoporotic bone fractures with high-dose/long-term use (>1 year); acute interstitial nephritis (AIN); fundic gland polyps.",
     "Headache, diarrhea, nausea, abdominal pain, flatulence, dizziness, arthralgia.",
     "Methotrexate (elevates methotrexate levels), HIV protease inhibitors (atazanavir), clopidogrel (minimal CYP2C19 interaction compared to omeprazole), iron salts (decreased absorption).",
     "Category B. Preferred safe PPI in pregnancy and clopidogrel co-therapy."),
    ("Omeprazole", "20 mg", "Oral Capsule", "7646", "A02BC01", "Proton Pump Inhibitor Prototype", ["Prilosec", "Omez", "Omee"],
     "Duodenal and gastric ulcers, GERD, erosive esophagitis, Helicobacter pylori eradication.",
     "20 mg to 40 mg orally once daily in the morning 30-60 minutes before breakfast.",
     "Hypersensitivity to benzimidazoles; concurrent rilpivirine.",
     "CDAD colitis; hypomagnesemia; bone fractures; acute interstitial nephritis; vitamin B12 deficiency.",
     "Headache, abdominal pain, constipation, diarrhea, flatulence, nausea.",
     "Potent CYP2C19 inhibitor: significantly reduces clopidogrel active metabolite and antiplatelet efficacy; increases diazepam, phenytoin, warfarin.",
     "Category C."),
    ("Esomeprazole", "40 mg", "Oral Capsule / IV", "283742", "A02BC05", "S-Isomer Proton Pump Inhibitor", ["Nexium", "Nexpro"],
     "Gastroesophageal reflux disease, healing of erosive esophagitis, H. pylori eradication, NSAID ulcer risk reduction.",
     "20 mg to 40 mg orally once daily 30 minutes before breakfast.",
     "Benzimidazole hypersensitivity.", "CDAD, bone fractures, hypomagnesemia, subacute cutaneous lupus erythematosus.",
     "Headache, diarrhea, flatulence, abdominal pain, constipation, dry mouth.",
     "Clopidogrel (CYP2C19 interaction), cilostazol, digoxin, methotrexate.",
     "Category C."),
    ("Lansoprazole", "30 mg", "Oral Capsule", "283744", "A02BC03", "Proton Pump Inhibitor", ["Prevacid", "Lanzol"],
     "Healing and maintenance of duodenal/gastric ulcers, GERD, Zollinger-Ellison syndrome.",
     "15 mg to 30 mg orally once daily before breakfast.",
     "Hypersensitivity to lansoprazole.", "CDAD, hypomagnesemia, bone fractures, interstitial nephritis.",
     "Diarrhea, abdominal pain, nausea, headache.", "Theophylline, warfarin, sucralfate (decreases lansoprazole absorption).",
     "Category B. Safe in pregnancy."),
    ("Rabeprazole", "20 mg", "Oral Tablet", "283745", "A02BC04", "Proton Pump Inhibitor", ["Aciphex", "Rablet"],
     "GERD, duodenal ulcers, H. pylori eradication.", "20 mg orally once daily in the morning after a meal or before breakfast.",
     "Benzimidazole allergy.", "CDAD, hypomagnesemia, fracture risk.",
     "Headache, diarrhea, nausea, pharyngitis, abdominal pain.", "Digoxin, atazanavir, ketoconazole.",
     "Category B."),
    ("Dexlansoprazole", "60 mg", "Oral Capsule", "849733", "A02BC06", "Dual Delayed-Release Proton Pump Inhibitor", ["Dexilant"],
     "Healing of erosive esophagitis and maintenance of GERD symptom relief (dual peak release).",
     "30 mg to 60 mg orally once daily without regard to food.",
     "Benzimidazole allergy.", "CDAD, hypomagnesemia, bone fractures.",
     "Diarrhea, abdominal pain, nausea, upper respiratory tract infection.", "Methotrexate, clopidogrel, atazanavir.",
     "Category B."),
    ("Famotidine", "20 mg", "Oral Tablet / IV", "4278", "A02BA03", "Histamine H2 Receptor Antagonist", ["Pepcid", "Famocid"],
     "Treatment and prevention of peptic ulcer disease, GERD, heartburn, sour stomach.",
     "20 mg to 40 mg orally once or twice daily (or 20-40 mg at bedtime).",
     "Hypersensitivity to famotidine or other H2 receptor antagonists.",
     "Central nervous system adverse reactions (confusion, hallucinations, delirium, agitation) in elderly or renal impairment (CrCl <50 mL/min - reduce dose by 50%).",
     "Headache, dizziness, constipation, diarrhea, transient fatigue.",
     "Cefuroxime, atazanavir, ketoconazole (reduces absorption by raising gastric pH).",
     "Category B. Preferred, well-established acid suppressant in pregnancy."),
    ("Cimetidine", "400 mg", "Oral Tablet", "2541", "A02BA01", "Histamine H2 Receptor Antagonist Prototype", ["Tagamet"],
     "Duodenal and gastric ulcers, GERD.", "400 mg orally twice daily or 800 mg at bedtime.",
     "Hypersensitivity.", "Potent pan-CYP inhibitor (CYP1A2, 2C9, 2D6, 3A4); anti-androgenic painful gynecomastia and impotence in males.",
     "Gynecomastia, impotence, confusion in elderly, diarrhea, headache.",
     "Massive drug interactions: increases warfarin, theophylline, phenytoin, lidocaine, tricyclics.",
     "Category B."),
    ("Sucralfate", "1 g", "Oral Tablet / Suspension", "10156", "A02BX02", "Sucrose Sulfate-Aluminum Mucosal Protectant", ["Carafate", "Sucrafil"],
     "Short-term treatment and maintenance of active duodenal ulcers; radiation proctitis enema.",
     "1 g orally four times daily on an empty stomach (1 hour before meals and at bedtime).",
     "Known hypersensitivity.", "Bezoar formation in patients with impaired gastric motility; aluminum toxicity in chronic renal failure.",
     "Constipation (most common - 2%), flatulence, dry mouth, nausea.",
     "Binds and prevents absorption of fluoroquinolones, warfarin, digoxin, levothyroxine, phenytoin (administer other drugs >=2 hours before sucralfate).",
     "Category B. Non-absorbed; safe in pregnancy."),
    ("Misoprostol", "200 mcg", "Oral Tablet", "6983", "A02BB01", "Synthetic Prostaglandin E1 (PGE1) Analog", ["Cytotec"],
     "Prevention of NSAID-induced gastric ulcers in high-risk patients; labor induction / pregnancy termination (with mifepristone).",
     "200 mcg orally four times daily with food (last dose at bedtime).",
     "Pregnancy for the prevention of NSAID ulcers (strictly contraindicated - abortifacient).",
     "Black Box: Uterine rupture, severe bleeding, and fetal death when administered to pregnant women; abortifacient.",
     "Diarrhea (dose-dependent - 40%), severe abdominal cramping, nausea, flatulence, vaginal spotting.",
     "Magnesium-containing antacids (aggravate severe diarrhea).",
     "Category X. Absolute contraindication in pregnancy for ulcer prophylaxis."),
    ("Bismuth Subsalicylate", "262 mg", "Oral Tablet / Suspension", "1545", "A07BA", "Antidiarrheal & Mucosal Protectant", ["Pepto-Bismol"],
     "Traveler's diarrhea, indigestion, nausea, H. pylori eradication quadruple therapy component.",
     "524 mg (2 tablets or 30 mL) orally every 30-60 minutes PRN (max 8 doses/24h).",
     "Aspirin/salicylate allergy; children recovering from viral illness (Reye's syndrome); active bleeding.",
     "Reye's syndrome in children; harmless temporary black/dark discoloration of tongue and stool.",
     "Black tongue, black stools, constipation, tinnitus (salicylate toxicity in overdose).",
     "Aspirin, warfarin (increased bleeding), tetracyclines (chelates and blocks absorption).",
     "Category C/D in 3rd trimester."),
    ("Ondansetron", "4 mg", "Oral / ODT / IV", "26225", "A04AA01", "Selective 5-HT3 Receptor Antagonist", ["Zofran", "Emeset", "Zofer", "Zofran ODT"],
     "Prevention of chemotherapy-induced, radiation-induced, and postoperative nausea and vomiting (PONV); hyperemesis gravidarum.",
     "4 mg to 8 mg orally, ODT (dissolve on tongue), or IV every 8 hours PRN.",
     "Concomitant use of apomorphine (profound hypotension and loss of consciousness); congenital long QT syndrome.",
     "Dose-dependent QT interval prolongation and torsades de pointes (max single IV dose 16 mg); Serotonin Syndrome when combined with serotonergic agents; masks progressive ileus.",
     "Headache (most common - 20%), constipation, fatigue, diarrhea, dizziness, transient QT prolongation.",
     "Apomorphine (contraindicated - fatal collapse), QT-prolonging drugs, SSRIs/SNRIs (Serotonin Syndrome).",
     "Category B. Extensively utilized in hyperemesis gravidarum with careful clinical evaluation."),
    ("Granisetron", "1 mg", "Oral / IV / Transdermal", "4917", "A04AA02", "5-HT3 Receptor Antagonist", ["Kytril", "Sancuso"],
     "Prevention of chemotherapy and radiation-induced nausea and vomiting.",
     "1 mg to 2 mg orally daily or 1 mg IV 30 min before chemo; transdermal patch applied 24-48h prior.",
     "Hypersensitivity.", "QT prolongation, Serotonin Syndrome, constipation.",
     "Headache, constipation, asthenia, diarrhea.", "Serotonergic drugs.",
     "Category B."),
    ("Palonosetron", "0.25 mg", "IV Injection", "358262", "A04AA05", "Second-Generation Long-Acting 5-HT3 Antagonist", ["Aloxi"],
     "Prevention of acute and delayed chemotherapy-induced nausea and vomiting (half-life 40 hours).",
     "0.25 mg IV single dose 30 minutes prior to chemotherapy.",
     "Hypersensitivity.", "Serotonin Syndrome, constipation.",
     "Headache, constipation, diarrhea, dizziness.", "Serotonergic agents.",
     "Category B."),
    ("Aprepitant", "125 mg", "Oral Capsule", "358261", "A04AD12", "Substance P / Neurokinin-1 (NK1) Receptor Antagonist", ["Emend"],
     "Prevention of acute and delayed chemotherapy-induced nausea and vomiting (with ondansetron + dexamethasone).",
     "125 mg orally on day 1 (1 hour before chemo), then 80 mg orally once daily on days 2 and 3.",
     "Concurrent pimozide, cisapride.", "Moderate CYP3A4 inhibitor and inducer of CYP2C9 (decreases warfarin INR).",
     "Fatigue, diarrhea, asthenia, dyspepsia, hiccups, elevated ALT.",
     "Warfarin (significantly decreases INR on days 7-10 post-dose), oral contraceptives (decreases efficacy), dexamethasone (doubles dexamethasone exposure).",
     "Category B."),
    ("Metoclopramide", "10 mg", "Oral Tablet / IV", "6915", "A03FA01", "Dopamine D2 & 5-HT4 Receptor Prokinetic & Antiemetic", ["Reglan", "Maxolon", "Perinorm"],
     "Diabetic gastroparesis, GERD refractory to other therapy, prevention of postoperative/chemo nausea.",
     "10 mg to 15 mg orally up to four times daily 30 minutes before each meal and at bedtime (max duration 12 weeks).",
     "Gastrointestinal obstruction, perforation, or active hemorrhage; pheochromocytoma; history of tardive dyskinesia; epilepsy.",
     "Black Box: Tardive dyskinesia (irreversible involuntary choreoathetoid movements of tongue, face, and extremities; highest risk in elderly females and therapy >12 weeks); extrapyramidal symptoms (acute dystonia); neuroleptic malignant syndrome.",
     "Somnolence, restlessness, acute dystonic muscle spasms, fatigue, diarrhea, hyperprolactinemia (galactorrhea).",
     "Antipsychotics (severe additive extrapyramidal reactions), anticholinergics (antagonize prokinetic effect), levodopa.",
     "Category B. Acute dystonia treated with IV Diphenhydramine 50 mg."),
    ("Domperidone", "10 mg", "Oral Tablet", "3544", "A03FA03", "Peripheral Dopamine D2 Antagonist Prokinetic", ["Motilium", "Domstal"],
     "Gastroparesis and nausea/vomiting (does not readily cross blood-brain barrier - low EPS risk).",
     "10 mg orally three times daily before meals (max 30 mg/day).",
     "Prolonged cardiac QT interval; severe hepatic impairment; GI hemorrhage/obstruction; prolactinoma.",
     "QT interval prolongation and sudden cardiac death (especially in patients >60 years or doses >30 mg/day); hyperprolactinemia.",
     "Dry mouth, diarrhea, hyperprolactinemia (gynecomastia, galactorrhea, amenorrhea), QT prolongation.",
     "Strong CYP3A4 inhibitors (ketoconazole, erythromycin contraindicated), QT-prolonging agents.",
     "Category C. Not FDA approved in US due to cardiac arrhythmia concerns; widely used globally."),
    ("Prochlorperazine", "10 mg", "Oral / IV / Rectal Suppository", "8644", "N05AB04", "Phenothiazine Antiemetic & Antipsychotic", ["Compazine", "Stemetil"],
     "Severe nausea and vomiting, acute vertigo/labyrinthitis, schizophrenia.",
     "5 mg to 10 mg orally or IV every 6 to 8 hours PRN (or 25 mg rectal suppository BID).",
     "Comatose states, CNS depression from alcohol/barbiturates, children <2 years.",
     "Black Box: Increased mortality in elderly patients with dementia-related psychosis; acute dystonic reactions; tardive dyskinesia; neuroleptic malignant syndrome (NMS).",
     "Drowsiness, dizziness, extrapyramidal symptoms, hypotension, dry mouth, blurred vision.",
     "CNS depressants, anticholinergics, lithium.",
     "Category C."),
    ("Promethazine", "25 mg", "Oral / IV / IM / Rectal", "8745", "R06AD02", "Phenothiazine H1 Antihistamine & Antiemetic", ["Phenergan"],
     "Nausea and vomiting, motion sickness, allergic conditions, sedation.",
     "12.5 mg to 25 mg orally, IM, or rectal every 4 to 6 hours PRN.",
     "Children <2 years (fatal respiratory depression); intra-arterial or subcutaneous injection.",
     "Black Box: Severe tissue necrosis and gangrene with IV extravasation (deep IM preferred); fatal respiratory depression in children <2 years; severe sedation.",
     "Sedation (severe), dry mouth, blurred vision, dizziness, urinary retention.",
     "CNS depressants, alcohol, anticholinergics.",
     "Category C."),
    ("Scopolamine", "1.5 mg", "Transdermal Patch", "9604", "A04AA", "Anticholinergic / Muscarinic Antagonist", ["Transderm Scop"],
     "Prevention of motion sickness and postoperative nausea and vomiting (PONV).",
     "1.5 mg transdermal patch applied to hairless skin behind ear >=4 hours before travel (delivers 1 mg over 72 hours).",
     "Narrow-angle glaucoma, severe hypersensitivity.", "Anticholinergic delirium in elderly; mydriasis/blurred vision if residue touches eye; urinary retention.",
     "Dry mouth (frequent), blurred vision, somnolence, dizziness, disorientation, urinary retention.",
     "Anticholinergic agents, sedatives, alcohol.",
     "Category C. Wash hands thoroughly with soap after handling patch."),
    ("Loperamide", "2 mg", "Oral Capsule", "6468", "A07DA03", "Peripheral Mu-Opioid Receptor Antidiarrheal", ["Imodium", "Eldoper"],
     "Symptomatic relief of acute non-specific diarrhea, traveler's diarrhea, chronic diarrhea of IBD.",
     "4 mg orally initially, followed by 2 mg after each unformed loose stool (max 8 mg/day OTC; max 16 mg/day prescription).",
     "Children <2 years; acute dysentery (bloody stools and high fever); bacterial enterocolitis (Salmonella, Shigella, Campylobacter); acute ulcerative colitis; pseudomembranous colitis.",
     "Black Box: Higher than recommended doses (misuse/abuse as opioid substitute) causes QT prolongation, torsades de pointes, cardiac arrest, and sudden death; toxic megacolon.",
     "Constipation, abdominal cramping, dizziness, nausea, dry mouth.",
     "P-gp and CYP3A4/2C8 inhibitors (quinidine, ritonavir, gemfibrozil increase loperamide CNS penetration and cardiac toxicity).",
     "Category B. Safe in pregnancy when clinically indicated."),
    ("Diphenoxylate and Atropine", "2.5-0.025 mg", "Oral Tablet", "3432", "A07DA01", "Opioid Antidiarrheal + Subtherapeutic Anticholinergic", ["Lomotil"],
     "Adjunctive therapy in the management of diarrhea.", "5 mg (2 tablets) orally four times daily (max 20 mg/day).",
     "Obstructive jaundice, children <6 years, pseudomembranous colitis.", "Black Box: Respiratory depression; toxic megacolon; anticholinergic overdose in children.",
     "Drowsiness, dizziness, dry mouth, nausea, restlessness, euphoria.", "MAO inhibitors, sedatives, alcohol.",
     "Category C."),
    ("Lactulose", "10 g/15ml", "Oral Solution", "6240", "A06AD11", "Synthetic Disaccharide Osmotic Laxative & Ammonia Detoxicant", ["Enulose", "Duphalac", "Constulose"],
     "Prevention and treatment of portal-systemic hepatic encephalopathy (reduces blood ammonia); chronic constipation.",
     "Hepatic encephalopathy: 30 mL to 45 mL orally 3 to 4 times daily titrated to produce 2 to 3 soft stools per day; Constipation: 15-30 mL daily.",
     "Galactosemia (requires low galactose diet); bowel obstruction.", "Electrolyte imbalance and severe dehydration with excessive diarrhea; abdominal gas/cramping.",
     "Flatulence (frequent initially - 20%), abdominal distention, cramping, diarrhea, nausea, hypokalemia.",
     "Other laxatives (falsely masks titration for hepatic encephalopathy), oral antibiotics (may decrease efficacy by altering flora).",
     "Category B. Safe and non-absorbed in pregnancy."),
    ("Polyethylene Glycol 3350", "17 g", "Oral Powder", "8528", "A06AD65", "Osmotic Laxative", ["MiraLAX", "Golytely"],
     "Occasional constipation (MiraLAX) and complete colonoscopy bowel cleansing (Golytely/PEG-ELS).",
     "17 g (1 heaping tablespoon) dissolved in 4-8 oz of water, juice, or beverage once daily.",
     "Gastrointestinal obstruction, bowel perforation, toxic colitis or megacolon.",
     "Fluid and electrolyte shifts (with large bowel prep volumes); allergic reactions.",
     "Abdominal bloating, cramping, gas, nausea, loose stools.",
     "Oral medications taken within 1 hour of bowel cleanse may be flushed through GI tract unabsorbed.",
     "Category C. Non-absorbed; preferred safe osmotic agent in pregnancy."),
    ("Senna", "8.6 mg", "Oral Tablet", "9659", "A06AB06", "Anthraquinone Stimulant Laxative", ["Senokot", "Ex-Lax"],
     "Short-term relief of acute constipation; opioid-induced constipation (combined with docusate - Senna-S).",
     "1 to 2 tablets orally once or twice daily (typically at bedtime).",
     "Undiagnosed acute abdominal pain, intestinal obstruction, appendicitis.", "Melanosis coli (reversible dark pigmentation of colon mucosa); laxative dependence with chronic abuse.",
     "Abdominal cramping, nausea, diarrhea, reddish-brown urine discoloration.", "Digoxin, diuretics (worsened hypokalemia).",
     "Category C. Compatible with breastfeeding."),
    ("Bisacodyl", "5 mg", "Oral Tablet / Rectal Suppository", "1540", "A06AB02", "Diphenylmethane Stimulant Laxative", ["Dulcolax"],
     "Constipation and bowel evacuation prior to surgery/endoscopy.", "5 mg to 15 mg orally once daily (or 10 mg rectal suppository acting in 15-60 min).",
     "Ileus, acute surgical abdomen, appendicitis.", "Severe abdominal cramping; do not take oral tablet within 1 hour of milk or antacids (dissolves enteric coating causing vomiting).",
     "Abdominal cramps, nausea, diarrhea, rectal burning (suppository).", "Milk and antacids (destroy enteric coating).",
     "Category C."),
    ("Docusate Sodium", "100 mg", "Oral Capsule", "3536", "A06AA02", "Anionic Surfactant Stool Softener", ["Colace", "Dulcolax Stool Softener"],
     "Prevention of dry hard stools in patients who should avoid straining (post-MI, hemorrhoids, postpartum).",
     "50 mg to 200 mg orally daily in single or divided doses.",
     "Concomitant use of mineral oil (docusate increases mineral oil systemic absorption and toxicity).",
     "Ineffective for active severe constipation (stool softener, not a laxative).",
     "Mild abdominal cramping, bitter taste, diarrhea.", "Mineral oil (contraindicated combination).",
     "Category C. Widely used postpartum and in pregnancy."),
    ("Mesalamine", "800 mg", "Oral Tablet / Enema / Suppository", "6762", "A07EC02", "5-Aminosalicylic Acid (5-ASA) Anti-Inflammatory", ["Asacol HD", "Lialda", "Pentasa", "Rowasa"],
     "Induction and maintenance of remission in mild-to-moderate ulcerative colitis; proctitis.",
     "1.6 g to 4.8 g orally daily (or 1 g rectal suppository at bedtime for proctitis).",
     "Severe hypersensitivity to salicylates or mesalamine.", "Acute intolerance syndrome (cramping, acute abdominal pain, bloody diarrhea indistinguishable from IBD flare); nephrotoxicity / interstitial nephritis.",
     "Abdominal pain, headache, nausea, flatulence, diarrhea, elevated transaminases.",
     "Nephrotoxic agents (NSAIDs), azathioprine/6-MP (increases bone marrow suppression).",
     "Category B. First-line maintenance in pregnancy with ulcerative colitis."),
    ("Sulfasalazine", "500 mg", "Oral Tablet", "10232", "A07EC01", "5-ASA + Sulfapyridine Conjugate", ["Azulfidine"],
     "Ulcerative colitis and rheumatoid arthritis.", "1 g to 2 g orally 3 to 4 times daily after meals (give with Folic Acid 1 mg daily).",
     "Sulfa or salicylate allergy; intestinal or urinary obstruction; porphyria.",
     "Severe sulfa hypersensitivity (SJS/TEN); agranulocytosis; reversible oligospermia/male infertility (60%); impairs folic acid absorption.",
     "Nausea, vomiting, dyspepsia, headache, reversible male infertility, orange-yellow urine.",
     "Digoxin, folic acid (blocks folate absorption - supplement mandatory), warfarin.",
     "Category B. High dose requires supplemental folic acid during pregnancy."),
    ("Ursodiol", "300 mg", "Oral Capsule", "11100", "A05AA02", "Hydrophilic Bile Acid (Ursodeoxycholic Acid)", ["Actigall", "Urso 250", "Udiliv"],
     "Dissolution of radiolucent gallstones; Primary Biliary Cholangitis (PBC); Intrahepatic Cholestasis of Pregnancy (ICP).",
     "300 mg orally 2 to 3 times daily with food (13-15 mg/kg/day for PBC).",
     "Complete biliary obstruction, calcified gallstones, acute cholecystitis.", "Hepatotoxicity monitoring; minimal systemic side effects.",
     "Diarrhea, nausea, dyspepsia, dizziness, pruritus reduction.",
     "Bile acid sequestrants (cholestyramine) and aluminum antacids reduce absorption; estrogens reduce gallstone dissolution.",
     "Category B. Drug of choice for intrahepatic cholestasis of pregnancy (reduces fetal bile acids)."),
    ("Rifaximin", "550 mg", "Oral Tablet", "257211", "A07AA11", "Non-Systemic Rifamycin Antibiotic", ["Xifaxan", "Rifagut"],
     "Reduction in risk of overt hepatic encephalopathy recurrence (550 mg BID); irritable bowel syndrome with diarrhea (IBS-D 550 mg TID for 14 days); traveler's diarrhea.",
     "550 mg orally twice daily with or without food (for hepatic encephalopathy).",
     "Hypersensitivity to rifamycins.", "CDAD; minimal systemic absorption (<0.4%); does not treat systemic bacteremia.",
     "Peripheral edema, nausea, dizziness, fatigue, ascites.", "P-gp inhibitors (cyclosporine increases rifaximin exposure).",
     "Category C. Non-absorbed; safe in hepatic encephalopathy.")
]

# Domain 8: Respiratory, Antiasthmatic & Antiallergic (45)
CAT_8_RESP: List[Tuple] = [
    ("Cetirizine", "10 mg", "Oral Tablet", "310489", "R06AE07", "Second-Generation H1 Antihistamine", ["Zyrtec", "Cetzine", "Alerid", "Zyncet"],
     "Allergic rhinitis (seasonal and perennial) and chronic idiopathic urticaria.", "5 mg to 10 mg orally once daily in the evening.",
     "Hypersensitivity to cetirizine, hydroxyzine, or levocetirizine; end-stage renal disease (CrCl <10 mL/min).",
     "Somnolence and central nervous system depression (highest sedative potential among second-generation antihistamines - 14%).",
     "Somnolence (14%), dry mouth, fatigue, pharyngitis, dizziness.",
     "Alcohol and CNS depressants increase somnolence; theophylline decreases cetirizine clearance.",
     "Category B. Preferred, safe antihistamine in pregnancy and lactation."),
    ("Levocetirizine", "5 mg", "Oral Tablet", "311354", "R06AE09", "Pure R-Enantiomer Antihistamine", ["Xyzal", "Levocet", "Vozet"],
     "Seasonal and perennial allergic rhinitis, chronic urticaria.", "5 mg orally once daily in the evening (2.5 mg in children 6-11 years).",
     "End-stage renal disease (CrCl <10 mL/min) or hemodialysis; children <11 years with renal impairment.",
     "CNS depression, somnolence, urinary retention.",
     "Somnolence, nasopharyngitis, dry mouth, pharyngitis, fatigue.", "CNS depressants, alcohol, theophylline.",
     "Category B."),
    ("Loratadine", "10 mg", "Oral Tablet", "6470", "R06AX13", "Non-Sedating Second-Generation H1 Antihistamine", ["Claritin", "Lorfast", "Alastin"],
     "Relief of symptoms of allergic rhinitis and chronic idiopathic urticaria.", "10 mg orally once daily on an empty stomach or with meals.",
     "Known hypersensitivity to loratadine.", "Completely non-sedating at recommended 10 mg dose; hepatic dose adjustment required.",
     "Headache, somnolence (at high doses), fatigue, dry mouth.",
     "CYP3A4 and CYP2D6 inhibitors (ketoconazole, erythromycin) increase loratadine blood levels without QT prolongation.",
     "Category B. First-line antihistamine of choice in pregnancy."),
    ("Desloratadine", "5 mg", "Oral Tablet", "329528", "R06AX27", "Active Metabolite Second-Generation Antihistamine", ["Clarinex", "Aerius"],
     "Allergic rhinitis and chronic idiopathic urticaria.", "5 mg orally once daily.",
     "Hypersensitivity to desloratadine or loratadine.", "Lacks anticholinergic and central sedative properties.",
     "Pharyngitis, dry mouth, fatigue, somnolence, myalgia.", "None significant.",
     "Category C."),
    ("Fexofenadine", "180 mg", "Oral Tablet", "1544463", "R06AX26", "Pure Non-Sedating H1 Antihistamine (Terfenadine Metabolite)", ["Allegra", "Fexova", "Allegra 24hr"],
     "Seasonal allergic rhinitis and chronic idiopathic urticaria.",
     "60 mg orally twice daily or 180 mg once daily WITH WATER (DO NOT take with fruit juice).",
     "Hypersensitivity to fexofenadine.", "Completely non-sedating (does not cross blood-brain barrier); no QT prolongation.",
     "Headache, upper respiratory tract infection, nausea, dysmenorrhea, dyspepsia.",
     "Fruit juices (grapefruit, orange, apple) inhibit intestinal OATP1A2 influx transporters and reduce bioavailability by 40%; antacids (aluminum/magnesium).",
     "Category C."),
    ("Diphenhydramine", "25 mg", "Oral / IV / IM", "3498", "R06AA02", "First-Generation Ethanolamine Antihistamine & Anticholinergic", ["Benadryl"],
     "Acute allergic reactions, anaphylaxis adjunct, motion sickness, insomnia, dystonic extrapyramidal reactions.",
     "25 mg to 50 mg orally, IV, or IM every 4 to 6 hours PRN (max 300 mg/day).",
     "Neonates or premature infants; nursing mothers; narrow-angle glaucoma; stenosing peptic ulcer.",
     "Severe sedation and impaired driving; profound anticholinergic toxicity (dry mouth, urinary retention, blurred vision, delirium in elderly - Beers Criteria Avoid); paradoxical CNS excitation in young children.",
     "Marked drowsiness, dry mouth, urinary retention, blurred vision, dizziness, thick bronchial secretions.",
     "CNS depressants, alcohol, MAO inhibitors (prolongs anticholinergic effects), anticholinergics.",
     "Category B. Drug of choice for acute extrapyramidal dystonias."),
    ("Hydroxyzine", "25 mg", "Oral / IM", "5552", "N05BB01", "First-Generation Piperazine Antihistamine & Anxiolytic", ["Atarax", "Vistaril"],
     "Pruritus due to allergic conditions, generalized anxiety disorder, perioperative sedation.",
     "25 mg to 50 mg orally 3 to 4 times daily (or 50-100 mg IM injection). NEVER administer IV/SC (tissue necrosis).",
     "Early pregnancy; prolonged QT interval; porphyria.",
     "Dose-dependent QT interval prolongation and torsades de pointes; severe tissue injury/necrosis if injected IV/SC; marked sedation.",
     "Sedation, dry mouth, headache, fatigue, dizziness.",
     "QT-prolonging drugs, CNS depressants, alcohol.",
     "Category C. Contraindicated in 1st trimester."),
    ("Montelukast", "10 mg", "Oral Tablet", "311689", "R03DC03", "CysLT1 Leukotriene Receptor Antagonist (LTRA)", ["Singulair", "Montair", "Telekast"],
     "Chronic asthma maintenance, prevention of exercise-induced bronchoconstriction (EIB), seasonal/perennial allergic rhinitis.",
     "10 mg orally once daily in the evening (take at least 2 hours before exercise for EIB; 4 mg for ages 2-5, 5 mg for ages 6-14).",
     "Known hypersensitivity to montelukast.",
     "Black Box: Serious neuropsychiatric events (agitation, aggression, depression, sleep disturbances, nightmares, suicidal ideation and behavior); not indicated for acute bronchospasm.",
     "Headache, abdominal pain, neuropsychiatric symptoms, cough, upper respiratory infection, fever.",
     "CYP3A4 and CYP2C8/2C9 inducers (phenytoin, phenobarbital, rifampin decrease montelukast levels).",
     "Category B. Extensively documented and safe in gestational asthma management."),
    ("Salbutamol", "100 mcg", "Inhalation Aerosol (MDI)", "435", "R03AC02", "Short-Acting Beta-2 Agonist (SABA)", ["Ventolin", "ProAir", "Asthalin", "Proventil"],
     "Relief and prevention of acute bronchospasm in asthma, COPD, and exercise-induced bronchospasm.",
     "1 to 2 inhalations (90-100 mcg/puff) every 4 to 6 hours PRN (or nebulizer 2.5 mg q6-8h).",
     "Hypersensitivity to albuterol.", "Paradoxical bronchospasm (life-threatening); cardiovascular stimulation (tachycardia, palpitations, arrhythmias); hypokalemia.",
     "Fine skeletal muscle tremor, nervousness, tachycardia, palpitations, headache, hypokalemia.",
     "Non-selective beta-blockers (propranolol antagonizes effect and triggers severe bronchospasm); MAOIs and tricyclics.",
     "Category C. Treatment of choice for acute asthma exacerbations in pregnancy."),
    ("Levalbuterol", "45 mcg", "Inhalation Aerosol", "214199", "R03AC16", "Pure R-Enantiomer SABA", ["Xopenex"],
     "Treatment and prevention of bronchospasm in asthma and COPD (reduced beta-1 tachycardia vs racemic albuterol).",
     "1 to 2 inhalations (45 mcg/puff) every 4 to 6 hours PRN.",
     "Hypersensitivity.", "Paradoxical bronchospasm, tachycardia, hypokalemia.",
     "Tremor, nervousness, headache, dizziness, tachycardia.", "Beta-blockers.",
     "Category C."),
    ("Salmeterol", "50 mcg", "Dry Powder Inhaler (DPI)", "36117", "R03AC12", "Long-Acting Beta-2 Agonist (LABA - 12 Hour)", ["Serevent Diskus"],
     "Maintenance treatment of asthma (ONLY with inhaled corticosteroid) and COPD maintenance.",
     "1 inhalation (50 mcg) twice daily approximately 12 hours apart.",
     "Asthma monotherapy WITHOUT concomitant Inhaled Corticosteroid (ICS) (strictly contraindicated).",
     "Black Box: LABA monotherapy in asthma increases risk of asthma-related death; not for acute relief.",
     "Headache, tremor, palpitations, upper respiratory infection, tachycardia.",
     "Strong CYP3A4 inhibitors (ketoconazole increases salmeterol 15-fold - QT prolongation), beta-blockers.",
     "Category C."),
    ("Formoterol", "12 mcg", "Dry Powder / Nebulizer", "25669", "R03AC13", "Fast-Onset Long-Acting Beta-2 Agonist (LABA)", ["Foradil", "Perforomist"],
     "Maintenance of asthma (with ICS) and COPD (fast onset within 2-3 min + 12-hour duration).",
     "12 mcg inhalation twice daily 12 hours apart.",
     "Asthma without ICS.", "Black Box: Asthma death when used without ICS; not for acute rescue.",
     "Tremor, headache, insomnia, nausea, palpitations.", "Beta-blockers, macrolides.",
     "Category C."),
    ("Ipratropium", "17 mcg", "Inhalation MDI / Nebulizer", "6011", "R03BB01", "Short-Acting Muscarinic Antagonist (SAMA)", ["Atrovent", "Dey-Dose"],
     "COPD bronchospasm maintenance, severe acute asthma exacerbations (combined with albuterol - DuoNeb/Combivent).",
     "2 inhalations (34 mcg) 4 times daily (max 12 puffs/day; nebulizer 0.5 mg q6-8h).",
     "Hypersensitivity to ipratropium or atropine derivatives.", "Paradoxical bronchospasm; worsening of narrow-angle glaucoma or urinary retention if sprayed directly in eyes.",
     "Dry mouth (most common), bitter taste, cough, urinary retention, blurred vision.",
     "Anticholinergic drugs.",
     "Category B. Safe in pregnancy."),
    ("Tiotropium", "18 mcg", "Inhalation DPI / Mist", "274786", "R03BB04", "Long-Acting Muscarinic Antagonist (LAMA - 24 Hour)", ["Spiriva HandiHaler", "Spiriva Respimat"],
     "Long-term maintenance treatment of bronchospasm associated with COPD (reduces exacerbations); asthma maintenance.",
     "1 capsule (18 mcg) inhaled once daily via HandiHaler or 2 puffs (2.5 mcg/puff) once daily via Respimat.",
     "Hypersensitivity to tiotropium or atropine.", "Worsening of narrow-angle glaucoma; acute urinary retention in BPH; paradoxical bronchospasm.",
     "Dry mouth (16%), upper respiratory tract infection, sinusitis, pharyngitis, urinary retention, constipation.",
     "Anticholinergic agents.",
     "Category C."),
    ("Fluticasone Propionate", "110 mcg", "Inhalation MDI / Nasal Spray", "315677", "R03BA05", "Potent Inhaled Corticosteroid (ICS)", ["Flovent HFA", "Flonase"],
     "Maintenance treatment of asthma; relief of seasonal and perennial allergic rhinitis (Flonase nasal spray).",
     "Inhalation: 88 mcg to 440 mcg twice daily; Nasal spray: 2 sprays per nostril once daily.",
     "Primary treatment of status asthmaticus; hypersensitivity to milk proteins (DPI formulation).",
     "Oropharyngeal candidiasis (thrush - rinse mouth with water and spit after each use); dysphonia (hoarseness); systemic adrenal suppression with high doses; decreased growth velocity in children.",
     "Oral candidiasis (thrush), dysphonia, headache, pharyngitis, upper respiratory infection, epistaxis (nasal spray).",
     "Strong CYP3A4 inhibitors (ritonavir, ketoconazole cause massive increase in systemic fluticasone exposure leading to Cushing's syndrome and adrenal crisis).",
     "Category C. Preferred inhaled corticosteroid in pregnancy asthma control."),
    ("Budesonide", "180 mcg", "Inhalation DPI / Nebulizer", "19831", "R03BA02", "Inhaled Corticosteroid (ICS)", ["Pulmicort Flexhaler", "Pulmicort Respules", "Rhinocort"],
     "Maintenance treatment of asthma (Respules approved for infants >=12 months); allergic rhinitis.",
     "180 mcg to 720 mcg inhaled twice daily (Respules 0.25-0.5 mg daily via jet nebulizer).",
     "Status asthmaticus.", "Oral candidiasis, dysphonia, bronchospasm, pediatric growth delay.",
     "Oral candidiasis, dysphonia, cough, respiratory infection.", "Strong CYP3A4 inhibitors (ketoconazole, itraconazole).",
     "Category B. FDA pregnancy category B approved for asthma in pregnancy.")
]

print("Domains 4-8 components ready.")
